### ISSUE TITLE
Перевод клиента

### ISSUE THREAD

**Issue by ValeryLitvin** [GolosChain/tolstoy#1]

**Comment by 21xhipster** [comment]
<img width="747" alt="screen shot 2016-10-07 at 6 08 33 pm" src="https://cloud.githubusercontent.com/assets/410789/19197267/2244bbb4-8cb9-11e6-8465-4db598fd750d.png">

**Comment by 21xhipster** [comment]
https://github.com/xanoxt/golos.io/blob/develop/app/locales/ru.js @tomarcafe @Undeadlol1 Необоходимо смерджить результаты этой работы
