### ISSUE TITLE
Не отображается количество репостов у поста

### ISSUE THREAD

**Issue by BaroH4er** [GolosChain/tolstoy#1000]
Баг ишью #767

**Проблема:** ```кнопка Репост ( + количество репостов)``` - не отображается количество репостов.
**Воспроизведение:** 
1. Зайти на https://sandbox.golos.io/ и авторизоваться
2. Открыть ленты постов и открыть любой пост
3. Поделиться постом
![image.png](https://images.zenhubusercontent.com/5a6f31974b5806bc2bc4b26e/f370c64b-e599-4711-81e1-542b54c3f440)
4. Обновить страницу ctrl+f5

**Результат:** не отображается количество репостов.
**Ожидаемый результат:** отображается количество репостов.

**Comment by NickShtefan** [comment]
к сожалению, в текущий момент блокчейн не отдает количество репостов для поста.
в связи с чем реализация данного функционала откладывается либо до того момента, когда это будет сделать в БЧ, либо до реализации кеширующих сервисов.
так или иначе в ближайшее время решить данный вопрос не получится.
