### ISSUE TITLE
Сделать надпись на первой странице аккаунта гендер-нейтральной

### ISSUE THREAD

**Issue by gamerate** [GolosChain/tolstoy#101]
Заменить 

Похоже что Наташа еще не завёл блог!

На например:

Похоже этот блог пока пуст. @username скоро напишет первый пост.

**Comment by naftalmm** [comment]
Аналогично - для страниц 
https://golos.io/@[username]/posts и 
https://golos.io/@[username]/recent-replies

**Comment by Undeadlol1** [comment]
Спасибо
