### ISSUE TITLE
Реализовать возможность редактирования своих постов

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/tolstoy#1028]

**Comment by daryasattarova** [comment]
1. в html редакторе на фото отображается посторонний символ
![image](https://user-images.githubusercontent.com/42342756/47087629-2ae3df80-d225-11e8-9e1d-b6787547c11f.png)

**Comment by Bacher** [comment]
Стой

**Comment by Bacher** [comment]
Не надо в эту задачу это добавлять. Этой баге больше чем мне.
