### ISSUE TITLE
Ротация страницы трендинг

### ISSUE THREAD

**Issue by serejandmyself** [GolosChain/tolstoy#103]
В связи с не возможностью выплат по постам до первых выплат, предлагаю ввести ограничение по времени появления постов на странице трендинг - скажем 36 часов, для ротации

**Comment by Undeadlol1** [comment]
На выдачу повлиять невозможно.
https://github.com/GolosChain/tolstoy/issues/76

**Comment by serejandmyself** [comment]
Написал возможности решения проблемы в чат

**Comment by serejandmyself** [comment]
Вот некоторые решения проблемы:

1) Сделать Акутальное за главную странцу, переимновать трендинг в "лучшее за все время" и повесить банер а ля - "не работает до хххх по тех причинам, просьба читать новое"

и/или

2 ) сделать некий фильтр для трендинга по дате, без учета выплат если это возможно

и/или

3) Сделать акутальное дефолтной страницей при этом разбить её на 2 колонки - лучшее за все время и актуальное на сейчас

**Comment by Undeadlol1** [comment]
"Популярное" переименовано в "лучшее". Главная ссылка теперь ведет в "актуальное".
Спасибо за предложение.
