### ISSUE TITLE
Обновить шапку сайта, согласно новому дизайну

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/tolstoy#1037]
при нажатии на область аватара и батарейки открываем "профиль пользователя"
при нажатии на гамбургер открываем меню, [согласно дизайну
](https://app.zeplin.io/project/5ba9f49fb422725fe0f07dbf/screen/5bb1f0f0d8f1991eabd935de)

**Comment by daryasattarova** [comment]
гамбургер должен быть синим, как в дизайне
![image](https://user-images.githubusercontent.com/42342756/47364250-83155880-d6e1-11e8-9365-7a7e14579d5e.png)
