### ISSUE TITLE
Некоторые фото не отображаются в превью поста

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/tolstoy#1052]
Воспроизведение:
1. открыть https://sandbox.golos.io/
2. авторизоваться
3. открыть профиль, например @joseph.kalu

Ожидаемый результат: если в посте есть фото, то на превью поста она должна отображаться
Реальный результат: фото не отображается
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/59d8e0b0-db96-49fa-8a8d-95124ab0470d)
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/dc0f507d-7965-41d8-bd6c-9dbec93a7084)

**Comment by NickShtefan** [comment]
Карточка поста была обновлена, необходимо актуализировать задачу
