### ISSUE TITLE
Добавить ссылку на пост, по которому пришла награда 

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/tolstoy#1054]
Воспроизведение:
1. открыть https://sandbox.golos.io/
2. авторизоваться
3. открыть свой профиль и перейти на Активность -> Награды

Ожидаемый результат: должна быть ссылка на пост, по которому пришла награда
Реальный результат: ссылки нет
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/e47ceb27-c4a1-4f09-a96a-f829793ab35d)

**Comment by NickShtefan** [comment]
дубль #1044
