### ISSUE TITLE
Создать ссылку на Вики страницу Я здесь в первые

### ISSUE THREAD

**Issue by serejandmyself** [GolosChain/tolstoy#106]
Сделать ссылку, так же как на данный момент работает ссылка на страницу краудсейла / дисклеймера

**Comment by Undeadlol1** [comment]
Каждый пользователь редиректится на страницу лэндинга, где все детально обьясняется,
Интерфейс не резиновый, еще больше разноцветных кнопок вставлять не целесообразно.

**Comment by serejandmyself** [comment]
К сожалению лэндинг временный + на нем нет инфы для новых пользователей 

Ведь кнопки Дисклеймер и Краудсейл все равно потом исчезнут (они будут не нужны через какое то время).... Если есть возможность, я бы вставил ссылку в "ховер" меню слева, возле ссылки на чат =)

**Comment by Undeadlol1** [comment]
Добавил ссылку на вики в сайдбар.
Спасибо за предложение.
