### ISSUE TITLE
Кнопка "Назад" на посте работает некорректно 

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/tolstoy#1066]
Воспроизведение:
1. открыть https://sandbox.golos.io/
2. авторизоваться
3. открыть свой пост, например
4. выполнить шаги, например: нажать значок редактирования -> переключиться на html-редактор
5. нажать стрелочку назад 
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/27a3ab7c-2b1f-4903-9f72-42142ac55e5b)

Ожидаемый результат: экран поста должен закрыться
Реальный результат: осуществляется шаг назад

**Comment by NickShtefan** [comment]
поведение корректное
