### ISSUE TITLE
Ссылка на видео в комменте делает сам текст невидимым

### ISSUE THREAD

**Issue by gamerate** [GolosChain/tolstoy#107]
Если коммент содержит ссылку на ютуб которая превращается в видео, то весь остальной текст в этом комменте не показывается - что явно не то что ожидает пользователь.

![screenshot from 2016-11-02 22-55-09](https://cloud.githubusercontent.com/assets/954529/19945088/8d4c3342-a14f-11e6-8ba9-7c4180c6bb28.png)

**Comment by gamerate** [comment]
Уточнение - ссылка на видео в одной строке с текстом его скрывает
Если текст на других строчках то с ним все ок

**Comment by serejandmyself** [comment]
Суть в том что алгоритм ищет в строке совпадение со строкой youtube/vimeo. Как только алгоритм находит совпадение, то вместо строки подставляет видео блок затирая все что там было. Проблема в том что обработка эта происходит в объектном дереве xmldomtree, там так просто не добавить еще одну строчку сохранив текст комментария о котором упоминается в issue
В Стиме это проблема также существует

**Comment by b1acksun** [comment]
` -identify plain youtube/vimeo URLs and prep them for "rich embed"`
```
function embedYouTubeNode(child, links, images) {try{
.....
const v = DOMParser.parseFromString(`~~~ embed:${id} youtube ~~~`)
child.parentNode.replaceChild(v, child)
.....
```
Используется, для создания блока с видео-контентом, который в дальнейшем вставляется в DOM дерево документа, поиск URL происходит во всей строе, найдя URL, остальное отбрасывается, используется для исключения парсинга URL в тексте и разрыва его блоком с контентом, для всатвки контента, необходимо перейти на новую строку
