### ISSUE TITLE
Разрешить использование dataURI в HTML-редакторе постов

### ISSUE THREAD

**Issue by naftalmm** [GolosChain/tolstoy#110]
Приведу пример поста:
```
<html>
<p>Тестовый пост</p>
<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAYAAACNMs+9AAAABmJLR0QA/wD/AP+gvaeTAAAAB3RJTUUH1ggDCwMADQ4NnwAAAFVJREFUGJWNkMEJADEIBEcbSDkXUnfSgnBVeZ8LSAjiwjyEQXSFEIcHGP9oAi+H0Bymgx9MhxbFdZE2a0s9kTZdw01ZhhYkABSwgmf1Z6r1SNyfFf4BZ+ZUExcNUQUAAAAASUVORK5CYII="/>
</html>
```
Данный HTML валиден ([и давно поддерживается большинством браузеров](http://caniuse.com/#feat=datauri)), но клиент его не пропускает - не отображает в preview и выкидывает ошибку при нажатии на кнопку "Пост":

![image](https://cloud.githubusercontent.com/assets/10289217/19975443/06848df6-a1fd-11e6-9739-7b4916e049c2.png)

**Comment by Undeadlol1** [comment]
В ближайшее время планируется полностью поменять редактор. Работы над ним вести бессмысленно
Если кто-то хочет исправить эту ошибку, то регекс создающий эту ошубку находится [тут](https://github.com/GolosChain/tolstoy/blob/develop/app/utils/SanitizeConfig.js#L87)

**Comment by naftalmm** [comment]
Спасибо за наводку на нужный файл исходников.
Правильный регекс в соответствии со стандартами [RFC2397](https://www.ietf.org/rfc/rfc2397.txt), [RFC2045](https://tools.ietf.org/html/rfc2045) и [утвержденными IANA MIME-типами для изображений](http://www.iana.org/assignments/media-types/media-types.xhtml#image) будет такой:
```
^(https?:)?\/\/|^data\:image\/(bmp|cgm|dicom-rle|emf|example|fits|g3fax|gif|ief|jls|jp2|jpeg|jpm|jpx|ktx|naplps|png|prs\.btif|pwg-raster|svg\+xml|t38|tiff|tiff-fx|vnd\.adobe\.photoshop|vnd\.airzip\.accelerator\.azv|vnd\.cns\.inf2|vnd\.dece\.graphic|vnd\.djvu|vnd\.dwg|vnd\.dxf|vnd\.dvb\.subtitle|vnd\.fastbidsheet|vnd\.fpx|vnd\.fst|vnd\.fujixerox\.edmics-mmr|vnd\.fujixerox\.edmics-rlc|vnd\.globalgraphics\.pgb|vnd\.microsoft\.icon|vnd\.mix|vnd\.ms-modi|vnd\.mozilla\.apng|vnd\.net-fpx|vnd\.radiance|vnd\.sealed\.png|vnd\.sealedmedia\.softseal\.gif|vnd\.sealedmedia\.softseal\.jpg|vnd\.svf|vnd\.tencent\.tap|vnd\.valve\.source\.texture|vnd\.wap\.wbpm|vnd\.xiff|vnd\.zbrush\.pcx|wmf);base64,[a-zA-z0-9+\/]{2,}={0,2}$
```
Также, как я понял, текущий редактор не поддерживает тэги audio и video, которые также допускают Data URIs как src. Планируется ли поддержка этих тэгов в новом редакторе?

Но вообще все это имеет мало смысла в свете ограничения максимальной длины поста всего 100 килобайтами. Данное ограничение хардкодом прописано [тут](https://github.com/GolosChain/tolstoy/blob/master/app/components/elements/MediumEditor.jsx#L382) и [тут](https://github.com/GolosChain/tolstoy/blob/master/app/components/elements/ReplyEditor.jsx#L424).
Не могли бы вы прокомментировать, чем оно обусловлено? 
Будет ли оно ослаблено (хотя бы до нескольких Мб) при переходе на новый редактор?

**Comment by tomarcafe** [comment]
@naftalmm - про ограничение на длину ппоста и встроенные изображения - следует понимать существенную особенность блокчейна Голоса, и других основанных на ядре graphene - весь блокчейн хранится в оперативной памяти. с одной стороны, это позволяет сделать его ультрабыстрым, с другой - не очень-то разгонишься с количеством хранимых данных. да, оперативная память дешевеет - но не настолько быстро. 
поэтому, запрет на встраиваемые изображения кажется мне правильным, увеличение максимального размера поста - не очень осмысленным. то есть, аудио, видео, картинки - в любом случае останутся лишь ссылками, не будут записываться в блокчейн.

**Comment by naftalmm** [comment]
@tomarcafe существует ли соответствующее ограничение на уровне блокчейна?
В настройках ноды я видел только параметp miner-maximum-block-size - "Maximum block size (in bytes) to be voted on upon successful POW - Max block size must be between 128 KB and 750 MB"
Я правильно понимаю, что при желании можно форкнуть этот репозиторий, снять это ограничение, и, подняв ноду майнера, увеличивать блокчейн на 750Мб каждые 3 секунды?

**Comment by Undeadlol1** [comment]
Спасибо @tomarcafe за пояснение.
Извините, @naftalmm, но в улучшении отказано по причине не нужной нагрузки на блокчейн.

**Comment by tomarcafe** [comment]
@naftalmm - я так понимаю, если Вы соберетесь писать в блокчейн голоса - получится так, что Ваши блоки просто не будут приняты - у остальных нод ограничение будет жестче Вашего. если же это будет отдельный блокчейн - то почему нет.
