### ISSUE TITLE
Несоответствие значения выплат на посте со значениями в плашке

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/tolstoy#1100]
Воспроизведение:
1. открыть https://sandbox.golos.io/
2. авторизоваться
3. открыть любой пост
4. нажать на значение выплат

Ожидаемый результат: значение выплат, написанное на посте, должно соответствовать значениям в плашке
Реальный результат: значения разные
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/43d3d0fe-fcb2-4075-a2c5-a20997b3e8d6)

**Comment by NickShtefan** [comment]
отображение корректное.

**Comment by NickShtefan** [comment]
отображение корректное.
