### ISSUE TITLE
Ошибки локализации в UserProfileContainer

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/tolstoy#1105]
Воспроизведение:
1. открыть https://sandbox.golos.io/
2. авторизоваться
3. перейти в свой профиль
4. сменить английский язык на украинский

Ожидаемый результат: панель UserProfileContainer с вкладками должна перевестись на украинский
Реальный результат: переводится частично 
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/7e6b0e09-5a90-4b05-acd4-70d1bb517e8e)

**Comment by b1acksun** [comment]
61480d1a4febdb7844fb870526bf86866cb05417
