### ISSUE TITLE
Добавить в ленту feed посты, написанные авторами до момента моей подписки на них

### ISSUE THREAD

**Issue by naftalmm** [GolosChain/tolstoy#111]

**Comment by pavelit** [comment]
На данный момент логика ленты feed предполагает отображение постов пользователей на которые подписан владелец своей ленты. Никак иначе.

**Comment by serejandmyself** [comment]
Ну я бы не стал пока закрывать. Если @Nemo1369 сделает такую возможность в цепочки то можно будет применять и здесь. Пусть висит пока

**Comment by serejandmyself** [comment]
referenced 144 goloschain/golos
