### ISSUE TITLE
Сделать Pull Request с i18n в steemit.com

### ISSUE THREAD

**Issue by Undeadlol1** [GolosChain/tolstoy#112]
Работа будет вестись в ветке [steemit-intl](https://github.com/GolosChain/tolstoy/tree/steemit-intl)

**Comment by tomarcafe** [comment]
попробую сначала подтянуть  ихний мастер. мне кажется, там уже есть локали

**Comment by Undeadlol1** [comment]
Не нужно, я сам 
--
Отправлено из Mail.Ru для Android пятница, 04 ноября 2016г., 10:34 +02:00 от angelo  notifications@github.com :

**Comment by Undeadlol1** [comment]
Ветка, в которой парни из стимита делают мердж наших изменений - https://github.com/steemit/steemit.com/tree/from-golos.
Собираюсь форкнуть ее, и работать уже там. Так проще будет.

**Comment by tomarcafe** [comment]
круто!

**Comment by Undeadlol1** [comment]
То что осталось вне коммит лога:
- Исправлены merge конфликты
- Убраны Landing элементы
- Убрано множество golos specific кода

@valzav ассийню тебя, чтобы ты мог следить за изменениями. Таким образом наши команды не будут работать над одними и теми же вещами.

**Comment by Undeadlol1** [comment]
Устарело, пулл реквесты будут оформляться маленькими частями.
