### ISSUE TITLE
Орфографическая ошибка

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/tolstoy#1127]
Воспроизведение:
1. открыть https://sandbox.golos.io/
2. авторизоваться
3. открыть пост
4. в боковой панели навести на значок поделиться в соц. сети

Ожидаемый результат: должно быть написано "ПоделитЬся в соц. сети"
Реальный результат:

![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/faf6ba93-4c24-4152-9ff6-26301083dc37)

**Comment by b1acksun** [comment]
67e93f11b080de53da0811ab5eabffe4c7262d3d
