### ISSUE TITLE
Прийти к единому разделителю дробной части в разделе Кошелек

### ISSUE THREAD

**Issue by 0n0t0le** [GolosChain/tolstoy#114]
Значения Голос, Сила Голса и Золотой используют точку для разделения дробной части от целой, 
в оценочной стоимости аккаунта используется запятая

![](http://i.imgsafe.org/dd4842d205.png)

**Comment by Undeadlol1** [comment]
Спасибо что сообщили.
Если где-то будут еще разногласия, пожалуйста скажите.
