### ISSUE TITLE
Сделать окно отображения проголосовавших за запись в соответствии с дизайном

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/tolstoy#1143]
Воспроизведение:
1. открыть https://sandbox.golos.io/
2. авторизоваться
3. выбрать пост

Ожидаемый результат: при КЛИКЕ на число проголосовавших, касается и лайка и дизлайка (будь то пост, коммент или ответ) должно появляться окно проголосовавших в соответствии с дизайном
Реальный результат: при наведении на значок лайка/дизлайка всплывает окно с перечнем проголосовавших 

Дизайн:
веб
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/d94c9b24-1e9b-48a5-8959-046876e23679)
моб
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/f00cc801-5e89-4cc9-a41b-86b25a18db9e)

**Comment by daryasattarova** [comment]
Добавить проценты в соответствии с дизайном

**Comment by jevgenika** [comment]
https://github.com/GolosChain/tolstoy/issues/964
