### ISSUE TITLE
Изменить экран в соответствии с дизайном, который появляется при нажатии на кнопку "Отблагодарить"

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/tolstoy#1144]
Воспроизведение:
1. открыть https://sandbox.golos.io/
2. авторизоваться
3. открыть пост другого пользователя
4. пролистать до блока с инф-ей об авторе
5. нажать кнопку "отблагодарить"

Ожидаемый результат: должно появиться окно в новом дизайне (см. дизайн ниже)
Реальный результат: старый дизайн
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/88690176-93f9-43b8-ac8b-d8593582d2c1)

Дизайн: 
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/ae853be5-5450-45af-b3d7-a6b19f6b7ccf)

**Comment by Bacher** [comment]
Сделал новый диалог, но не такой какой на скриншоте, дизайн немного более старой версии.
