### ISSUE TITLE
Перевести уведомление о невозможности power down для аккаунта

### ISSUE THREAD

**Issue by 0n0t0le** [GolosChain/tolstoy#115]
![](http://i.imgsafe.org/dd9fe4eed4.png)

**Comment by Chiliec** [comment]
Давайте подумаем как правильнее перевести:
`Account registered by another account requires 10x account creation fee worth of Steem Power before it can power down`

**Comment by 0n0t0le** [comment]
Учетная запись должна набрать количество СП в 10 раз большее чем значение которое было заплачено за её создание, прежде чем она сможет начать Павердаун

Суть примерно такая, можно перефразировать...

**Comment by gamerate** [comment]
Думаю корректнее будет написать так: "Учетная запись должна набрать количество Силы Голоса в 10 раз большее чем значение которое было заплачено за её создание, прежде чем она сможет начать уменьшение силы голоса"

Но нюанс тут состоит в том, что строка не в скрипте перевода, но в в скрипте транзакции захардкожена на английском, там надо прописать сначала вызов перевода, а я пока не разбирался как он тут сделан, так что пока не буду трогать.
