### ISSUE TITLE
Возможность загружать картинки из редактора

### ISSUE THREAD

**Issue by Chiliec** [GolosChain/tolstoy#116]
Наверное не все пользователи знают как и куда можно загрузить картинку. Нужна возможность загрузить локальную картинку прямо из редактора и получить на неё ссылку. Найти или поднять свой надёжный хостинг картинок. Обязательно с http**s** протоколом.

**Comment by Undeadlol1** [comment]
Спасибо за предложение.
@tomarcafe Будем осуществлять или отказываем?
Имхо: если в стимите этого нет, то и нам не обязательно. Дополнительные расходы (финансовые и временные) на данном этапе вряд ли оправданы.
Но, все же, лучше обсудить с командой.

**Comment by tomarcafe** [comment]
как только закрой более жаркую жару - на очереди стоит поднятие ноды ipfs
думается, это закроэ этот и подобные вопросы

**Comment by Undeadlol1** [comment]
А как работает IPFS? Картинки будут загружаться через редактор или нода фетчит картинки через юрл и сохраняет где-то? Насколько IPFS относится конкретно к загрузке картинок через редактор?
Ишью закрываю?

**Comment by tomarcafe** [comment]
ишью пусть висит.
ну ipfs тут чисто по приколу - любой файловый сервер бы подошел еще и легче встал бы.

возможны оба варианта, до тех пор пока мы в состоянии картинку пробросить туда куда нам надо в том в каком надо виде - тут скорее от тебя пожелания - внешний юрл или загрузка по кнопке с локального, или оба варианта.

**Comment by tomarcafe** [comment]
к конкретно загрузке картинок через редактор ипфс не относится, думай о ней как о файловом хранилище в которое можно покласть и затем прочитать

**Comment by serejandmyself** [comment]
Осуществлено в стиме, drag&drop, будет в следующей версии веб клиента
