### ISSUE TITLE
Отображается на постах реблог своего же поста

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/tolstoy#1160]
Воспроизведение:
1. открыть https://sandbox.golos.io/
2. авторизоваться
3. перейти в профиль @joseph.kalu

Ожидаемый результат: свои посты не могут быть реблогнуты вами
Реальный результат: отображаются реблоги свих постов
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/d06b9372-956a-4270-b511-f5016c280f63)

**Comment by Bacher** [comment]
В текущей версии приложения все кнопки которые вызывают репост скрыты для своих постов.
Репосты которые уже были совершены останутся.
