### ISSUE TITLE
Доработка делегирования СГ

### ISSUE THREAD

**Issue by b1acksun** [GolosChain/tolstoy#1164]
1. Брать минимальное количество для делегирования из get_chain_properties.min_delegation
2. При делегировании проверять - если акку уже делегированна СГ, то отображать кол-во длегированной силы, ошибка если сумма указанна меньше текущей
3. Обработка ошибок

**Comment by NickShtefan** [comment]
было реализовано временное решение, рефакторинг будет осуществлен позже
