### ISSUE TITLE
Пропала былая глубина комментария

### ISSUE THREAD

**Issue by imag1ne666** [GolosChain/tolstoy#117]
Выдает ошибку даже на 5 строчках! ->  **_Comment is nested 5 posts deep, maximum depth is 5_** 
Куда же подевалась былая глубина комментария? Или я что-то пропустил?
Не хотелось бы ограничиваться 5ю строками. Спасибо.
https://i.imgsafe.org/187684c0b3.jpg

**Comment by 0n0t0le** [comment]
Дело не в строчках, а в количестве комментариев в глубину. В данный момент установлено ограничение на 5 комментарием уровнем ниже

**Comment by Undeadlol1** [comment]
Это не баг, а фича.
Спасибо что сообщили, ошибку перевел.
