### ISSUE TITLE
Правки верстки в мобильной версии 

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/tolstoy#1172]
https://github.com/GolosChain/tolstoy/issues/1035
поправить верстку шапки при условии не авторизированного пользователя
1. близко расположен юзернейм и полное имя
![inkedphoto_2018-10-24_13-33-44_li](https://user-images.githubusercontent.com/42342756/47425533-46a23500-d793-11e8-8133-9d7f29d0907e.jpg)
2. иконка накладывается на кнопку "назад"
![inkedphoto_2018-10-24_13-33-44 3 _li](https://user-images.githubusercontent.com/42342756/47425552-56217e00-d793-11e8-860d-b4512825c16f.jpg)
3. экран редактирования поста
![photo_2018-10-24_13-33-44 2](https://user-images.githubusercontent.com/42342756/47425561-5f124f80-d793-11e8-8537-0a52b43c08bb.jpg)

Окружение: iphone 5s

**Comment by Bacher** [comment]
1 - поправил,
2 - кнопку вообще убрали (ото всюду)
3 - вынес в отдельный таск #1211
