### ISSUE TITLE
При клике на действия будучи неавторизированным сначала должна открыться форма авторизации.

### ISSUE THREAD

**Issue by Bacher** [GolosChain/tolstoy#1179]
При клике на действия будучи неавторизированным сначала должна открыться форма авторизации.

![image.png](https://images.zenhubusercontent.com/5b0ff4b64b5806bc2bd5811e/f4e9c8c5-b777-4bdc-b598-ca3ce6b2c9e9)

![image.png](https://images.zenhubusercontent.com/5b0ff4b64b5806bc2bd5811e/9c794e5d-9bc9-4154-851d-d5db14d3caed)

**Comment by daryasattarova** [comment]
связанная задача https://github.com/GolosChain/tolstoy/issues/1186
