### ISSUE TITLE
в анонимном режиме при нажатии кнопки "отблагодарить появляется белый экран"

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/tolstoy#1181]
Воспроизведение:
1. открыть https://sandbox.golos.io/ (не логиниться)
2. открыть пост любой
3. нажать кнопку "отблагодарить"

Ожидаемый результат: должно появиться окно авторизации
Реальный результат: белый экран

![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/5e2b670f-1168-4d4b-ad87-489205ff65e3)

**Comment by Bacher** [comment]
Исправлено в #1179

**Comment by daryasattarova** [comment]
не исправлено

**Comment by Bacher** [comment]
Поправлено в рамках Issue #1144
