### ISSUE TITLE
в анонимном режиме на экране пользователя при нажатии кнопки "делегировать СГ" появляется белый экран

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/tolstoy#1183]
Воспроизведение:
1. открыть https://sandbox.golos.io/ (не логиниться)
2. перейти в профиль любого пользователя
3. в боковой панели нажать кнопку "делегировать СГ"

Ожидаемый результат: должно появиться окно авторизации
Реальный результат: белый экран
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/43780298-2973-4b7c-b48f-2507054be8ee)

**Comment by Bacher** [comment]
Будет поправлено вместе с #1182
