### ISSUE TITLE
в анонимном режиме при нажатии на звездочку должно появляться окно авторизации

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/tolstoy#1186]
Воспроизведение:
1. открыть https://sandbox.golos.io/ (не логиниться)
2. открыть любой пост
3. нажать на звездочку "В избранное"

Ожидаемый результат: должно появиться окно авторизации
Реальный результат: ничего не происходит
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/6a6e7475-a731-4583-9254-61b2caf0e252)

**Comment by Bacher** [comment]
Поправил в #1179
