### ISSUE TITLE
На странице поста нет блока для отображения незарегистрированным пользователям

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/tolstoy#1191]
Воспроизведение:

- открыть https://sandbox.golos.io/
- не авторизоваться
- открыть пост
- прокрутить вниз

Результат: на странице поста нет блока для отображения незарегистрированным пользователям

Ожидаемый результат: После блока об авторе перед комментарием незарегистриванным пользователям отображается текстовый блок с кнопкой  Зарегистрироваться с редиректом на регистрацию.
[Дизайн](https://app.zeplin.io/project/5ba9f49fb422725fe0f07dbf/screen/5ba9fafc130bb036df1c9a63)
![image](https://user-images.githubusercontent.com/30616421/47446402-7107e880-d7bb-11e8-891f-072885b76cf9.png)
текст 
> Авторы получают вознаграждение, когда голосуют за их посты. 
> Голосующие читатели также получают вознаграждение за свои голоса.
Кнопка -Зарегистрироваться

**Comment by jevgenika** [comment]
https://github.com/GolosChain/tolstoy/issues/1510

**Comment by AlexRekish** [comment]
#1510
