### ISSUE TITLE
Вместо кнопки Отписаться отображать кнопку Подписки в соответствии с дизайном

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/tolstoy#1196]
В случаи, когда пользователь подписан на юзера на https://sandbox.golos.io
отображается кнопка Отписаться.
Кнопка стимулирует отписаться от юзера, на которого пользовтаель подписан. Цели мотивировать на отписку у нас нет.

Ожидаемый результат:
Показывать пользовтаелю статус юзера -в подписчиках или подписке.

Решение:
- Вместо кнопки Отписаться отображать кнопку Подписки в соответствии с дизайном
- при вызове кнопки Подписки отображать окно с текстом
Заголовок: Отписаться
Вы уверенны, что хотите отменить подписку @username?
кнопки: отменить подписку/отмена

Заменить:
- на профиле пользователя (см. скрин 1); 
- в плашке, появляющейся при нажатии на юзерпик автора поста (см. скрин 2); 
- в блоке информации об авторе на экране поста (см. скрин 3);
- в окне просмотра подписок/подписчиков изменить кнопки в соответсвии с дизайном

1.
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/c4cb6ca8-b85c-41f5-b615-4daa4d39c01f)
2. 
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/f10ef831-44f8-4b36-bae3-631da23d6296)
3.
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/f904ccf9-1e4d-4caf-a4e8-6bc2587b2d81)
4.
![image](https://user-images.githubusercontent.com/42342756/47485617-23d15880-d847-11e8-9d2f-d4b26b6e7c39.png)

Дизайн:
![image](https://user-images.githubusercontent.com/42342756/47482897-7d825480-d840-11e8-9c11-a710dc22c394.png)
https://app.zeplin.io/project/5ba9f49fb422725fe0f07dbf/screen/5ba9f674a00626840bfa45f4

**Comment by daryasattarova** [comment]
связанные задачи https://github.com/GolosChain/tolstoy/issues/1192

**Comment by jevgenika** [comment]
- На странице профиля
- в плашке, появляющейся при нажатии на юзерпик автора поста 
- в блоке информации об авторе на экране поста 
- в окне просмотра списка пользователей подписок/подписчиков 
- в окне просмотра проголосовавших за запись

- [ ] вместо кнопки Отписаться отображать кнопку Подписки в соответствии с дизайном.

- [ ] при вызове кнопки Подписки
- На странице профиля
- в плашке, появляющейся при нажатии на юзерпик автора поста 
- в блоке информации об авторе на странице поста 
- в окне просмотра списка пользователей подписок/подписчиков 
- в окне просмотра проголосовавших за запись
- [ ] отображать окно с текстом
Заголовок: Отписаться
Вы уверенны, что хотите отменить подписку @username?

кнопки
отменить подписку
отмена

**Comment by kuchinskaya** [comment]
https://zpl.io/aw1pM4j http://prntscr.com/lbu394

**Comment by kuchinskaya** [comment]
http://prntscr.com/lbu3s1 https://app.zeplin.io/project/5ba9f49fb422725fe0f07dbf/screen/5ba9f5c91b8c11a10ef588fb

**Comment by jevgenika** [comment]
Боковой блок топ авторы на главной
Хедер страницы поста
Результат
![image](https://user-images.githubusercontent.com/30616421/47705194-7dae9580-dc2e-11e8-984d-59f712907ca3.png)

Ожидаемый результат:
кнопка подписки меняется на плюс
кнопка подписки меняется на глаку

- [ ] Заменить кнопку подписаться  в соответсвии с [дизайном](https://zpl.io/agrPe8M)
![image](https://user-images.githubusercontent.com/30616421/47705142-5657c880-dc2e-11e8-9699-42a4736d5cae.png)

**Comment by daryasattarova** [comment]
не реализована кнопка "подписки"

**Comment by daryasattarova** [comment]
не исправлено на странице профиля 
![image](https://user-images.githubusercontent.com/42342756/47837093-cba4d400-ddbb-11e8-9619-76b89a7ba76e.png)
