### ISSUE TITLE
Адаптировать редактор создания/редактирования поста для мобильных устройств

### ISSUE THREAD

**Issue by Bacher** [GolosChain/tolstoy#1211]
Адаптировать редактор создания/редактирования поста для мобильных устройств

Сейчас всё разъезжается.

**Comment by kuchinskaya** [comment]
https://app.zeplin.io/project/5ba9f49fb422725fe0f07dbf/dashboard?seid=5c176ed881415cb00645e4e8

**Comment by MachtFrei** [comment]
в самом низу страницы какая-то ерунда (квадратная) , которая скроллится отдельно от переключателей
![screenshot_2018-12-21-13-02-24-728_com android chrome](https://user-images.githubusercontent.com/2689880/50336885-5d110680-0520-11e9-9199-5a3a42b50fd9.png)

**Comment by MachtFrei** [comment]
кнопка Х которая видимо должна закрыть окно создания поста не работает,

android chrome
![screenshot_2018-12-21-13-10-02-152_com android chrome](https://user-images.githubusercontent.com/2689880/50337220-79fa0980-0521-11e9-8b76-d61da2292423.png)

**Comment by daryasattarova** [comment]
1. жду фикс с подсказками из чейна
2. (экран редактирования поста) по нажатию на три точки появляется окно и после его закрыть невозможно. По идее по нажатию на бэкграунд окно должно закрываться
![image](https://user-images.githubusercontent.com/42342756/50372592-4a5f0600-05e2-11e9-945d-f98057cabeb2.png)
