### ISSUE TITLE
Сделать НОРМАЛЬНЫЙ установщик

### ISSUE THREAD

**Issue by tomarcafe** [GolosChain/tolstoy#122]
чтобы можно было клонировать и запустить по инструкции, а не как сейчас

**Comment by Chiliec** [comment]
Поддерживаю! Клёво было бы увидеть готовый докер-контейнер, например.

**Comment by Undeadlol1** [comment]
Дубликат
https://github.com/GolosChain/tolstoy/issues/98

**Comment by tomarcafe** [comment]
так. ну сейчас не хватает нескольких вещей.
самая важная - это инструкции как настраивать конфиг, пример конфига с разбором по строчкам.
тоже важная - перевести и дополнить инструкции в части sequelize db:migrate
