### ISSUE TITLE
некорректное отображение плашки в мобильной версии

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/tolstoy#1236]
Окружение: iphone 5s

При нажатии на юзерпик на экране поста появляется плашка. в мобильной версии отображается некорректно 
![photo_2018-10-26_15-32-14.jpg](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/9cc1faf9-e658-4641-ac00-31f04772ddc9)

**Comment by daryasattarova** [comment]
<img width="320" alt="png" src="https://user-images.githubusercontent.com/42342756/47647570-6cab4900-db88-11e8-95c0-f3efc4e514ff.png">

**Comment by NickShtefan** [comment]
Так же необходимо вернуть плашку, когда пользователь нажимает на свой аватар (почему ты её опять отключили), с учетом того, что кнопки "подписаться и отписаться" не должны отображаться (было реализовано)

**Comment by daryasattarova** [comment]
**Не исправлено**
