### ISSUE TITLE
Баг с регистрацией через ВК

### ISSUE THREAD

**Issue by 0n0t0le** [GolosChain/tolstoy#124]
Довольно неприятный баг - встречал его ранее, думал уже кто-то отрепортил, но вроде не нашел.

При попытке регистрации юзеру выдается почта, на которую будет отправлено письмо для подтверждения. Прикол в том, что если юзер ранее (ХОТЬ РАЗ) менял почту, привязанную к аккаунту ВК - он видит именно этот (старый) адрес почты (без возможности редактирования). Зачастую доступ к данной почте юзером уже утрачен. Даже если он оперативно меняет почту в настройках ВК, форма регистрации все равно выдает ему старую.

Нужно копать либо в парсинге почты с ВК, либо еще проще - добавить возможность редактирования поля с адресом почты.

С ФБ вроде никто не отписывал по такой проблеме, но проверить не помешает.

**Comment by 21xhipster** [comment]
Это еще актуально?

**Comment by serejandmyself** [comment]
Да, недавно такое "отрепортили" опять

**Comment by serejandmyself** [comment]
Проверили несколько раз, действительно проблема есть. Но я снимаю это с "повестки" так как похоже вопрос больше к ВК, чем к Голосу. Голос парсит верно
