### ISSUE TITLE
Добавить СТА popup для незарегистрированных пользователей в новом дизайне

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/tolstoy#1240]
Добавить СТА popup для незарегистрированных пользователей в новом дизайне
https://github.com/GolosChain/tolstoy/issues/547
- Обновленный [web дизайн](https://app.zeplin.io/project/5ba9f49fb422725fe0f07dbf/screen/5ba9fafc130bb036df1c9a63) окон
- [мобильная верстка](https://app.zeplin.io/project/5ba9f49fb422725fe0f07dbf/screen/5ba9fae9c0d81b488dc233eb)

**Comment by AlexRekish** [comment]
#1510
