### ISSUE TITLE
Сделать ко всем элементам описания

### ISSUE THREAD

**Issue by denis-skripnik** [GolosChain/tolstoy#1247]
1. Элементам типа изображений (Иконки и т.п.): имеют вид ``<img src="">`` добавить атрибут alt="" с описанием того, что это. Например, у иконки апвота надпись "проголосовать" (Это пример - иконка там или нет, не знаю);
2. Кликабельным тегам p, div, span добавить текст с описанием. Пример:
``<span onclick="vote();">Проголосовать</span>``
Вместо:
``<span onclick="vote();"></span>``
То же самое касается иконок внутри тегов данного типа.

Второй пункт может быть представлен:
- Атрибутом onclick;
- Каким-то id, а затем обработкой при помощи javascript с использованием jQuery или без оного.

Буду благодарен за реализацию в редизайне.
**В настоящее время очень сложно пользоваться, так как нет понимания, что будет, если нажму на тот или иной элемент: просто озвучивается "по щелчку", без описания, типа "проголосовать".**
P. S. Примеры кода не являются действующими на golos.io, а взяты на основе опыта.

**Comment by daryasattarova** [comment]
комментарий Дениса: 
![image](https://user-images.githubusercontent.com/42342756/48332054-80b07980-e663-11e8-931b-641b7083ef36.png)

**Comment by daryasattarova** [comment]
![image](https://user-images.githubusercontent.com/42342756/48408171-b760bf80-e749-11e8-9c0e-e49ecbee6835.png)
описка!!!

+
![image](https://user-images.githubusercontent.com/42342756/48408195-c21b5480-e749-11e8-80bf-033904b8d036.png)
Исходя из ответа: нужно указать кол-во проголосовавших за и против.
