### ISSUE TITLE
Добавить меню смены языка интерфейса в хедер

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/tolstoy#1251]
- Добавить меню смены языка интерфейса в хедер. [Дизайн](https://app.zeplin.io/project/5ba9f49fb422725fe0f07dbf/screen/5ba9f650fc85293fd366f56c), [дизайн](https://app.zeplin.io/project/5ba9f49fb422725fe0f07dbf/screen/5ba9f6c59ffc5157e0b59ea7)
- Сделать синхронизацию с настройками

**Comment by MachtFrei** [comment]
1) при залогиненом пользователе нет менюхи
2) если мы переключаем язык а потом логинимся, язык слетает на тот который в настройках

**Comment by b1acksun** [comment]
выбор локали отображается только если не залогинен, про логине локаль сохраняется в настройках, если поменять локаль в настройках, сохранить а затем выйти - то да, будет отображаться последняя выбранная локать, тк она сохраняется в куку

**Comment by NickShtefan** [comment]
необходимо добавить отображение смены языка в header в том числе и для залогиненых пользователей

**Comment by MachtFrei** [comment]
а где дизайн?
![screenshot_15](https://user-images.githubusercontent.com/2689880/50084834-51180280-0209-11e9-8782-0bf144929588.png)
