### ISSUE TITLE
Добавить подсказку при вводе неверного ключа

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/tolstoy#1255]
войти https://sandbox.golos.io/
открыть окно авторизации
вести неверный пароль

результат короткая подсказка -неверный пароль

![image](https://user-images.githubusercontent.com/30616421/47639481-1202f480-db6a-11e8-8430-a756f48a9ea1.png)

Ожидаеммый результат получить расширенную подсказку

![image](https://user-images.githubusercontent.com/30616421/47639704-a79e8400-db6a-11e8-96c4-5c9349a6a466.png)

Добавить подсказку
при вводе активного ключа для постинг оппераций
Добавить подсказку
Привязан к главному ключу аккаунта и не может быть использован для входа на этот сайт. Вы можете использовать этот активный ключ на других более безопасных страниц, таких как страницы: Кошелек или Биржа. 

![image](https://user-images.githubusercontent.com/30616421/47639408-da944800-db69-11e8-932a-44d53d0cf8b8.png)
Добавить подсказку
Неверный пароль.
Ключ был введен неправильно. Вероятно,

**Comment by daryasattarova** [comment]
**Текущие текстовки:** 
1. ввод несуществующего имени
![image](https://user-images.githubusercontent.com/42342756/47640460-ba1dbb00-db74-11e8-8e00-62240e6bbc23.png)
2. при вводе постинг ключа, но который не принадлежит введенному имени
![image](https://user-images.githubusercontent.com/42342756/47640554-dfaac480-db74-11e8-9b09-a95249a4c9ad.png)
3. при вводе активного ключа 
![image](https://user-images.githubusercontent.com/42342756/47640681-2e585e80-db75-11e8-9ab0-0c383c51b73e.png)

**Comment by jevgenika** [comment]
https://github.com/GolosChain/tolstoy/issues/1260

**Comment by jevgenika** [comment]
[Дизайн окна](https://app.zeplin.io/project/5ba9f49fb422725fe0f07dbf/screen/5ba9fd72c0d81b488dc253a5)

**Comment by Bacher** [comment]
Не хватает дизайна ошибки про некорректность пароля, или он по аналогии с именем аккаунта под инпутом?

**Comment by Bacher** [comment]
Я у Аллы уточню детали, тут можно не отвечать.

**Comment by jevgenika** [comment]
при вводе активного ключа при входе
выводить предупреждение, но дать возможность войти с активным,  обьяснив, что его лучше для денежных оппераций.

Подзказка при авторизации активным ключом.
> Вы ввели ключ для денежных оперраций. Если вы не планируйте подобных действий на сайте, войдите с постинг ключом.

**Comment by daryasattarova** [comment]
в анонимном режиме при нажатии на лайк/дизлайк появляется окно авторизации вместо окна входа 
![image](https://user-images.githubusercontent.com/42342756/48137584-72550d00-e2b3-11e8-8184-c9b325fe57c2.png)

**Comment by Bacher** [comment]
В целом я понимаю, что тебя смущает. Сейчас попробую поправить.

**Comment by Bacher** [comment]
Поправится вместе с задачей #1361

**Comment by daryasattarova** [comment]
при нажатии на кнопку подписки (из любого места) появляется окно авторизации. заменить на вход

**Comment by daryasattarova** [comment]
не исправлено выше написанное

**Comment by Bacher** [comment]
Ждем мёржа PR https://github.com/GolosChain/tolstoy/pull/1545
