### ISSUE TITLE
Сплошной перевод ошибок

### ISSUE THREAD

**Issue by lehard** [GolosChain/tolstoy#126]
Ошибка простая:
Когда после вставки ссылки с аватаром ввожу пароль или любой ключ выбивает - ( Missing Active Authority ).

https://golos.io/ru--golos/@radogost/privet-mir-ya-radogost-i-ya-rozhdyon-chtoby-sdelat-golos-gostepriimnym-mestom#@desraben/re-radogost-re-desraben-re-radogost-privet-mir-ya-radogost-i-ya-rozhdyon-chtoby-sdelat-golos-gostepriimnym-mestom-20161115t171421377z

**Comment by lehard** [comment]
Еще один случай https://golos.io/ru--golos/@borishaifa/nevozmozhno-zagruzit-fotografiyu-profilya

**Comment by borishaifa** [comment]
Что, так и ничего не решилось? По-прежнему, не могу разместить аватарку. Смотрю и у вас глухо пока)

**Comment by Undeadlol1** [comment]
Без понятия в чем проблема

**Comment by Undeadlol1** [comment]
Что в поле пишите? Какой юрл вставляете?

**Comment by borishaifa** [comment]
Да самый обычный урл, например, этот
http://i042.radikal.ru/1611/a2/2c27c9f8f894.jpg
Но и другие пробовал, не хочет вставать, система, похоже пароль не
принимает для публикации аватарки
Я заходил в Голос со Стимита - может это как-то связано.
Но странно то, что не аппрувится ни с одним паролем, идёт запись
Missing Active Authority...

2016-12-15 9:36 GMT+02:00 Mihail Paley <notifications@github.com>:

**Comment by 21xhipster** [comment]
Похоже это потому, что сайт на котором вы хостите картинку выдает редирект на рекламную страницу. Попробуйте другой хостинг.

**Comment by borishaifa** [comment]
Ничего подобного, прбовал где-то с 10 разнх хостингов. Проблема в другом - это очевидно. Появляется команда о неподтверждении экаунта (после ввдения пароля), а не хостинга.

**Comment by borishaifa** [comment]
Без проблем, для чистоты эксперимента, взл ссылку на фото с сериса gmail http://s001.radikal.ru/i193/1701/ae/a51e6f70b4d5.jpg

**Comment by 21xhipster** [comment]
Эксперимент не очень чистый. Как видите по ссылке отдается не картинка, а вебстраница с рекламой. Поэтому у Вас и не выходит. Попробуйте что-нибудь типа https://habrastorage.org.
<img width="1311" alt="screen shot 2017-01-02 at 4 53 03 pm" src="https://cloud.githubusercontent.com/assets/410789/21586436/fd5ddf46-d10b-11e6-96ec-5b4d473339ea.png">

**Comment by borishaifa** [comment]
Можно и этот попробовать, но результат тот же
https://habrastorage.org/files/3b3/e8f/b1d/3b3e8fb1d1ee460da94a8ecaa37e480b.jpg

**Comment by 21xhipster** [comment]
Так это проблема в другом. Нужно просто активный ключ указывать, а не тот который для постинга. Вообще эту ищью надо переименовать в перевод ошибок.

**Comment by borishaifa** [comment]
Вот и я об этом!))) Тут ещё вот что. Я пробовал вводить все ключи, которые есть н Голосе. Не работают. Я думаю, что это происходит от того, что некоторые люди "перевелись" со Стимита (или это как-то связано), в том числе я, топикстартер и некоторые другие. Сразу попытался об этом сообщить в своём посте на Голосе, но видимо "не донёс". В кодировании я не силён, то бишь, вообще никак)) Но будучи учителем английского сразу понял, что всплывающая при установке команда не относится к картинке. Надеюсь, что еперь вы разберётесь, ребята. Удачи!!

**Comment by 21xhipster** [comment]
@borishaifa Попробуйте обновить свои ключи. Только конечно же очень аккуратно.

**Comment by borishaifa** [comment]
То есть, изменить их? Все или какие-то определённые?

**Comment by 21xhipster** [comment]
https://golos.io/@hipster/password

Только будьте очень аккуратны

**Comment by borishaifa** [comment]
Однако... Ситуация странная. Попытался обновить пароль. Сгенер ировал новый, записал, сохранил, но до конца обновление не прошло, вышла команда "expected, but need "c" Вышел из эккаунта, попробовал зайти по новому паролю... Система не пустила. Ввёл пароль от Стимита... Зашёл... Ничего не понимаю.

**Comment by 21xhipster** [comment]
Значит пароль не обновился

**Comment by 21xhipster** [comment]
Попробуйте ещё раз

**Comment by borishaifa** [comment]
Увы, снова выдаёт .... Expected '"' but read 'c' Не даёт обновить получается Ввод ил уже все абсолютно и тайные и скрутые ключи и пароли, всё что есть в кнопке "Разрешения"

**Comment by 21xhipster** [comment]
Приватный ключ должен начинаться на `5`. Для того, чтобы показать его нужно нажать на кнопку "войти чтобы показать"
<img width="1206" alt="screen shot 2017-01-03 at 11 34 54" src="https://cloud.githubusercontent.com/assets/410789/21599520/afce2324-d1a8-11e6-90f5-68ab82fc377b.png">

Вам не нужно перебирать ключи. Нужен Активный ключ

**Comment by borishaifa** [comment]
Сегодня на свежую голову попробовал ещё раз обновить пароль, ничего не получается, ввожу активный ключ, эффект тот же - Expected '"' but read 'c' Может попробовать воспользоваться кнопкой "ВОССТАНОВИТЬ ЭККАУНТ"?

**Comment by 21xhipster** [comment]
@Undeadlol1 есть какие идеи?

**Comment by Undeadlol1** [comment]
Нет, без понятия в чем проблема

**Comment by serejandmyself** [comment]
Это вообще актуально? @borishaifa

**Comment by borishaifa** [comment]
Да, Сергей, увы, проблема осталась. По прежнему, картинка не становится, точнее не авторизируется (подтверждается) паролем.

**Comment by serejandmyself** [comment]
Просьба проверить сейчас

**Comment by borishaifa** [comment]
У меня сейчас выдаёт 502 Bad Gateway

**Comment by serejandmyself** [comment]
Почисти кеш / куки / историю

**Comment by borishaifa** [comment]
Странно, пока ничего не получается, пробую ещё, нажимаб на кнопку обновить и.. тишина

**Comment by borishaifa** [comment]
а сейчас и вовсе кнопка почти исчезла, только при наведении появляется, но не активна, нет допуска к обновлению

**Comment by serejandmyself** [comment]
мдааа. боюсь что все это локально, но инфы не достаточно в описаниях. Надо бы ка кто это все на яву увидеть

**Comment by borishaifa** [comment]
Вот скриншот https://habrastorage.org/files/f38/ddf/e1a/f38ddfe1a5724ef184f17817119782ac.jpg

**Comment by borishaifa** [comment]
Это фотография с хабра, то же и с другими фотохостингами

**Comment by serejandmyself** [comment]
Попробуй обновить страницу и загрузить прямую ссылку, например с postimage

**Comment by borishaifa** [comment]
то же самое https://postimg.org/image/45sh1gxit/

**Comment by serejandmyself** [comment]
Так стопе... ты вставляешь не ПРЯМУЮ ССЫЛКУ, а просто ССЫЛКУ

**Comment by borishaifa** [comment]
Я уже и такую и такую пробовал и эту https://postimg.org/image/l51fgq8qd/ и эту https://s26.postimg.org/7bd2rog55/main_fb_768x730.jpg Как заколдованное все

**Comment by serejandmyself** [comment]
https://s21.postimg.org/oxq3ycfg7/main_fb_768x730.jpg

эту ставь

**Comment by serejandmyself** [comment]
Такого не бывает )

**Comment by borishaifa** [comment]
Прикидываешь, оказывается, бывает))) https://s26.postimg.org/ry1sczzjt/posimage2.jpg

**Comment by borishaifa** [comment]
Давай дам все пароли, зайди сам проверь, дай только мыло куда сбросить

**Comment by serejandmyself** [comment]
А другие поля обновить можешь попробовать?

**Comment by serejandmyself** [comment]
Нет, нет. Пароли не надо

**Comment by borishaifa** [comment]
Нет, не ничего не даёт обновить

**Comment by borishaifa** [comment]
Язык дал английский поменять

**Comment by borishaifa** [comment]
Больше ничего, и то сначала русский выплывает, а через секунду на английский меняется

**Comment by borishaifa** [comment]
Сегодня хотел перевести GBG в гоЛОС тоже не получилось. Система не признаёт ни один из моих паролей, ничего не даёт делать вообще - ни поменять, ничего.  Зайти и выйти из эккаунта даёт. И больше ничего. Интересно, что в когда нажимаю кнопку в РАЗРЕШЕНИЯХ  - в ОБСУЖДАЕМОЕ - ВОЙТИ, ЧТОБЫ ПОКАЗАТЬ  пароль ни один не проходит, а вместо логина у меня там почему-то стоит не borishaifa, a borishaifa/active

**Comment by serejandmyself** [comment]
Ты залогинен под актив паролем. 

Что значит не признает? Что пишет?

**Comment by borishaifa** [comment]
Можешь сам всё посмотреть, я не переживаю, если там пропадут все деньги, всё нормально, главное, чтобы понять что происходит, иначе мне смысла нет оставаться в этом логине.
ПОСТИНГ
GLS4vkdWDX9ZBHX8mNDLgPGkqQ8SN24Rh5bRGxrrDc5hixJUXSWv2
ПОКАЗАТЬ ПРИВАТНЫЙ КЛЮЧ
Постинг ключ используется для постинга и голосования. Он должен отличаться от активного и ключа владельца.
Вот этот пароль выходит после  - ПОКАЗАТЬ приватный ключ
5KMMkcMiYxstXRxuKqbavseEwW3bTFyqTDE4tx6e2688We4sfdJ

ОБСУЖДАЕМОЕ
GLS5FphWZU8wacDrZ8L8yPNHX2umYnUAJbkrNL6bqricDdtaz4z3e
ВОЙТИ ЧТОБЫ ПОКАЗАТЬ
Активный ключ используется для переводов и размещения заказов на внутреннем рынке.
ВЛАДЕЛЕЦ
GLS72r5JQTJuEqibWJ4n4H83xUdbhq6wDmH7D9na7hzzsxd7hwc1T
Ключ владельца, это главный ключ аккаунта, он необходим для изменения других ключей.
Приватный ключ или пароль должен храниться в оффлайне так часто насколько это возможно.
ЗАМЕТКА
GLS7ZcHyqsy5SotHzkMaXxoQjAXQncJEPooyWrDBnimahRRxiuEUR
Ключ заметок используется для создания и чтения заметок.

**Comment by serejandmyself** [comment]
Ок... Ты скинул набор паблик ключей и приватный постинг ключ. С постинг ключом я вхожу и выхожу из акаунта. Все здорово. Под ним тебе и надо юзать платформу

Не пойму в чем проблема. Тебе нужен Приватный актив ключ для переводов (ну или мастер, тот который был при создании). Чтобы посмотреть другие.

Убедительная просьба, не скидывать приватные мастер / актив и тд сюда

**Comment by borishaifa** [comment]
Всё, я их убрал. Вот дальше начинается проблема, я точно ничего не создавал, а тупо перевёлся со стимита, по какой-то ссылке, когда она там предлагалась. У меня нет никаких больше ни паролей - ничего, только то, что указал ранее.

**Comment by serejandmyself** [comment]
Я не пойму в чем проблема пока что.

Ты когда аккаунт в стиме создавал, тебе был выдан пароль... Это и есть "мастер". Ты под каким паролем заходишь в Голос?

**Comment by borishaifa** [comment]
Не понял... Что мастер Стимита - это и есть мастер голоса7

**Comment by serejandmyself** [comment]
Ты же их не менял...

**Comment by borishaifa** [comment]
Твою мать))) Извиняюсь.... дошло наконец. Получается, надо везде юзать мастер со стимита... Дурдом, столько мозгоделки. Спасибо за терпение, Сергей. Сейчас попробую и фотку поставить.

**Comment by serejandmyself** [comment]
Только поправочка... желательно юзать не "мастер", а записать свой актив и юзать его. Но  да, мастер тоже пойдет
