### ISSUE TITLE
заголовок в окне авторизации

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/tolstoy#1260]
зайти https://sandbox.golos.io/
нажать на лайк/ дизлайк/ написать пост

результат
![image](https://user-images.githubusercontent.com/30616421/47644979-56958c80-db78-11e8-9784-e98d5623900f.png)

ожиданный результат
окно авторизации  новом дизайне, но с текстовой подсказкой
текст: Войдите, чтобы выполнить это дейтсвие
![image](https://user-images.githubusercontent.com/30616421/47645183-e4717780-db78-11e8-8961-c3a267e8a008.png)

**Comment by daryasattarova** [comment]
варианты, когда появляется окно авторизации в анонимном режиме
при нажатии на:
- экран профиля
1. лайк
2. дизлайк
3. подписаться
4. реблог
5. "В избранное"
6. "Передать"
7. "Делегировать СГ"

-экран поста
1. подписаться
2. заблокировать
3. "В избранное"
4. лак (боковая панель + футер)
5. дизлайк (бок. панель + футер)
6. реблог
7. share
8. "Отблагодарить"
9. добавление комментария
10. добавление ответа

-лента
1. реблог
2. лайк
3. дизлайк
4. "В избранное"

**Comment by jevgenika** [comment]
[дизайн окна](https://app.zeplin.io/project/5ba9f49fb422725fe0f07dbf/screen/5ba9fd72c0d81b488dc253a5)

**Comment by jevgenika** [comment]
Заголовоки окна в анонимном режиме
на экранах профиль, лента, экран поста и в боковой панели страницы поста
при клике на лайк, дизлайк - Войдите, чтобы проголосвать
при клике на подписаться -Войдите, чтобы подписаться
при клике на реблог -Войдите, чтобы поделиться записью
при клике на В избранное" -Войдите, чтобы добавить в избранное
при клике на "Передать" -Войдите, чтобы передать
при клике на "Делегировать СГ" -Войдите, чтобы делегировать

на страницы поста
при клике на при клике на заблокировать- Войдите, чтобы заблокировать
при клике на share -Войдите, чтобы поделиться записью
при клике на "Отблагодарить" -Войдите, чтобы отблагодарить автора
при клике на добавление комментария -Войдите, чтобы добавить комменатрий
при клике на добавление ответа -Войдите, чтобы добавить ответ

**Comment by Bacher** [comment]
![image](https://user-images.githubusercontent.com/2598671/47919985-e6fa0700-dec1-11e8-964d-9b19638776e0.png)

Сделал унифицированное окно подтверждения.
Отображать на какое именно действие требуется подтверждение я думаю нет смысла, так как оно возникает ровно после действия пользователя.

**Comment by Bacher** [comment]
Код изменений совмещен с задачей #1255 
https://github.com/GolosChain/tolstoy/pull/1409
