### ISSUE TITLE
При просмотре уведомлений во вкладке "Активность" цифра на колокольчике не сбрасывается

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/tolstoy#1265]
Воспроизведение:
1. открыть песочницу
2. авторизоваться
3. (при условии, что в колокольчике висят уведомления) перейти во вкладку "Активность"

Ожидаемый результат: т.к. уведомления по факту просмотрены во вкладке, то цифра на колокольчике должна обнулиться
Реальный результат: цифра остается на колокольчике при просмотре уведомлений через вкладку "Активность"

**Comment by beautyfree** [comment]
При получение активности, в редьюсере, нужно брать summary и сохранять в стор

![image](https://user-images.githubusercontent.com/656531/47783362-8dec7080-dd13-11e8-9339-2828b6f21c99.png)
