### ISSUE TITLE
Неверная оценка стоимости аккаунта

### ISSUE THREAD

**Issue by lehard** [GolosChain/tolstoy#127]
Неправильно отображается оценка стоимости аккаунта в кошельке на golos.io
Цена 1 Голоса сейчас примерно 30 копеек. Сайт отображает исходя из курса 2,7 рубля

**Comment by 0n0t0le** [comment]
Так точно

**Comment by litrbooh** [comment]
Она почему скачет иногда примерно на порядок.

**Comment by Undeadlol1** [comment]
Леша починил.
