### ISSUE TITLE
кнопки "подписаться" на экране поста не кликабельные

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/tolstoy#1270]
Ожидаемый результат: при клике должна осуществиться подписка
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/d39b1daf-47d9-4b85-8009-c215768b2ed1)
![image](https://user-images.githubusercontent.com/42342756/47656530-4a252a00-dba0-11e8-80f2-37580f554d37.png)

Реальный результат: ничего не происходит

**Comment by Bacher** [comment]
Пофиксил при решении задачи #1207
