### ISSUE TITLE
(не стабильно) при открытии окна создания поста появляется белый экран 

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/tolstoy#1273]
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/2ecd74ff-baa5-475f-aa30-275064dd4d27)

**Comment by muhazzz** [comment]
на sandbox вообще нет рэйтлимитов, проблема не в них

**Comment by Bacher** [comment]
Может ошибку получилось словить в момент выкатки новой версии? Да, я думаю это из-за этого.

**Comment by Bacher** [comment]
Если окно браузера было открыто до выкатки, а страница поста открылась после выкатки, то файлы нужные приложение уже не найдет на сервере.

**Comment by Bacher** [comment]
Короче это проблема. Поскольку у нас выкатка происходит через Docker, то все старые файлы тут же удаляются при релизе. И получается если человек зашел к нам на сайт, потом мы выкатили новую версию, и после этого он пытается написать пост, файлов отвечающих за пост уже нет на сервере.

Это по любому надо фиксить, вопрос как.
