### ISSUE TITLE
Таймер ICO не переключился на 20%

### ISSUE THREAD

**Issue by gamerate** [GolosChain/tolstoy#128]
![screenshot from 2016-11-16 14-34-28](https://cloud.githubusercontent.com/assets/954529/20345795/da0c574c-ac09-11e6-8f45-56a16d7550d4.png)
На странице ICO и в профайле по прежнему показывает 25% и отрицательное время до переключения на 20%
Это плохо тем, что кто-то может вложиться ожидая что 25% еще активны и потом будет приходить жаловаться, что ему посчитало не 25% а 20%.

**Comment by tomarcafe** [comment]
пока могу только рекомендовать к ознакомлению и распространению https://golos.io/ru--poprichincheskimtekhninam/@pio/pro-bonusy-za-rannii-vkhod-v-ico

**Comment by Chiliec** [comment]
Уже переключился, можно закрывать :)

**Comment by gamerate** [comment]
На главной теперь все ок - но в профайле на странице краудсейла пока баг сохраняется:
Минимальная Покупка	Максимальная Покупка	Текущий Бонус	Бонус уменьшится
0.001 биткоина	100 биткоинов	25%	8 часов назад

**Comment by tomarcafe** [comment]
список покупок на крауде - вьюха расширится. добавится колонка "бонус". в ней будет указан размер бонуса на покупку - соотв от 25% до 5%
т.к. транзакции упорядочены по времени, смотреть будет достаточно удобно. 

и, возможно, рядом будет небольшая табличка с пояснением расчётов

**Comment by tomarcafe** [comment]
@Undeadlol1  привет.

**Comment by Chiliec** [comment]
Почему-то для лендинга взяли и захардкодили значения https://github.com/GolosChain/tolstoy/commit/12d63be8dae1c65350c2064a30e1241777d5c1cd
Но это плохо, поэтому не решусь делать такой PR для профайла на странице краудсейла.
