### ISSUE TITLE
некорректное отображение ссылок в кошельке

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/tolstoy#1289]
Воспроизведение:
1. открыть песочницу
2. авторизоваться
3. перейти в кошелек

Ожидаемый результат: ссылки всегда должны отображаться корректно.
Реальный результат: ссылки некорректные

![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/2ea662dd-e785-4c37-b81c-2a7075d31c01)

**Comment by Bacher** [comment]
Бага там нет, это такие текста просто прикреплены к транзакциям.
Это надо править ботов. Мы по сути только отображаем текст который есть в транзакции ищем там ссылки.

**Comment by daryasattarova** [comment]
закрывать карточку?

**Comment by Bacher** [comment]
Даже не знаю. В целом мы можем парсить сообщения от `@robot` и немного менять их отображение. Но в любом случае это будет фича, не баг. Но это только когда время будет.

**Comment by Bacher** [comment]
Вернул в TODO.
