### ISSUE TITLE
обновить список пользователей в соотвествии с дизайном

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/tolstoy#1290]
Воспроизведение:
зайти на https://sandbox.golos.io
навести на футор поста в ленте
навести на число проголосовавших

Результат:
![image](https://user-images.githubusercontent.com/30616421/47708986-fd8d2d80-dc37-11e8-9748-e24289c01ed6.png)

Ожидаемый результат:
обновить список пользователей в соотвествии с[ дизайном](https://app.zeplin.io/project/5ba9f49fb422725fe0f07dbf/screen/5bc4915f23bfd05fb6e4c5f2)
![image](https://user-images.githubusercontent.com/30616421/47903023-c8791900-de8b-11e8-84a5-f78d6e80bb22.png)

сделать переход на открытое окно со списком проголосовавших за пост

**Comment by jevgenika** [comment]
добавлен [дизайн окна](https://app.zeplin.io/project/5ba9f49fb422725fe0f07dbf/screen/5bc4915f23bfd05fb6e4c5f2)

**Comment by daryasattarova** [comment]
поправить углы в соответствии с дизайном
