### ISSUE TITLE
Ограничить высоту <div>, добавить прокрутку "scroll-y"

### ISSUE THREAD

**Issue by tomarcafe** [GolosChain/tolstoy#130]
когда редактируешь длинный пост - неудобно выходит, что окошко редактирования скролится - в нём всё рядом. а окошко предварительного просмотра тупо имеет высоту своего контента. и получается когда редактируешь длинную телегу - то чтобы посмотреть превьюшку изменений - надо скролить экран - а потом скролить обратно в редактор.

предложение - ограничить высоту окошку предпросмотра, типа например так - `max-height: 20em;` ну и сделать его scrollable

**Comment by 0n0t0le** [comment]
Дико напрягает, ага+

**Comment by litrbooh** [comment]
а меня наоборот напрягает узкое окно редактирования комментария, если коммент большой

**Comment by Undeadlol1** [comment]
Поле редактирования увеличино
