### ISSUE TITLE
Орфографическая ошибка в окне делегирования сг

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/tolstoy#1312]
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/2203a783-5266-4195-b8a9-82edfb8e00d7)
Исправить на Дел**Е**гировать

**Comment by rodnikova** [comment]
И еще одна опечатка в заголовке. Должно быть «Делегировать Силу Голоса», а не «Делегировать Силу Голос»
