### ISSUE TITLE
Подключить SDK amplitude.com в приложение Android

### ISSUE THREAD

**Issue by Azarod** [GolosChain/tolstoy#1314]
- [ ] трекать открытие приложения

**Comment by NickShtefan** [comment]
Issue moved to [GolosChain/golos-android #130](https://github.com/GolosChain/golos-android/issues/130) via [**ZenHub**](https://www.zenhub.com/)

**Comment by NickShtefan** [comment]
Issue moved to [GolosChain/golos-android #131](https://github.com/GolosChain/golos-android/issues/131) via [**ZenHub**](https://www.zenhub.com/)
