### ISSUE TITLE
Сделать ссылку на статистику ICO со странички лэндинг

### ISSUE THREAD

**Issue by serejandmyself** [GolosChain/tolstoy#132]
Запрс в редиме лайв - Вечер с Голосом 

Ссылки можно дать на:

http://www.steeme.ru/gf.html

ИЛИ

http://steemul.ru/top/?tab=ico

Миша Спасибо тебе!

**Comment by primusd** [comment]
Комментарий: вторая ссылка берёт данные с http://www.steeme.ru/gf.html т.е. именно эта ссылка является первоисточником данных, на steemul затем идёт трансляция данных из этого же источника.

Так что если ставить ссылку - лучше на первоисточник.

**Comment by AlekseiSmirnov** [comment]
Предлагаю сделать этот таск в приоритете, т.к. сегодня-завтра про ICO будут писать Rusbase и VC.ru и оттуда пойдет трафик. Было бы неплохо, чтобы к этому времени ссылка на табличку Примуса уже была на лендинге

**Comment by Undeadlol1** [comment]
Куда именно ссылки вставлять? Что конкретно нужно?

**Comment by serejandmyself** [comment]
[![Безымянный.jpg](https://s13.postimg.org/3yf23l9mv/image.jpg)](https://postimg.org/image/xqc4irwg3/)

И в слово статситика вставить ссылку на http://www.steeme.ru/gf.html

Только конечно не в таком виде как я нарисовал... Лучше назвать это не просто статистика, а :
СТАТИСТИКА ПО КРАЙДСЕЙЛУ В РЕАЛЬНОМ ВРЕМЕНИ

**Comment by Undeadlol1** [comment]
Сережа, ничего не видно в картинке

**Comment by serejandmyself** [comment]
[![Безымянный.jpg](https://s22.postimg.org/vrg6zrlg1/image.jpg)](https://postimg.org/image/v1xenekwd/)

**Comment by gamerate** [comment]
Только не на http://www.steeme.ru/gf.html а на http://www.steeme.ru/golos-ico.html
