### ISSUE TITLE
Пропала кнопка поиска по сайту голоса

### ISSUE THREAD

**Issue by AlekseiSmirnov** [GolosChain/tolstoy#135]
Пропала кнопка поиска по сайту.
![2016-11-19_21-34-42](https://cloud.githubusercontent.com/assets/10200871/20457603/025ac39e-aea0-11e6-802d-77a32818e7e9.png)

Без нее навигация и поиск по стали намного сложнее

**Comment by Undeadlol1** [comment]
Она выключена специально до тех пор пока не будет починен кастомный гуглопоиск.

**Comment by tomarcafe** [comment]
круто. а как мы поймем что он починен?

**Comment by Undeadlol1** [comment]
Вот как https://github.com/GolosChain/tolstoy/issues/13
