### ISSUE TITLE
Скрывать из ленты посты с отрицательным рейтингом и спец. тегами

### ISSUE THREAD

**Issue by litrbooh** [GolosChain/tolstoy#136]
Сейчас в ленте отображаются посты с отрицательным рейтингом (хотя и бледно-серым), а также показываются посты с тегами #мат #ню #18+ #порно

Предлагаю сделать так, чтобы посты с отрицательным рейтингом и спец. тегами скрывались сражу же в ленте за табличками: 
"пост скрыт из низкого рейтинга"
"пост содержит мат"
"пост с голыми сиськами"
и тп. 

Предложение родилось от сюда: https://golos.io/ru--golos/@jerlis/flag

**Comment by Gutalean** [comment]
Я считаю, что сокрытие таких постов должно быть настраиваемым, т.е. только если пользователь поставил соответствующие галочки у себя в аккунте на golos.io.

**Comment by jerlis** [comment]
Вопрос в том, что люди могут размещать контент не размещая при этом теги. Речь была о флагнутых постах.

**Comment by primusd** [comment]
Да, надо скрывать флагнутые посты из ленты на главной golos.io

В блоге автора показ флагнутых постов оставить без изменений, т.е. скрывать бледно-серым, как сейчас. А вот с из глобального "нового" их следует убрать.

**Comment by Chiliec** [comment]
Поддерживаю настраиваемость, однако для незарегистрированного пользователя они вообще никак не должны быть доступны, чтобы хотя бы отсрочить блокировку от РКН и не давать таким постам влиять на ранжируемость в поисковых системах. Внутри анархия, снаружи - строгая цензура :)

**Comment by litrbooh** [comment]
Gutalean, Chiliec - да, думаю настройка нужна типа : показывать посты с:
- низким рейтингом
- матом
- ню

jerlis, не разместил тег - получи флаг и скройся в связи с низким рейтингом.

**Comment by jerlis** [comment]
@21xhipster читает тему?

**Comment by 0n0t0le** [comment]
Считаю как вариант решения - добавить кнопку репорта, отрепорченные посты (имеющие достаточное количество флагов) и набравшие определенное число репортов будут скрываться автоматически, либо в ручную клиент модераторами (придется ввести новые должности?)
Почему это важно? посты с матами и оскорблениями - пол беды, а вот если кто то запостит ЦП, или что похуже - сколько времени уйдет прежде чем фронтэндер выпилит контент с клиента? 
- час
- 5 часов
- сутки

**Comment by tomarcafe** [comment]
до 3го-4го декабря можно просто слать команде основателей. а то и до первых выплат :) как бы основные интересанты на данном этапе

**Comment by tomarcafe** [comment]
мы флагуем наглухо

**Comment by 0n0t0le** [comment]
Флагуете наглухо, или выпиливаете полностью с клиента?

**Comment by 21xhipster** [comment]
Я не против это имплиментировать, над ресурсами команды, над формированием которой мы сейчас работаем. Если честно не видел ни одного похабного поста на данный момент. ИМХО есть задачи приоритетнее

**Comment by serejandmyself** [comment]
NSFW функционал в новом ХФ
