### ISSUE TITLE
окно авторизации не закрывается после ввода активного ключа

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/tolstoy#1361]
Воспроизведение:
1. открыть песочницу
2. авторизоваться
3. перейти в профиль
4. открыть окно "передать"
5. ввести кому и сколько нужно передать и нажать кнопку "передать"
6. в окне авторизации ввести активный ключ и подтвердить

Ожидаемый результат: окно авторизации должно закрыться и транзакция по передаче должна быть выполнена
Реальный результат: окно авторизации не закрывается

**Comment by Bacher** [comment]
У меня не получается воспроизвести. Можешь уточнить как надо воспроизводить? И стабильно ли воспроизводится?

**Comment by Bacher** [comment]
И, есть ли ошибки в консоли при этом?

**Comment by NickShtefan** [comment]
Стабильно воспроизводится на странице https://golos.io/~witnesses
Ошибка в консоли

![image](https://user-images.githubusercontent.com/6249597/48266032-bf2a1680-e460-11e8-9f45-1134cfb9a137.png)

**Comment by Bacher** [comment]
@NickShtefan Да, как воспроизвести нашли.

**Comment by daryasattarova** [comment]
исправить закрытие окна без нажатого чекбокса

**Comment by Bacher** [comment]
Ошибку на https://golos.io/~witnesses поправил.

**Comment by daryasattarova** [comment]
1. как только отмечаешь чекбокс , то появляется ошибка 
![image](https://user-images.githubusercontent.com/42342756/48554736-43ace700-e8f0-11e8-9de9-6d2c3939ed06.png)

**Comment by Bacher** [comment]
> 1. как только отмечаешь чекбокс , то появляется ошибка
>    ![image](https://user-images.githubusercontent.com/42342756/48554736-43ace700-e8f0-11e8-9de9-6d2c3939ed06.png)

Сейчас не воспроизводится.

**Comment by daryasattarova** [comment]
1. открыть окно делегатов (анонимный режим)
2. нажать на апвоут
3. в окне авторизации ввести данные и убрать чекбокс
4. нажать кнопку "подтвердить"

Реальный результат: ничего не происходит

**Comment by daryasattarova** [comment]
не реализован комментарий, написанный выше
