### ISSUE TITLE
Иногда возникает белый экран при логине

### ISSUE THREAD

**Issue by Bacher** [GolosChain/tolstoy#1365]
Ошибку потерял, но она звучала примерно так
```
Max call stack exceeded
from
HelmetWrapper
```

**Comment by daryasattarova** [comment]
вот она
![image](https://user-images.githubusercontent.com/42342756/47857976-09c1e800-ddfc-11e8-9462-d1e884539b0f.png)
![image](https://user-images.githubusercontent.com/42342756/47857996-11818c80-ddfc-11e8-8886-423843827b98.png)

**Comment by Bacher** [comment]
Вот на всякий случай обсуждение этой баги
https://github.com/nfl/react-helmet/issues/373
