### ISSUE TITLE
Постоянная анимация загрузки при просмотре блога пользователя

### ISSUE THREAD

**Issue by Gutalean** [GolosChain/tolstoy#137]
При просмотре списка постов пользователя (раздел "блог" профиля) и прокрутке до самого первого поста нету сообщения, что это первый пост и более ранних постов у пользователя нет. Вместо этого появляется значок подгрузки новых постов, хотя подгружать уже больше нечего. Значок висит бесконечно долго, вводя в заблуждение.

**Comment by Undeadlol1** [comment]
Не актуально, похоже Леша исправил.
