### ISSUE TITLE
Всегда показывается слайдер при лайке/дизлайке

### ISSUE THREAD

**Issue by Bacher** [GolosChain/tolstoy#1371]
Всегда показывается слайдер при лайке/дизлайке

![image.png](https://images.zenhubusercontent.com/5b0ff4b64b5806bc2bd5811e/1a1dd45c-2213-479e-8a3e-909add68876a)

**Comment by jevgenika** [comment]
Если в настройках выставлена мощность голосоа по умолчанию, не выводить слайдер
