### ISSUE TITLE
Дать возможность добавлять свои посты в избранное

### ISSUE THREAD

**Issue by gropox** [GolosChain/tolstoy#1378]
В избранное можно добавить только чужие посты. Звездочка отсутствует на своих постах.

**Comment by jevgenika** [comment]
@gropox своои посты можно закреплять - пинить

**Comment by jevgenika** [comment]
Избранные посты отображаться во вкладке «Избранное»,
закрепленные - в ленте вашего блога, сверху. Закрепить можно максимум пять постов.

**Comment by gropox** [comment]
Запилить можно только один какой то. У меня есть несколько постов с инструкциями, которые переодически спрашивают. Приходится мотать ленту, пока не найду нужное. Можно конечно в браузере закладок понаделать, но зачем тогда Избранное?

**Comment by jevgenika** [comment]
запинить можно максимально 5 постов

**Comment by gropox** [comment]
Я считаю, что запинить != добавить в избранное. Запинить скорее для посетителей, а закладки для себя.

Можно в принципе и в запиненном посте накидать ссылок. Если с избранным трудно сделать

**Comment by jevgenika** [comment]
Посты добавленные в избранное публично открыты и отображаются в профиле пользовталя.
Закрепленные посты  -посты автора, которые он закрепил, так же публично отображаются во вкладке блоги и окне с краткой информацией об авторе.

Вы можете создать свой пост с инструкциями и закрепить его. Он будет выше остальных ваших постов в блоге, а также закреплен в окне об авторе.

**Comment by Bacher** [comment]
> Посты добавленные в избранное публично открыты и отображаются в профиле пользовталя.

Нет, избранные посты не отображаются публично. Видны только свои избранные посты.

**Comment by daryasattarova** [comment]
не работает добавление в избранное из компактного меню 
![image](https://user-images.githubusercontent.com/42342756/49290615-7d691a80-f4b8-11e8-8a7f-cdb4ae9f3fed.png)
