### ISSUE TITLE
Настройки: добавить настройку мощности голоса по умолчанию

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/tolstoy#1382]
Добавить настройку мощности голоса по умолчанию
Синхронизировать между девайсами
![image](https://user-images.githubusercontent.com/30616421/47904022-307c2f00-de8d-11e8-8284-4bdbe88eb399.png)

Текст
Настройка мощности голосования
Мощность голосования

[Дизайн](https://app.zeplin.io/project/5ba9f49fb422725fe0f07dbf/screen/5ba9f83d205428703d134d02)
[Дизайн моб верстки](https://app.zeplin.io/project/5ba9f49fb422725fe0f07dbf/screen/5ba9f83a9b7041902de7b2d3)

при выставлении мощности голосования по дефолту
отменяется условие всегда отображать слайдер при голосовании https://github.com/GolosChain/tolstoy/issues/1371

**Comment by NickShtefan** [comment]
Необходимо добавить чекбокс (по умолчанию false) "использовать настройки голосования"
Если пользователь устанавливает состояние в true, 

- [ ] Ниже появляется слайдер для настройки процентов
- [ ] По умолчанию состояние слайдера установлено в 100%
- [ ] При голосовании за пост/комментарий происходит автоматическое голосование с установленным в слайдере значением. 

У пользователей c < 1000000 GEST данная опция отсутсвует
