### ISSUE TITLE
Устаревшая информация об ответах и комментариях при просмотре профиля

### ISSUE THREAD

**Issue by AlekseiSmirnov** [GolosChain/tolstoy#139]
Иногда, когда заходишь в профиль пользователя (комментарии и ответы) отображается устаревшая информация (наример, показывает что последний комментарий был 17 часов назад, хотя комментарии были и 10минут и час назад). Переключение между вкладками информацию не обновляет. Только после полного релоуда страницы (f5 или ctrl+f5) начинает отображаться актуальная информация.

Браузер - chrome

**Comment by 21xhipster** [comment]
Причина была на стороне серверов. Это когда одна из нод виснет, и отдает несвежую инфу. Вроде пофиксили.
