### ISSUE TITLE
значок уведомлений не соответствует дизайну в mozilla

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/tolstoy#1390]
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/21d982c0-13c8-425f-8186-e6a40cdb79b8)

**Comment by daryasattarova** [comment]
не исправлено. обводка значка не убрана
![image](https://user-images.githubusercontent.com/42342756/48130731-a40fa900-e29e-11e8-9dd3-d86005da2bce.png)
Ожидаемый результат: 
![image](https://user-images.githubusercontent.com/42342756/48130776-ce616680-e29e-11e8-8d32-68df49acdb35.png)

**Comment by b1acksun** [comment]
![image](https://user-images.githubusercontent.com/3322340/48140209-fc4fa680-e2b0-11e8-8a11-d8e1fcbda64d.png)
