### ISSUE TITLE
какая-то фигня с текущим бонусом и таймерами

### ISSUE THREAD

**Issue by tomarcafe** [GolosChain/tolstoy#140]
<img width="593" alt="screen shot 2016-11-20 at 12 38 26" src="https://cloud.githubusercontent.com/assets/1535817/20462182/56ccf5f4-af1e-11e6-8df6-9f7e5dc37246.png">

 UTC 10:39, 12:39 калининград,

**Comment by Undeadlol1** [comment]
Не могу воспроизвести, еще актуально?

**Comment by Undeadlol1** [comment]
Хотя, нет, не актуально, таймера уже нет.
