### ISSUE TITLE
при переходе по тегу "emoji" ничего не находит (ошибка в консоли)

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/tolstoy#1400]
https://sandbox.golos.io/@joseph.kalu/favorites
1. нажать на тег emoji
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/a206076c-6605-4fc6-90ac-a7813bcb9418)

**Comment by beautyfree** [comment]
Действительно не отображалось сообщение, что постов нет.
Блокчейн по данному тегу не отдает посты, т.к в трендинге нет постов с данным тегом
