### ISSUE TITLE
некорректное отображение в mozilla анимации

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/tolstoy#1401]
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/e3c8675e-6282-4248-879c-1ef6b2eab44e)

**Comment by Bacher** [comment]
Какая версия? У меня в 63 не воспроизводится.

**Comment by Bacher** [comment]
На маке тоже не воспроизводится.

**Comment by Bacher** [comment]
Отключил анимацию для Edge и Firefox.
