### ISSUE TITLE
под комментарием всегда выплаты отображаются целым числом

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/tolstoy#1402]
в настройках установлено "три знака после запятой". в комментариях всегда отображается целое число
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/c682671d-06c7-4df3-8599-5955b6df1b34)

**Comment by Bacher** [comment]
Должно быть 0.000? Мне кажется 0 лучше. Как правильно?

**Comment by Bacher** [comment]
![image](https://user-images.githubusercontent.com/2598671/47927952-c9369d00-ded5-11e8-8ef2-84df62983ac6.png)
