### ISSUE TITLE
добавить предупреждение на дизлайк

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/tolstoy#1405]
Добавить предупреждение при нажатии на дизлайк, как это было в старой версии с флагом.
Текст использовтать тот же
[Дизайн окна](https://app.zeplin.io/project/5ba9f49fb422725fe0f07dbf/screen/5bd7185dc19e0709b994d69d)
![image](https://user-images.githubusercontent.com/30616421/47915824-bfe50a80-deac-11e8-9c4f-4601e81c4d4c.png)

**Comment by daryasattarova** [comment]
1. убрать точки и точки с запятыми
2. сделать заглавные буквы у каждого пункта
![image](https://user-images.githubusercontent.com/42342756/48263705-1667c100-e438-11e8-8114-259898476334.png)
