### ISSUE TITLE
Стрелочки которые листают влево и вправо скрывают текст на мобильных устройствах

### ISSUE THREAD

**Issue by serejandmyself** [GolosChain/tolstoy#141]
Так же я бы убрал бэкграунд цвет - сделал бы его прозрачным 

(Стрелочки которые появляются при открытие статьи)

**Comment by tomarcafe** [comment]
свернём эту дискуссию на том, что стрелочки работают сейчас только в просмотре по тагам, а блог юзера либо главную не отрабатывают

**Comment by serejandmyself** [comment]
Пользователи выходят с сайта из за этого с мобильных устройтсв, так как это скрывает текст статьи
