### ISSUE TITLE
ошибка локализации в плашке при наведении на значок списка

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/tolstoy#1410]
добавить английский и украинский перевод
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/c4d1978b-c908-46cb-a01a-ceae55047d79)

**Comment by daryasattarova** [comment]
украинский язык не добавлен

**Comment by b1acksun** [comment]
https://github.com/GolosChain/tolstoy/commit/538082a906488a85d88114fc0d10b74140a2cdcd#diff-026da282da7ac235e89d3ccb49b8aa83R173
