### ISSUE TITLE
в меню "краудсейл" не все транзакции

### ISSUE THREAD

**Issue by govantage** [GolosChain/tolstoy#143]
14SJ4h8oc46BWXHKfaZVebipuqxEuwPkeM
0.86123474 BTC - в меню
1.06123474 BTC - по факту
Спасибо за внимание!

**Comment by 0n0t0le** [comment]
Аналогично:
https://golos.io/@dmilash/crowdsale
https://blockchain.info/address/1LUufG4ZCgUHDKV7bS5tGeViLgwkJTrHWt

**Comment by Undeadlol1** [comment]
@tomarcafe Леша, взгляни, пожалуйста.

**Comment by tomarcafe** [comment]
Миш, а чего я не вижу адресов теперь в разделах краудсейла?
не очень удобно дебажить.

решили отрисовывать транзакции НА персональный адрес краудсейла тоже.

**Comment by Undeadlol1** [comment]
Я там вообще ничего не трогал с начала краудсейла 
--
Отправлено из Mail.Ru для Android вторник, 22 ноября 2016г., 20:33 +02:00 от angelo  notifications@github.com :

**Comment by govantage** [comment]
судя по всему показываются последние 5 транзакций и суммируются только эти 5 транзакций.

**Comment by Undeadlol1** [comment]
@tomarcafe ты там вроде что-то подправил, закрываем?
