### ISSUE TITLE
Длинные непрерывные заголовки не влезают

### ISSUE THREAD

**Issue by Bacher** [GolosChain/tolstoy#1437]
![image.png](https://images.zenhubusercontent.com/5b0ff4b64b5806bc2bd5811e/e3bad8c0-14ec-4c66-b0b8-b320c62e999a)

![image.png](https://images.zenhubusercontent.com/5b0ff4b64b5806bc2bd5811e/74c345de-f381-43e3-8a76-8afc76a479d6)

**Comment by daryasattarova** [comment]
не исправлено в mozilla и edge
![image](https://user-images.githubusercontent.com/42342756/48133239-387e0980-e2a7-11e8-805e-aad8d93c1db1.png)

![image](https://user-images.githubusercontent.com/42342756/48133200-1ab0a480-e2a7-11e8-97f1-f81c673942c2.png)
