### ISSUE TITLE
Переработать автокомплит для переводов крипты

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/tolstoy#1449]
Автокомплит по умолчанию предлагает пользователю только 
1. Из списка тех на кого ты подписан
2. Из списка тех, кому пользователь ранее осуществлял переводы

**Comment by Bacher** [comment]
Будет странное поведение, в одних случаях будет подтверждение в других не будет, это путает. Если его делать, то оно должно всегда показываться.

**Comment by Bacher** [comment]
Не, это очень странно всё.
У нас получается после нажатия "Отправить" будет последовательно открываться два диалога, первый подтверждение ника, второй про авторизацию пользователя.
Это точно нельзя так делать.

**Comment by jevgenika** [comment]
Можно сделать авторизацию сразу при входе на окно трасфера
После автокомплита ввода имени в окне трансфера выдавать диалог подтверждение
