### ISSUE TITLE
Рядом с Ником проголосовавшего показывать силу голоса в %

### ISSUE THREAD

**Issue by AlekseiSmirnov** [GolosChain/tolstoy#145]
Предлагаю реализовать следующую фичу: при просмотре списка проголосовавших показывать силу их голоса
![2016-11-21_19-03-05](https://cloud.githubusercontent.com/assets/10200871/20490011/9fbb913a-b01d-11e6-82a4-b754c8f41b46.png)

**Comment by lehard** [comment]
Отличная идея!

**Comment by 0n0t0le** [comment]
Тогда это не будет эксклюзивной фичей телеграм-бота....))

**Comment by Azzot88** [comment]
А смысл? Видеть кому пост понравился, а кому очень понравился? Может лучше добавить сумму сколько посту принес чей-то лайк?

**Comment by 0n0t0le** [comment]
Суммы вида 0,00001 и 0,001 =)) - тоже не самое интересное

**Comment by AlekseiSmirnov** [comment]
сумма у каждого ника будет меняться и считается по сложной формуле. 
% во первых - постоянны, а во вторых понятны пользователям, т.к. у них самих будет ползунок с % и уже будет осознание того, что они значат
