### ISSUE TITLE
Некорректное отображение dropdown листа при вводе имени получателя

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/tolstoy#1457]
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/453436c0-b6de-403d-a79d-9e480390df08)
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/22345716-0607-4a5c-a5b9-16b57d653313)

**Comment by beautyfree** [comment]
Есть зависимость от браузера? Не получается воспроизвести
