### ISSUE TITLE
При просмотре страниц со списком постов неправильно отображаются выплаты

### ISSUE THREAD

**Issue by AlekseiSmirnov** [GolosChain/tolstoy#146]
При просмотре страниц со списком постов вначале неправильно отображаются выплаты и нужно подождать некоторое время, чтобы цифры обновились (см видео). Иногда бывает такое, что подвисаеи и неправильные цифры не пересчитываются. В этом случае помогает только f5

https://cloud.mail.ru/public/MeLM/Rz6CJfJhb

**Comment by gamerate** [comment]
Насколько я понимаю, это эффект от кэширования отображения и если принудительно пересчитывать при каждом обновлении это увеличит нагрузку на сервер сайта.

**Comment by lehard** [comment]
У нас же куча валют, мне кажется это подгружается из блокчейна отображение в Золотых, а затем цифры обновляются в зависимости от установленной валюты.

Такой же эффект есть со скрытыми пользователями. У меня есть 1 пользователь, которого я скрыл через mute. При загрузке он сначала показывается, т.к. из блокчейна грузятся все посты, а потом скрывается, т.к. клиент его отфильтровывает.

**Comment by Undeadlol1** [comment]
Вебсайт предварительно рендерится на сервере, для ускорения загрущки страницы.
Когда код попадает в браузер, он получает для себя нужную информацию, и изменяет данные.
В данном случае, он видит читает данные о обменных курсах из LocalStorage/cookie браузера и отображает правильную информацию. Но с задержкой.
Поставил заглушку, отображающую надпись "загрузка", до тех пор, пока данные из браузера не будут прочтены.
