### ISSUE TITLE
Сделать sitemap для robots.txt

### ISSUE THREAD

**Issue by gamerate** [GolosChain/tolstoy#147]
Поисковики более оперативно и хорошо индексируют контент на тех сайтах у которых есть sitemap
Описание протокола:
http://www.sitemaps.org/protocol.html
В robots.txt прописывается примерно так:
Sitemap: http://rashka.ru/site-map-main.xml
Пример сайтмапа:
http://rashka.ru/site-map-main.xml
Логично туда будет вывести просто основные разделы сайта - новое, популярное и тп, можно придумать что-то еще, больше сайтмапов лучше.
~~Кроме этого в robots.txt было бы логичнее поставить вместо~~
~~"Disallow:  " - как сейчас, те "ничего не запрещать"~~
~~Прямое:~~
~~"Allow: /" - те "разрешить индексировать все"~~

**Comment by Chiliec** [comment]
Насчет sitemap, согласен, можно что-то придумать.
Насчет директивы `allow` не согласен, `disallow` имеет большее значение, и то что вы предлагаете было недавно намеренно переделано https://github.com/GolosChain/tolstoy/commit/3647f54b949321a37b3860e7ca5e0d1c6a291068

[Из справки Яндекса](https://yandex.ru/support/webmaster/controlling-robot/robots-txt.xml?lang=ru):

> Директивы Allow и Disallow без параметров

Если директивы не содержат параметры, учитывает данные следующим образом:
```robots.txt
User-agent: Yandex
Disallow: # то же, что и Allow: /
User-agent: Yandex
Allow: # не учитывается роботом
```

**Comment by gamerate** [comment]
Формально как тут и написано "Disallow: # то же, что и Allow: /" - просто раньше было принято везде ставить именно "Allow: **/**", но если все поисковики устраивает "Disallow:", то согласен что это не важно. То что ""Allow: " игнорируется тоже вполне логично, оно же означает "разрешить ничего" и скорее всего его ставят по недоразумению.

**Comment by gamerate** [comment]
Сайтмап в гугл и яндекс прописал, но проблема в том что он пока содержит только 74 ссылки на разные теги, это конечно тоже полезно, но гораздо важнее иметь сайтмап (лучше отдельными файлами) по новым записям, в этом его главный смысл - сообщать поисковикам что добавилось на сайт.
Соответственно когда я писал выше:
> Логично туда будет вывести просто основные разделы сайта - новое, популярное и тп, можно придумать что-то еще, больше сайтмапов лучше.
Я не имел ввиду только буквально внести туда разделы, но внести туда именно записи из этих разделов, виде Х отдельных сайтмапов.

**Comment by serejandmyself** [comment]
Уже сделано, закрываю
