### ISSUE TITLE
Обрезается плашка с именами проголосовавших

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/tolstoy#1480]
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/33836069-e4b5-43e8-bce1-159c2e25cb5e)

**Comment by AlexRekish** [comment]
Неактуально после изменения подсказок:

![_003](https://user-images.githubusercontent.com/37471019/48199438-0f27b100-e36d-11e8-8854-78ed47eba5ac.png)

**Comment by daryasattarova** [comment]
данное окно перенеслось на число проголосовавших за пост. при наведении на него отображается данное окно. проблема актуальна
![image](https://user-images.githubusercontent.com/42342756/48256632-3f308c00-e421-11e8-8127-8c40707b8a59.png)

**Comment by b1acksun** [comment]
![image](https://user-images.githubusercontent.com/3322340/49952974-cf249280-ff05-11e8-8302-4d01439a3167.png)

**Comment by MachtFrei** [comment]
![screenshot_14](https://user-images.githubusercontent.com/2689880/50007627-9d253600-ffc2-11e8-985e-49e243ead652.png)
