### ISSUE TITLE
расчет бонусов во вкладке краудсейл

### ISSUE THREAD

**Issue by AlekseiSmirnov** [GolosChain/tolstoy#149]
Это скорее не тикет, а обсуждение.

Вчера была спам атака на биткоин и транзакции долго валидировались (больше чем пол дня).
Аккаунты, которые закидывали btc за несколько часов до уменьшения бонусов получили подтверждение транзакции уже после того, как бонус был понижен. Поэтому во вкладке краудсейл у них отображается бонус 10%, а не 15, на который они рассчитывали

Вот например люди жалуются:
https://golos.io/ru--golos/@sem3/tranzakcii-proshli-no-bonus-stal-menshe

Лично мое мнение - сами виноваты что тянули до последнего

**Comment by 0n0t0le** [comment]
Если бы люди внимательно читали договора, с которым соглашаются, таких вопросов бы не было

**Comment by AlekseiSmirnov** [comment]
https://golos.io/ru--kraudseijl/@paramedic/khotel-poluchit-bonus-15-poluchilos-10

обсуждение тут
