### ISSUE TITLE
Относительные ссылки перестали работать

### ISSUE THREAD

**Issue by bitfag** [GolosChain/tolstoy#1507]
Раньше можно было ставить относительные markdown-ссылки вида `[foo](/@vvk/p2pdexexchangebot/)`, а сейчас они обрабатываются как обычные ссылки с показом страницы "вы покидаете golos.io" и т.д.

**Comment by gropox** [comment]
Плюс перестали работать ссылки вида /@author/permlink. Раньше можно было указать только автора и permlink. С сейчас еще и parent_permlink надо указывать. Вроде /parent_permlink/@author/permlink. В старом дизайне кажется был редирект на полный URL, теперь показывает

![image](https://user-images.githubusercontent.com/26039472/48303057-a889cb00-e505-11e8-9aa9-76d59f133436.png)
