### ISSUE TITLE
Язык сайта «по умолчанию» в зависимости от языковых настроек клиента

### ISSUE THREAD

**Issue by testzcrypto** [GolosChain/tolstoy#151]
По умолчанию использовать i18n в зависимости от языковых настроек клиента, т.е. если обращение идет от клиента, в настройках языков которого нет русского – использовать английскую локализацию.

**Comment by tomarcafe** [comment]
нет.
русскоязычная платформа.

**Comment by Undeadlol1** [comment]
Открою, пусть повисит.

**Comment by Undeadlol1** [comment]
Язык по умолчанию в любом случае будет русским, я просто детектор региона снова включу. Его нужно только улучшить немного.

**Comment by Undeadlol1** [comment]
Функционал добавил.

**Comment by testzcrypto** [comment]
Не работает, проверил в IE11, перед проверкой полностью очищал все настройки браузера, проверял для английского и украинских языков (en, en-US, uk, uk-UA)

**Comment by Undeadlol1** [comment]
Теперь должно работать нормально.
Когда писал этот код похоже был уставший, забыл одну строчку кода дописать. Обидненько.
