### ISSUE TITLE
на странице поста в неавторизованном режиме, показывать блог регистрации, не показывать блог об авторе

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/tolstoy#1510]
На странице поста в неавторизованном режиме, не показывать 2 блока после поста. 
убрать блог об авторе

Зайти в дизайн страницы поста
прокрутить пост вниз
после поста у авторизованного пользовтаеля идут 2 блока подряд
блог об авторе поста и блог зарегистрироваться
![image](https://user-images.githubusercontent.com/30616421/48335089-65466e00-e665-11e8-91b2-186a6ca91b47.png)

Ожидаемый результат

- [ ] при верстке блоков на странице поста в неавторизованном режиме, показывать блог регистрации, не показывать блог об авторе
![image](https://user-images.githubusercontent.com/30616421/48335171-a3dc2880-e665-11e8-930b-c7c5bc4c24fd.png)
[Дизайн страницы](https://app.zeplin.io/project/5ba9f49fb422725fe0f07dbf/screen/5ba9fafc130bb036df1c9a63)

**Comment by AlexRekish** [comment]
Решено оставить блок с автором, вместо блока ввода комментария показывать банер.
