### ISSUE TITLE
В редакторе некорретно отображаются 3 и 5 уровни заголовков

### ISSUE THREAD

**Issue by 0n0t0le** [GolosChain/tolstoy#153]
# Как надо:
***
# Первый уровень
###### Шестой уровень
***
# Как сейчас в Голосе:
![](https://s18.postimg.org/3w0f075sp/image.png)
> Третий и Пятый уровни идентичны
P.S. на Стиме четвертый и пятый уровни идентичны

**Comment by Undeadlol1** [comment]
Спасибо.
