### ISSUE TITLE
Косяк с транслитерацией тегов

### ISSUE THREAD

**Issue by Chiliec** [GolosChain/tolstoy#154]
Найденный пример - "животные" превращается в "[животнэ](https://golos.io/trending/ru--zhivotnye)".

**Comment by Chiliec** [comment]
Нашел кажется [как раз эту тудушку](https://github.com/GolosChain/tolstoy/blob/master/app/utils/ParsersAndFormatters.js#L113). Кто-нибудь понимает что там происходит и почему оно закомментировано?

**Comment by tomarcafe** [comment]
действительно косяк.
про "ые" подумаем, действительно проще одним исключением закрыть это, и смотреть, найдутся ли еще слабые места. беда в том, что уже созданные тэги так и останутся корявыми.
закомментировано оно было потому что поменяли схему транслитерации, предыдущая вроде как глючила.

**Comment by Chiliec** [comment]
C "ые" стало всё хорошо 👍
