### ISSUE TITLE
Убрать с реформал, добавить лайв чат - tawk 

### ISSUE THREAD

**Issue by serejandmyself** [GolosChain/tolstoy#156]
Формат реформала подходит для сайта в разработке или для сайтов завязаных с системой образования и тд.

Есть работающий лайв чат tawk.ru (Русская панель, аналитика, тригеры, бесплатно) 

По технике - выслал инвайты

**Comment by tomarcafe** [comment]
а смысл?
и да - сайт в разработке. как бы не хотелось обратного - пока что сайт в разработке.

**Comment by gamerate** [comment]
С кнопкой реформала в текущем виде еще есть проблема, что она закрывает при создании поста опцию - не голосовать за свой пост. Вероятно это можно вылечить если повесить кнопку слева или справа сайта, обычно такая опция есть в настройках сервиса.

**Comment by tomarcafe** [comment]
передвинуть -ок.
убирать инструмент, который за  пару дней зарекомендовал себя как работающий - нет.

**Comment by tomarcafe** [comment]
wont fix

**Comment by serejandmyself** [comment]
В чем измеряется успех... в кол-ве постов? Все эти предложения звучали на Голосе, уже не раз. Точно так же набирают там лайки (причем большинство функционала в предложениях заложено и так и так в развития платформы)

Так же реформал не решил ситуацию с регистрациями. 

Предлагаю вынести включение лайв чата на голосование делегатам и сообществу

**Comment by tomarcafe** [comment]
про успех никто не говрит в контексте этой задачи пока что.
нам бы инструмент, удобный нам самим. я извиняюсь, но сейчас, по факту, команда разработки веб-клиента - это полтора человека - Миша и я.

и оттого, что ты, sereja, считаешь, что знаешь как надо - нам не тепло и не холодно. 
при чем тут делегаты и сообщество - я не сильно понимаю - и пойму только когда увижу существенный вклад в разработку. вот Васермане например доставляет чотко оформленые issues в гитхаб. на регулярной основе, качественно. спасибо ему такому.

**Comment by tomarcafe** [comment]
еще раз, кратенько. 

1. лив чат супорт и система типа реформала - решают РАЗНЫЕ задачи. nuff said. 
убирать реформал мотивируя тем, что "есть же ливчат" - не пройдёт.

2. часто звучит идея, что есть же голосование за комментарии - можно мол делать предложения отдельным постом, или комментарием к посту и считать голоса.

 тут 2 нехороших момента. 
первый, не очень важный - но не решаемый :) - голоса против на реформале решены тривиально, на действующем блокчейне - решаются флагами - и это не алло. 
второй, более важный - сейчас голосование длится сутки с момента публикации поста. как сооснователь проекта заявляю, что это НЕ вариант для системы обратной связи. когда пойдут выплаты, и голосование будет работать вменяемый срок - можно будет убирать реформал.

**Comment by tomarcafe** [comment]
и третье, по tawk.ru - pull requests are welcome!

**Comment by serejandmyself** [comment]
Задача какой её вижу я, это - максимальная синергия и коллаборация между всеми участниками проекта. С чего ты взял что я считаю что "знаю лучше"? Я исхожу из соображений из которых я понимаю продукт. 

На сколько мне понятен смысл issue в github, это - не призыв к действию, а предложение или улучшение, исходя из тех или иных соображений предлагающего.

Делегаты и сообщество при том что они выступают в роли стейк-холдеров и конечного потребителя, которые может и не понимают how но знают what. Продукт по сути предназначен для потребителя (как это вижу я).

Конечно же аргумент о том что голосование длиться 24 часа весомый. Тут как раз и вступает в смысл лайв чат, тем что он работает 24 часа в сутки и позволяет четrо найти проблему и предоставить максимально правильный issue. 

Есть две точки зрения - разработка и маркетинг. Исходя из своего понимания продукта который есть (клиент голос.ио), я вижу то что реформал не сможет решить то что сможет решить живое общение с пользователем. 

Если ты видишь иначе, то ок. Еще раз, как я вижу issue - не призыв к действию, а именно предложение о улучшении. Как говорится, на нет и суда нет...
