### ISSUE TITLE
На вкладке краудсейла отображаются не все транзакции...

### ISSUE THREAD

**Issue by t3ran13** [GolosChain/tolstoy#157]
после последнего перевода на краудсейл одна или больше транзакций исчезло и сумма стала меньше

было ~0,25, добавил 0,014 и чтото сломал,п оскольку стало 0.23559438. 
 https://golos.io/@t3ran13/crowdsale

а вот у примуса показывает правильно 0.2655 http://www.steeme.ru/gf.html
в общем че-та там с отображением косяк какой-то

**Comment by 0n0t0le** [comment]
Надо бы задеплоить...
