### ISSUE TITLE
Время смены суммы бонуса

### ISSUE THREAD

**Issue by t3ran13** [GolosChain/tolstoy#158]
http://screencloud.net/v/6f1F
вот картинка

Не знаю у кого как часы идут, но на сайте еще 5 мин отображается до конца бонуса, а мне бонус нулевой) вот)

**Comment by tomarcafe** [comment]
бонус отображается нулевой т к транзакци не подтверждена.
далее, на сайте мы отображаем бонус исходя из времени поступления перевода на мультисиг крауда - в окончательных расчетах, вроде (уточнять у litvintech) будт использоваться суммы и времена переводов на личные  адреса крауда - то есть транзакции будут учтены как более ранние, и на 1/10000 более крупные - но у всех. 
то есть по факту, более мелким вкладчикам будет небольшой (реально небольшой) бонус, а доля крупных чучуть уменьшится. 

то есть, собранная сумма от суммы перечислений отличается на 10000*N сатоши (где N - общее число транзакций) - если предположить что весь краудсейл - это 1000 переводов - разница получается в 0.1 битка - это даст примерно 3 сотых доли процента поправку в расчет

а вообще, я вот не понимаю, зачем Вы кидаете деньги в последний момент. либо это тест системы на прочность - либо просто так приходят средства?

**Comment by t3ran13** [comment]
спс за ответ)
Обстоятельства, я работаю, когда дорвался/впомнил, тогда перевел)

**Comment by t3ran13** [comment]
можно закрывать)
