### ISSUE TITLE
Поправить диалог восстановления аккаунта

### ISSUE THREAD

**Issue by Bacher** [GolosChain/tolstoy#1585]
Переделать диалог на новый дизайн

Нужно сделать, чтобы избавиться от `react-foundation-components`.

![image](https://user-images.githubusercontent.com/2598671/48572580-e11d1080-e91a-11e8-9d92-57dc6213ba04.png)

**Comment by daryasattarova** [comment]
алгоритм появления данного окна нужно поправить.
