### ISSUE TITLE
Добавить кнопку "перейти в пост"

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/tolstoy#1587]
При переходе из профиля (раздел комментарии или ответы) на комментарий отсутсвует возможность перейти в пост.

**Comment by Nikita-Pobazhak** [comment]
уже реализовано

**Comment by daryasattarova** [comment]
при нажатии на тело комментария осуществляется переход в пост непосредственно к выбранному комментарию. при нажатии на Re: (название поста) осуществляется переход в пост
