### ISSUE TITLE
Предложения по буквам, знакам препинания, редактированию

### ISSUE THREAD

**Issue by mguryeva** [GolosChain/tolstoy#159]
https://golos.io/ru--golos/@azzot88/kosyaki-platformy-nuzhdayushiesya-v-ispravleniiоправить Поправить буквы и знаки препинания. Таких артефактов прилично.

Убрать ограничение вложенности комментариев. "Комментарий слишком глубоко в цепочке. Максимум вложенности - 5"

Добавить возможность редактировать собственные посты позже, чем через сутки. То есть нужна ревизия версий с сохранением всех изменений.

Нужна подстановка имен пользователей при наборе сразу после знака @.
Добавить сортировку комментариев по принципу фейсбука. Там новые комментарии появляются сверху. Так намного удобнее видеть развитие дискуссии и не приходится скроллить вниз в поисках новых реплик. Свежее всегда сверху.
Исходники и подробную инструкцию по подъему и настройке собственного клиента.

**Comment by tomarcafe** [comment]
> Убрать ограничение вложенности комментариев. "Комментарий слишком глубоко в цепочке. Максимум вложенности - 5"
это в соседний репозиторий, golos

> Добавить возможность редактировать собственные посты позже, чем через сутки. То есть нужна ревизия версий с сохранением всех изменений.
это тоже в соседний репозиторий golos.

**Comment by tomarcafe** [comment]
Исходники и подробную инструкцию по подъему и настройке собственного клиента.
дубликат #122

**Comment by Undeadlol1** [comment]
> Добавить сортировку комментариев по принципу фейсбука. Там новые комментарии появляются сверху. Так намного удобнее видеть развитие дискуссии и не приходится скроллить вниз в поисках новых реплик. Свежее всегда сверху.

Справа вверху есть опция выбрать сортировку комментариев, выбери "новое"
