### ISSUE TITLE
Правки опечаток

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/tolstoy#1595]
1. 
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/f6728f6d-a6d9-47b2-8156-2b4c7099bb54)
2.
 ![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/10f6baa3-fa6a-44c2-b438-689caaed5cf1)
3. переписать: "Ключ владельца - это главный ключ ко всему аккаунту. Он необходим для изменения других ключей."
![image](https://user-images.githubusercontent.com/42342756/48621836-e24f4b80-e9b5-11e8-990a-2534d8a58451.png)

**Comment by dankinescop** [comment]
![image](https://user-images.githubusercontent.com/32875649/48830274-3f1b7f00-ed85-11e8-93b7-163f39577865.png)
![image](https://user-images.githubusercontent.com/32875649/48830425-a2a5ac80-ed85-11e8-8e36-944acd0fb6ec.png)
"Силы Голоса" - с заглавной буквы в обеих строчках; заменить "на" на "с"
