### ISSUE TITLE
Баг с отображением постов в Ленте + баг с подписчиками

### ISSUE THREAD

**Issue by 0n0t0le** [GolosChain/tolstoy#160]
Пользователь подписан на 3 юзеров, которые имели посты, однако мало того, что он не видит посты в Ленте, он еще получает уведомление

> Похоже что имяпользователя еще **никого** ни на кого не подписан
(фразу надо бы тоже подкорректировать=)
![](https://s12.postimg.org/tdfpa2925/bug.png)

**Comment by 21xhipster** [comment]
Вроде [работает](https://golos.io/@quasimax/feed)
