### ISSUE TITLE
Добавить в скобочки отображение стоимости поста в GBG 

### ISSUE THREAD

**Issue by lehard** [GolosChain/tolstoy#161]
Давайте сделаем возможность отображения стоимости поста в Золотых. Валют куча вариантов, а смотреть в своей валюте нет возможности.

**Comment by tomarcafe** [comment]
поддерживаю.
 с точки зрения "как это сделать" - getPriceFromPair @ UserWallet - видимо, куда-то надо будет экспортировать неподалеку от localizedCurrency - ну и можно использовать

**Comment by serejandmyself** [comment]
Я бы вообще рубли убрал... только путает всех (нужно чтобы по умолчанию были золотые, а уже в дропдаун меню (локал куренси - нужно оно вообще?)

**Comment by t3ran13** [comment]
Я тоже за золотые, рубли с толку только сбивают)

**Comment by serejandmyself** [comment]
Рядом с потенциальной выплатой и платой за продвижение указывать стоимость в GBG
