### ISSUE TITLE
Реализовать авторизацию с owner key

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/tolstoy#1611]
**Воспроизведение:**
1. открыть песочницу
2. нажать кнопку "Войти"
3. ввести ник и owner key
4. нажать кнопку "Войти" 

**Ожидаемый результат:** разрешить авторизацию с owner key. должно появиться окно для подтверждения авторизации с этим ключом как здесь. только заменить текст "Введен ключ владельца - это главный пароль. Для обеспечения большей безопасности вам рекомендуется обновить ваши ключи в Настройках и войти с помощью приватного постинг ключа. кнопки: Сменить ключи (редирект в Настройки - > Ключи -> Новый ключ) / Отмена"
![image](https://user-images.githubusercontent.com/42342756/48773519-ae876500-ecd8-11e8-980c-b8db64335fe3.png)
по нажатию на "Сменить ключи" происходит редирект. поле ввода текущего пароля должно быть заблокировано или скрыто вовсе. **(только при авторизации с owner key)** (для того чтобы сменить ключи нужно просто скопировать сгенерированный мастер ключ в поле "Введите сгенерированный пароль")
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/818e414e-95c2-4b22-b216-003333d603ee)

**Comment by Bacher** [comment]
Ребят, это задача очень непростая.

Нужно будет пересмотреть логику всех диалогов подтверждения (при передаче денег и тд).
Проверить, что везде где сейчас передается posting ключ всё будет работать с owner ключом, и сделать, чтобы везде в таких случаях брался owner ключ.

Учитывая сложность всего этого, не уверен, что стоит ли сейчас её брать.

**Comment by daryasattarova** [comment]
не открывается диалог сброса ключей по клику на ссылку 
![image](https://user-images.githubusercontent.com/42342756/50472766-3133cc00-09cb-11e9-9fb6-6126c0bea203.png)

**Comment by b1acksun** [comment]
Ошибка только при продовой сборке
![image](https://user-images.githubusercontent.com/3322340/50509290-fc3c7d80-0a8d-11e9-8f03-e94efdaae3df.png)

**Comment by daryasattarova** [comment]
задача реализована. есть проблемы с версткой на мобильных устройствах
iphone 5s
![image](https://user-images.githubusercontent.com/42342756/50894995-d1e7aa00-1415-11e9-8057-1e9299f216af.png)

iphone 8 plus (данная проблема актуальна для всех моб устройств)
![image](https://user-images.githubusercontent.com/42342756/50895015-e3c94d00-1415-11e9-8643-89788afe033f.png)

**Comment by daryasattarova** [comment]
1. углы не закруглены 
![image](https://user-images.githubusercontent.com/42342756/51473351-33503700-1d8d-11e9-8196-fa4169970e69.png)
