### ISSUE TITLE
Окно подписчиков: сортировать весь список подписчиков/подписок по алфавиту

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/tolstoy#1616]
Воспроизведение:
открыть профиль
нажать в блоке краткой информации на кол-во подписчиков/подписок (пример аккаунт https://golos.io/@nadiyamikhno)

Ожидаемый результат: упорядочить список юзернеймов по английскому после русскому алфавиту
![image](https://user-images.githubusercontent.com/30616421/48842082-fcb16c80-ed9b-11e8-9881-a2f66e9bd493.png)
Реальный результат: список подписчиков неупорядочен

**Comment by jevgenika** [comment]
https://github.com/GolosChain/tolstoy/issues/1618

**Comment by kuchinskaya** [comment]
https://zpl.io/aw1pM4j и https://zpl.io/adPpBOE
