### ISSUE TITLE
в окне проголосовавших за пост сортировать проголосовавших по силе апвоута от большего к меньшему.

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/tolstoy#1618]
Воспроизведение:
открыть https://golos.io/
открыть список проголосовавших за пост

Ожидаемый результат:  в окне проголосовавших за пост сортировать проголоосвавших по силе апвоута от большего к меньшему. При одинаковой мощности голосования соритировтать список юзернеймов по алфавиту английскому, потом русскому

Реальный результат: список проголосовавших не упорядочен
![image](https://user-images.githubusercontent.com/30616421/48842486-1a330600-ed9d-11e8-983e-5412bd43c88c.png)

**Comment by AlexRekish** [comment]
Будет реализовано в 19 ХФ

**Comment by b1acksun** [comment]
> Будет реализовано в 19 ХФ 

Можно проверить на sandbox.golos.io

**Comment by daryasattarova** [comment]
не реализовано. (в связи с 19 ХФ)
