### ISSUE TITLE
Исправить текст в кошельке

### ISSUE THREAD

**Issue by 0n0t0le** [GolosChain/tolstoy#162]
![](https://s13.postimg.org/3v0l11yl3/image.png)
сейчас так:

Перемещаемые цифровые токены, которые **могут переданы** куда угодно в любой момент.
Голос может быть конвертирован в Сила Голоса, этот процесс называется "усиление голоса".

должно быть

> могут **быть** переданы

UPD: заодно поправить перевод в названии ключей во вкладке Разрешения
Активный ключ называется "Обсуждаемое"

**Comment by gamerate** [comment]
"могут быть переданы" пофиксил, а вот с Обсуждаемое все сложнее, дело в том что один ключ в переводе соответствует и разделу Обсуждаемое и названию ключа - на стиме и то и другое active - нужно менять ключи перевода в коде на два разных.

**Comment by 0n0t0le** [comment]
Вообще надо все переделывать по уму, только Мише не говорите))

**Comment by Undeadlol1** [comment]
"Обсуждаемое" в "разрешениях" будет изменено после мерджа стимитовских изменений.
Спасибо за коммиты.
