### ISSUE TITLE
Белый экран при переходе во вкладку "Избранное"

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/tolstoy#1626]
стабильно воспроизводится на профиле joseph.kalu
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/db5f45bc-02fa-4e6e-9bb9-452a8a955a80)
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/3cacacbf-e494-43fb-85eb-3cba0e8fe943)

**Comment by b1acksun** [comment]
https://github.com/GolosChain/tolstoy/issues/1627
