### ISSUE TITLE
Предложение. Добавить фильтры постов для 18+

### ISSUE THREAD

**Issue by lehard** [GolosChain/tolstoy#163]
Оформил в виде поста https://golos.io/ru--golos/@lehard/mat-i-kontent-18-predlozhenie-po-filtracii-lenty

**Comment by serejandmyself** [comment]
Согласен, я в продолжение воспользовался бы еще идеей Ярослава о том что при использование тэга Голос - будет появляться предупреждение о том уверен и он в его использовании

**Comment by Undeadlol1** [comment]
Дубликат https://github.com/GolosChain/tolstoy/issues/136
