### ISSUE TITLE
Крутится лоадер при попытке передать пользователю golos/gbg

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/tolstoy#1631]
при попытке передачи пользователю golos/gbg появляется экран авторизации. после ввода логина и пароля и подтверждения авторизации крутится лоадер и передача не осуществляется. касается окна конвертирования тоже
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/7a69e114-a13f-4abe-8c75-af82bc4cee63)

**Comment by Bacher** [comment]
Это уже починено.

**Comment by daryasattarova** [comment]
я так понимаю на песке еще этого нет?
