### ISSUE TITLE
после обновления страницы поста пропадает кнопка "Вернуться назад"

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/tolstoy#1632]
Воспроизведение:
1. авторизоваться
2. открыть любой пост
3. перезагрузить страницу

Ожидаемый результат: все элементы страницы должны остаться на месте
Реальный результат: кнопка "Вернуться назад" пропадает

**Comment by MachtFrei** [comment]
не работает

**Comment by Bacher** [comment]
Да, пропадает, это нормально. Ничего сделать с этим нельзя.
