### ISSUE TITLE
не отображается аватар юзера

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/tolstoy#1655]
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/c5759973-bbd4-421c-9587-fd32114f0995)
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/01bc30f6-b875-4a50-a2b9-a34a9b0cd22d)

**Comment by chinpu** [comment]
В имени файла с аватаркой был пробел, после переустановки авы проблема решена.
