### ISSUE TITLE
никнейм в формате @nicname не определяется как ссылка

### ISSUE THREAD

**Issue by AlekseiSmirnov** [GolosChain/tolstoy#166]
Мелкий косячок. Если нику в посте предшествует скобка, например "(@alex" , то он не пределяется как ссылка на профайл

**Comment by gamerate** [comment]
Чуть уточню: если @ предшествует "что угодно кроме пробела"

**Comment by Chiliec** [comment]
А если кто-то захочет емейл написать, то вы хотите чтоб оно преобразовывало во что-то типа blablabla[@gmail](https://golos.io/@gmail).ru ?

**Comment by 0n0t0le** [comment]
Нужно делать в виде мгновенной ссылки, типа\
<blablabla@gmail.ru>

**Comment by 21xhipster** [comment]
Предлагаю добавить к пробелу `(` так как кейс достаточно популярный.

**Comment by serejandmyself** [comment]
Я так понимаю это еще из стима. @Undeadlol1 а оно в мердже включено? Это дубликат или отдельный кейс?

**Comment by Undeadlol1** [comment]
@serejandmyself без понятия.

**Comment by serejandmyself** [comment]
Это актуально еще?

**Comment by Undeadlol1** [comment]
Акутально.

**Comment by serejandmyself** [comment]
Closed HF 16.3
