### ISSUE TITLE
Реализовать отображение компактной ленте в мобильной версии 

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/tolstoy#1669]
[ссылка на дизайн](https://app.zeplin.io/project/5ba9f49fb422725fe0f07dbf/screen/5bf56096f2efb23f7f9b66bf)

**Comment by MachtFrei** [comment]
кнопка изменения отображения в ленте находится под стрелкой

**Comment by MachtFrei** [comment]
разъезжается верстка при не залогиненом пользаке
![screenshot_8](https://user-images.githubusercontent.com/2689880/49810247-df0b6d80-fd71-11e8-8c9a-4f3426bf13ca.png)
