### ISSUE TITLE
Упорядочить меню

### ISSUE THREAD

**Issue by lehard** [GolosChain/tolstoy#168]
Некоторые предложения можно тут посмотреть
https://golos.io/ru--tyeg/@dhrms/vesyolye-kartinki-po-motivam-segodnyashnego-vechera-s-golosom

**Comment by serejandmyself** [comment]
Требуется более подробный и более согласованный вариант. Также, это не приоритет, гораздо более user frendly было бы сделать интро видео (я так понимаю смыл в том чтобы сделать все более понятным) при регистрации (идея в работе, но не скоро)

**Comment by serejandmyself** [comment]
Изменения внесены в новую версию веб клиента (они не такие как тут, но уже все иначе)
