### ISSUE TITLE
Некорректное отображение элементов в ленте в мобильной версии

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/tolstoy#1683]
девайс Xiaomi redmi note 2 
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/88344ead-4c94-4ee6-8b9d-609f562df447)

**Comment by AlexRekish** [comment]
Невозможно воспроизвести, возможно проблема существует только на старых версиях родного браузера xiaomi.
