### ISSUE TITLE
Поправить ранги юзеров

### ISSUE THREAD

**Issue by Azarod** [GolosChain/tolstoy#1696]
Юзеры просят вернуть как было. Очень-очень просят. Для них это супер-важно. Надо вернуть.

![Screen Shot 2018-11-29 at 5.45.01 PM.png](https://images.zenhubusercontent.com/5bceef19b198c93527505714/16078d19-d18e-4d2b-b5d6-ebc9505a6207)

**Comment by litrbooh** [comment]
не надо возвращать гольянов, у нас таких гальюнов не было :)
