### ISSUE TITLE
Неверные (кирилические) ссылки в меню просмотра по тэгу

### ISSUE THREAD

**Issue by gamerate** [GolosChain/tolstoy#170]
Например на странице trending тэга БМ
https://golos.io/trending/ru--bm
В меню сверху ссылки выглядят как
https://golos.io/created/%D0%B1%D0%BC
https://golos.io/hot/%D0%B1%D0%BC
и тд
В результате клик по ним дает 404
Возможно это появилось недавно и с этим связана часть жалоб на участившиеся 404 сегодня.

**Comment by Undeadlol1** [comment]
О, спасибо!

**Comment by tomarcafe** [comment]
а я думал так и надо - а это баг оказывается

**Comment by gamerate** [comment]
И видимо связанный баг:
Ссылки на странице личного фида
https://golos.io/@dr2073/feed
ведут теперь на https://golos.io/created/@dr2073
что тоже взывает соответственно 404 - так как ник там лишний

**Comment by Undeadlol1** [comment]
Спасибо что нашел проблему и указал направление, в котором рыть, чтобы найти решение.
