### ISSUE TITLE
В мобильной версии некорректно работает постановка регистра 

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/tolstoy#1702]
Ожидаемый результат: при постановке курсора в поле ввода первая буква должна ставиться автоматически заглавной, последующие - строчные. после точки снова должна ставиться заглавная буква (при условии, что в телефоне выставлены настройки автопрописных букв)
Реальный результат: буквы все строчные. если нажать кнопку для постановки заглавной буквы, то весь текст пишется капсом

**Comment by AlexRekish** [comment]
Нужно больше инфы. О каком именно поле ввода идет речь? На первый взгляд все работает корректно.

**Comment by Nikita-Pobazhak** [comment]
это в к примеру поле создания комментария, там не стандартное поведение клавиатуры iPhone

**Comment by MachtFrei** [comment]
На андроиде в поле комментария сохраняется

**Comment by Bacher** [comment]
На iOS поправилось, на Android не получается поправить. Это поведение самого редактора (codemirror). Предлагаю эту задачу переименовать в фикс для iOS, и создать отдельную для Android которая пока что будет вынужденно лежать в backlog до тех пор пока не сменим редактор.

**Comment by AlexRekish** [comment]
Сегодня проверял на андроиде, у меня все работает корректно. Возможно проблема только на определенных девайсах.

**Comment by MachtFrei** [comment]
проверили на ios и на android. не работает в комментариях первая заглавная буква

**Comment by bacher** [comment]
Убрал залипание КАПСА, остальные проблемы поправить не могу, надо наверное разделить задачу на две.

**Comment by MachtFrei** [comment]
на хроме ок, на сафари не ок

**Comment by daryasattarova** [comment]
проверяла на айфоне в сафари: проблема сохранилась, т.е.:
1. при нажатии на инпут для ввода коммента показывается клавиатура со строчными буквами. 
2. при нажатии на шифт весь текст пишется капсом
