### ISSUE TITLE
Просьбы Дениса Скрипника

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/tolstoy#1710]
1. В настройках, в частности, в уведомлениях, сделайте галочки вида input type=“checkbox”. Сейчас непонятно, отмечена настройка или нет.
2. При открытии, например, активности, выводился заголовок уровня 1 (h1) “активность“.

**Comment by MachtFrei** [comment]
в указанных местах не чекбоксы

![screenshot_10](https://user-images.githubusercontent.com/2689880/49811333-1f6beb00-fd74-11e8-8afa-dbbf821c994a.png)

**Comment by Bacher** [comment]
![image](https://user-images.githubusercontent.com/2598671/49812126-c4d38e80-fd75-11e8-9364-5f68a87bb1fe.png)

Вот тут нет checkbox.
С radio всё ок.

**Comment by Bacher** [comment]
Я поправлю.
