### ISSUE TITLE
Дела по мерджу стимитовских изменений

### ISSUE THREAD

**Issue by Undeadlol1** [GolosChain/tolstoy#172]
UPD: задачи обновлены 04.01.2017
Работы ведутся в ветке [from-steemit](https://github.com/GolosChain/tolstoy/tree/from-steemit).
Сравнение разницы в коде между двумя проектами можно увидеть в [первом коммите](https://github.com/GolosChain/tolstoy/commit/199890e22541e35bdc4ad3581edb6bc4b5a1c101).
Изменения можно потрогать онлайн на [стэйджинге](https://staging.golos.io/).
Осталось сделать:
- [ ] починить шрифт в посте
- [ ] починить резолвинг youtube видео в посте
- [x] В профиле пользователя не подгружаются статьи пользователя (возможно 0 статей тоже выдает ошибку)
- [ ] залить на стэйджинг и пригласить желающих для тестирования
- [ ] смерджить в мастер

Задачи бэк-энда:
настроить tarantool
вернуть routes для нотификэйшенов и счетчика просмотра страниц
добавить библиотеку shared-db в голосчейн

**Comment by serejandmyself** [comment]
Они еще апгрейдили:

- Настройки юзера, теперь можно добавить описание, место нахождение и ссылку на сайт
- 
- Добавили ФАК страницу как делаешь логин
- 
- Добавили сортировку по комента внутри поста и внутренний счетчик просмотров поста  

Не уверен, если что то из этого уже включено в список выше, если так, то вычеркивай

**Comment by Undeadlol1** [comment]
В списке выше замеченные баги, которые случились при "слиянии" нашего и ихнего кода.
Спасибо что сказал, Сережа. Я почти никогда не захожу на стимит, без понятия что там у них.

**Comment by serejandmyself** [comment]
Вот тебе с картинками =)

Изменение в настройках:

[![1.jpg](https://s18.postimg.org/ucyf3951l/image.jpg)](https://postimg.org/image/lhxksqg91/)

Страница "welcome":

[![2.jpg](https://s13.postimg.org/8mfuqtkuf/image.jpg)](https://postimg.org/image/5flb770eb/)

Сортировка постов, счетчик и иконки соц сетей:

[![3.jpg](https://s17.postimg.org/stqi4yrqn/image.jpg)](https://postimg.org/image/3npjy4qgb/)

Когда выбираешь опцию "заплатить 100% в SP" в ленте у всех, такая вот штука:

[![4.jpg](https://s16.postimg.org/mtfrg6oid/image.jpg)](https://postimg.org/image/65o9dotqp/)

**Comment by Undeadlol1** [comment]
Вах!

**Comment by 0n0t0le** [comment]
Это просто сказка
