### ISSUE TITLE
Дублирование уведомлений об ответах при редактировании комментариев

### ISSUE THREAD

**Issue by rodnikova** [GolosChain/tolstoy#1721]
Сделать так, чтобы уведомление о новом комментарии или ответе приходило только один раз, а после редактирования комментария/ответа, уведомления не дублировались.

**Comment by NickShtefan** [comment]
Issue moved to [GolosChain/notify-service #32](https://github.com/GolosChain/notify-service/issues/32) via [**ZenHub**](https://www.zenhub.com/)
