### ISSUE TITLE
Скрыть отображение постов с тегом test по умолчанию

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/tolstoy#1725]
1. Юзер видит посты с тегом test, если сам их написал
2. Во всех возможных лентах тег test скрыт по умолчанию
3. Если пользователь производит поиск по тегу test, то мы отображаем все что приходит из БЧ
4. 500 ошибка неприемлема ни при каких условиях.

**Comment by MachtFrei** [comment]
https://sandbox.golos.io/created?tags=test

500 ошибка

**Comment by MachtFrei** [comment]
итак итоговое:
в фиде и в популярных тегах test не отображается

при поиске по тегу отображаются посты с тегом тест

**Comment by MachtFrei** [comment]
Репосты записей с тегом тест вообще нигде не отображается, ни в профиле, ни в ленте, ни поиском по тегу
