### ISSUE TITLE
Баг с отображением новых постов на сайте golos.io

### ISSUE THREAD

**Issue by serejandmyself** [GolosChain/tolstoy#173]
В ленте [новые](https://golos.io/created) (created), посты отображаются не правильно: 

[![Безымянный.jpg](https://s13.postimg.org/6gf9nb3qv/image.jpg)](https://postimg.org/image/ytardrpgz/)

Время от времени новые посты начинают отображаться корректно, потом опять исчезают, и появляются именно с того поста который на картинке "Церковь и автобус" (В это время возможность голосование за другие посты исчезает).

Браузер - Chrome (С другими браузерами тоже самое)

**Comment by Undeadlol1** [comment]
Сегодня с серверами беда, возможно из-за этого.
