### ISSUE TITLE
Убрать взаимоисключающие пункты (Понижение силы голоса / отмена)

### ISSUE THREAD

**Issue by 0n0t0le** [GolosChain/tolstoy#174]
В кошельке в разделе Сила Голоса одновременно присутствуют кнопки `Понизить Силу Голоса` и `Отменить понижение Силы Голоса`.
Дабы не вводить в заблуждение должна присутствовать только одна кнопка - либо понизить, либо отменить, если понижение выбрано 

![](https://s16.postimg.org/bdpz70a1x/image.png)

**Comment by Undeadlol1** [comment]
Если честно, до первых выплат я не знаю как это сделать, чтобы быть уверенным на 100% что работает нормально.

**Comment by serejandmyself** [comment]
Ok. Will put in the backlog for now, but let's leave it open.

**Comment by serejandmyself** [comment]
Set for sprint №2

**Comment by serejandmyself** [comment]
Closed in HF 16
