### ISSUE TITLE
Подготовить файлы robots.txt для доменов golos.io и golos.blog

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/tolstoy#1742]
Отключить индексирование для golos.blog
Прописать путь к sitemap

**Comment by Bacher** [comment]
Для сайта https://golos.io/ добавить строку:
```
Sitemap: https://golos.io/sitemap.xml
```
Перед строкой `Crawl-Delay: 2`

![image](https://user-images.githubusercontent.com/2598671/49587674-9fa9df00-f975-11e8-9058-15b84bc881fd.png)

**Comment by muhazzz** [comment]
Done.
