### ISSUE TITLE
При ssr загрузке страницы неправильно отображается котировка

### ISSUE THREAD

**Issue by beautyfree** [GolosChain/tolstoy#1743]
При загрузке страницы по url отображаются разные котировки

Выбранная котировка RUB

![image](https://user-images.githubusercontent.com/656531/49589066-7428f380-f979-11e8-8a27-f63e08f6b061.png)

**Comment by Bacher** [comment]
Оказалось, что забыли выставить переменную окружения с сервером rates.
Должно починиться с первым деплоем.
