### ISSUE TITLE
Нерабочая ссылка на youtube в FAQ

### ISSUE THREAD

**Issue by MachtFrei** [GolosChain/tolstoy#1751]
В теле статьи нерабочая ссылка
https://wiki.golos.io/1-introduction/faq.html

![Screenshot_1.png](https://images.zenhubusercontent.com/5c0e396352c51c42a50ed4bb/10c3a21f-3b1b-47cb-8e3c-6d72d72907e3)

**Comment by MachtFrei** [comment]
+ вот эта страница 
https://wiki.golos.io/5-development/roadmap.html

**Comment by AlexRekish** [comment]
https://github.com/GolosChain/wiki/pull/67
