### ISSUE TITLE
баг на лендинге

### ISSUE THREAD

**Issue by Azarod** [GolosChain/tolstoy#1755]
- англ версия лендинга
- не отображаются картинки
- это может помешать пройти ревью из-за того что сайт может выглядить как неработающий или неподдерживаемый
![Screen Shot 2018-12-10 at 3.45.31 PM.png](https://images.zenhubusercontent.com/5bceef19b198c93527505714/dfe9f9f0-fb15-4f95-acb7-45cb4b70aea1)

**Comment by muhazzz** [comment]
Done.
