### ISSUE TITLE
Реализовать на странице делегатов отображение голосуемых параметров сети

### ISSUE THREAD

**Issue by litrbooh** [GolosChain/tolstoy#1756]
В связи с тем, что количество голосуемых параметров в сети растет как на дрожжах, надо сделать отображение медианы по всем параметрам и форму, куда делегаты могут их пихать.

**Comment by NickShtefan** [comment]
Необходимо вынести версию ноды на основную плашку (до раскрытия), сразу после прайс фида
Количество голосов перенести в параметры, которые отображаются при раскрытии
![image](https://user-images.githubusercontent.com/6249597/51464825-80291300-1d77-11e9-9182-0075499fa453.png)

**Comment by daryasattarova** [comment]
не отображается кол-во голосов в параметрах
