### ISSUE TITLE
Отображать в профайле статус "делегат"

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/tolstoy#1771]
Отображать статус делегат, если пользователь является делегатом
Добавить кнопку проголосовать/снять голос, в случае если первый пункт true

**Comment by kuchinskaya** [comment]
https://zpl.io/amyM8JA https://zpl.io/bA4BzMo  https://zpl.io/aw1pM4j

**Comment by daryasattarova** [comment]
некорректное отображение в мобильной версии (iphone 5s)
![image](https://user-images.githubusercontent.com/42342756/50372110-572b2c00-05d9-11e9-84bb-2bbc34b936f6.png)
