### ISSUE TITLE
Проанализировать количество символов публикуемых всеми пользователями в постах за месяц

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/tolstoy#1773]

**Comment by Bacher** [comment]
Count: 30592
Avg post length ~ 2580.50
Medium post length ~ 2676.60 (отброшены 10% самых коротких и 10% самых длинных)

**Comment by Bacher** [comment]
Это количество символов включая разметку, по этому процентов 10% можно отбросить длинны.

**Comment by Bacher** [comment]
Data by interval: 2018-11-13T10:26:46.877Z - 2018-12-13T10:26:46.877Z
Posts count: 30288
Avg post length ~ 2584.34
Medium post length ~ 2680.94

Data by interval: 2018-10-14T10:26:46.877Z - 2018-11-13T10:26:46.877Z
Posts count: 31203
Avg post length ~ 2677.16
Medium post length ~ 2786.60

Data by interval: 2018-09-14T10:26:46.877Z - 2018-10-14T10:26:46.877Z
Posts count: 30787
Avg post length ~ 2824.46
Medium post length ~ 2931.43

Data by interval: 2018-08-15T10:26:46.877Z - 2018-09-14T10:26:46.877Z
Posts count: 32598
Avg post length ~ 2932.56
Medium post length ~ 3032.84

Data by interval: 2018-07-16T10:26:46.877Z - 2018-08-15T10:26:46.877Z
Posts count: 31948
Avg post length ~ 2732.40
Medium post length ~ 2717.31

Data by interval: 2018-06-16T10:26:46.877Z - 2018-07-16T10:26:46.877Z
Posts count: 30719
Avg post length ~ 2860.64
Medium post length ~ 2819.80

**Comment by Bacher** [comment]
Source code:
https://gist.github.com/Bacher/84dd9afabc606a6f435ee3c920831b5a
