### ISSUE TITLE
Активация и верификация google webmasters для аналитики сайта golos.io

### ISSUE THREAD

**Issue by serejandmyself** [GolosChain/tolstoy#178]
Для того чтобы иметь возможность считывать более детальную аналитику с сайта golos.io нужно подключить webmaster . Для этого вот по этой ссылке:

https://www.google.com/webmasters/verification/verification?hl=ru&siteUrl=http://golos.io/

Нужно его верифицировать, либо путем Размещение HTML-файла на сервере, либо другим альтернативным способом.

Сам webmaster настроим (нужен будет только доступ в него, в ГА у меня доступ есть).

Было бы круто еще и тут активировать (чтобы два раза не делать) - https://webmaster.yandex.com/ 

Данке

**Comment by Undeadlol1** [comment]
Гугл подтвердил. Яндексом заниматься нет никакого желания, делай сам

**Comment by gamerate** [comment]
Я готов дать готовый код куда что прописать, просто скажи как именно подтвердил каким методом - что-бы для него и дать =)

**Comment by gamerate** [comment]
Яндекс прописал по аналогии с гуглом, осталось что-бы оно стало активным.

**Comment by Undeadlol1** [comment]
Задеплоил, можно верифицировать.

**Comment by gamerate** [comment]
Спасибо - с постмейстером и яндекс вебмастером все ок.
Хорошая новость что 100% писем на мейл пока доходят, плохая что DKIM не настроен что сильно снижает доставляемость в целом https://help.mail.ru/mail-help/work/dkim - но это тема для отдельного тикета. Иконку голоса для мейла в письма прописал.
Спам репортов пока относительно немного ~25 на примерно 500 писем, но это подозрительно высокий процент, тот же SendGrid, через который они идут, обычно банит при более 0.5% спам-репортов, просто пока наверно количество их небольшое для его реакции - значит стоит подумать над дизайном письма или другими их причинами.
Осталось разобраться с доступом к google webmaster (у меня пока его нет) и видимо можно будет закрывать тикет.

**Comment by serejandmyself** [comment]
Миша, дай плиз доступ к гугл webmaster на:

serejandmyself@gmail.com
markygre@gmail.com 

Чтобы мы смогли смотреть статы и настроить все. Спасибо!

**Comment by Undeadlol1** [comment]
Добавил, извини за задержку.
@gamerate Спасибо за помощь!
