### ISSUE TITLE
Автоматическое удаление HTML элемента ins из поста (или внос его в список разрешенных)

### ISSUE THREAD

**Issue by gamerate** [GolosChain/tolstoy#179]
В случае копирования ссылок, например из википедии, к ним часто присоединяется тэг ins (подчеркивание).
При попытки записать такой пост выдается ошибка:
"Пожалуйста удалите эти HTML элементы из вашего поста: ins"
Идеальным вариантом будет если мы просто внесем этот тэг в список разрешенных, ведь он совершенно безобиден, но даст больше простора для визуального оформления постов.
Или же нужно вместо вывода сообщения, просто молча и автоматически удалить эти тэги из текста.
Новичка эта ошибка вводит в ступор, ведь вряд ли он догадается, что надо зайти в просмотр исходного кода, выявить где там появился неожиданно какой-то загадочный  "HTML элемент" и удалить его там. Уверен, что часть новичков просто забивают и уходят из Голоса ругаясь на его безумно неудобный редактор.
Конечно есть шанс, что эта проблема будет решена в "новом редакторе стима" когда он появится, но мы не знаем сколько времени займет его разработка, а авторов на этом неудобстве интерфейса мы теряем уже сейчас.

**Comment by gamerate** [comment]
Вроде как этого должно быть достаточно =)
Закрываю баунти https://golos.io/ru--zadacha-golos/@dr2073/zadacha-golos-179-avtomaticheskoe-udalenie-html-elementa-ins-iz-posta-ili-vnos-ego-v-spisok-razreshennykh
Приз достается @michael (ник в Голосе)

**Comment by Undeadlol1** [comment]
Не нужно отдавать баунти человеку пока код не написан, не принят пулл реквестом в голос и пока ишью не закрыто.

**Comment by Undeadlol1** [comment]
<img width="695" alt="screen shot 2016-12-08 at 17 35 48" src="https://cloud.githubusercontent.com/assets/4124323/21010247/d3e55980-bd6c-11e6-897d-c69ce5b75466.png">

**Comment by Undeadlol1** [comment]
Ответ получил, вот теперь можно и закрыть.
