### ISSUE TITLE
Не работает www.golos.io

### ISSUE THREAD

**Issue by gamerate** [GolosChain/tolstoy#180]
В мире существует ненулевое олдскульное сообщество людей которые уже много лет набивают в строке браузера все сайты обязательно с www, поэтому общепринятой практикой является сделать так что-бы сайт работал и с www и без www, при этом в гугл вебмастере и яндекс весбмастере и роботс тхт прописать какой из доменов является каноническим, а с www можно либо делать жесткий редирект (лучше) либо просто показывать зеркало.
Но ситуация когда www.golos.io показывает "www.golos.io’s server DNS address could not be found." это крайне печально - мы теряем на этом некоторый процент аудитории которая уходит думая что сайт упал.

**Comment by tomarcafe** [comment]
ПРОВЕРЯЙ
@
ЗАКРЫВАЙ

**Comment by tomarcafe** [comment]
сделал редирект 301 на глагне

**Comment by gamerate** [comment]
Да - спасибо - все прекрасно =)
