### ISSUE TITLE
Обновить страницу голосования за делегатов

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/tolstoy#1804]
Необходимо переработать страницу голосования за делегатов. 
Помимо уже имеющихся данных необходимо добавить следующие поля: 

"account_creation_fee",
"maximum_block_size",
"sbd_interest_rate",
"create_account_min_golos_fee",
"create_account_min_delegation",
"create_account_delegation_time", 
"min_delegation",
"max_referral_interest_rate",
"max_referral_term_sec",
"min_referral_break_fee",
"max_referral_break_fee",
"posts_window",
"posts_per_window", 
"comments_window",
"comments_per_window",
"votes_window",
"votes_per_window", 
"auction_window_size", 
"max_delegated_vesting_interest_rate", 
"custom_ops_bandwidth_multiplier", 
"min_curation_percent", 
"max_curation_percent", 
"curation_reward_curve", 
"allow_distribute_auction_reward", 
"allow_return_auction_reward_to_fund"

Страница должна быть оптимизирована для мобильных устройств.

**Comment by Azarod** [comment]
@NickShtefan нужны ли нам все эти данные?

**Comment by MachtFrei** [comment]
1) отсутствуют данные по "max_referral_break_fee",
comments_per_window
votes_per_window
auction_window_size
2) в мобильном устройстве сортировка полей идет не по колонкам а по строкам
красные стрелки as-is синие should-be
![image](https://user-images.githubusercontent.com/2689880/50894755-1c1c5b80-1415-11e9-95a8-213666053197.png)

**Comment by NickShtefan** [comment]
![image](https://user-images.githubusercontent.com/6249597/50898399-24c65f00-1420-11e9-8181-e746dd7a36c1.png)


![image](https://user-images.githubusercontent.com/6249597/50898407-2ee85d80-1420-11e9-8462-81952352c546.png)

Подсветка наличия голоса инвертирована

**Comment by b1acksun** [comment]
Время публикации прайс фида должно быть в строке с прайс фидом
![image](https://user-images.githubusercontent.com/3322340/50899017-8b944a00-1419-11e9-8c9f-e2a400c763d1.png)

**Comment by b1acksun** [comment]
Неверно отображаются проценты
![image](https://user-images.githubusercontent.com/3322340/50899214-23923380-141a-11e9-9f46-e8c2c7a4ff59.png)

Необходимо делить на 100%
![image](https://user-images.githubusercontent.com/3322340/50899280-4cb2c400-141a-11e9-9a81-88ab161cbdcd.png)
