### ISSUE TITLE
Неприятный баг с тегами

### ISSUE THREAD

**Issue by 0n0t0le** [GolosChain/tolstoy#182]
В поле для тегов если используется 5 тэгов и после последнего стоит пробел, то пост не публикуется, выдавая ошибку:
> У вас 6 тегов...бла бла бла

![](https://s18.postimg.org/y2cnkls0p/image.png)

Нужно фиксить либо хотябы поменять сообщение об ошибке т.к. у новичков диссонанс

**Comment by Undeadlol1** [comment]
Не фиг пробелы ставить =)

**Comment by gamerate** [comment]
Да надо автоматом удалять пробелы в конце (и начале) строки с тегами конечно.

**Comment by tomarcafe** [comment]
@gamerate удачки с добавлением нового тега - автоматом удаляем пробел - и оппа - всё еще пишется старый тег )

**Comment by tomarcafe** [comment]
как вариант, можно когда считаешь таги, считать не `tagsLine.split(' ').length`, а считать только элементы ненулевой длины (пустая строка приведенная к булеву типу, даёт false

**Comment by Undeadlol1** [comment]
Есть специальный метод, убирающий пробелы в строке: string.trim()
