### ISSUE TITLE
Правки по футеру поста (от Аллы)

### ISSUE THREAD

**Issue by Bacher** [GolosChain/tolstoy#1828]
Тут конечно сложно разобраться, что я нарисовала, но я бы сделала меньше отступы, добавила бы полоску между иконками. Иконку репоста перенесла бы на1-й уровень, Ширинг переместила бы в 3 точки, а ответить отцентровала

![image.png](https://images.zenhubusercontent.com/5b0ff4b64b5806bc2bd5811e/8049df90-04c5-4aaa-9bfa-12cb46dd7c08)

**Comment by kuchinskaya** [comment]
должно быть так: http://prntscr.com/lwwgrc

**Comment by bacher** [comment]
Из-за того что пока что нет иконки с количеством просмотров поста, нижнюю часть пришлось оставить пока как есть.

Менять выравнивание верхний линии тоже надо будет вместе с выравниванием нижней линии.

Поправил отступы, добавил разделительную линию. Выглядит уже вполне неплохо.
