### ISSUE TITLE
Обойти на клиенте ограничение по максимальной вложенности в 5 комментов

### ISSUE THREAD

**Issue by gamerate** [GolosChain/tolstoy#183]
У нас есть самая видимо неприятная на данный момент проблема в Голосе: "Комментарий слишком глубоко в цепочке. Максимум вложенности - 5"
Мы знаем, что это ограничение зашито в блокчейн, но все всегда при желании можно обойти на стороне клиента.
Вариантов решения тут много, но я выбрал одно (наиболее простое по реализации, но при этом достаточно удобное):
Если коммент 6й в цепочке, то записываем его "на этаж выше" и добавляем в начало коммента ссылку на них того на чей коммент отвечают (в духе @dr2073) - таки образом подобное не надо будет делать вручную, боты известят человека о том что его ник упомянули, дискуссия 5+ просто станет линейной, как сделано на многих форумах где поддерживаются деревья комментов.
Возможно есть и другие, более лучшие варианты решения - давайте обсудим. 
[Пост - баунти на эту задачу здесь](https://golos.io/ru--zadacha-golos/@dr2073/zadacha-golos-183-oboiti-na-kliente-ogranichenie-po-maksimalnoi-vlozhennosti-v-5-kommentov)

**Comment by 0n0t0le** [comment]
Пофиксить на уровне блокчейна, обсуждение порой даже важнее самого поста, ограничение в 5 слишком критично.

**Comment by gamerate** [comment]
Увеличив в блокчейне на 5+ мы возможно создадим некие побочные проблемы и что тоже неприятно будут проблемы с визуальным отображением на сайте - ведь оно будет все больше сдвигаться вправо и уменьшаться в размере.

**Comment by Undeadlol1** [comment]
Во-первых, визуально будет сложно читать большое количество вложенных комментариев.
Во-вторых, насколько я помню, вариант отключения этого ограничения в блокчейне не рассматривается, так как будет слишком сильно нагружать сеть.

**Comment by 21xhipster** [comment]
Ограничение в 5 уровней вложенности установил я перед запуском. Это на один уровень вложенности меньше чем в Стиме.
Причины:
1. Большое количество уровней вложенности делает невозможным адекватное отображение на мобильных клиентах. 
2. Создание большого количества уровней вложенности сильно затрудняет восприятие тредов. Ограничение в 5 уровней стимулирует вести дискуссию более конструктивно.
3. На практике такая вложенность достигается редко. [Посмотрите](https://golos.io/ru--komanda/@creat0r/golosovanie-dream-team-vybor-komandy-dlya-razvitiya-blokcheina-golos-i-golos-io) на один из самых популярных постов. Комментов последнего уровня вложенности в общей доле - единицы.

Но вопрос с удобством надо решать. Решение может быть очень простым на клиенте: для комментов 5-го уровня при нажатии кнопки ответить вместо того, чтобы выдавать ошибку
<img width="648" alt="screen shot 2016-12-31 at 2 48 53 pm" src="https://cloud.githubusercontent.com/assets/410789/21576391/4940d882-cf68-11e6-9baf-e1515fe6b6a7.png">, нужно отправлять транзакцию на комментарий того же уровня вложенности в которой (1) parent = parent коммента на который нужно ответить и (2) есть упоминание пользователя которому отвечаем в начале комментария типа: `@Undeadlol1, а не пойти ли бы Вам в жопу`

**Comment by Undeadlol1** [comment]
После мерджа кнопка будет просто выключена.

**Comment by 21xhipster** [comment]
Как вариант

**Comment by 21xhipster** [comment]
А где issue с мерджем?

**Comment by Undeadlol1** [comment]
#172

**Comment by gamerate** [comment]
> После мерджа кнопка будет просто выключена.

Фейспалм - те выключить кнопку это решение проблемы?
Люди постоянно упираются в это ограничение и очень расстраиваются, а теперь они вообще кнопку ответить не смогут нажать? 
Крайне дружелюбный вариант для пользователей. Наша задача всех разогнать с Голоса?
Хипстер описал прекрасный вариант решения (с-но который я описал в самом начале) почему не сделать так?

**Comment by Undeadlol1** [comment]
Потому что слишком много мороки, которой на данный момент заниматься некому.
Я с удовольствием приму пулл реквест решающий эту проблему.
