### ISSUE TITLE
Правки по футеру комментария в мобильной версии (увеличить отступы между иконками)

### ISSUE THREAD

**Issue by kuchinskaya** [GolosChain/tolstoy#1832]
![image](https://user-images.githubusercontent.com/37017857/50215785-193dc600-0395-11e9-9b7a-7fe61be033e7.png)
Должно быть так: http://prntscr.com/lwx5wo

**Comment by daryasattarova** [comment]
должна быть разделяющая линия между комментом и ответом и под ответом должны быть те же кнопки, что и под комментом
https://prnt.sc/ly8w9i

**Comment by bacher** [comment]
Отображены не все кнопки потому что это твой ответ. У чужих ответов отображаются все кнопки.
