### ISSUE TITLE
Определение языка по умолчанию через IP адрес

### ISSUE THREAD

**Issue by aleksandrazz** [GolosChain/tolstoy#184]
При загрузке страницы для незарегистрированных пользователей первые 2-5 секунд интерфейс показывается на русском, после чего обновляется язык и весь интерфейс отображается на английском, например: 

![15397642_1624713530927064_686436953_o](https://cloud.githubusercontent.com/assets/23729515/21061228/18f43798-be54-11e6-8a28-71b59915238d.png)

Предложения: 

1. Лучше всего дать возможность незарегистрированному пользователю выбрать язык, при этом дефолтным оставить русский

2. Просто пофиксить все и оставить для незарегистрированных пользователей только русский язык, так как платформа ориентирована на русскоговорящих

**Comment by gamerate** [comment]
Переключение происходит автоматически на то язык который выставлен приоритетным в браузере, так что это не баг, а фича. 
В идеале конечно оно должно не переключаться, а изначально показывать на правильном языке, но это не очень существенно.

**Comment by Undeadlol1** [comment]
Можно сделать определение местонахождение пользователя по ip, и выставлять язык соответственно.
Я, вроде пару месяцев назад делал это, где-то код должен лежать.

**Comment by Undeadlol1** [comment]
@gamerate спасибо, я это проверяю.

**Comment by 21xhipster** [comment]
Я за то, чтобы оставить настройки юзера и не привязываться к IP. Людей которые путешествуют может сильно напрягать это. Обратный кейс это когда юзер себе выставляет настройки UX на английском. Он это делает осознано, т.к. ему так больше нравится. Закрываю вопрос

**Comment by 21xhipster** [comment]
Почему?

**Comment by Undeadlol1** [comment]
Пусть повисит, я хочу подумать над этим вопросом.

**Comment by 21xhipster** [comment]
Миш. Вот ей богу нечего тут думать. Показываем локаль на основании настроек браузера юзера. Все остальное - доказанная шляпа. Ты задач гораздо более важных уйма

**Comment by Undeadlol1** [comment]
Браузер Chrome по-умолчанию использует английский язык. Им пользуется много людей.
Для них сайт будет на английском,  даже если они его не знают. На тех кто путешествует мне плевать.
Не закрывай то, что я открыл, не лезь.

**Comment by 21xhipster** [comment]
@Undeadlol1 Мы тут так не общаемся.

**Comment by Undeadlol1** [comment]
@21xhipster Как так? Ты вечно приходишь, то ишью закроешь, то репозиторий в какую-то хуйню переименуешь, то людей левых пригласишь, который код прямо в мастер ветку коммитят без моего ведома.
Вечно делов наделаешь в моем репозитории без моего ведома, а мне расхлебывать потом.

**Comment by 21xhipster** [comment]
Просто мы так тут не общаемся. Давай конструктивнее.
