### ISSUE TITLE
Регистрация аккаунта

### ISSUE THREAD

**Issue by siberianshamen** [GolosChain/tolstoy#187]
Здравия! Реализую сейчас проект - https://golos.io/ru--golos/@siberianshamen/podari-zhizn позавчера зарегистрировал аккаунт на Steemet - golos-zoo-fund
а на Голосе не удается. 2-е суток бьюсь и без толку. Помогите.

**Comment by Chiliec** [comment]
А в чём проблема? Нужно больше информации чтобы помочь.

**Comment by siberianshamen** [comment]
Проблема в том, что Голос не дает регистрировать 2-й аккаунт. На другой акк в ВК и другую почту.
Выставляет адрес привязанной к нему почты и говорит, что уже есть акк и нефик ломиться.

**Comment by gamerate** [comment]
А из инкогнито сессии браузера пробовал?

**Comment by siberianshamen** [comment]
все перепробовал и 6 других браузеров и куки и новые акк на ВК и почту и даже более того - попросил друга из Махачкалы зарегать, дал акк на ВК новый, на почту новую связанную с ВК пришло уведомление что выполнен вход, а ссылка регистрации пришла на мою почту связанную с Голосом
и далее все также - у вас ест акк и нефик ломится еще делать

**Comment by Undeadlol1** [comment]
Я без понятия в чем проблема. @tomarcafe может ты знаешь?

**Comment by 0n0t0le** [comment]
На стиме же даже с однгого IP уже не дает регать акки. на Голосе не уверен.

**Comment by siberianshamen** [comment]
Спасибо всем. Победил!
Через новый акк на ФБ, новую почту и чужой комп =)

**Comment by Undeadlol1** [comment]
Да, скорее всего в IP была проблема. Я где-то видел в коде настройки, ограничивающие регистрацию, но я не бэк-эндер, в своих знаниях не уверен
