### ISSUE TITLE
некорректно работает страница "Вы покидаете Golos.io" в моб версии

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/tolstoy#1870]
на iphone 5s страница не скролится, кнопки не отображаются 
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/2b0214f6-d309-4e7f-a0a4-417af4e7e5f3)

**Comment by MachtFrei** [comment]
на живом девайсе из браузерстека работать не хочет ни кнопка перейти ни кнопка вернуться
![image](https://user-images.githubusercontent.com/2689880/50424179-78a64500-0871-11e9-8041-af6fc6a8649d.png)

**Comment by MachtFrei** [comment]
@daryasattarova , ты вроде как проверила на живом девайсе?
