### ISSUE TITLE
Ошибка в футере (на голос с ***)

### ISSUE THREAD

**Issue by MachtFrei** [GolosChain/tolstoy#1878]
На мобильной версии отображается на голос с Invalid date![Screenshot_19.png](https://images.zenhubusercontent.com/5c0e396352c51c42a50ed4bb/a80a51e4-d99c-45cf-9c95-483d218f2dbb)![Screenshot_20.png](https://images.zenhubusercontent.com/5c0e396352c51c42a50ed4bb/fe09b987-d84d-4a26-93b0-0e4a0b3773aa)

**Comment by daryasattarova** [comment]
не исправлено
