### ISSUE TITLE
Не закрывается попап в сафари 

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/tolstoy#1887]
Проблема:
1. при нажатии на ... открывается попап
2. при попытке его закрыть путем нажатия на бэкграунд ничего не происходит
(браузер сафари)
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/a34d38a0-5937-41e4-961d-23705d9b5db7)

Решение: сделать в правом верхнем углу крестик для закрытия попапа

**Comment by AlexRekish** [comment]
поправлено в #1888
