### ISSUE TITLE
Возможность "запланировать" свой пост

### ISSUE THREAD

**Issue by aleksandrazz** [GolosChain/tolstoy#189]
Очень пригодилась бы фича "запланировать свой пост" - т.е. заранее заготовить пост, который автоматически будет опубликован в определенный день в определенное время. 😇 

Спасибо! :)

**Comment by Undeadlol1** [comment]
Не приоритетно, в ближайшем будущем не ждите

**Comment by serejandmyself** [comment]
Это относится к блокчейну.
