### ISSUE TITLE
часто появляется ошибка в консоли "Gate error"

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/tolstoy#1898]
при загрузке страниц, например профиля, поста, ленты появляется ошибка gate error
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/53da23df-e90e-4c20-be18-49060f31d465)
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/0e0a5121-bc54-4156-914a-765b9f88672e)

**Comment by AlexRekish** [comment]
вроде уже исправлено
