### ISSUE TITLE
Ошибка ссылки в шапке сайта при нахождении внутри ресскоязычного тэга

### ISSUE THREAD

**Issue by primusd** [GolosChain/tolstoy#191]
Если перейти по ссылке внутрь любого русскоязычного тэга, например #история (https://golos.io/trending/ru--istoriya), то в шапке сайта (слева вверху, сразу после ссылки на главную Голоса) выводится название тэга "история" с некорректной ссылкой: https://golos.io/hot/история

Нужно исправить ссылку, подставив вместо тэга на русском его правильное кодирование английском.

Для англоязычных тэгов этой ошибки нет - только для тэгов на русском языке.

**Comment by Undeadlol1** [comment]
Спасибо что сообщили.
Исправил еще вчера, но задеплоил только сейчас.
