### ISSUE TITLE
некорректно отображается краткая информация в браузерах на движке webkit

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/tolstoy#1915]
в масштабе 90% краткая информация у пользователей с рейтингом 0 отображается некорректно
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/bfb142b9-3811-4861-bded-e506ea9aab1b)

**Comment by daryasattarova** [comment]
у некоторых юзеров тоже есть проблемы с отображением 
![image](https://user-images.githubusercontent.com/42342756/50895696-dd3bd500-1417-11e9-804b-856ad442bd18.png)

**Comment by MachtFrei** [comment]
текста рейтинг 0 нету, это ок? 
'https://sandbox.golos.io/@test2'
![image](https://user-images.githubusercontent.com/2689880/51045757-6b10ef00-15d5-11e9-8281-28a61d0e0ad5.png)

**Comment by AlexRekish** [comment]
так и задумано
