### ISSUE TITLE
не приходят онлайн нотификации

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/tolstoy#1917]
не приходят нотификации. отображаются лишь во вкладке "активность"

**Comment by AlexRekish** [comment]
на локальной версии и в дев и в прод сборке все работает корректно, на песочнице нотификации с вебсокета не приходят вообще.

UPD: не приходят нотификации с wss://dev-gate.golos.io .

**Comment by NickShtefan** [comment]
После исправления конфигурации на песочнице проблема не актуальна.
