### ISSUE TITLE
Большая дырка...

### ISSUE THREAD

**Issue by lehard** [GolosChain/tolstoy#192]
...стала в поле для комментариев

![image](https://cloud.githubusercontent.com/assets/22220976/21256295/48214e86-c393-11e6-859f-363d8efa87e1.png)

**Comment by Undeadlol1** [comment]
Окей, разберемся

**Comment by tomarcafe** [comment]
это часом не textarea там? так-то они тянутся за угол

**Comment by Undeadlol1** [comment]
Я вчера textarea увеличил чтобы редактировать посты удобнее было. 
Похоже теперь нужно специальный селектор для поле комментирования сделать.
