### ISSUE TITLE
Регистрация закрыта, комментарии анонимам недоступны. Откройте комментарии на чтение!

### ISSUE THREAD

**Issue by Nashev** [GolosChain/tolstoy#1921]
https://goldvoice.club/registration/ - закрыта
https://goldvoice.club/@golosio/golos-io-obnovleniya-na-platforme/ - комментарии не видны не залогинившимся, а залогиниться невозможно, потому что регистрация закрыта

Это очень плохо, так как в комментариях как правило очень много всего полезного.

**Comment by Nashev** [comment]
https://golos.io/golosio/@golosio/golos-io-obnovleniya-na-platforme#comments - открыты и комментарии, и регистрация.
Кажется, https://goldvoice.club не под Вашим контролем. Извиняюсь, если действительно тикет не к вам. Закрывайте, если так.

**Comment by NickShtefan** [comment]
действительно тикет не к нам
