### ISSUE TITLE
Реализовать возможность установить желаемый процент кураторских наград при создании/редактировании поста

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/tolstoy#1939]

**Comment by NickShtefan** [comment]
https://zpl.io/aByOGDL и https://zpl.io/25rmEpQ

**Comment by NickShtefan** [comment]
выбор может быть сделан в пределах значений (А и В), установленного делегатами. 

Интересующие параметры называются

Min Curation Percent | Значение А
-- | --
Max Curation Percent | Значение В

**Comment by bacher** [comment]
Пока что запрещаю редактирование этого поля после создания поста, так как блокчейн отвечает ошибкой при этой попытке:

```
invalid operation in transaction (3010000)↵Invalid operation 1 in transaction: business logic error (2030000)↵A comment cannot accept a greater percent SBD.
```
