### ISSUE TITLE
при открытии страницы в консоли отображаются ошибки 

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/tolstoy#1940]
Воспроизведение: 
1. открыть песочницу
2. залогиниться
3. перейти в свой профиль

Реальный результат: данные не загружаются
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/55449c32-463c-43c8-969f-d563c16b7cb3)
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/0aa9a015-ad5a-481f-9172-e077614c5916)

**Comment by AlexRekish** [comment]
скорее всего надо обновить ws_connection_client на актуальную версию

**Comment by NickShtefan** [comment]
ошибка на стороне тестовой версии сервисов, продовые эндпоинты работают без проблем
