### ISSUE TITLE
OAuth на блокчейн голос

### ISSUE THREAD

**Issue by t3ran13** [GolosChain/tolstoy#196]
https://geektimes.ru/company/hashflare/blog/284228/

Насколько реально реализовать OAuth  по аналогии для нашего блокчейна

**Comment by t3ran13** [comment]
обсуждение тут https://golos.io/ru--golos/@t3ran13/oauth-na-baze-blokchein-golos

**Comment by Undeadlol1** [comment]
Так это задача golos.io или [goloschain](https://github.com/GolosChain/golos)?
