### ISSUE TITLE
при попытке откомментировать пост появляется ошибка (testnet)

### ISSUE THREAD

**Issue by daryasattarova** [GolosChain/tolstoy#1961]
![image.png](https://images.zenhubusercontent.com/5b851e384b5806bc2be425f1/5a93f829-53c9-4c69-b455-747941bc70e3)
Error: transaction.operations = comment,[object Object],comment_options,[object Object]     cause: comment_options.extensions = 1,[object Object]     cause: 1.destination = undefined     cause: Illegal value: undefined (not an integer or Long)
stack: TypeError: Illegal value: undefined (not an integer or Long)

**Comment by b1acksun** [comment]
https://github.com/GolosChain/tolstoy/pull/1963/commits/ac968b01b781b087f7e843dd0977fb9412f94cca
