### ISSUE TITLE
Убрать лишнее слово в уведомлении

### ISSUE THREAD

**Issue by lehard** [GolosChain/tolstoy#198]
Лишнее слово в уведомлении о подписках:

[![Безымянный.jpg](https://s29.postimg.org/hyit333br/image.jpg)](https://postimg.org/image/44uge1aqb/)

https://golos.io/ru--oshibka/@dreamer/gospoda-razrabotchiki-dizaina-uberite-lishnee-slovo

**Comment by 0n0t0le** [comment]
Забавно, issue закрыт месяц назад... 
(*проглядели=)*)

https://github.com/GolosChain/tolstoy/issues/160
