### ISSUE TITLE
Для рекламных целей прописать "пиксель" FB в код Golos.io

### ISSUE THREAD

**Issue by solodikov** [GolosChain/tolstoy#200]
Нужно установить на сайте два вида сниппетов кода:
1. Базовый код пикселя на каждой странице сайта.
2. Код события на определенных веб-страницах (на 3).

1 - Установка базового кода пикселя
Базовый код пикселя отслеживает активность на сайте и помогает измерять определенные события. Скопируйте приведенный ниже базовый код и вставьте его между тегами заголовка на каждой странице своего сайта:

```
<!-- Facebook Pixel Code -->
<script>
!function(f,b,e,v,n,t,s)
{if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};
if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];
s.parentNode.insertBefore(t,s)}(window,document,'script',
'https://connect.facebook.net/en_US/fbevents.js');
 fbq('init', '136063983553382'); 
fbq('track', 'PageView');
</script>
<noscript>
 <img height="1" width="1" 
src="https://www.facebook.com/tr?id=136063983553382&ev=PageView
&noscript=1"/>
</noscript>
<!-- End Facebook Pixel Code -->
```

2 - Код события позволяет отслеживать конкретные действия и использовать их в рекламе. Вам понадобится установить код события на тех страницах сайта, где будут выполняться интересующие вас действия.

Вы можете использовать 9 стандартных событий, которые предлагает отслеживать Facebook, и оптимизировать рекламу для привлечения конверсий. Чтобы измерить результаты, вы можете добавить параметры в свои события с помощью рекомендуемого или расширенного вариантов установки тегов события. Кроме того, вы можете создать индивидуально настроенные события для действий, которые важны вашей компании. Есть три варианта интеграции: базовый, рекомендуемый и расширенный.

а) код ViewContent - Отслеживание просмотров ключевых страниц (например, страницы продукта, целевой страницы или статьи):
`fbq('track', 'ViewContent');`
 - поставить сюда: https://golos.io/ru--golos/@natasha/znakomstvo-s-platformoi-golos-tokeny-registraciya-i-lichnyi-kabinet

б) код Lead - Отслеживание интереса пользователя к вашему предложению (например, отправка формы, регистрация на пробную подписку, переход на страницу с расценками):
`fbq('track', 'Lead');`
- поставить сюда: https://golos.io/create_account

в) код CompleteRegistration - Отслеживание заполнения формы регистрации (например, оформление подписки, регистрация на использования услуги):
`fbq('track', 'CompleteRegistration');`
- поставить сюда: https://golos.io/create_account

**Comment by Undeadlol1** [comment]
Последнее нужно трэкать после успешного завершения регистрации, правильно?

**Comment by solodikov** [comment]
Да.

**Comment by solodikov** [comment]
@Undeadlol1, найс! )
