### ISSUE TITLE
(staging) В профиле пользователя не подгружаются недавние ответы

### ISSUE THREAD

**Issue by Undeadlol1** [GolosChain/tolstoy#201]

**Comment by Undeadlol1** [comment]
@serejandmyself 
Вот какая ситуация, многие данные не подгружаются нормальное: недавние комментарии пользователя, количество постов, количество подписчиков и прочее.
Есть два варианта: я потрачу кучу часов на то, чтобы пофиксить и вернуть как было, или мы можем подождать хардфорка, когда в блокчейне будет использоваться shared-db, из-за которого вся передряга и приключилась.
Второй вариант предпочтительней, потому что сначала придется тратить время на фикс загрузки данных, а затем тратить время на то чтобы вернуть все назад.
Когда хардфорк планируется?

**Comment by Undeadlol1** [comment]
Закрываю пока

**Comment by serejandmyself** [comment]
Ждем share db конечно, зачем делать двойную работу?
