### ISSUE TITLE
Добавить тег META Description

### ISSUE THREAD

**Issue by serejandmyself** [GolosChain/tolstoy#203]
Добавить тег META Description с содержанием: Голос - это блог-платформа, основанная на технологии блокчейн (blockchain), децентрализованная социальная медиаплатформа для блогеров и журналистов c уникальным контентом.

**Comment by serejandmyself** [comment]
Предлагаю отложить пока. Так как не разобрались с этим вопросом (позиционирование)

**Comment by 21xhipster** [comment]
Мета Описание не должно быть одним и тем же. Лучше его генерить из тагов и возможно тизера поста. Надо обсуждать. Но лучше его вообще не использовать, чем спамить и Гугл и код страницы одним и тем же текстом.

**Comment by Undeadlol1** [comment]
Апдейт есть?
Сейчас стоит вот это

> 'Голос - социальная сеть, построенная на публичном блокчейне. Вознаграждение пользователей осуществляется за счет дополнительной эмиссии токенов. При этом распределением токенов управляют текущие пользователи сети через голосование за лучший контент.'

Менять будем?
