### ISSUE TITLE
Настроить редирект с WWW

### ISSUE THREAD

**Issue by serejandmyself** [GolosChain/tolstoy#204]
Аналайзер ругается, что не настроен редирект. Дословно:

"Перенаправление не настроено.
Если сайты www.golos.io и golos.io работают по отдельности без редиректов. Эти две копии могут «склеится» поисковыми системами, что негативно скажется на поисковой оптимизации"

**Comment by Undeadlol1** [comment]
На стороне клиента это можно сделать, теоретически, но это будет тупо. Этим нужно заниматься на уровне nginx.

**Comment by serejandmyself** [comment]
Так оно в бэкэнд стоит

**Comment by Undeadlol1** [comment]
Под клиентом я имел ввиду веб-приложение. Имелся ввиду редирект из node.js.
