### ISSUE TITLE
Оптимизировать соотношение текста к коду на странице

### ISSUE THREAD

**Issue by serejandmyself** [GolosChain/tolstoy#205]
Подробно: соотношение текста на странице к общему количеству html-кода слишком низкое. Рекомендуется держать его на уровне 25% и выше, а на проанализированной странице 2%. Это означает много кода и мало текста, нужно сделать перевес в сторону последнего. Попробуйте вынести стили во внешние CSS-файлы, а JavaScript-скрипты во внешние JS-файлы. Кроме того посмотрите сам HTML, вероятно в нем есть что оптимизировать.
Длина текста:
7138 символов

Длина html-кода:
362986 символов

Общая длина страницы:
370124 символов

Соотношение текста страницы к html коду напрямую влияет на индексацию поисковиками. Чем больше текста - тем лучше страница выглядит в глазах поисковых систем. Поисковые системы оценивают контент, а не код, поэтому основная часть веб-страницы должна отводиться именно под текстовое содержимое. Рекомендуемое значение - текста на странице должно быть не менее 25%)

**Comment by Undeadlol1** [comment]
Я проанализировал наш код, и сутация следующая:
у нас куча скриптов и стилей находятся в теле страницы, а не во внешних файлов. Это сделано специально, чтобы снизить количество запросов к серверу, и чтобы ускорить загрузку страницы.
Придется довольно сильно попердолиться с тем, чтобы вынести эти скрипты и стили во внешний файл. В итоге сервер будет с каждым запросом отправлять три файла вместо одного, загрузка страницы чуть увеличится (хотя это и спорный момент), и неизвестно насколько результут аналайзера будет лучше.
@serejandmyself @solodikov

**Comment by serejandmyself** [comment]
Если, это увеличит время загрузки страницы, то это большее зло, чем на "не понятно сколько сотых %" увеличить результат аналайзера

**Comment by Undeadlol1** [comment]
Вот как это работает сейчас:
Брауузер получает хтмл и начинает обрабатывать его > во время обработки хтмл он запускает скрипты и обрабатывает css.
Как это будет работать:
Браузер получает html файл > он обрабатывает его > он видит ссылки на скипты и стили и начинает и делает запрос к серверу > сервер возвращает файлы > браузер начинает их обрабатывать.

Это увеличит скорость загрузки страницы, да.

**Comment by Undeadlol1** [comment]
@solodikov Антон, мы без этого сможем прожить? Это очень важно?
Просто скорость загрузки страницы пострадает, мы с Сережей за то чтобы отказаться от этой задачи.

**Comment by solodikov** [comment]
Ок. Давайте пока откажемся, а если в дальнейшем аналайзер будет сильно ругаться - я привлеку экспертизу по вопросам "сможем ли мы без этого прожить?" и "оно нам надо?". Закрывайте )

**Comment by 21xhipster** [comment]
Я бы подобного рода оптимизации отложил в дальний ящик. Но рано или поздно это придется делать, т.к. апликухи уже давно не только для людей, но еще и для роботов. Иначе контент людьми просто не находится.

**Comment by solodikov** [comment]
@21xhipster, важно, много ли мы на этом теряем сейчас?
