### ISSUE TITLE
Решить проблему с JS, CSS

### ISSUE THREAD

**Issue by serejandmyself** [GolosChain/tolstoy#206]
В верхней части страницы найден блокирующий CSS: 3.
В верхней части страницы найден блокирующий JS: 1.

Комментарий аналайзера:

"Перед отображением страницы браузер должен выполнить ее синтаксический анализ. Если при этом он обнаруживает внешний скрипт, он должен его загрузить. Это лишний цикл операций, который замедляет показ страницы. Также браузеры запрашивают внешние файлы CSS перед отображением контента на экране. Это приводит к задержке и замедляет обработку страницы.

Код JavaScript, необходимый для отображения верхней части страницы, должен быть встроенным, а код, отвечающий за дополнительные функции, должен выполняться после загрузки верхних элементов.

Если внешние ресурсы CSS имеют малый объем, их можно вставить непосредственно в документ HTML. Подобное встраивание позволяет браузеру продолжать загрузку страницы. Если файл CSS слишком велик, вам необходимо найти код CSS, отвечающий за контент в верхней части страницы и встроить его в HTML, отложив загрузку остальных стилей."

**Comment by solodikov** [comment]
Удалите код JavaScript и CSS, блокирующий отображение верхней части страницы.

Количество блокирующих скриптов на странице: 1.
Количество блокирующих ресурсов CSS на странице: 3.
Они замедляют отображение контента. 

Все содержание верхней части страницы отображается только после загрузки указанных далее ресурсов. Попробуйте отложить загрузку этих ресурсов, загружать их асинхронно или встроить их самые важные компоненты непосредственно в код HTML.

Удалите код JavaScript, препятствующий отображению:

`https://cdn.polyfill.io/v2/polyfill.min.js?features=Intl.~locale.en,Intl.~locale.ru,Intl.~locale.ua`

Оптимизируйте работу CSS на следующих ресурсах:

```
https://fonts.googleapis.com/css?family=Roboto
https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css
https://golos.io/assets/app-af930eb21c23f62fcf67.css
```

**Comment by Undeadlol1** [comment]
@solodikov что за анализатор ты используешь? Он все внешние ресурсы считает блокирующими. Css вообще никак не влияет на контент, который краулерам нужен. Тут какой-то подвох заключается.
Мне нужна ссылка на то что ты видишь.

**Comment by solodikov** [comment]
@Undeadlol1, Миш, все анализаторы ругаются, например:
https://a.pr-cy.ru/golos.io/#/tests/pageSpeedMinimizeRenderBlockingResources
или: https://seowins.ru/ru/www/golos.io
Посмотри эти пункты там в соответствующих разделах.

**Comment by Undeadlol1** [comment]
Переделал загрузку стилей и скриптов и все-равно они отображаются блокирующими. Обидно.

**Comment by lehard** [comment]
Похоже из-за этого сайт стал странно открываться. На мгновение такая штука появляется

![image](https://cloud.githubusercontent.com/assets/22220976/21749609/04c2ae08-d5c4-11e6-8d6d-fbe94da984e9.png)

**Comment by solodikov** [comment]
Увидел. Странно.

**Comment by Undeadlol1** [comment]
@lehard тем не менее сайт стал загружаться быстрее. Это эксперимент.

**Comment by Undeadlol1** [comment]
Почитал я стимитовский код. Оказалось что в новых релизах эти проблемы решены. После мерджа и у нас все будет нормально.

**Comment by sualex** [comment]
Штука, которая появляется - это отрендеренный DOM с непримененными стилями, а позже залетают стили и все становится ок. То ли бандлер их долго подтягивает, то ли монтируются поздно как-то ... неделю назад не было этого )

**Comment by serejandmyself** [comment]
Сам косяк где "это" появляется вроде решили. Остался сам иссью, но если он в мердже решен, то тогда можно не тратить время, так как мердж уже почти "сделан"

**Comment by sualex** [comment]
А решения косяков не пул-реквестами оформляются? Как происходит деплой на боевой сервак? Где посмотреть на скрипты развертывания? С уважением.

**Comment by 21xhipster** [comment]
@sualex Похоже это вопросы на которые придется отвечать тебе. @tomarcafe можешь начать передавать дела?
