### ISSUE TITLE
Настроить протокол OG - cоздать и разместить мета теги Og Meta Properties

### ISSUE THREAD

**Issue by serejandmyself** [GolosChain/tolstoy#208]
Бесплатный генератор: http://seowarlock.ru/webmaster/generator-og-properties.php

**Comment by serejandmyself** [comment]
Разве это не оно:

https://github.com/GolosChain/tolstoy/blob/master/app/utils/ExtractMeta.js

https://github.com/GolosChain/tolstoy/blob/master/config/client_config.js

@Undeadlol1 ?

Если так, то закрываем, если там что то не верно, то тогда вопрос к тебе @solodikov

**Comment by serejandmyself** [comment]
@solodikov Проверить анализаторы

**Comment by solodikov** [comment]
Проверил. Нет, не настроено.

**Comment by solodikov** [comment]
#221 закрыли и совместили с этой #208
@serejandmyself и @Undeadlol1 - актуально.

**Comment by Undeadlol1** [comment]
Во-первых, почему оба ишью закрыты?
Во-вторых, эти исправления есть в мердже

**Comment by solodikov** [comment]
Миша, а когда у нас они активируются?

**Comment by Undeadlol1** [comment]
Когда хардфорк примем
