### ISSUE TITLE
Вынести в отдельный CSS файл inline-стили

### ISSUE THREAD

**Issue by serejandmyself** [GolosChain/tolstoy#209]
Комментарий аналайзера:

Сначала аналайзер пишет:
Внимание, в коде страницы обнаружены inline-стили оформления верстки. Всего робот нашел 60 инлайновых стилей. Необходимо вынести их в отдельный CSS файл.

И даёт этот список из 64 пунктов.

А следом пишет пишет такую странность:

Inline-стили (или инлайновые стили) - стили которые не выносятся в отдельный CSS файл, а задаются прямо в HTML-коде. Это негативно сказывается на размере страницы. Кроме того инлайновые стили негативно влияют на соотношение текста к html-коду, который необходимо держать в определенных рамках. Поисковые системы ценят контент страницы, а не ее код.
Я так понял, если это побороть, то и с соотношением контент/код возможно не придётся парится.
Но видимо в этом больше смысла.

Найдено 65:

Тег содержит:
display:inline-block;width:1.12rem;height:1.12rem;

Тег содержит:
display:inline-block;width:1.12rem;height:1.12rem;

Тег  содержит:
display:inline-block;width:2rem;height:2rem;

Тег содержит:
display:inline-block;width:1.12rem;height:1.12rem;

Тег содержит:
display:inline-block;width:1.12rem;height:1.12rem;

Тег содержит:
background-image:url(https://imgp.golos.io/128x256/https://img1.steemit.com/0x0/https://scontent-...

Тег содержит:
display:inline-block;width:1.12rem;height:1.12rem;

Тег содержит:
display:inline-block;width:1.12rem;height:1.12rem;

Тег содержит:
background-image:url(https://imgp.golos.io/128x256/https://img1.steemit.com/0x0/http://pix.toile-...

Тег содержит:
display:inline-block;width:1.12rem;height:1.12rem;

Тег содержит:
display:inline-block;width:1.12rem;height:1.12rem;

Тег содержит:
background-image:url(https://imgp.golos.io/128x256/https://habrastorage.org/files/a76/0b9/08a/a76...

Тег содержит:
display:inline-block;width:1.12rem;height:1.12rem;

Тег содержит:
display:inline-block;width:1.12rem;height:1.12rem;

Тег содержит:
background-image:url(https://imgp.golos.io/128x256/https://img.youtube.com/vi/qfc5O684Cdo/0.jpg);

Тег содержит:
display:inline-block;width:1.12rem;height:1.12rem;

Тег содержит:
display:inline-block;width:1.12rem;height:1.12rem;

Тег содержит:
background-image:url(https://imgp.golos.io/128x256/http://konnov.name/akina-master/img/2016-12/29...

Тег содержит:
display:inline-block;width:1.12rem;height:1.12rem;

Тег содержит:
display:inline-block;width:1.12rem;height:1.12rem;

Тег содержит:
background-image:url(https://imgp.golos.io/128x256/http://vivasan-global.ru/wp-content/uploads/20...

Тег содержит:
display:inline-block;width:1.12rem;height:1.12rem;

Тег содержит:
display:inline-block;width:1.12rem;height:1.12rem;

Тег содержит:
background-image:url(https://imgp.golos.io/128x256/https://pp.vk.me/c637124/v637124938/22dda/FF_K...

Тег содержит:
display:inline-block;width:1.12rem;height:1.12rem;

Тег содержит:
display:inline-block;width:1.12rem;height:1.12rem;

Тег содержит:
background-image:url(https://imgp.golos.io/128x256/http://konnov.name/akina-master/img/2016-12/29...

Тег содержит:
display:inline-block;width:1.12rem;height:1.12rem;

Тег содержит:
display:inline-block;width:1.12rem;height:1.12rem;

Тег содержит:
background-image:url(https://imgp.golos.io/128x256/https://img.youtube.com/vi/gNBek3-i3R0/0.jpg);

Тег содержит:
display:inline-block;width:1.12rem;height:1.12rem;

Тег содержит:
display:inline-block;width:1.12rem;height:1.12rem;

Тег содержит:
background-image:url(https://imgp.golos.io/128x256/http://konnov.name/akina-master/img/2016-12/29...

Тег содержит:
display:inline-block;width:1.12rem;height:1.12rem;

Тег содержит:
display:inline-block;width:1.12rem;height:1.12rem;

Тег содержит:
background-image:url(https://imgp.golos.io/128x256/http://i5.imageban.ru/out/2016/01/08/d3d49637e...

Тег содержит:
display:inline-block;width:1.12rem;height:1.12rem;

Тег содержит:
display:inline-block;width:1.12rem;height:1.12rem;

Тег содержит:
background-image:url(https://imgp.golos.io/128x256/http://storage2.static.itmages.ru/i/16/1228/h_...

Тег содержит:
display:inline-block;width:1.12rem;height:1.12rem;

Тег содержит:
display:inline-block;width:1.12rem;height:1.12rem;

Тег содержит:
background-image:url(https://imgp.golos.io/128x256/http://i.imgur.com/2rxRf3C.png);

Тег содержит:
display:inline-block;width:1.12rem;height:1.12rem;

Тег содержит:
display:inline-block;width:1.12rem;height:1.12rem;

Тег содержит:
background-image:url(https://imgp.golos.io/128x256/http://i075.radikal.ru/1612/56/7ced2356b425.png);

Тег содержит:
display:inline-block;width:1.12rem;height:1.12rem;

Тег содержит:
display:inline-block;width:1.12rem;height:1.12rem;

Тег содержит:
background-image:url(https://imgp.golos.io/128x256/https://i1.wp.com/habr.habrastorage.org/post_i...

Тег содержит:
display:inline-block;width:1.12rem;height:1.12rem;

Тег содержит:
display:inline-block;width:1.12rem;height:1.12rem;

Тег содержит:
background-image:url(https://imgp.golos.io/128x256/http://www.infpol.ru/upload/iblock/5ca/5cafb3e...

Тег содержит:
display:inline-block;width:1.12rem;height:1.12rem;

Тег содержит:
display:inline-block;width:1.12rem;height:1.12rem;

Тег содержит:
background-image:url(https://imgp.golos.io/128x256/http://i.imgsafe.org/38f4adc303.jpg);

Тег содержит:
display:inline-block;width:1.12rem;height:1.12rem;

Тег содержит:
display:inline-block;width:1.12rem;height:1.12rem;

Тег содержит:
background-image:url(https://imgp.golos.io/128x256/https://i.imgsafe.org/4215fba534.jpg);

Тег содержит:
display:inline-block;width:1.12rem;height:1.12rem;

Тег содержит:
display:inline-block;width:1.12rem;height:1.12rem;

Тег содержит:
background-image:url(https://imgp.golos.io/128x256/http://i.imgsafe.org/3b04b120e7.jpg);

Тег содержит:
display:inline-block;width:1.12rem;height:1.12rem;

Тег содержит:
display:inline-block;width:1.12rem;height:1.12rem;

Тег содержит:
background-image:url(https://imgp.golos.io/128x256/https://pp.vk.me/c984/u17260216/103294897/x_d3...

Тег содержит:
display:inline-block;width:1.12rem;height:1.12rem;

Тег содержит:
display:inline-block;width:1.12rem;height:1.12rem)

**Comment by Undeadlol1** [comment]
Сейчас должно быть исправлено. Нужно вновь проанализировать. @solodikov

**Comment by solodikov** [comment]
Ок. @Undeadlol1

**Comment by solodikov** [comment]
Норм. Настроено.
