### ISSUE TITLE
Переделать страницу /ico#team

### ISSUE THREAD

**Issue by serejandmyself** [GolosChain/tolstoy#210]
Переделать страницу /ico#team согласно обговорённому ранее с Костей и Сергеем:

киберфонд убираем
в команде пока пишем нас четверых (+ фулл, как будет)
добавляем делегатов в меню
составляем список делегатов с фото, возможно настраиваем и подтягиваем авто-обновление этого списка

**Comment by serejandmyself** [comment]
Not important - backlog issue

**Comment by Undeadlol1** [comment]
Данные о делегатах будут фетчится из сети. Они будут отображаться согласно их позиции в списке.

**Comment by serejandmyself** [comment]
Дабы не плодить issue:

Добавить на /ico#team:

Михаил Комаров
Блокчейн разработка 
[![2765860.png](https://s23.postimg.org/ju1d2msuz/2765860.png)](https://postimg.org/image/jh9ywgal3/)
(ссылка - https://s23.postimg.org/ju1d2msuz/2765860.png )

Профиль - github - https://github.com/Nemo1369

**Comment by solodikov** [comment]
Перепишите "Проджект менеджер" на **Project Manager**.

**Comment by 21xhipster** [comment]
@solodikov Не! Надо по-русски - Проектный менеджер

**Comment by serejandmyself** [comment]
На Русском нет слова менеджер )

На рууском это - Управляющий проектом / Руководитель проекта

**Comment by serejandmyself** [comment]
В новой версии веб клиента
