### ISSUE TITLE
Задать язык для сайта 

### ISSUE THREAD

**Issue by serejandmyself** [GolosChain/tolstoy#211]
Бесплатный генератор мета-тэгов: http://seowarlock.ru/webmaster/meta-tags-generator.php

**Comment by serejandmyself** [comment]
Мне кажется нужны уточнения

**Comment by solodikov** [comment]
Всё просто же. Аналайзер ругается, что не видит тэг языка.

> Вы не установили язык веб-сайта. Используйте бесплатный генератор мета-тэгов, чтобы установить язык Вашего веб-сайта.

**Comment by serejandmyself** [comment]
Я думаю, что тебе надо написать @Undeadlol1 какой поставить, или @Undeadlol1 ты можешь это выбрать сам?

**Comment by pavelit** [comment]
Тег языка присутствует.
