### ISSUE TITLE
Сделать крестик закрытия страницы скользящим при прокрутке страницы

### ISSUE THREAD

**Issue by serejandmyself** [GolosChain/tolstoy#212]
Есть вариант, что это учтено в мердже, тогда, просьба закрыть 

[![d4a1a35929e1.png](https://s24.postimg.org/l8z7ski5x/d4a1a35929e1.png)](https://postimg.org/image/z2nkhmar5/)

[![24aac90200cb.png](https://s28.postimg.org/xh4j9pj9p/24aac90200cb.png)](https://postimg.org/image/r3fg6gedl/)

**Comment by Undeadlol1** [comment]
Пофикшено в мердже
