### ISSUE TITLE
Сделать изображения по умолчанию отцентрированными в редакторе

### ISSUE THREAD

**Issue by Undeadlol1** [GolosChain/tolstoy#213]

**Comment by serejandmyself** [comment]
@Undeadlol1 Миша, дублирую ответ тут, если смысл только в том чтобы сделать youtube видео по центру, то это скорее ограничение, а не фича. Многие пользователи пишут с align left или align right, а многим нравится ставить картинки с правой стороны по умолчанию. 

Хотя, с другой стороны логичней чтобы картинка была по центру, и если надо то пользователь её бы сдвинул, в случае нужды

**Comment by Undeadlol1** [comment]
Я вижу несколько причин сделать это:
99% которых я вижу используют лишь пару картинок, которые они никак не алайнят. Центровка сделала бы эти посты красивее. Потому что картинка прикрепленная к левому краю выглядит неаккуратно.
Многие пользователи вообще про алаймент картинок не знают и не умеют пользоваться. Но центровка по центру выглядит наиболее логично, если текст не обтекается текстом. А он никогда не обтекается.
Я, и многие другие, всегда центрируют свои картинки. Так выглядит лучше.

А те кто любит пердолиться с алайментом разницы особой не заметят. Им так или иначе нужно лишние действия делать.

**Comment by Undeadlol1** [comment]
А ютьюб видео отцентрировать пока не получается. Iframe ихний что-то не дается мне. В будущем еще попробую.

**Comment by serejandmyself** [comment]
Let's do it
