### ISSUE TITLE
Поставить второй FB-пиксель на сайт.

### ISSUE THREAD

**Issue by solodikov** [GolosChain/tolstoy#216]
Желательно оставить оба - если не будет конфликта.
Но если конфликт - то первый убрать, второй поставить.

```
<!-- Facebook Pixel Code -->
<script>
!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
document,'script','https://connect.facebook.net/en_US/fbevents.js');
fbq('init', '217726192019770', {
em: 'insert_email_variable,'
});
fbq('track', 'PageView');
</script>
<noscript><img height="1" width="1" style="display:none"
src="https://www.facebook.com/tr?id=217726192019770&ev=PageView&noscript=1"
/></noscript>
<!-- DO NOT MODIFY -->
<!-- End Facebook Pixel Code -->
```

**Comment by solodikov** [comment]
Такой вопрос. Если поставить ещё один нижеприведённый код, что он нам даст? Не пойму его отличие от короткого 'CompleteRegistration'

```
<head>
<!-- Facebook Pixel Code -->
<script>
!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
document,'script','https://connect.facebook.net/en_US/fbevents.js');
fbq('init', '217726192019770'); // Insert your pixel ID here.
fbq('track', 'PageView');
</script>
<noscript><img height="1" width="1" style="display:none"
src="https://www.facebook.com/tr?id=217726192019770&ev=PageView&noscript=1"
/></noscript>
<!-- DO NOT MODIFY -->
<!-- End Facebook Pixel Code -->
</head>
<script>fbq('track', '<EVENT_NAME>');</script>
```

Описание такое:

> Вставьте код события.
> Место размещения кода события зависит от того, как регистрируется действие на сайте: во время загрузки страницы или одновременно с выполнением действия.
> ВАРИАНТ А. РЕГИСТРАЦИЯ СОБЫТИЙ ВО ВРЕМЯ ЗАГРУЗКИ СТРАНИЦЫ
> Если после выполнения действия человек попадает на новую страницу, настройте регистрацию события во время загрузки страницы. Например: после совершения покупки человек попадает на страницу подтверждения заказа.
> Чтобы регистрировать события во время загрузки страницы, добавьте код события (между тегами <script>) прямо под тегом </head>. Благодаря этому код события будет загружен вместе с базовым кодом пикселя во время загрузки страницы.
> Notice
> 
> Не вставляйте код события между тегами <head>.

**Comment by Undeadlol1** [comment]
Если внимательно посмотреть код, то видно что мы что-то не указали.
`fbq('init', '217726192019770', {
em: 'insert_email_variable,'
});
`

**Comment by Undeadlol1** [comment]
Во втором посте код инициализации. Он не делает сам трекинг

**Comment by Undeadlol1** [comment]
Дай мне документацию

**Comment by solodikov** [comment]
Вот мануал: https://www.facebook.com/business/help/952192354843755

**Comment by solodikov** [comment]
А где там?

**Comment by solodikov** [comment]
{ em: 'insert_email_variable,' }) - здесь?

**Comment by solodikov** [comment]
В инструкции по установке нет указания на вписание имейла.
И ID же в коде сразу сам проставился - 217726192019770.
Может этот email не требует отдельного указания? 
В инструкции ничего нет. Просто "скопируйте это код и вставьте и всё".

**Comment by Undeadlol1** [comment]
Залил новый код. Проверь, пожалуйста.

Но, мне кажется я понял в чем проблема. У нас с помощью того же скрипта инициализации запускается Facebook Connect с id 150154408771266. Затем, когда дело доходит до Facebook Pixel, он и идет попутка запустится с другим id, что-то идет не так.
Отказаться от коннекта мы уже не можем, давайте я вас в наш facebook developers приглашу, там уже настроите пиксель заного и проблем с разными айди не будет.
Скажите ваши контакты в фейсбуке @serejandmyself, @solodikov. Можно в скайпе.

**Comment by Undeadlol1** [comment]
Хотя нет, не надо, сам нашел ваши странички.

**Comment by solodikov** [comment]
Как я понимаю,  id 150154408771266 - это приложение, через который коннектятся новые акки Golos.io. Пиксели же мы настраиваем через FB-Бизнес-Менеджер. Сейчас мы активировали 217726192019770 (пиксель Сергея) и он работает, предыдущий пиксель - 136063983553382 (мой) - теперь не работает, но два нам не нужно. Там же можно их удалить, или настроить новые, но id у них будут опять новые. В общем, через Facebook Developers ничего такого я не увидел.

Короче - сейчас всё работает, можно закрывать.
