### ISSUE TITLE
Изображения на превью

### ISSUE THREAD

**Issue by lehard** [GolosChain/tolstoy#217]
Стали неестественно вытянуты

![image](https://cloud.githubusercontent.com/assets/22220976/21740528/06467778-d4de-11e6-959a-6a76370d0d80.png)

**Comment by tomarcafe** [comment]
https://imgp.golos.io/128x256/https://imgp.golos.io/0x0/https://s6.postimg.org/d7b4fyafl/image.png

так выглядит ссылка по которой резолвится картинка - имхо в серединке там 1 прокси лишняя - и вроде последний раз когда я смотрел - они подгружались как background-image - а сейчас как img src=" 
когда картинке жостко задаешь ширину и высоту - она конечно будет растягиваться. 

как вариант - рисовать img внутри div 128x256, и настроить там overflow: hidden,для картинки тогда указать width: 100% height: auto - но тогда будет показываться верхняя часть картинки а не средняя как сейчас..

как вариант - изучить возможности imageproxy - он, вроде, умеет не только растягивать пропорционально - но и обрезать в размер,  - просто это чуть сложнее чем /128x256/ будет записано

**Comment by tomarcafe** [comment]
нет, imageproxy по кр мере из коробки ничего не обрезает...
счас попробую наладить это дело
