### ISSUE TITLE
Интеграция голоса на ifttt.com

### ISSUE THREAD

**Issue by gamerate** [GolosChain/tolstoy#218]
Для того что-бы у авторов контента была удобная возможность кроспостить их посты на Голос им нужны удобные инструменты. На данный момент мировым лидером в этом плане вероятно является https://ifttt.com/ который позволяет настроить умный кросспостинг откуда угодно куда угодно и при этом совершенно бесплатно. Если бы мы смогли интегрировать туда поддержку Голоса - это был бы прекрасный инструмент для авторов.

**Comment by 21xhipster** [comment]
С одной стороны согласен, с другой стороны нет. Нам надо думать как сделать авторам удобно писать прямо используя Голос. Сейчас с этим большие вопросы. Но любом случае поддержка Ifttt или подобных штук нужна, т.к. ему ровным счетом пофигу в какую сторону кроспостить.

**Comment by serejandmyself** [comment]
Нам нужно делать автопостинг из Голоса в другие места, а не наоборот. Так как, это будет означать что человек ставит Голос на первое место

**Comment by t3ran13** [comment]
Сергей прав)

**Comment by serejandmyself** [comment]
А над этим мы уже работаем. Предлагаю закрыть @gamerate
