### ISSUE TITLE
Добавить вид сортировки комментов от старого к новому

### ISSUE THREAD

**Issue by litrbooh** [GolosChain/tolstoy#224]
Не хватает сортировки комментов к посту, позволяющей расположить их в хронологическом порядке.
https://golos.io/ru--ispravleniya/@dreamer/uvazhaemye-razrabotchiki-dizaina-obratite-vnimanie

**Comment by serejandmyself** [comment]
Сортировка от нового к старому есть

**Comment by litrbooh** [comment]
Где есть, если на скрине видно, что нет?

**Comment by serejandmyself** [comment]
Новое!

**Comment by litrbooh** [comment]
Сергей, при чем здесь от нового к старому есть, если просят сделать сделать от старого к новому, как сделано на всех сайтах и форума?
