### ISSUE TITLE
Сделайте изменение ширины ленты в зависимости от разрешения монитора

### ISSUE THREAD

**Issue by litrbooh** [GolosChain/tolstoy#225]
Коллеги, на моем мониторе ГОЛОС выглядит очень странно. Ширина ленты просмотра поста занимает 1000 точек фиксировано, а самого текста и фотографий всего 840 (остальное поля). При разрешении монитора 2560 по длинной это всего 32% от ширины экрана.
http://www.steemimg.com/images/2017/01/11/LENTA207835.jpg

Аналогичная ситуация и в основной ленте:
http://www.steemimg.com/images/2017/01/11/LENTA3e3446.jpg

Но если в основной ленте это не страшно, так как там только превью, то урезание ленты при просмотре поста очень губительно для фото, так как  при ресайзе до 840 они выглядят очень мелкими на мониторах с большим разрешением.
http://www.steemimg.com/images/2017/01/11/FOTO5196c.jpg

При этом ресайз периодически делается кривой (не знаю это браузер делает, или код голоса), но зачастую этим кривым ресайзам не хватает резкости.

Резюме: Просьба сделать ширину ленты адаптивной, т.е. задавать не в пикселях, а в % от разрешения экрана. И фотографии ресайзить уже в зависимости от ширины получившейся ленты, если фотография не влезает целиком.

**Comment by serejandmyself** [comment]
Бэклог

**Comment by litrbooh** [comment]
Насколько это в будущее?

**Comment by pavelit** [comment]
Вопрос юзабили текущей ленты очень щепетильный. Растянуть на весь экран ленту можно, но читать ее будет невозможно. Ни один из лидирующих css фреймвороков не рекомендует поступать таким образом. Во всех лидирующих css фреймворках заранее заложена схема отображения контента под различные типы/размеры экранов.

**Comment by litrbooh** [comment]
Вот так я всё жду, жду, а оказывается решили не делать печально.

Я из объяснения не понял, что толку с этих лидирующих css, если у меня лента Голоса занимает 1/3 экрана, а максимальный размер отображаемой картинки 840 по длинной - это ад. Фотоблогеров такой хренью не заманишь личные блоги вести, только бабки заколачивать
