### ISSUE TITLE
Сделать автопостинг

### ISSUE THREAD

**Issue by solodikov** [GolosChain/tolstoy#226]
Сделать автопостинг всех новых постов в Голосе в:

- [ ] FB

- [ ] VK

- [ ] ЖЖ

**Comment by solodikov** [comment]
Сделать не автоматом, а чек-боксами (для выбора) под любым создаваемым постом в Голосе.

**Comment by litrbooh** [comment]
Хорошая идея

**Comment by pavelit** [comment]
Автопостинг не получится сделать. Нет такой возможности.

**Comment by serejandmyself** [comment]
Предлагаю пока не закрывать. Почему нет?
