### ISSUE TITLE
Оптимизировать Golos.io для смартфонов

### ISSUE THREAD

**Issue by solodikov** [GolosChain/tolstoy#227]
У нас Голос на смартфонах некорректно отображается.
Откройте golos.io на смартфоне - и перед нами будет белый экран, но скролл вниз за пределы экрана покажет контент.

- [ ] поправить отображение главной страницы

- [ ] проверить корректность отображения постов и комментариев внутри Голоса

**Comment by Undeadlol1** [comment]
У меня нет такой фигни.

**Comment by solodikov** [comment]
Проверил - магическим образом уже всё работает норм )
Снято с повестки.
