### ISSUE TITLE
Неправильно отображается комментарий в клиенте

### ISSUE THREAD

**Issue by AlekseiSmirnov** [GolosChain/tolstoy#228]
Почему-то цифра 6 в клиенте отображается как цифра 1. [Вот комментарий,](https://golos.io/ru--psikhologiya/@whiskardi/chert-vozmi-ya-kak-vsegda-prekrasna-itak-poekhali#@everythink/re-radogost-re-chert-vozmi-ya-kak-vsegda-prekrasna-itak-poekhali-20170114t172008-20170114t174445099z
) в котором проблема воспроизвелась. 

[Вот](http://golosd.com/tx/be255ee0e9734a828cfa679e16ef450fdfdb64db) как он выглядит в блок эксплоере

**Comment by serejandmyself** [comment]
У меня все правильно отображается

**Comment by AlekseiSmirnov** [comment]
Вот как у меня отображается этот коммент. И в самом комменте показывается "1. Другое" хотя в соответствии с блок эксплоером должно быть "6. Другое"
![2017-01-15_14-58-05](https://cloud.githubusercontent.com/assets/10200871/21962285/449e25f6-db33-11e6-8d00-eb327c61bd1c.png)

**Comment by serejandmyself** [comment]
Closed HF 16.3
