### ISSUE TITLE
«Смержить» со Стима возможность получения информации о пользователе в формате JSON

### ISSUE THREAD

**Issue by testzcrypto** [GolosChain/tolstoy#229]
Недавно в Стиме была добавлена возможность получений JSON профиля пользователя: https://steemit.com/steemit/@sneak/steemit-com-now-supports-fetching-profile-data-as-json

Например: https://steemit.com/@dantheman/json

Данная возможность позволит сторонним сервисам просто и быстро получать нужную информацию по пользователе Голоса (включая ссылку на его аватарку).

**Comment by Undeadlol1** [comment]
Мне кажется что это решится само собой после очередного мерджа стимитовских изменений. Специально этим заниматься не стоит, не продуктивно.

**Comment by serejandmyself** [comment]
Все верно, оно стоит "в спринте" так как мы решим спринт на этой неделе

**Comment by serejandmyself** [comment]
HF 16.3
