### ISSUE TITLE
Биржа. Мои ордера

### ISSUE THREAD

**Issue by lehard** [GolosChain/tolstoy#232]
Сейчас не видно список моих ордеров и нет возможности их отменить

**Comment by 21xhipster** [comment]
Это какие-то проблемы с инфраструктурой, т.к. у меня даже сниппеты по данным с рынка не обновляются

**Comment by serejandmyself** [comment]
Да, все так. тестируем

**Comment by Undeadlol1** [comment]
Со стороны фронт-энда сделал все что мог. Не нашел причину проблем.

**Comment by 21xhipster** [comment]
@Undeadlol1 
Оставляем биржу не рабочей? Я понимаю когда транзакции не приходят по какой-то магической причине. Но там не появляется целый блок информации с открытыми ордерами.
cli_wallet вполне отлично выдает инфу по открытым ордерам
<img width="1163" alt="screen shot 2017-01-16 at 23 24 11" src="https://cloud.githubusercontent.com/assets/410789/21988653/fcd6430a-dc42-11e6-8c2c-3f1f4c4a74d6.png">

Проверяй есть ли этот блок инфы в коде, уходит ли запрос `get_open_orders` и всё такое.
Потому-что если эта штука не работает сейчас, значит надо взять этот блок и сделать с нуля.

**Comment by serejandmyself** [comment]
Проблема явно на фронт энде или бэк энде. С ядром все ок
