### ISSUE TITLE
Что-то не то с отображением кураторских наград

### ISSUE THREAD

**Issue by 21xhipster** [GolosChain/tolstoy#238]
<img width="1186" alt="screen shot 2017-01-15 at 20 40 57" src="https://cloud.githubusercontent.com/assets/410789/21962537/326f69aa-db63-11e6-8751-7e38e34eb6a2.png">
Маловероятно чтобы я столько заработал на курировании. К тому же их на балансе нет.

**Comment by serejandmyself** [comment]
Причем в истории, они отображаются нормально

**Comment by Undeadlol1** [comment]
Похоже что уже не актульно

**Comment by serejandmyself** [comment]
Актуально, у меня все еще показывает астрономические цифры

**Comment by serejandmyself** [comment]
![image](https://cloud.githubusercontent.com/assets/7550961/21975611/ae79998c-dbde-11e6-9686-743f948c078b.png)

**Comment by Undeadlol1** [comment]
У Димы уже не показывает.

**Comment by lehard** [comment]
Предлагаю дождаться 14 мск, может исправится. Возможно это эффект вчерашней лавины выплат

**Comment by serejandmyself** [comment]
Как всегда, я один остался. Все равно я 3 миллиона не получил

**Comment by Undeadlol1** [comment]
У меня вот такая вот фигня.
<img width="1680" alt="screen shot 2017-01-16 at 13 28 47" src="https://cloud.githubusercontent.com/assets/4124323/21975693/d5e51512-dbef-11e6-9d4d-7f55feeda9d1.png">

**Comment by serejandmyself** [comment]
Смотри еще авторские
