### ISSUE TITLE
Сделайте флажок уведомление о новых ответах, коментах и постах избранных авторов

### ISSUE THREAD

**Issue by litrbooh** [GolosChain/tolstoy#239]
Я не знаю насколько у нас фронт-энд отвязан от фронт-энда стимит, поэтому хочется иметь как там флажок красный об новых событиях: комментах, ответах, новых публикациях избранных авторов. 
Как это сделано в FB, яблоке и в общем везде.

**Comment by serejandmyself** [comment]
На сколько мне известно, доступно в новом ХФ

**Comment by litrbooh** [comment]
будем надеяться

**Comment by litrbooh** [comment]
@serejandmyself , как там с уведомлением в новом форке? Че-то я их не вижу

**Comment by serejandmyself** [comment]
#303
