### ISSUE TITLE
Блокировка и подписка не только по авторам, но и по разделам

### ISSUE THREAD

**Issue by litrbooh** [GolosChain/tolstoy#240]
Сейчас есть подписка и блокировка только на авторов. Было бы круто иметь возможность формировать свою лету подпиской на теги и исключать из общей ленты неинтересные темы блокировкой тегов. (реализовать можно быстро на уровне фторн-энда сначала)

**Comment by 21xhipster** [comment]
О да. Сам об этом мечтаю

**Comment by serejandmyself** [comment]
Set for sprint №2

**Comment by litrbooh** [comment]
судя по количеству надписей работа кипит, но что всё это значит? :)

**Comment by gagin** [comment]
Кстати, если работа над этим уже идет, здорово было бы сразу поддерживать опцию подписки на комбинацию тегов, типа "голос+статистика" и "статистика-голос".

**Comment by 21xhipster** [comment]
Кто-нибудь может объяснить как именно это планируется имплементировать?

**Comment by pavelit** [comment]
> Кто-нибудь может объяснить как именно это планируется имплементировать?

При просмотре разделов Новое/Актуальное/Популярное/Промо справа есть блок "Тэги и топики", в данном блоке появится возможность выделять интересующие пользователя теги. Выборка тегов будет хранится в массиве состояния state, т.е. сохраняться в текущем браузере до момента очистки кэша. Выборка тегов будет применятся ко всем разделам. При переходе в каждый раздел будет выводится лента с учетом данной выборки.

**Comment by 21xhipster** [comment]
@pavelit Не уверен, что это прямо то, что просят человеки.  

1. Когда человеки говорят что им интересно подписаться на тэг обычно они имеют ввиду то, что они это хотят видеть в ленте. Механизм который предлагается тобой - это не подписка на тэги, а фильтрация по тэгам.
2. Инфа о фоловинге должна храниться в цепочке, а не в бразуере. Иначе этим просто не будут пользоваться после первого же сброса настроек. Нужно использовать кастомную операцию. Вот [пример](http://golosd.com/tx/c8afaf0c3d82543e31f2413644e75b02be042b63). Надо подумать подходит ли формат текущей кастомной операции под наш юзкейс.
3. У человека должна быть возможность подписаться не на тэг, а на новое, популярное, актуальное и т.д. в этом тэге. 

@serejandmyself Предлагаю вовлеч сообщество в обсуждение того, как должна быть реализована эта фича.

**Comment by serejandmyself** [comment]
Дима, уже волекали. Боюсь ты пропустил. Также боюсь что @pavelit не до конца выразил мысли. Идет речь именно о подписке и фильтрации. С возможностью сохранить, сбросить и тд

**Comment by 21xhipster** [comment]
@serejandmyself Можно посмотреть историю обсуждения? В любом случае чего бы там не было решено - состояние подписки нужно хранить на цепочке, так как в противном случае приложение буквально `лочит` человеков. Я категарически против такого подхода. Это сильно вредит экосистеме приложений.

Кстати я [создал предложение по стандарту](https://github.com/GolosChain/gip/issues/2), которое реализует то, что нам надо.

**Comment by serejandmyself** [comment]
https://golos.io/ru--golos/@golos/otchyot-o-prodelannoi-rabote-komandy-golosa-za-20-02-2017-05-03-2017

**Comment by serejandmyself** [comment]
Вопрос не просто в подписке, а именно в подписке + фильтрации. На данный момент в организации контента на Голосе бардак

**Comment by 21xhipster** [comment]
Я тут сетую скорее не за то, как это в UX применить. Это все таки вам решать. А за то, чтобы приложение не лочило человеков. Соответственно если человек подписался на что-то, то эта информация должна быть портируема из одного приложения в другое, соответственно записана в блокчейн. Подход при котором мы сейчас удовлетворим пользователей golos.io, а на других разработчиков забъем - не соответствует нашей стратегии.

**Comment by t3ran13** [comment]
@21xhipster +
Если будет правильно сделано то круто
Быстрее конечно сделать костыль (для голос ио только) но иногда лучше переработать и не возвращаться к вопросу

Кстати авки у нас тоже не в блокчейне??

**Comment by 21xhipster** [comment]
@t3ran13 Авки в цепочке. [Спецификация](https://github.com/GolosChain/gip/issues/1)

**Comment by t3ran13** [comment]
А куда после форка моя авка ушла??? Видимо баг какой-то

**Comment by serejandmyself** [comment]
@t3ran13 уже же писали... Это не баг, а теперь данные авок хранятся по другому. Придется просто загрузить новую

**Comment by t3ran13** [comment]
Ок

**Comment by serejandmyself** [comment]
- Блок фильтр который действует во всех вкладках кроме ленты, находится над тегами и топиками. 
- Теги кликабельны плюсом/минусом слева
- Блок имеет возможность разворачиваться
- Заголовок фильтр указывает кол-во подписок
- Возможность подписки сохраняется
- Возле любого тега добавить символ + который означает добавить в фильтр
- На странице другие теги добавить возможность кликнуть на плюс или минус 
- Блокировка тегов в настройках взрослого контента
- Расширяем профайл 2 массивами select tags / filter tags
