### ISSUE TITLE
Исправьте оценку постов в рублях

### ISSUE THREAD

**Issue by litrbooh** [GolosChain/tolstoy#242]
С оценкой постов  рублях какой-то явный косяк. 

Вот мой пост вчерашний, выплаты по нему прошли позже первых. 
http://golosd.com/ru--fotografiya/@litrbooh/zimnii-peizazh-vsem-v-lentu

Что видим:
total_payout_value	**106.506 GBG**
curator_payout_value	21.598 GBG

 litrbooh author reward: **53.253 GBG** and 1.231M GESTS for @litrbooh/zimnii-peizazh-vsem-v-lentu 

Текущий курс 1 мг золота (Deutsche Bank): 2.29434 руб.
отсюда: http://www.steeme.ru/gf.html

Получается, что после выплаты пост должен быть оценен в 106.506*2.29434=**244,36р**

А сайте написано: **₽ 325,31**
https://golos.io/ru--fotografiya/@litrbooh/zimnii-peizazh-vsem-v-lentu

**Comment by primusd** [comment]
**325 руб.** - правильная оценка, т.к. она учитывает всю награду за пост - и авторские начисления и кураторские.

Авторы получают **75%** от выплат за пост. Как раз **325*0.75=244**, так что цифры сходятся.

Другой вопрос - стоит ли выводить полную стоимость поста или только авторские вознаграждения - это надо думать отдельно.

**Comment by litrbooh** [comment]
Проблема вся в том, что до выплаты оценка было >400р :)

**Comment by litrbooh** [comment]
Кстати, прибавлять 25% - это неправильно. Кураторское вознаграждение может быть меньше 25%, что собственно мы тут и видим: 
curator_payout_value 21.598 GBG
21/21+106=16%

**Comment by AlekseiSmirnov** [comment]
Бага нету
Ответил [тут](https://golos.io/ru--golos/@litrbooh/nepravilnaya-cenka-stoimosti-postov-v-rublyakh-i-mozhet-li-nagrada-kuratorov-byt-menee-25#@phenom/re-litrbooh-nepravilnaya-cenka-stoimosti-postov-v-rublyakh-i-mozhet-li-nagrada-kuratorov-byt-menee-25-20170115t212241067z)

**Comment by litrbooh** [comment]
Почему закрыли  Issue? Баг есть, если кто-то написал, что его нет - это не значит, что его нет. 

Объясняю ещё раз почему Phenom не прав:
1) После выплаты оценка поста включает в себя только выплату автору, так было на стимит ещё до запуска голоса и тут тоже после выплат оценка поста уменьшается. С чего вдруг @AlekseiSmirnov сложил награду автора и куратора?

2) Что за бредовая логика высчитывать курс в обратную сторону и говорить, что всё верно? Награда  выплачивалась вчера, курс **НА МОМЕНТ ВЫПЛАТ** был 2.29434 руб., в не 2.539.

**Comment by Undeadlol1** [comment]
Потому что сейчас все работает так как в стимите. Наш код должен быть максимально похож на стимитовский, поэтому я не хочу ничего перепиливать.

**Comment by litrbooh** [comment]
@Undeadlol1 , хорошо я понимаю, что сейчас силы возможно брошены на подготовку к ХФ и решению проблемы биржи, но оценка поста в рублях на треть - это не нормально. Это вызывает негатив и вопросы у пользователей: 
https://golos.io/ru--mysli/@redhat/podozritelno-tikho
https://golos.io/ru--golos/@t3ran13/konkurs-100-golosov-tomu-kto-luchshe-vsekh-razbiraetsya-v-ekonomike-golosa

Люди всегда расстраиваются, когда получают меньше чем рассчитано. Оно нам надо? Если это будет исправлено  в ФХ - отлично, но просто забивать болт - это не нормально.

Ведь оценка поста это элементарная функция, как мне кажется. Возможно, что просто у нас неправильно считается курс золотого в фронт-енде и это правится в одной строчке.

Просто странная реакция, все либо говорят - что не знают, либо ничего.

**Comment by t3ran13** [comment]
+

**Comment by t3ran13** [comment]
Вы, ребята, для людей работаете, или пытаетесь себе удобно сделать???

**Comment by litrbooh** [comment]
Не уверен, что это косяк, но странно. За 4 часа до выплаты была оценка 560GBG, а после выплаты 442GBG. Неужели за 4 часа курс GBG скакнул на 26%?

Вот до выплат:
![2](https://cloud.githubusercontent.com/assets/22373216/21988477/6930f2fa-dc18-11e6-974a-725afa22dd0c.PNG)

Вот после:
![4](https://cloud.githubusercontent.com/assets/22373216/21988484/6e617844-dc18-11e6-8163-d0fae67b1440.PNG)

Вот сам пост: http://golosd.com/ru--fotogolosishche/@litrbooh/obyavlenie-pobeditelei-konkursa-fotogolosishe-1

Хотел отследить как меняется оценка после выплат. За 4 часа сильно изменилась.
![1](https://cloud.githubusercontent.com/assets/22373216/21988508/8af7d4ee-dc18-11e6-975d-03a1683e8a5f.PNG)

![3](https://cloud.githubusercontent.com/assets/22373216/21988509/8d2734ee-dc18-11e6-8cd1-006ed6f3e1b3.PNG)

Конечно, мог курс скакнуть, но странно. Сам не умею курс проверить бывший.

**Comment by 21xhipster** [comment]
@t3ran13 Твой коммент был удален тобой?

**Comment by t3ran13** [comment]
нет, я сам удивлен)

**Comment by serejandmyself** [comment]
@litrbooh проверь сейчас

вознаграждение руб = Сумма Золотых х (Биржевая цена унции в USD / 31103.4768) * курс USD ЦБ РФ

**Comment by litrbooh** [comment]
@serejandmyself 
Ну, не знаю... смотри сам. Первый пост ещё не выплачен, второй выплачен:
![default](https://cloud.githubusercontent.com/assets/22373216/22154218/b3e1ca38-df3b-11e6-8166-819a5b207c3c.png)

Золотой = 1200/31103,4768*59,67=2,3021
![default](https://cloud.githubusercontent.com/assets/22373216/22154271/e608c4bc-df3b-11e6-8d60-6f3dc9273b2c.png)
25,923*2,3021=59,67 - а отображается 46,06 (почему-то заметно меньше). Возможно это доля автора? Тогда 18,253*2,3021= 42,02 (похоже на правду)


Второй пост выплаченный, там в подробностях видно что в топе сумма за автора и кураторов:
![default](https://cloud.githubusercontent.com/assets/22373216/22154329/214910f4-df3c-11e6-8fe9-69192d2a8145.png)

![default](https://cloud.githubusercontent.com/assets/22373216/22154348/35b1c0a4-df3c-11e6-97a5-5f5a638827bb.png)

Всего: 24,994*2,3021=57,538 отображается 63,41 (выплата была 11 часов назад) Возможно курс ЦБ брался тогда ещё вчерашний, но он был меньше. 

В целом - ОК, если задумано, что до выплаты отображается только награда автора.

**Comment by serejandmyself** [comment]
@litrbooh ок, думаем дальше

**Comment by t3ran13** [comment]
мб курсы парсяться с сайтов в которых курсы завышены/занижены
и класические грабли - у буржуинов десятичный разделитель - точка, у нас  - запятая. поэтому когда с разных сейтов что-то берем, нужно это учитывать, чб не округлило либо в тысячи не превратило

**Comment by serejandmyself** [comment]
https://golos.io/mapala/@litrbooh/ovrag-opasnyij---kamchatka-rossiya
1420,89 рублей
1247,324 (автор)
1 час назад	Авторские вознаграждения 247.724 GBG и 202.474 Сила Голоса за litrbooh/ovrag-opasnyij---kamchatka-rossiya
247,724*0,802*0.057220*59,22 = 673,222
202,474*0,057220*59,22 = 686,097
673,222 + 686,097 = 1359,319
8% разница (но курс я брал не час назад, а сейчас который)

надо бы словить пост котоый сию секунду считается, и где нет скачков курса на биржах

**Comment by litrbooh** [comment]
Вы скажите как вы считаете, и я проверю с вашими данными. Где курс берете, как умножаете :)
Можно же брать курс ЦБ, например, он меняется 1 раз в день.

**Comment by serejandmyself** [comment]
referenced #298
