### ISSUE TITLE
Не отображаются посты под русскими тегами

### ISSUE THREAD

**Issue by aleksandrazz** [GolosChain/tolstoy#246]
Непонятное что-то происходит с отображением постов по тегам.

 Мне по делу нужно было, а дальше уже пробовала ради интереса, и вот, если нажимать на теги под постом, либо из списка тегов, а потом если еще и переключатся внутри тега между новое/актуальное/популярное/обсуждаемое, то время от времени в ссылке браузера тег начинает отображаться кириллицей, и тогда ловится ошибка и ничего не отображается. 

<img width="1128" alt="screen shot 2017-01-17 at 14 57 21" src="https://cloud.githubusercontent.com/assets/23729515/22021584/cca31d28-dcc6-11e6-8b08-ec1436d7e229.png">

Вот ссылка, получила ее нажав на тег под своим постом и потом перешла на "новое", ожидая увидеть все созданные посты в этом теге в хронологическом порядке.

https://golos.io/created/%D1%82%D0%B5%D0%BC%D0%B0%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D0%B8

Вот ссылка, получила ее нажав на тег из списка тегов и потом перейдя на "популярное" 

https://golos.io/trending/%D0%B2%D0%B5%D1%87%D0%B5%D1%80%D1%81%D0%B3%D0%BE%D0%BB%D0%BE%D1%81%D0%BE%D0%BC

и таких примеров много :)

**Comment by serejandmyself** [comment]
У меня все равно не отображаються:

https://golos.io/created/%D0%B3%D0%BE%D0%BB%D0%BE%D1%81

(это тэг голос)

**Comment by Undeadlol1** [comment]
Они и не должны работать

**Comment by serejandmyself** [comment]
Юникод?

**Comment by Undeadlol1** [comment]
Проблема вообще не в этом была. Ссылка в навигации была "/голос" вместо /ru--golos"
Проблема исправлена.

**Comment by aleksandrazz** [comment]
Де, теперь все хорошо открывается, спасибо! :)

**Comment by serejandmyself** [comment]
Ok, я видно смешал 2 проблемы в одну кучу.

**Comment by Undeadlol1** [comment]
Пожалуйста.
