### ISSUE TITLE
Ошибка facebook:2 error: SequelizeUniqueConstraintError: Validation error при регистрации через ФБ 

### ISSUE THREAD

**Issue by serejandmyself** [GolosChain/tolstoy#248]

**Comment by serejandmyself** [comment]
Set for sprint №2

**Comment by serejandmyself** [comment]
Еще одна

[![i82^cimgpsh_orig.png](https://s27.postimg.org/ev23nadvn/i82_cimgpsh_orig.png)](https://postimg.org/image/wl3s8brgf/)

**Comment by serejandmyself** [comment]
Леша, отпишись по хукам!

**Comment by solodikov** [comment]
![screenshot 2017-01-24 21 43 34](https://cloud.githubusercontent.com/assets/24874226/22256976/377b77fa-e27e-11e6-8718-f85b383a1290.jpg)

**Comment by sualex** [comment]
Активно занимаемся проблемой. Нельзя просто взять и пофиксить, т.к. большинство новых аккаунтов проходит регистрацию через соцсети правильно. Все будет проанализировано и исправлено в самое ближайшее время, как только увидим причину.

**Comment by serejandmyself** [comment]
Как я понимаю ты выставил хуки по обеим ошибкам? Я могу снять с нее milestone?

**Comment by solodikov** [comment]
Получил 3 сообщения об ошибке регистрации через FB:

> 1. Не получилось создать аккаунт. Сервер вернул эту ошибку:
> 10 assert_exception: Assert Exception o.fee >= wso.median_props.account_creation_fee: Insufficient Fee: 3.000 GOLOS required, 1.000 GOLOS provided {"f":"3.000 GOLOS","p":"1.000 GOLOS"} th_a steem_evaluator.cpp:113 do_apply {"op"😞"account_create",{"fee":"1.000 GOLOS","creator":"golosio","new_account_name":"brd","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS898NhzpXWWtyDi17saKXbM9Euj912KYkRBMgX1Afb91y4Y8QvG",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS67TmZehLNYTmB2cQYfRzvke24qXsH5qxwHiqR4fJzZ9iEENyQu",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS8ixKiYHEFQ1uCm9tLS5PjGoAeBxbQgqfTjoAXizyC8eEhycMRZ",1]]},"memo_key":"GLS8GEoKidgympV9jLntqXqLKF4Qry8HzditE6tFAW9YzGrXJHkMw","json_metadata":"{}"}]} th_a database.cpp:3075 _apply_transaction {"trx":{"ref_block_num":31638,"ref_block_prefix":43323846,"expiration":"2017-02-10T12:19:36","operations":[["account_create",{"fee":"1.000 GOLOS","creator":"golosio","new_account_name":"brd","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS898NhzpXWWtyDi17saKXbM9Euj912KYkRBMgX1Afb91y4Y8QvG",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS67TmZehLNYTmB2cQYfRzvke24qXsH5qxwHiqR4fJzZ9iEENyQu",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS8ixKiYHEFQ1uCm9tLS5PjGoAeBxbQgqfTjoAXizyC8eEhycMRZ",1]]},"memo_key":"GLS8GEoKidgympV9jLntqXqLKF4Qry8HzditE6tFAW9YzGrXJHkMw","json_metadata":"{}"}]],"extensions":[],"signatures"😞"1f1ca7b79b1f57b2fb2eb6a88a1d84ad35e3f7aec16f7e26c0f0a4f5306c07e12a0d241d155e427c51b296a9b63df8d73cb9621a55926f6c6bd49722fc392a33be"]}} th_a database.cpp:3079 _apply_transaction {"trx":{"ref_block_num":31638,"ref_block_prefix":43323846,"expiration":"2017-02-10T12:19:36","operations":[["account_create",{"fee":"1.000 GOLOS","creator":"golosio","new_account_name":"brd","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS898NhzpXWWtyDi17saKXbM9Euj912KYkRBMgX1Afb91y4Y8QvG",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS67TmZehLNYTmB2cQYfRzvke24qXsH5qxwHiqR4fJzZ9iEENyQu",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS8ixKiYHEFQ1uCm9tLS5PjGoAeBxbQgqfTjoAXizyC8eEhycMRZ",1]]},"memo_key":"GLS8GEoKidgympV9jLntqXqLKF4Qry8HzditE6tFAW9YzGrXJHkMw","json_metadata":"{}"}]],"extensions":[],"signatures"😞"1f1ca7b79b1f57b2fb2eb6a88a1d84ad35e3f7aec16f7e26c0f0a4f5306c07e12a0d241d155e427c51b296a9b63df8d73cb9621a55926f6c6bd49722fc392a33be"]}} th_a database.cpp:700 push_transaction digest 07cdc8b709f1ef9cfe30fe866e2948f2849f9662b9f0ccf9e835669a51275044 transaction 967bc6119502d8af9d580109e80300000000000003474f4c4f53000007676f6c6f73696f0362726401000000000103ac538ae52b38f5df9cf8f5ec220ca81ee1d04bc479e9fdd72dce9ddb0e33fdcd010001000000000102a126f39c783baef3ed06936c570a75cc38a20abe6e6959612b3830a7a5838227010001000000000103f9224d50638ab3dca3709ec5aa41ac0f30d9dc603c7902dd414d38bcb3dc02d5010003bc78e233b57ab5ccf00a5119ffcee59d276697d02bda40cf18bea71e33cf59a0027b7d00011f1ca7b79b1f57b2fb2eb6a88a1d84ad35e3f7aec16f7e26c0f0a4f5306c07e12a0d241d155e427c51b296a9b63df8d73cb9621a55926f6c6bd49722fc392a33be {"ref_block_num":31638,"ref_block_prefix":43323846,"expiration":"2017-02-10T12:19:36","operations":[["account_create",{"fee":"1.000 GOLOS","creator":"golosio","new_account_name":"brd","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS898NhzpXWWtyDi17saKXbM9Euj912KYkRBMgX1Afb91y4Y8QvG",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS67TmZehLNYTmB2cQYfRzvke24qXsH5qxwHiqR4fJzZ9iEENyQu",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS8ixKiYHEFQ1uCm9tLS5PjGoAeBxbQgqfTjoAXizyC8eEhycMRZ",1]]},"memo_key":"GLS8GEoKidgympV9jLntqXqLKF4Qry8HzditE6tFAW9YzGrXJHkMw","json_metadata":"{}"}]],"extensions":[],"signatures"😞"1f1ca7b79b1f57b2fb2eb6a88a1d84ad35e3f7aec16f7e26c0f0a4f5306c07e12a0d241d155e427c51b296a9b63df8d73cb9621a55926f6c6bd49722fc392a33be"]}
> 

2. Скрин:

![16735746_102396056950235_238328817_o](https://cloud.githubusercontent.com/assets/24874226/22897193/b11c0590-f244-11e6-912f-3809efc89eb3.png)

3. Жду скрин.

**Comment by serejandmyself** [comment]
Когда это было, узнай точные даты и время, судя по датам это не сегодня

**Comment by solodikov** [comment]
1 - 10.02.17 (ПТ) 17:19
2 - 12.02.17 (ВС) 18:52

**Comment by serejandmyself** [comment]
Так это уже было устранено вчера

**Comment by solodikov** [comment]
У всех запросил подтверждение регистрации или сохранение ошибки.

**Comment by serejandmyself** [comment]
Пусть кэш потрут сначала и куки все Ошибка устранена вчера, именно эта. Уже проверено

**Comment by serejandmyself** [comment]
Еще не все

**Comment by serejandmyself** [comment]
На данный момент ошибка больше не наблюдается
