### ISSUE TITLE
При наборе поста пропадает кнопка перехода в редактор

### ISSUE THREAD

**Issue by litrbooh** [GolosChain/tolstoy#249]
При наборе поста пропадает кнопка перехода в редактор, в результате, если пользователь не умеет пользоваться Markdown, он не может оформить пост. Это дико неудобно, надо очищать пост, и начинать его заново, переходить сразу в редактор и только тогда переключение нормально работает.

![default](https://cloud.githubusercontent.com/assets/22373216/22058916/c5499c9a-dd7b-11e6-8458-469ba201d513.PNG)

**Comment by serejandmyself** [comment]
Closed HF 16.3
