### ISSUE TITLE
На бирже в местах отображения курска не правильно написано отношение валют

### ISSUE THREAD

**Issue by litrbooh** [GolosChain/tolstoy#253]
![default](https://cloud.githubusercontent.com/assets/22373216/22083652/14b7167e-ddde-11e6-9fc6-72bd938b2f29.png)

не gbg/голос, а просто gbg. Можно написать "Цена за Голос" __________ GBG

**Comment by litrbooh** [comment]
даже не так, я бы написал просто цена хххх GBG. Голос там совсем не нужен, так понятнее будет

**Comment by serejandmyself** [comment]
Тест

**Comment by serejandmyself** [comment]
Set for this sprint
