### ISSUE TITLE
Проблема с отображением в постах нумерованных списков

### ISSUE THREAD

**Issue by solodikov** [GolosChain/tolstoy#256]
Урезана нумерация. Выглядит так:
[![Screenshot 2017-01-22 в 17.23.48.jpg](https://s5.postimg.org/wbcb130nr/Screenshot_2017_01_22_17_23_48.jpg)](https://postimg.org/image/99vpvc103/)

Посмотреть в больших списках, например: https://golos.io/ru--desyatxfaktovobomne/@jerlis/10-faktov-obo-mne

**Comment by serejandmyself** [comment]
Дублируется с #228
