### ISSUE TITLE
Пройтись по всему нашему тексту на Golos.io и поправить "русскоязычность"

### ISSUE THREAD

**Issue by solodikov** [GolosChain/tolstoy#257]
Есть мнение, что кое-где наши тексты переводились с китайского гугл-переводчиком, хорошо бы поправить.
Пост на эту тему: https://golos.io/golos/@rossomaha.xyz/vopros-kasaemo-nekotoroi-syrosti-perevoda-golos

**Comment by solodikov** [comment]
Марина по этому поводу дописала:
>И доделайте переводы на русский - до сих пор если лайкать быстро появляется надпись на английском You can like a post only after 3 esc after the last post

**Comment by serejandmyself** [comment]
/transfers инструкция "перевести в голос"
Заменить весь текст, на:

Конвертация золотых будет происходить в течении 7 дней с момента запуска. Отменить её нельзя. После запуска конвертации, конвертируемые монеты станут недоступны.

Токены Золотой ликвидны и их можно передавать между аккаунтами. Перед запуском конвертации, проверьте опции купить / продать Золотой, на внутренней бирже. Также, токен Золотой, доступен к выводу (и торговле) на внешних биржах.

Неделя отсрочки, путем автоматической конвертации, необходима, в целях предотвращения злоупотребления спекуляцией, по средней ценовой котировке.

**Comment by serejandmyself** [comment]
/transfers инструкция "усилить силу Голоса"

Заменит текст, на:

Перевести Голос в Силу Голоса
Сила Голоса неперемещаемая, количество токенов Силы Голоса, увеличивается при долгосрочном хранении. Чем их больше, тем сильней вы влияете на вознаграждения за пост и тем больше зарабатываете за голосование.

Силу Голоса нельзя передать другому аккаунты, потребуется 2 года или 104, равных выплаты чтобы конвертировать её обратно в Голос.

**Comment by serejandmyself** [comment]
/transfers инструкция "усилить силу Голоса"

Заменить кнопку ПРОДВИНУТЫЙ, на:

Расширенные опции

**Comment by serejandmyself** [comment]
/permissions ключ владельца

Заменить описание на:

Ключ владельца, это главный ключ аккаунта, он необходим для изменения других ключей.
Приватный ключ или пароль должен храниться в оффлайне так часто насколько это возможно.

**Comment by serejandmyself** [comment]
/curation-rewards описания наград за кураторство

Сейчас так:
28 минут назад	Кураторские вознаграждения 3.850 Сила Голоса за lada94/10-faktov-obo-mne	

Добавить падеж:

Силы Голоса

**Comment by serejandmyself** [comment]
/feed (или любая страница где видны посты)

Надпись под тэгами
Показать больше сообщений низкой стоимости

Заменить, на:

Показать больше постов с более низким вознаграждением

Там же - подпись:

Показать больше топиков..

Заменит, на:

Другие тэги

**Comment by serejandmyself** [comment]
/tags.html/trending 
Заголовки в таблице

Сейчас:
Тэг, 	Ответы, Выплаты

Заменить, на:

Ключевое слово, Количество комментариев, Сумма выплат

**Comment by serejandmyself** [comment]
/submit.html

Чек боксы под постом

Сейчас:
Заплатите мне 100% в Сила Голоса

Добавить падеж:
...100% в Силе Голоса


Сейчас:
Проголосовать за пост

Заменить, на
Проголосовать за свой пост

**Comment by serejandmyself** [comment]
Скрытое меню слева (три полоски):
(слева текущей слово, справа вариант на который надо заменить)

Исследовать - Выплаты по тэгам
Биржа - Внутренний рынок
Изменить пароль аккаунта - Сменить пароль
Делегаты - Голосовать за Делегатов

**Comment by serejandmyself** [comment]
Заменить слова "обновить твой пароль" на слова:
обновить Ваш пароль 

[![Безымянный.jpg](https://s24.postimg.org/aqzxnyk6d/image.jpg)](https://postimg.org/image/end9jy55t/)

Это окно всплывает при вводе одноразового пароля (bound to account password) (созданный из cli wallet)

**Comment by serejandmyself** [comment]
#269 #268

**Comment by AlekseiSmirnov** [comment]
У меня клиент по дефолту на английском, несмотря на это многие слова и выражения все равно отображаются на русском. Тоже надо поправить

**Comment by serejandmyself** [comment]
@AlekseiSmirnov Было бы удобней, если бы ты дал конкретные примеры. Но это немного другая задача (не Русификация, а Англо... вайса верса), так что если найдешь, смело открывай новый issue

**Comment by zhe1ka** [comment]
локально не могу перейти на страницу
/submit.html
на сервере ошибки выдает

**Comment by zhe1ka** [comment]
"Силу Голоса нельзя передать другому аккаунты,"

подозреваю, что имелось в виду слово "аккаунту". Оставил новый вариант
