### ISSUE TITLE
Проверить конвертацию золотых

### ISSUE THREAD

**Issue by t3ran13** [GolosChain/tolstoy#258]
если я правильно понимаю, то конвертация золотых должна происходить по среднему прайс фиду за неделю по голосд

всю неделю он был в раене 3+, а по факту я получил чуть меньше 2. если береться средний, то такое никак не могло произойти, я прав?
математика простая, давайте на вскидку(яследил всю неделю, можэно перепроверить по авторским наградам, прайсфид сильно уше вниз в вс):
3+3+3+3+3+3+1=19
19/7 = 2,71
и это очень грубо, так должно быть 3 или больше
но никак не 1.99 как мне выплатилось вечером

**Comment by t3ran13** [comment]
https://screencloud.net/v/i105
ну вот пример
из 200 золотых я получил 192 голоса... за средненедельный фид прайс это неверно!
Это конвертация по текущему фиду который сейчас на golosd.com
http://screencloud.net/v/5682

**Comment by t3ran13** [comment]
так что нужно пересчитать каждую выплату и доплатить

**Comment by lehard** [comment]
Текущий прайс фид на golosd как раз отображается как среднедельный фид. Текущие прайс фиды, которые поставляют делегаты, уже значительно изменились - От 0.643 до 0.8
http://steemul.ru/witnesses/

**Comment by serejandmyself** [comment]
Голод показывает курс по которому золотые конвертировались бы сейчас, если бы конвертация была бы запущена 7 дней назад. ТЕ среднее за пред неделю. Конвертация происходит по курсу median_sbd_price на момент конвертаци

**Comment by t3ran13** [comment]
в пятницу фид на голосд изменился с 3+ до 2 за часов 6, не сильно ли отрефлексировало в течении одного дня?

**Comment by t3ran13** [comment]
если в сб фид был 3+ то при публикации только отрицательного фида в вс он может стать 2

**Comment by litrbooh** [comment]
А какой сейчас фид? Ещё пару дней назад он был 3.

**Comment by t3ran13** [comment]
Чуть меньше 1, он не может быть средненедельным, слишком круто изменился за сутки

**Comment by serejandmyself** [comment]
Прогнали большое количество тестов. Не увидели ошибок в расчетах формул
