### ISSUE TITLE
Добавить регистрацию через мобильный телефон 

### ISSUE THREAD

**Issue by serejandmyself** [GolosChain/tolstoy#259]
Проверить законодательную базу

**Comment by Undeadlol1** [comment]
Костя говорил что регистрация по номеру телефона попадает под закон о сохранении персональных данных пользователя. С этим могли быть проблемы. Поэтому этот функционал я выключил.

Если же мы все же будем добавлять это, то @sualex тебе нужно лишь настроить внешние сервисы для отправки SMS чтобы они работали с нашим сайтом, так как в "from-steemit" весь этот функционал уже есть готовый.
Так же тебе нужно в server.js отключить переадресацию с "enter_email" на "create_acount". Или типа того. Не помню как там точно было.

**Comment by serejandmyself** [comment]
Тогда давайте пока поставим на паузу, проверим вопрос на законодательном уровне.

**Comment by serejandmyself** [comment]
Закрываю, так как это проблема на данный момент
