### ISSUE TITLE
Ошибка при вводе данных в поле логина Русскими буквами 

### ISSUE THREAD

**Issue by serejandmyself** [GolosChain/tolstoy#260]
Цитата:

ptiza_elli
2017-01-23 05:43 am (UTC)
.... почту подтврдила пароль сохранила - имя пользователя пишу - в ответ имя должно начинаться с буквы. А я с чего пишу? и висит себе это идиотство

**Comment by serejandmyself** [comment]
проверка регулярных выражений на стороне клиента

**Comment by sualex** [comment]
Нужно посмотреть регулярки на кириллицу. Если набирать латиницей этого нет :

**Comment by sualex** [comment]
![2017-01-23_232101](https://cloud.githubusercontent.com/assets/19490632/22221269/48bde798-e1c3-11e6-84e7-19f5cd007773.png)

**Comment by sualex** [comment]
Кириллицей - есть : 

![2017-01-23_232008](https://cloud.githubusercontent.com/assets/19490632/22221291/67c37e0a-e1c3-11e6-81ee-c2caf9dde731.png)

**Comment by sualex** [comment]
/app/components/cards/CategorySelector.jsx ?

**Comment by Undeadlol1** [comment]
Так что сделать то нужно?
Исправить ошибку или разрешить создание русскоязычных ников?
Второе врятли с прокатит с блокчейном.

**Comment by serejandmyself** [comment]
Исправить ошибку, но эта задача не стоит на эту неделю,

**Comment by serejandmyself** [comment]
Не баг
