### ISSUE TITLE
Поменять в БД поле последнего действия на блокчейн, на последнее посещение сайта

### ISSUE THREAD

**Issue by solodikov** [GolosChain/tolstoy#262]

**Comment by pavelit** [comment]
Это необходимо переместить в репозиторий https://github.com/GolosChain/golos

**Comment by Nemo1369** [comment]
@pavelit Каким образом дата последнего посещения одного из множества веб-порталов на базе блокчейна может быть сохранена в блокчейне?

**Comment by pavelit** [comment]
@solodikov поясни о каких датах идет речь. На одном из брифингов это уже обсуждалось.

**Comment by solodikov** [comment]
Записано несколькими строками выше и проговорено на многих брифингах.

![screenshot 2017-07-14 11 25 50](https://user-images.githubusercontent.com/24874226/28200822-956dfd80-6887-11e7-8715-7c825dd91d78.jpg)

**Comment by jevgenika** [comment]
@pavelit

**Comment by jevgenika** [comment]
Прописать в БД ивенты пользователей:
-по последнему входу на сайт
-по последней активности на сайте (пост, коммент, апвоут)
-по последней активность на Бирже

**Comment by NickShtefan** [comment]
Доставать список пользователей зарегистрировавшихся в течение последней неделе
Собирать следующие данные
- Дата последнего апвоута/флага
- Дата последнего комментария
- Дата последнего поста
- Дата последней активности на бирже
