### ISSUE TITLE
Доработать поле тегов

### ISSUE THREAD

**Issue by aleksandrazz** [GolosChain/tolstoy#263]
Когда в поле текста вставляешь какой-либо #тег - система считает его как один из тегов, который "есть" (но не отображается!) внутри поля тегов. 

Бывают такие посты, как, например, этот: https://golos.io/ru--knigagolos/@katrin/kniga-pro-golos-ispolzovanie-tegov 
когда в посте вписывается список одних тегов, но в поле тегов нужно было бы ввести совсем другие теги. 

У пользователей такая ситуация вызывает много недопониманий - вписывают 5 тегов вручную, а система отображает им, что у них якобы вписано больше тегов, и они не могут понять - "откуда больше-то? Вписал же пять!" 

Предложение: 

1. Либо теги, отмеченные в поле текста не брать в расчет для поля тегов
2. Либо, если вдруг учитывать теги внутри текста очень важно, тогда теги из текста автоматически выводить ВИЗУАЛЬНО в поле тегов, чтобы пользователь наглядно видел, что вот, у него действительно указано больше пяти тегов. 

Я за первый вариант. :)

**Comment by serejandmyself** [comment]
Первый вариант надо откинуть, уже проходили на Стиме. Будет просто злоупотребление тэгами. Изначально на стиме так и было.

Второй вариант более реальный, но сложнее, можем поставить в бэклог
