### ISSUE TITLE
Не правильно читается OG разметка при использовании сокращалки ссылок

### ISSUE THREAD

**Issue by solodikov** [GolosChain/tolstoy#264]
Проблема следующая.

>**On Thu, Jan 26, 2017 at 05:14 PM, "Антон"**: 
Нид хелп.

>**On Thu, Jan 26, 2017 at 05:15 PM, "Александра"**: 
Здравствуйте. Какой вопрос?

>**On Thu, Jan 26, 2017 at 05:20 PM, "Антон"**: 
Здравствуйте. 
Посмотрите на примере 2 моих публикаций сегодня: [16.07](https://ok.ru/group/58062155808810/topic/66470413221930) и [19.27](https://ok.ru/group/58062155808810/topic/66470750601258).

>В первом случая я публиковал без сокращения ссылки - к посту подтянулась OG карточка именного этого поста, всё ок.

>Во втором случае, я использовал гугл-сокращалку и к той же ссылке из первого поста не подтянулась OG карточка именного этого поста. Хотя ссылка ведёт на тот же нужный пост! Откуда в этом случае тянется OG? На чьей стороне проблема?

>И в первом и во втором случае конечная ссылка одна и та же, а оформление поста в соцсети разное - в первом правильно, а во втором не правильно.

>**On Thu, Jan 26, 2017 at 05:20 PM, "Александра"**:
Так ведут опенграф-дебаггер ваши тэги на сайте. Перешла по одной ссылке и нашла [одну картинку](https://uploads.intercomcdn.com/i/o/16990244/543b399511282763953abfd1/Screen+Shot+2017-01-26+at+18.55.13.png), по второй - [другую картинку](https://uploads.intercomcdn.com/i/o/16990243/46f21e8ed85f743fe977c2b6/Screen+Shot+2017-01-26+at+18.55.25.png)

>**On Thu, Jan 26, 2017 at 05:23 PM, "Антон**:
Как исправить?

>**On Thu, Jan 26, 2017 at 05:26 PM, "Александра"**:
Я не знаю, это у вас где-то в коде.

>**On Thu, Jan 26, 2017 at 05:30 PM, "Антон"**:
Сейчас глянем.

Нужно исправить.

**Comment by Undeadlol1** [comment]
OG данные зависят от юрла. Естественно что сокращалка убивает эти данные

**Comment by Undeadlol1** [comment]
Ну, смотрите, когда вы даете прямую ссылку, то браузер идет по ней и берет соответствующие OG данные из golos.io.
Когда вы сокращаете ссылку, то браузер идет на сервер гугла и не видит там этих данных.

**Comment by solodikov** [comment]
@Undeadlol1, это не так, иначе сокращалками никто бы не пользовался.
Проблема на нашей стороне.

**Comment by Undeadlol1** [comment]
Почему ты в этом так уверен?

**Comment by solodikov** [comment]
Миша, долго объяснять, показываю на примере [нашей публикаций](https://twitter.com/goloschain/status/824603175332278272) в Твиттере.
Посмотри через какую сокращенную ссылку идёт переход в ту же публикацию на наш конечный урл, но при этом посмотри, как оформляется карточка этого же поста в Твиттере - с правильной картинкой и описанием.

**Comment by Undeadlol1** [comment]
Значит проблема в одноклассниках.

**Comment by solodikov** [comment]
Миша, ещё раз - **проблема на нашей стороне**, потому что через сокращалку и в FB мы идём так же криво и в ВК и везде.

Посты с других сайтов **через сокращалку** публикуются на и FB, и в ВК, и в Одноклассниках с нормальной разметкой. Можешь проверить.

**Comment by Undeadlol1** [comment]
Дай сокращенную ссылку для тестов

**Comment by Undeadlol1** [comment]
Хотя нет, я сам сделаю
