### ISSUE TITLE
Выплата не число? Меня ждет приз? :)

### ISSUE THREAD

**Issue by litrbooh** [GolosChain/tolstoy#266]
![default](https://cloud.githubusercontent.com/assets/22373216/22366338/2dcc561e-e48d-11e6-989f-459bcaa6ae37.png)

Ссылка на пост: https://golos.io/ru--rassledovanie/@litrbooh/rassledovanie-kak-obmanut-kulturugolosa-multivodstvo-stado-khalyavshikov-ili-realnye-polzovateli

В блок-чейне вроде всё ОК.
![default](https://cloud.githubusercontent.com/assets/22373216/22366366/4bbf7f0c-e48d-11e6-89e2-f4019590b497.png)
http://golosd.com/ru--rassledovanie/@litrbooh/rassledovanie-kak-obmanut-kulturugolosa-multivodstvo-stado-khalyavshikov-ili-realnye-polzovateli

Это мелочь, но всё же какой-то баг.

**Comment by serejandmyself** [comment]
Fixed HF 16.3
