### ISSUE TITLE
Починить приватные заметки в транзакциях

### ISSUE THREAD

**Issue by 0n0t0le** [GolosChain/tolstoy#267]
Имхо на 14 версии стима они работали, у нас как то не очень...

![](https://s23.postimg.org/4ym2tfeff/image.png)

Вообще вроде тут все ок 

https://github.com/GolosChain/tolstoy/blob/master/shared/chain/memo.js

**Comment by serejandmyself** [comment]
https://github.com/steemit/steemit.com/issues/98

**Comment by pavelit** [comment]
Теперь доступно.
<img width="449" alt="2017-07-13 18 50 50" src="https://user-images.githubusercontent.com/25533641/28175731-b5254a50-67fd-11e7-901f-5fe115f39761.png">
Осталось из цепочки получить.
