### ISSUE TITLE
Добавить поддержку LaTex формул

### ISSUE THREAD

**Issue by AlekseiSmirnov** [GolosChain/tolstoy#271]
Скоро начну пропагандировать Голос в научных кругах.
Да и сам планирую в ближайшее время начать публикации научных статей. Для этого необходимо добавить в редактор (и просмотрщик) поддержку LaTex формул. Можно посмотреть, как это сделано на других ресурсах, например на хабре

**Comment by 21xhipster** [comment]
Ага. Очень важная тема. https://khan.github.io/KaTeX/ - вот даже есть очень неплохая библиотека. Поидее не должно имплементироваться сложно.

**Comment by serejandmyself** [comment]
Implemented in HF
