### ISSUE TITLE
Front-end image cache prevent update

### ISSUE THREAD

**Issue by VIM-Arcange** [GolosChain/tolstoy#276]
If I use the following URL in a post:
`https://imgp.golos.io/50x60/http://golosboard.com/@arcange/posts.png`
 the image is resized by the front-end but also **cached**

 It means that if the target image change, it is not updated in the post :(

- how long is the cache duration (if any)?
- Is it possible to reduce/define the cache timeout?

We could prefix the URL with something like 
`https://imgp.golos.io/[width]x[heigth]x[cache timeout in minutes]/`

**Comment by t3ran13** [comment]
I need it too

**Comment by tomarcafe** [comment]
none yet. considering x[cache timeout in minutes] - there are far more things we can enhance there.. i think we d have to redefine resize/crop behaviour of imgp.. it s strange.. i do not get it although modified it :)

at the same time, i think using proxy url parametrization is not good idea. 
 any chances that when original image url is opened it already has expiration header? 

i got 
```
Content-Type: image/png
Last-Modified: Mon, 23 Jan 2017 22:08:04 GMT
Accept-Ranges: bytes
ETag: "a13a9b2bc575d21:0"
Server: Microsoft-IIS/10.0
X-Powered-By: ASP.NET
Date: Fri, 03 Feb 2017 16:56:41 GMT
Content-Length: 31610
```
in response to `curl -IXGET http://golosboard.com/@arcange/posts.png` (not curl guru, just googled)

so - good we have ETag here - but this turns into mnual check - like you said, by specifying cache exp in url --- which IS a mess considering how proxy works. or you re planning to just enter full link with cachexp setting by hand? i.e. kind of 'command string hack' but rather 'url hack'? 

i beieve it s better to teach imgp to respect Expires header and Cache-Control: max-age header. 
not an expert again, but googled this one - https://stackoverflow.com/questions/7549177/expires-vs-max-age-which-one-takes-priority-if-both-are-declared-in-a-http-resp. 

won't move further without @VIM-Arcange ; feedback :)

**Comment by VIM-Arcange** [comment]
Thanks for your reply.

In my opinion, a simple check against the Last-Modified date will do the trick.
If date is newer, don't use cached image and update with new one.

**Comment by tomarcafe** [comment]
i did not understand that. proxy saves image to cache, and that image has last-modified... or proxy issues HEAD request and checks last-modified against caching timestamp? how often? per image?
at best, this gives uust cache that invalidates 'eventually'.... 

this can be done, of course..yet i think we could spend some more time on that.. so, using http headers for cache control seems hard-to-implement at original image' storage? agreed, end user probably won't ever control that.. 

i see that s a thing to solve - but not sure what s best to do.. 
so your opinion is to have cached image  check interval specified by imgp url parameter, and then check these images on schedule vi head+get or get requests?
do we have default cache outdate interval then? what do we do when image disappears at origin? remove from cache?

**Comment by VIM-Arcange** [comment]
> so your opinion is to have cached image check interval specified by imgp url parameter

Yes, if there is no default 
If you implement default check interval (let say every 1 hour), then an additional parameter is not required

> and then check these images on schedule vi head+get or get requests?

Yes

> do we have default cache outdate interval then? 

It would be even simpler

>what do we do when image disappears at origin? remove from cache?

I would not change the current behavior.

**Comment by VIM-Arcange** [comment]
Any new on this issue?
More and more users are embedding their awards from Доска Почета, and those don't get refreshed.

**Comment by serejandmyself** [comment]
Unforunatly not. Currently we are not taking any isseues, until we finish with the new web client updates

**Comment by tomarcafe** [comment]
@VIM-Arcange i m sorry forgot about that.. soon!

**Comment by tomarcafe** [comment]
@serejandmyself - it s on imgp side solely - so far refresh will happen only for specific image urls, not available in wysiwyg editor mode

**Comment by tomarcafe** [comment]
current state: implemented new urls : same as /200x100/ you can use /200x100t45/ which is planned to mean "cache valid for 45 minutes" (minutes as best time unit is a guess).
so far i test locally, and i see information about cache timeout is retrieved when we hit the cache next time. yet, it s not used so far, only written to console..

**Comment by tomarcafe** [comment]
pushed changes to imgp.golos.io
url structure as above (i.e. can add 't9000' after '/100x500' to request 150 hours cache lifetime)

now some modification is needed at webclient side - currently posts/comments only store original url, and webclient wraps them with proxy, but it only uses /0x0/ (keep same) and /256x128/ and /640x480/ prefixes. also, it won't help pasting url already proxied with imgp - it will be double-proxied, with last hop still looking like /0x0/ or /256x128/ and not caching.
however, you can check by curl or browser that feature works as intended

note that /100x500t0/ means cache will work - i.e. store image - but on next request that cache will be removed (as >0 minutes passed).

**Comment by tomarcafe** [comment]
@VIM-Arcange , this also means you can call manually `https://imgp.golos.io/0x0t0/http://url.here.png` to reset cache for given image. i.e. while image still will load as /0x0/ at webclient - its cached contents will be reset upon 't' call.

**Comment by VIM-Arcange** [comment]
@tomarcafe Thanks for feedback and quick fix.
I tested it in my latest posts and it looks like it is working fine.
Excellent work!

**Comment by VIM-Arcange** [comment]
I am reopening this issue because the current implementation does not work.

2 days ago, I changed the image I use for myself on golosboard.com with this one
`http://golosboard.com/@arcange/level.pngµ
![image](https://cloud.githubusercontent.com/assets/21260036/23120424/922fbb0a-f75c-11e6-93ff-c40a09106b96.png)
It is a whale "swimming" toward right

If you check my last post (https://golos.io/golosboard/@arcange/doska-pocheta-obnovlenie-3), the footer include the following image link:
`[![](https://imgp.golos.io/100x80t1440/http://golosboard.com/@arcange/level.png)](http://golosboard.com/board.html?user=arcange)`

golos.io still display the old image (a whale "swimming" toward left), even if the timeout has expired.

To reproduce the problem:
- create a new post
- copy `https://imgp.golos.io/100x80t1440/http://golosboard.com/@arcange/level.png` in the body
If you see a left-swimming whale, it means golos.io still retrieve image from cache

**Comment by VIM-Arcange** [comment]
Things working correctly now. Closing the issue.

**Comment by VIM-Arcange** [comment]
It looks like the proxy timeout is broken again.

`https://imgp.golos.io/100x80t1440/http://golosboard.com/@arcange/level.png`

The above link in a post display a broken image 
![image](https://cloud.githubusercontent.com/assets/21260036/23656733/252f1c36-033b-11e7-9d07-a023bb2b2d1a.png)

When changing the timeout value, the image is displayed correctly

ex: `https://imgp.golos.io/100x80t1444/http://golosboard.com/@arcange/level.png`

**Comment by tomarcafe** [comment]
maybe because timeout in minutes is counted since cache update?

**Comment by VIM-Arcange** [comment]
Browsing https://imgp.golos.io/100x80t1440/http://golosboard.com/@arcange/level.png should at least return an image. It does not return anything.

**Comment by tomarcafe** [comment]
just checkrd, it returns whale swimming left

**Comment by VIM-Arcange** [comment]
You are right! I tested it again, and indeed it works **if I do a browser refresh (CTRL-F5)**
I have to do the same on all the post I published previously.
I had not this problem two days ago.
You can close the issue, if you think it is a client side only problem.

**Comment by tomarcafe** [comment]
let s just try to figure out how we can use it.. my best guess is simply calling /0x0t0/ or so to reset cache immediately. also cache freshness check is done upon next request, so passing t1440 not guarantees next cache reload will happen 1 day after. it only tells imgp to reset cache it it is older than 1440..

**Comment by pavelit** [comment]
You need to add some parameter to the end of the url address.

Old image cached by image proxy.
https://imgp.golos.io/0x0/http://distrowatch.com/images/cgfjoewdlbc/rosa.png

New image by old url and some parameter
https://imgp.golos.io/0x0/http://distrowatch.com/images/cgfjoewdlbc/rosa.png?0
