### ISSUE TITLE
Починить срочный баг

### ISSUE THREAD

**Issue by solodikov** [GolosChain/tolstoy#279]
У пользователя до сих пор нет "Ответов".
Сергей, просьба отписать ребятам в срочное исправление.
Подробности здесь: https://golos.io/ru--ispravleniya/@dreamer/kuda-propali-otvety-iz-kabineta

**Comment by serejandmyself** [comment]
Это куки, других вариантов быть не может

**Comment by solodikov** [comment]
Чьи? Он свои вычистил, я тоже, у меня тоже нет его "Ответов", а если на странице его "Ответов" нажать обновление - вообще появляется робот. Нам надо это пофиксить.

**Comment by serejandmyself** [comment]
Действительно нет

**Comment by serejandmyself** [comment]
Нет, они там есть...

https://golos.io/@dreamer/recent-replies

**Comment by serejandmyself** [comment]
Да, действительно.

Добавлю сюда же:

https://golos.io/@radogost/posts

**Comment by solodikov** [comment]
Вот ещё: https://golos.io/@ilya.boev/recent-replies

**Comment by solodikov** [comment]
Вот ещё: https://golos.io/@zlody/recent-replies

**Comment by solodikov** [comment]
Как минимум у того же пользователя @dreamer вновь пропали "Ответы", а при обновлении страницы вообще загружается заглушка с роботом: https://golos.io/@dreamer/recent-replies
