### ISSUE TITLE
Несколько косяков по сайту

### ISSUE THREAD

**Issue by 0n0t0le** [GolosChain/tolstoy#28]
- в форме восстановления пароля текст не влез в границы кнопки

![](http://i67.tinypic.com/rhu5ut.png)
- в разделе поиска сразу два поля для ввода (не думаю что фича)

![](http://i64.tinypic.com/1pxbpx.png)

**Comment by tomarcafe** [comment]
форварднул в командный чат.

**Comment by Undeadlol1** [comment]
Спасибо, что сообщили.
Исправил давно, но забыл закрыть ишью.
