### ISSUE TITLE
Непонятный глюк при вставке фото в пост

### ISSUE THREAD

**Issue by litrbooh** [GolosChain/tolstoy#280]
Хочу вставить в пост превью фото со ссылкой на оригинал, вставляю:
`<a href="http://ixbt.photo/photo/351453/22681z3EFWJJ2Mr/dcgrNYlrs3/1170002.jpg"><br><img src="http://ixbt.photo/photo/351453/22681z3EFWJJ2Mr/1170002w.jpg"></a>
`

Публикую пост, фото без ссылки. Открываю редактирование, а там только:
`<img src="http://ixbt.photo/photo/351453/22681z3EFWJJ2Mr/1170002w.jpg" width="820" height="251"/>`

Вставляю ещё раз:
`<a href="http://ixbt.photo/photo/351453/22681z3EFWJJ2Mr/dcgrNYlrs3/1170002.jpg"><br><img src="http://ixbt.photo/photo/351453/22681z3EFWJJ2Mr/1170002w.jpg"></a>
`

Сохраняю - всё ок.

**Comment by serejandmyself** [comment]
Актуально? Кое что менялось, могло подействовать

**Comment by serejandmyself** [comment]
Не понятна ситуация, не получается её возобновить.

**Comment by litrbooh** [comment]
@serejandmyself , ситуация повторяется.

Вставляю картинку:
![default](https://cloud.githubusercontent.com/assets/22373216/26746400/e21704b6-47f7-11e7-86eb-32aeffef9331.png)

Перехожу в Редактор
![default](https://cloud.githubusercontent.com/assets/22373216/26746411/eeb8ed2e-47f7-11e7-9f17-e3928e505862.png)

Редактирую текст 
![default](https://cloud.githubusercontent.com/assets/22373216/26746420/fe22cc9e-47f7-11e7-8ca1-7cfbe2ab61af.png)

Дальше если опубликовать - ссылка на фото пропадет, продает она с при обратном переходе в HTML редактор:
![default](https://cloud.githubusercontent.com/assets/22373216/26746428/1873cc92-47f8-11e7-9708-07b2382359c5.png)

**Comment by b1acksun** [comment]
Текст набранный в редакторе Markdown не совместим с режимом Raw HTML, при переключении возникают вышеперечисленные "глюки"
