### ISSUE TITLE
Проблема с отображением постов с тегом nsfw?

### ISSUE THREAD

**Issue by litrbooh** [GolosChain/tolstoy#281]
Может я чего-то не понимаю, но у автора есть 4 поста:
![default](https://cloud.githubusercontent.com/assets/22373216/22591185/458ff584-ea24-11e6-9c80-25789ddd18e9.png)
https://golos.io/trending/nsfw

Но в его блоге видно только 1 пост, который был убран под тэг уже после (как я понимаю).
![default](https://cloud.githubusercontent.com/assets/22373216/22591208/5d6b7c14-ea24-11e6-954c-7a2bbd83dc79.png)

https://golos.io/@brovaryleaks

**Comment by serejandmyself** [comment]
Все правильно, это не issue это feature.

Посты с тэгом nsfw не должны отображаться в ленте (сам функционал с отображением в настройках уже с 16.1)

У другого потса тэг nvsf а не nsfw

**Comment by litrbooh** [comment]
@serejandmyself
В ленте понятно - не должны, но в профиле то они должны быть? Или этот тег сейчас вообще фильтруется и в профиле появится в только 16.1?

**Comment by serejandmyself** [comment]
Нет, они скрыты. Только в 16.0 это поменялось
