### ISSUE TITLE
Сделать букву "ё" в теле поста видимой при использовании клавиши #

### ISSUE THREAD

**Issue by solodikov** [GolosChain/tolstoy#288]
Коммент [отсюда](https://golos.io/ru--idunavzlyot/@ondulyansion/popsa-vs-kreativ-obsuzhdaem-18#@tristamoff/re-ondulyansion-popsa-vs-kreativ-obsuzhdaem-18-20170210t115249940z).

**Comment by serejandmyself** [comment]
Это уже исправили, надо смотреть что на его стороне

**Comment by serejandmyself** [comment]
ПС, она и у него сработала. Или я что то не понял

**Comment by solodikov** [comment]
Показываю, как не отображается тег "идунавзлёт" в статье:
![screenshot 2017-02-12 0 34 38](https://cloud.githubusercontent.com/assets/24874226/22856816/43a39648-f0bb-11e6-8e8a-d323937d8941.jpg)
Статья [здесь](https://golos.io/ru--idunavzlyot/@lumia/3ec92k-vzlyot-promoushen-pervogo-mesyaca-na-golose).

**Comment by serejandmyself** [comment]
Просьба тогда описывать issue с самого начала не комментарием, а именно примерами, чтобы было понятно

**Comment by serejandmyself** [comment]
Вот в этом посте есть тэг идунавзлет с буквой ё..

**Comment by solodikov** [comment]
Поясняю. Тег #идунавзл**ёт** при публикации показывает активный линк #идунавзл, а **ёт** показывает не активным.

Необходимо поправить визуальное отображение опубликованного тега #идунавзл**ёт** так, чтобы **ёт** было в активном линке и проверить его работу, что:
а) тег корректно отображается
б) переход по линку ведёт на подгружение всех тегов #идунавзлёт

**Comment by serejandmyself** [comment]
Проверил еще раз...

[![Безымянный.png](https://s15.postimg.org/8pxzxwb7v/image.png)](https://postimg.org/image/n954zb4cn/)

**Comment by solodikov** [comment]
У меня скоро тик начнётся на эту задачу.
![screenshot 2017-02-13 20 10 26](https://cloud.githubusercontent.com/assets/24874226/22888733/9916c9c4-f228-11e6-81e1-f78bb016772d.jpg)

**Comment by serejandmyself** [comment]
Я все понимаю, но... ЕСЛИ В ПОЛЕ ТЭГ идунавзлёт не чего не ломает и работает, в чем проблема (я вижу что в теле письма оно якобы да ломает, НО, тэг срабатывает!!!)

То есть у автора проблема, что он не может написать пост с тэгом идуназлёт... но это не так, ведь автор явно пишет пост с тэгом............. идунавзлёт

**Comment by solodikov** [comment]
Проблема только в теле письма.

**Comment by serejandmyself** [comment]
Вот название (оригинальное) темы:

Сделать букву "ё" в тегах, она не работает, ломает тег

**Comment by solodikov** [comment]
Спасибо, что нашли согласовали более точное название! )
Осталось решить задачу.

**Comment by serejandmyself** [comment]
Closed HF 16.3
