### ISSUE TITLE
Разобраться с почтовым сервером @golos.io

### ISSUE THREAD

**Issue by serejandmyself** [GolosChain/tolstoy#290]
У кого доступ, как использовать в качестве нашего сервера

**Comment by solodikov** [comment]
Сергей, у нас же: https://postmaster.mail.ru/golos.io/

**Comment by serejandmyself** [comment]
Да, вот и надо понять как все это дело соединить в одно целое

**Comment by solodikov** [comment]
Кстати, а вот нам и бесплатный почтовый сервер нашёлся: https://biz.mail.ru/mail/

**Comment by solodikov** [comment]
Я подключаю нас.

**Comment by serejandmyself** [comment]
Пока погоди. Надо разобраться с этим вопросом Голосом чуть позже с @sualex

**Comment by solodikov** [comment]
Ок. Тогда жду созвон по теме.
