### ISSUE TITLE
Баг при голосовании из ленты

### ISSUE THREAD

**Issue by 0n0t0le** [GolosChain/tolstoy#291]
Иногда (редко) но все же встречается баг следующего вида:
при голосовании за посты из ленты при нажатии на `^` не появляется ползунок регулирования силы, и голосование проходит с той силой, которая была выбрана ранее. Проходит так же внезапно, как и появляется
***
Периодичность - хз, закономерность выявить не удалось, встречается на последнем FF/chrome

**Comment by serejandmyself** [comment]
Not actual in latest version
