### ISSUE TITLE
ошибки при Chaing мастер-ключ от steemit

### ISSUE THREAD

**Issue by gitbase1** [GolosChain/tolstoy#293]
<img width="459" alt="screen shot 2017-02-18 at 11 55 54 pm" src="https://cloud.githubusercontent.com/assets/25875309/23099474/2aad0a2c-f636-11e6-879e-eff26c0da507.png">
<img width="357" alt="screen shot 2017-02-18 at 11 56 38 pm" src="https://cloud.githubusercontent.com/assets/25875309/23099475/2cd00250-f636-11e6-83ad-3f28634c881b.png">

**Comment by gitbase1** [comment]
Проблема происходит при попытке сгенерировать новый пароль

**Comment by serejandmyself** [comment]
Не совсем понятно что Вы пытались сделать. Опишите ситуацию повторно пожалуйста

**Comment by mcifani** [comment]
обновление моего steemit владельца ключа на Голосе. когда я пытаюсь ввести новый ключ он дает эту ошибку

**Comment by gitbase1** [comment]
Привет, это происходит при сбросе пароля. Существует ошибка.
<img width="903" alt="screen shot 2017-02-19 at 11 53 00 am" src="https://cloud.githubusercontent.com/assets/25875309/23104354/089a70aa-f69a-11e6-8a99-8341640ac8fa.png">

**Comment by serejandmyself** [comment]
Просьба проверить повторно

**Comment by gitbase1** [comment]
Sorry, still not working.  Getting same error. 

К сожалению, до сих пор не работает. Получение же ошибку.

**Comment by b1acksun** [comment]
Просьба проверить повторно
