### ISSUE TITLE
Добавить окно предупреждения на несколько действий 

### ISSUE THREAD

**Issue by serejandmyself** [GolosChain/tolstoy#295]
Действия: Нажатие кнопок:

Подписаться, Отписаться, Блокировать, Разблокировать

Подписаться - всплывающее окно "Вы уверены что хотите подписаться на этого пользователя?" (Ответ да/нет)

Отписаться - всплывающее окно "Вы уверены что хотите отписаться от этого пользователя?" (Ответ да/нет)

Заблокировать - всплывающее окно "Вы уверены что хотите заблокировать этого пользователя? После данного действия, Вы не будите видеть посты и комментарии этого пользователя" (Ответ да/нет)

Разблокировать - всплывающее окно "Вы уверены что хотите разблокировать этого пользователя?" (Ответ да/нет)

**Comment by 21xhipster** [comment]
Я бы подвердение на подписку/отписку не стал делать. На блокировку - другое дело.

**Comment by serejandmyself** [comment]
Создавал по жалобам пользователей. В любом случае это беклог
