### ISSUE TITLE
баг с апвотом

### ISSUE THREAD

**Issue by t3ran13** [GolosChain/tolstoy#296]
Уже пол года висит, мое терпение и лень не выдержали))

Так вот, торчу на голосе с телефона, через firefox. Захожу в любой пост, жму проголосовать и не могу, поскольку некорректное отображение голосовали
https://habrastorage.org/files/8b5/85c/468/8b585c468a4d4392b06fc386a75a8397.png

С клиентами все норма

**Comment by t3ran13** [comment]
https://habrastorage.org/files/8b5/85c/468/8b585c468a4d4392b06fc386a75a8397.png

**Comment by BaroH4er** [comment]
Из-за отсутствия аккаунта с необходимой силой голоса, ишью проверено благодаря @NickShtefan - исправлено.
