### ISSUE TITLE
Сделать официальный запрос в РКН

### ISSUE THREAD

**Issue by tomarcafe** [GolosChain/tolstoy#299]
цель запроса - получить список uri, на которых размещен запрещенный контент.
https://rkn.gov.ru/

**Comment by serejandmyself** [comment]
Этих сайтов тысячи, там нет единого списка. Нужно вводить название и смотреть, по крайней мере такого списка я не видел.

**Comment by serejandmyself** [comment]
Вот сайт, где это смотреть : http://eais.rkn.gov.ru/

**Comment by serejandmyself** [comment]
То есть нужно быть оператором связи для получение такого списка

**Comment by serejandmyself** [comment]
Увы, это сделать не возможно, если мы не оператор связи - http://vigruzki.rkn.gov.ru/tooperators_form/

http://eais.rkn.gov.ru/docs/Recomendation.pdf
