### ISSUE TITLE
Неверно отображается счётчик голосов

### ISSUE THREAD

**Issue by petermz** [GolosChain/tolstoy#30]
Похоже, только если голосов ноль.
Здесь под первым комментарием нарисован правильно (Safari 9.1.2):

<img width="1019" alt="screen shot 2016-10-10 at 11 08 19" src="https://cloud.githubusercontent.com/assets/16533006/19229956/14f04d34-8eda-11e6-81ba-f8dce5c5bc79.png">

**Comment by petermz** [comment]
Проявляется в шапке блога:

<img width="1226" alt="screen shot 2016-10-11 at 20 27 37" src="https://cloud.githubusercontent.com/assets/16533006/19281124/6790a1d4-8ff1-11e6-8431-9a1a88de0cde.png">

**Comment by petermz** [comment]
Сейчас как будто не воспроизводится

**Comment by Undeadlol1** [comment]
Не актуально?

**Comment by petermz** [comment]
Нет, давно уже не видел такого

**Comment by Undeadlol1** [comment]
Спасибо за репорт.
