### ISSUE TITLE
User name reference in tables broken in markdown interpreter

### ISSUE THREAD

**Issue by VIM-Arcange** [GolosChain/tolstoy#306]
When you put username refrences in tables (@username), the reference is not displyed correctly:

Example:
```
| c1 | c2 | c3|
|-|-|-|
|@arcange xxx | @arcange   xxx | @arcange |
```

Displays

![image](https://cloud.githubusercontent.com/assets/21260036/23654621/d2aec5aa-0331-11e7-96da-012bfa8c3911.png)

In column 1, text is stuck to username
In column 2, I had to put 2 spaces between username and text to get 1 space in display
In column 3, username is not displayed as a link.

**Comment by serejandmyself** [comment]
Reference #303
