### ISSUE TITLE
Ошибки комментирования

### ISSUE THREAD

**Issue by petermz** [GolosChain/tolstoy#31]
Safari 9.1.2, ошибка при попытке оставить комментарий:
<img width="687" alt="screen shot 2016-10-10 at 11 14 44" src="https://cloud.githubusercontent.com/assets/16533006/19230101/4034ea6c-8edb-11e6-814e-1f8f79f2c0d0.png">

Если, ничего не написав, нажать ОТМЕНА, тоже ошибка. Повторное нажатие срабатывает:
<img width="882" alt="screen shot 2016-10-10 at 11 17 57" src="https://cloud.githubusercontent.com/assets/16533006/19230102/40570408-8edb-11e6-8746-e1100d015249.png">

**Comment by tomarcafe** [comment]
сафари 10.0 глюков не воспроизвёл. продолжаю наблюдения.

**Comment by petermz** [comment]
Первый баг не воспроизводится, то ли исправили, то ли я кэш почистил

Баг с отменой у меня воспроизводится постоянно

**Comment by Undeadlol1** [comment]
Еще актуально?

**Comment by petermz** [comment]
Баг с Отменой -- да

**Comment by serejandmyself** [comment]
Closed HF 16.3
