### ISSUE TITLE
Встраиваемый контент с популярных сайтов

### ISSUE THREAD

**Issue by 21xhipster** [GolosChain/tolstoy#310]
Уже прямо накипело, что с любимых сервисов нельзя встраивать контент. Реализация тривиальна. Нужен либо вайтлист доменов прямо в коде либо можно пойти вообще [кошерным путем](https://github.com/asvd/jailed). Приобретаемую ценность сложно перееоценить. Закрыл #82 в обмен на этот, т.к. всё это дело можно реализовать чохом и красиво продать пользователям. Большинство из списка взято [отсюда](https://golos.io/ru--golos/@vik/10-ki-saitov-kotorye-khotyat-byt-na-golose-s-kakikh-saitov-mozhno-vstraivat-video-foto-karty-i-drugoi-kontent)

Список сайтов:
- Coub
- Vine
- Instagram
- VK
- Facebook
- Vimeo
- Twitch
- IMDB
- Kinopoisk
- Soundcloud
- Google Maps
- Yandex Maps
- Openstreetmap
- Booking
- Tripadvisor
- Airbnb
- Privnote
- Codepen
- Github Gists
- Jsfiddle
- Pastebin
- Slideshare
- Speakerdeck
- Plotly
- Google Docs
- Kickstarter
- Indiegogo

**Comment by serejandmyself** [comment]
Imlemented a while ago. Needs to be updated with an actual list
