### ISSUE TITLE
Добавить для кнопки обратная связь описание по примеру как сделано с issue на github

### ISSUE THREAD

**Issue by serejandmyself** [GolosChain/tolstoy#311]

**Comment by solodikov** [comment]
Уважаемые пользователи! 

Вы находитесь на странице «обратной связи» с командой Голоса. Здесь вы можете оставить **свои отзывы и предложения** о работе нашей платформы, а также **сообщить нам об обнаружении бага**. Ваш сообщение будет опубликовано в открытом доступе.

Пожалуйста, не публикуйте здесь другие сообщения, не связанные с функционированием блокчейна ГОЛОС и блог-платформы GOLOS.io!

Если вы попали на эту страницу случайно и хотите опубликовать обычную запись на другие темы - нажмите «**Добавить пост**» в правом верхнем углу страницы.  

Спасибо!

**Comment by serejandmyself** [comment]
Закрыто в ХФ
