### ISSUE TITLE
Возможно некорректное начисление токенов GOLOS при упоминании пользователей

### ISSUE THREAD

**Issue by solodikov** [GolosChain/tolstoy#312]
Необходимо проверить корректность начисления токенов GOLOS при упоминании пользователей, если токены начисляются некорректно - исправить. Описание выявленной проблемы [здесь](https://golos.io/ru--golos/@nikalaich/opyat-nikalaich-s-voprosom-nepoladki-s-mention-bot).

**Comment by serejandmyself** [comment]
Вообще не к нам. Это стороняя фича

**Comment by solodikov** [comment]
Ок. Ответил.
