### ISSUE TITLE
Добавить currency в метаданные аккаунта

### ISSUE THREAD

**Issue by gropox** [GolosChain/tolstoy#315]
# Golos.io

## Issue Type

- [ X] Feature (https://github.com/GolosChain/tolstoy/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description

В настоящее время судя по всему выбранная в настройках валюта хранится в куках. Поэтому приходится на всех машинах и устройствах выбирать валюту вручную. Ну и как следствие хранения валюты в куках, при загрузке страницы все вознаграждения показывается сначала в рублях, потом только, после полной загрузки, вознаграждения показываются в выбранной валюте. Пару секунд кажется, что ты несметно богат.

Было бы неплохо добавить валюту (currency) в json_meta аккаунта и брать данные для интерфейса от туда. Тоже касается и языка интерфейса, как и валюта, сначала при загрузке показывает русский, потом переключает на английский или украинский. Добавить что-то вроде preffered_language. 

Возможно должно ускорить загрузку страницы, так как валюта и перевод не будут подгружаться.

![currency](https://cloud.githubusercontent.com/assets/26039472/23859070/c50d64b2-0802-11e7-95cf-4f2cbc83f48c.gif)

**Comment by pavelit** [comment]
Решено, но немного по другому. В момент загрузки страницы в браузере первое отображение рендерится на стороне сервера. Соотв. сервер не знает что там у пользователя выбрано (валюта, язык и др.). Поэтому мы добавили в cookie паремтр выбранной валютной пары для корректной генерации страницы на серверной стороне.
