### ISSUE TITLE
Срочно исправить мелкий баг с прилипанием текста к никнеймам

### ISSUE THREAD

**Issue by solodikov** [GolosChain/tolstoy#317]
Команда, выношу это в отдельную задачу, вопрос с этим багом сильно затянулся. Невыносимо видеть.

![screenshot 2017-03-14 16 17 44](https://cloud.githubusercontent.com/assets/24874226/23898344/9b32f578-08d2-11e7-9094-ff522a64a352.jpg)

**Comment by serejandmyself** [comment]
> referenced #303

**Comment by solodikov** [comment]
@serejandmyself, а я знаю, что это дубль. Нам нужно взять его и **вывести в отдельную задачу**, что я и сделал, иначе в этой братской могиле багов его совсем не видно, а это очень важно.

**Comment by serejandmyself** [comment]
Антон, все в курсе задачи, просьба не дублировать issue, спасибо

**Comment by solodikov** [comment]
Принято.
