### ISSUE TITLE
Не могу понять почему не отображаются картинки

### ISSUE THREAD

**Issue by lizikcas9** [GolosChain/tolstoy#319]
В этом [посте](https://golos.io/mapala/@lizik/plyazhi-ostrova-bali) часть картинок отображается, часть нет. По какой логике не ясно. Чтобы пост выглядел адекватно, исправлю перезалив на другой хостинг. Один неработающий образец оставляю в конце поста

**Comment by serejandmyself** [comment]
Для проверки не хватает информации

**Comment by lizikcas9** [comment]
Какой информации вам не хватает?

**Comment by serejandmyself** [comment]
Любой... Как грузили, что грузили, через что грузили, какой командой. 

Обычно значок летающей тарелки, обозначает не правильную загрузку. Но чтобы разобраться, нужна информация...

**Comment by lizikcas9** [comment]
Вставляла фото через Markdown как и остальные. В круглые скобки вставляла адрес из Google фото.

**Comment by serejandmyself** [comment]
Вы можете предоставить сам код ссылки (именно тот который вы вставляли)? Вы же не думаете что мы видим его на сквозь? =)

**Comment by lizikcas9** [comment]
Думаю, потому что он записан в блокчейне. Вот [пост](https://golosdb.com/mapala/@lizik/plyazhi-ostrova-bali), в котором не отображается последняя картинка (кстати, она у вас отображается?)

**Comment by serejandmyself** [comment]
Нет, картинка не отображается. И чтобы вам помочь мне нужен код, которым вы вставляли картинку, которую скопировали с хостинга

**Comment by lizikcas9** [comment]
![](https://lh3.googleusercontent.com/GY6E38QxPuSc5CAkO-SGZMh5RmfKgXV4XQC8H55tDnR-9N2G79OyyV6Lc9RYuzd-TmxhDnSoxW6Op7JUY0oAvhjnZfIPBUYR5wN-Y5SlSAP26LJj0lsAk6i0whWivofThZim868zmu4aiCkLCKN6AdoR5VUdu-XaNnHmelHXc5cz_Js89xdUfw01sq2U5BICVnQu7nfuiCoP4gYfLSeXcdkfSbwcs0f4H3rllt4OluJVBrp9QlxoIgtnbDa29pRJIQBq2D3DkYvD1k8heIIk69oEayxQyEThQO65T6hQFhHvkC9-59tBF4VMmYSeaUT6huL3Nrk90z_hsVpD2_gAb53BeMBMeKOntg7tM812ZmHz3NgHArya5YDff9UgT381n8OYca0qTAlPaw0LMt1ru4aWAd8tmlSxSK5gJk-9zuhjMPqtzcvzluT8vTGDRJDldogUlH5RL6rjboSEXqb2-HfF7MwSVziRIDkUVf3d955iXoU-IescL1wi2Pm8Ao-b675XAIqDf4O3Z7J3lCgO8_R_rltObxrc3Q7nHSnC-YeMaPDxPGyB3Lheh2-0MWKdy1gp1xWksDHFm3o842DMJUsNGZLTj5YaOy3WM_mJJaKx4O5-Di2Ygg)

**Comment by serejandmyself** [comment]
У вас битая ссылка. Вы скорее всего вставляете ссылку на прямую

**Comment by lizikcas9** [comment]
Что значит битая ссылка?

**Comment by serejandmyself** [comment]
Это значит что проблема не на стороне сайта, а в ссылке которую Вы пытаетесь вставить. К сожалению исходя из информации выше я не могу понять ни что, ни как вы пытаетесь это сделать. Но issue я закрываю, так как это не имеет никакого отношения к проблемам кода сайта и / или ядра. 

С уважением,

ПС Просьба за дальнейшей помощью по данному вопросу писать сюда:

https://chat.golos.io/channel/help_%25D0%25BF%25D0%25BE%25D0%25BC%25D0%25BE%25D1%2589%25D1%258C

**Comment by lizikcas9** [comment]
Хорошо, спасибо.
