### ISSUE TITLE
Ошибка оценки стоимости аккаунта

### ISSUE THREAD

**Issue by 21xhipster** [GolosChain/tolstoy#322]
Уже третий день наблюдаю картину при которой golos.io дает неадекватную оценку (раза в три приблизительно)
Проблема не только у меня.
https://golos.io/ru--golos/@ropox/ocenochnaya-stoimost

Думаю надо сроно пофиксить. С такими штуками лучше не шутить.

**Comment by gropox** [comment]
Я так думаю стоимость голосов и золотых определяется по разному. От этого скачки. Мне накапало со вчерашнего дня пару золотых и стоимость рывком поднялась с ~50 Евро, до 160 Евро. Я потом на все золотые купил голоса. Голоса никуда не перемещал, они в моем кошельке. Зато цена сразу упала со 160 Евро, до 43.

**Comment by serejandmyself** [comment]
Проблема немного в другом. Но, я в принципе думаю знаю в чем ошибка. Проверю

**Comment by serejandmyself** [comment]
Не получился фокус

**Comment by 21xhipster** [comment]
@serejandmyself Когда мы исправим оценку? Мы же людей обманываем.

**Comment by 21xhipster** [comment]
! High priority

**Comment by gropox** [comment]
У меня почему-то кошелек теперь в неизвестных цифрах оценивается. Но много)) Пробовал на рубли переключать, , на доллары, обратно на евры. 

![koshelok](https://cloud.githubusercontent.com/assets/26039472/24411241/b2ea633c-13d5-11e7-84ee-6802ed47b366.JPG)

**Comment by serejandmyself** [comment]
@gropox работа еще не завершена, issue закрыт так как мы знаем решение и выполняем его сейчас
