### ISSUE TITLE
Поиск по tranding tags не работает для русскоязычных тэгов

### ISSUE THREAD

**Issue by gropox** [GolosChain/tolstoy#324]
Значение фильтра используется без транслитерации, а поиск происходит по тэгам записанными латиницей. 

https://github.com/GolosChain/tolstoy/blob/master/app/components/pages/TagsIndex.jsx#L43

Смотри гифку
![filtergolos gif](https://cloud.githubusercontent.com/assets/26039472/24097349/b6c8df68-0d65-11e7-81f4-58a756e4fa11.gif)

**Comment by serejandmyself** [comment]
Да, только это не tags а categories. На данный момент, логика поисковика не исправлена на tags поэтому мы его скорее всего отключим, так как пользователи не видят разницу между tags and categories
