### ISSUE TITLE
Баги и фичи фильтра тегов

### ISSUE THREAD

**Issue by serejandmyself** [GolosChain/tolstoy#330]
- [ ] На странице всех тегов убрать лимит 250 тегов и сделать отображение всех тегов, что важно для возможности подписки на непопулярные теги (upd. @solodikov)

**Баги**:

- [ ] Починить баг, при переходе на любой сохранённый тег из фильтра сохранённых тегов, показывающий весь контент без фильтрации (upd. @solodikov)

- [ ] Починить баг, не сбрасывающий фильтр тегов после разлогинизации (upd. @solodikov)

- [ ] починить баг, сбрасывающий все фильтры при выполнения следующего алгоритма (upd. @solodikov):
а) нажать на кнопку "обратная связь"
б) на странице поста "обратной связи" нажать на тег "обратная связь"
в) перейти на страницу отображения всех постов по тегу "обратная связь"
результат: все сохранённые фильтры сброшены

**Фичи**:

- [ ] Добавить возможность отписаться от тега, То есть знак "-" 

- [ ] Добавить возможность сохранять несколько фильтров и задавать им названия.

- [ ] Добавить возможность видеть выбранные теги на странице “другие теги”.

- [ ] Возможность добавлять или удалять теги, напрямую из поста.

- [ ] Возможность "перетаскивать" фильтры в списке

**Comment by litrbooh** [comment]
Не работает сохранение тэгов, они вроде бы сохранились, но посты отображаются все
![default](https://cloud.githubusercontent.com/assets/22373216/24505492/bc6e178a-1562-11e7-9988-d920febc7ea5.png)

**Comment by pavelit** [comment]
В разделе "Лента" фильтр не работает. Это отдельный раздел, функциональность которого - подписка на авторов. Фильтр - подписка на теги для разделов: Новое/Актуальное/Популярное/Промо.

**Comment by litrbooh** [comment]
В новом тоже не работает
![default](https://cloud.githubusercontent.com/assets/22373216/24506316/bda0ec10-1565-11e7-919f-3a60f04b90c8.png)

![default](https://cloud.githubusercontent.com/assets/22373216/24506338/d2ffff6a-1565-11e7-8577-6af5f130f09f.png)

![default](https://cloud.githubusercontent.com/assets/22373216/24506351/db581832-1565-11e7-9ffc-67ba3ba18bac.png)

**Comment by litrbooh** [comment]
Поясните, моя проблема в работу принята?  Фильтр ни в каких вкладках не работает.

**Comment by serejandmyself** [comment]
@litrbooh Что значит не работает? Из твоего иссью понятно что он не сохраняет.

**Comment by serejandmyself** [comment]
reference #399

**Comment by jevgenika** [comment]
Доработать страницу welcome
- [ ] выбрать 30 самых популярных тегов
- [ ] показать страницу с 30 самых популярными тегами для новичков, с возможностью выбора 5 из них для первого захода на сайт (пример Medium App) 
![tags_medium](https://user-images.githubusercontent.com/30616421/31132175-76d05e62-a85c-11e7-8af6-36c6aec9d40a.JPG)

**Comment by jevgenika** [comment]
https://github.com/GolosChain/tolstoy/issues/455 дубликат

**Comment by jevgenika** [comment]
рубрикатор и настройка ленты под себя https://github.com/GolosChain/tolstoy/issues/457

**Comment by jevgenika** [comment]
https://golos.io/ru--golos/@trolik/obrashenie-k-razrabotchikam-golos-a-moi-mysli-i-pozhelaniya-kasatelno-tegov

**Comment by jevgenika** [comment]
https://github.com/GolosChain/tolstoy/issues/263

**Comment by jevgenika** [comment]
https://github.com/GolosChain/tolstoy/issues/720
