### ISSUE TITLE
Не отображаются посты в телеграм

### ISSUE THREAD

**Issue by gropox** [GolosChain/tolstoy#331]
Скорее вопрос, чем баг или фича.

До сих пор в telegram если в сообщении была ссылка на конкретный пост или комментарий, то telegram показывал содержимое (начало) поста. 

К примеру ссылка https://golos.io/ru--golos/@serejandmyself/re-ropox-re-serejandmyself-re-ropox-re-golos-filtraciya-kontenta-na-golose-20170328t130453562z

С некоторых пор однако ссылки резольвятся не так как надо. Telegram показывает текст главной страницы. Внимание вопрос :) Поменялось, что то недавно на голосе? Поменяли robots.txt? Похоже теперь все ссылки ведут на главную?

Вот как было до недавнего времени и как стало сейчас.
![](https://imgp.golos.io/0x0/http://i.imgsafe.org/b546d11123.png)

![telegrampost](https://cloud.githubusercontent.com/assets/26039472/24406809/6d1a2a2e-13c9-11e7-9db9-761e69579d89.JPG)

**Comment by gropox** [comment]
Я сейчас тестировал. Телеграмовский Link Preview не работает для свежих постов. Видимо golos api (wss://ws.golos.io) быстрее выдает новый контент, чем вебинтерфейс. :( Потому видимо вебинтерфейс перенаправляет на главную страницу. Так как думает, что линк не действительный. Я думаю это недавно началось, на выходных было еще все нормально.

В бот надо встраивать задержку как-то, что бы не сразу извещал, а давал время golos.io на..., что бы он там свои дела успевал делать.

**Comment by serejandmyself** [comment]
Вопрос с ботом, желательно направить его владельцу. Все остальное нам =)

**Comment by gropox** [comment]
Да я сам владелец. :) Просто до сих пор работало, а тут перестало. Буду думать.

**Comment by serejandmyself** [comment]
Разве это не бот @0n0t0le ?

**Comment by gropox** [comment]
Нет, это мой. Я своим пользуюсь, он как бы более продвинутый :) Скриншот сообщений от on0tole бота я в качестве примера привел.

**Comment by solodikov** [comment]
Я только что отправил в Телеграм случайный пост - карточка поста подгрузилась нормально.

![screenshot 2017-03-28 19 11 11](https://cloud.githubusercontent.com/assets/24874226/24409722/783f18f8-13ea-11e7-942a-2c861458e6ac.jpg)

**Comment by solodikov** [comment]
![screenshot 2017-03-28 19 13 58](https://cloud.githubusercontent.com/assets/24874226/24409807/bc1c3b64-13ea-11e7-9e16-ade25dbc012f.jpg)

**Comment by gropox** [comment]
не знаю, у меня превью для не которых грузится быстро, для некоторых и спустя несколько минут все еще текст главной страницы выдает. 

Вот к примеру, несколько раз пробовал, выдет текст главной страницы, потом через 40 секнуд внезаптно, на тот же линк показало preview

![golospreview](https://cloud.githubusercontent.com/assets/26039472/24410035/495c0d88-13d2-11e7-9d23-84711df29412.JPG)

**Comment by gropox** [comment]
О блин, а линк то другой. В первом варианте, без тэга в URL-е он главную страницу выдает, а во втором варианте, с тэгом выдет контент поста. Вот где собака порылась! Хотя обы линка рабочие.

Точно, сейчас на других линках потестировал, без тэга в URL не работает!

**Comment by solodikov** [comment]
А как к вам уходят посты без тега? Я и на посты сейчас понажимал и на комментарии - все урлы тегуется. На вашей стороне нюанс?

**Comment by gropox** [comment]
Это же бот, он берет данные из блока и строит сам URL. Раньше работало без тэга, а сейас вот залипло. Дело поправимое.

**Comment by gropox** [comment]
Вот к примеру, старый пост, с прошлой недели. Для него без тэга превью работает

https://golos.io/@t3ran13/23-03-2017-gmt-luchshie-stati-po-mneniyu-avtorov-ili-reiting-statei-na-osnove-reputacii-po-topovym-tegam
