### ISSUE TITLE
View count scroll over bug: Eng Translation

### ISSUE THREAD

**Issue by TheDegenSloth** [GolosChain/tolstoy#340]
Currently running into this bug on the English translated site.
![76eb0ce96bddc68fc25a1d6748c752ee](https://cloud.githubusercontent.com/assets/26608413/24615993/b6d1df84-1844-11e7-9249-d14d91f77e1e.png)

The text should be different after my next pull request is put thru.
Tho there will still be the issue of it still showing this error.

**Comment by serejandmyself** [comment]
Closed with coming HF
