### ISSUE TITLE
Wallet bug: Eng translation

### ISSUE THREAD

**Issue by TheDegenSloth** [GolosChain/tolstoy#341]
Amount is show in brackets on the wallet page.
![6e5dfa8699eaef3d32739f72282bf382](https://cloud.githubusercontent.com/assets/26608413/24616294/87bcfc3c-1845-11e7-96c7-33bcbc605d15.png)

Not game breaking but still and issue.

**Comment by serejandmyself** [comment]
Closed with coming HF
