### ISSUE TITLE
Add translation format.

### ISSUE THREAD

**Issue by TheDegenSloth** [GolosChain/tolstoy#342]
These need to pull from translation files not the default site.
ГОЛОС 
СИЛА ГОЛОСА
ЗОЛОТОЙ

If i find anymore that need to be added ill update this.

**Comment by serejandmyself** [comment]
GOLOS
GOLOS POWER
GOLD BACKED GOLOS

**Comment by TheDegenSloth** [comment]
Yes those are the translations but the translation files don't have them and they can't be changed in them.

**Comment by TheDegenSloth** [comment]
I have updated the files in my pull request to include a format for currency translate.

**Comment by serejandmyself** [comment]
Closed with coming HF
