### ISSUE TITLE
Сумма перевода, проверка формата

### ISSUE THREAD

**Issue by gropox** [GolosChain/tolstoy#344]
При вводе суммы перевода (transfer) не через точку, а в немецком формате, через запятую "10,34" перевод принимается, но переводится только целая часть введенной суммы "10". Видимо сумма перевода напрямую парсится без проверки. 

Неплохо было бы проверять формат и сообщать ошибкой. Хотя-бы указывать, что вводить надо через точку, если язык интерфейса русский. 

У жителей Германии на цифровой клавиатуре с права запятая вместо точки и запятая вводится на автомате. 

https://golos.io/ru--vopros/@dicov/kak-to-krivo-rabotayut-perevody-mezhdu-polzovatelyami

**Comment by NickShtefan** [comment]
В процессе работы над таском выявил дополнительные баги верификации. 

1) Если ввести вместо целой части, букву, то выдает ошибку, пишет "Обязательно". Если после этого поставить точку, то ошибка пропадает, кнопка перевести становится активной 
2) Если в качестве значения указать сначала число, а сразу следом за ней букву, то ошибку не выводит, кнопка передать активна
3) Если в качестве значения указать сначала число, и через точку буквы, то ошибки тоже нет, кнопка передать активна
