### ISSUE TITLE
Wallet confusion.

### ISSUE THREAD

**Issue by TheDegenSloth** [GolosChain/tolstoy#347]
Wallet has permissions and password which most users would look for these under settings.

Permissions and password should be moved to the settings page.

**Comment by gropox** [comment]
@TheDegenSloth I would normally also say, passwords and keys should be placed under settings. But hiere is all different. In wallet are stored keys and passwords, not the money. The balance shown just for info. It more like card wallet where you hold a visa card and not the cash.

**Comment by TheDegenSloth** [comment]
Oh okay i just didn't get the reason behind is because as a developer i would normally put that stuff in settings.

**Comment by serejandmyself** [comment]
I dont see a point leaving this open right now. If you do you may re-open as you wish of course
