### ISSUE TITLE
Проблема с открытием постов и лентой

### ISSUE THREAD

**Issue by sanchomalyutin** [GolosChain/tolstoy#350]
При открытии поста
![bug1](http://i.imgur.com/pXzLyvA.png)
а в ленте пост выглядит так
![Ibug2](http://i.imgur.com/Nak346k.png)

**Comment by serejandmyself** [comment]
Любопытно, попробуй обновится, почистить браузер. Походе на локальную проблему

**Comment by gropox** [comment]
Да, могу подтвердить. Такие же проблемы иногда возникают. Кликаешь на пост, появляется такое окно с НЛО. Окошко закрываю, а в ленте показывает репост без названия и тоже "47 лет назад". Если полностью страницу перезагрузить, то все нормально становится. За последние пару дней раза три случилось.

**Comment by serejandmyself** [comment]
Решено, не должно появляться
