### ISSUE TITLE
Странности с wss://ws.golos.io

### ISSUE THREAD

**Issue by gropox** [GolosChain/tolstoy#352]
Привет,

написал я бота для лотереи, он раз в минуту опрашивает серверное время и последний блок вызывая get_dynamic_global_propoerties. Для этого используется wss://ws.golos.io. Вызов в большинстве случаев нормально работает, но иногда после переподключения по сокету начинает возвращать один и тот же блок и время.  По ощущениям балансер иногда перенаправляет подключение на рассинхронизированную ноду. 

Может быть такое? Может это как то связанно с другим Issue, с НЛО вместо текста?

**Comment by gropox** [comment]
Воспроизводится вот тут тоже 

http://golostools.ru/explorer/#method=get_dynamic_global_properties&params=[]

Если нажимать "refresh" (F5) в браузере, то иногда тоже выдает старый блок

```
{
  "id": 1,
  "result": {
    "id": 0,
    "head_block_number": 5037825,
    "head_block_id": "004cdf011658d1a1925436618a62dd747e6a0b8b",
    "time": "2017-04-11T15:29:03",
    "current_witness": "phenom",
```

**Comment by serejandmyself** [comment]
Все тоже самое. Должно быть решено
