### ISSUE TITLE
Изменить визулизацию прочитанных постов

### ISSUE THREAD

**Issue by gropox** [GolosChain/tolstoy#354]
https://golos.io/ru--obratnaya-svyazx/@tarimta/luchshee-vrag-khoroshego-narodnyi-referendum

Народ хочет изменить визуальное выделение прочитанных постов. Выделение серым действительно портит все впечатление от ленты. На многих сайтах серым выделяются посты с низкими оценками и невольно возникает такая же ассоциация, что посты либо отфлагованы либо с матом. Взять тот же habrahabr, там тоже комментарии с минусами блекнут в ленте.

Хотелось бы что то другое для отметки прочитанных постов. Может быть иконка сбоку того же глазика, серая - еще не прочитано, черная - прочитано.  Или просто наличие иконки означает, что прочитано.

**Comment by serejandmyself** [comment]
Так это то что все просили(!), мы это поэтому и сделали.... Есть отсыл, на то где "народу" то не нравится?

**Comment by serejandmyself** [comment]
https://github.com/GolosChain/tolstoy/issues/292

**Comment by gropox** [comment]
Да, ссылку я привел на обсуждение. В #292  issue никакого обсуждения нет, только предложение которое и было реализовано. С моей точки зрения и видимо с точки зрения некоторых других не очень удачное решение. 

С точки зрения юзабилити не контрастный текст, серый  текст обычно используется для задизейбленных  элементов.  Пример с habbrahabr я приводил. во многих программах используется жирный текст для непрочитанных сообщений, про читанный обычно выводится обычным шрифтом. Пример  outlook. Мне кажется такой вариант более предпочтителен. Или хотя бы иконка "глаз", та же как и в тексте поста для отображения количества просмотров.

**Comment by serejandmyself** [comment]
Ок, подумаем как поменять.

**Comment by vadbars** [comment]
В Голосе собрались люди разных категорий. Часть рассматривает его как соцсеть, как ленты новостей. Для них обесцвечивание прочитанного вполне логично (с глаз долой). Другая часть (поэты, женщины-рукодельницы, блогеры...) воспринимают Голос как набор персональных страничек (блогов). Им надо, чтобы в "их" блоге "было красиво". Думаю, многие не понимают, что обесцвечивание видят только они (и другие прочитавшие).
В общем, вынужден согласиться с предложением ropox. Просто дополнительный значок "прочитано" или визуальный элемент типа полоски. 
Но кардинально решить вопрос могут, наверное, скины - возможность для пользователей выбирать разные шаблоны оформления для своих блогов и публикаций (двигаемся в сторону LJ и других блогохостингов).

**Comment by serejandmyself** [comment]
Есть конкретные предложения?

**Comment by gropox** [comment]
Как я понимаю, многим не нравится серая картинка-иконка поста. можно для начала убрать grayscale у visited картинки.  И немного добавить яркости к текста a:visited. Я к примеру тут установил цвет текста в #555 вместо #999. Читано/нечитано хорошо различается (для меня по крайней мере, а я слепой) и лента выглядит не так блекло и нудно. 
 
![sample1](https://cloud.githubusercontent.com/assets/26039472/25070831/f2c7924a-22a8-11e7-9f53-66284555e585.png)

**Comment by serejandmyself** [comment]
Так до этого так и было. Были просьбы сделать более явную индикацию. Вы же понимаете что серый цвет виден только вам?

**Comment by gropox** [comment]
Что значит только мне? **Все** видят так **свою** ленту. В зависимости, что просмотрели. Люди стараются, выбирают изображение, это один их факторов привлечения внимания. А оно уродуется после клика. Неважно мой это пост или нет.

**Comment by serejandmyself** [comment]
Вам, это значит. Что серым видно только тот пост который просмотрели Вы. Каждый видит серым только те посты которые он просмотрел. Ждем еще предложений по реализации. Пока их нет, думаем как сделать

**Comment by gropox** [comment]
Думайте

Вот  еще ввариант. Глазик на картинках отмечающий просмотренные посты. Но мне самому как то не очень.

![sample1](https://cloud.githubusercontent.com/assets/26039472/25071118/b2faa9ca-22af-11e7-8ba9-bbafb9a228a0.png)
