### ISSUE TITLE
Пропадает цвет в превьюхах

### ISSUE THREAD

**Issue by litrbooh** [GolosChain/tolstoy#355]
Второй день замечаю, что цвет в превьюхах то есть, то нет.
![default](https://cloud.githubusercontent.com/assets/22373216/25073925/ae640e8e-22f9-11e7-943e-26b9f4442731.png)

Сижу с Лисы, версия 52.0.2

**Comment by serejandmyself** [comment]
>reference 292

**Comment by serejandmyself** [comment]
>reference #354
