### ISSUE TITLE
сборка ноды Голос

### ISSUE THREAD

**Issue by stanta** [GolosChain/tolstoy#358]
Пытался собрать ноду под Win7/Vagrant/Ubuntu 16.04
1. версия Boost в репозитории Убунты - 1.54, а требуется мин 1.57. Приходится отдельно собирать.
2. попытка сделать make  с Boost 1.60-1.64 приводит к ошибке: 
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libboost_system.a(error_code.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/libboost_system.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status

Попытка перекомпилировать Boost  с опцией  -fPIC ничего не поменяла.

# Golos.io

Before opening a new issue, please take a moment to review our [**community guidelines**](https://github.com/GolosChain/tolstoy/blob/master/.github/CONTRIBUTING.md) to make the contribution process easy and effective for everyone involved.

**Before opening a new issue, you may find an answer in already closed issues**:
https://github.com/GolosChain/tolstoy/issues?q=is%3Aissue+is%3Aclosed

## Issue Type

- [x] Bug (https://github.com/GolosChain/tolstoy/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [ ] Feature (https://github.com/GolosChain/tolstoy/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description

(Add images if possible)

# Versions

- Node/NPM:
- Browser:

**Comment by stanta** [comment]
?

**Comment by serejandmyself** [comment]
Просьба перенести в правильный репозиторий gitgub.com/goloschain/golos
