### ISSUE TITLE
Active key bug

### ISSUE THREAD

**Issue by TheDegenSloth** [GolosChain/tolstoy#359]
More times then not when i use my active key for anything i get logged out.

edit:
I think i found the problem, well when it happens.
On page load of new a refresh you're logged out instantly.

Currently using firefox on windows 10 it also happened on chrome as well.

**Comment by serejandmyself** [comment]
You are getting logged out after you use your active key?

**Comment by TheDegenSloth** [comment]
Yes, ive tried everything including choosing to stay logged in.

### You get logged out after a refresh of the page in these cases:
##### After submitting the active key for promotion
* On reload or going to a different page it logs me out.

##### After submitting the active key in internal market
* On reload or going to a different page it logs me out.
---

**Comment by BaroH4er** [comment]
Issues actual
