### ISSUE TITLE
Баг imgp.golos.io ?

### ISSUE THREAD

**Issue by vadbars** [GolosChain/tolstoy#360]
Возможно, баг в image proxy Голоса. 

С адреса http://imgp.golos.io/0x0/http://distrowatch.com/images/cgfjoewdlbc/rosa.png показывается неправильная картинка. Она отличается от исходника - http://distrowatch.com/images/cgfjoewdlbc/rosa.png

Замечено на разнице между тем, как пост https://golos.io/linux/@sxiii/reliz-rossiiskii-distributiv-rosa-linux-r9-vstrechaem смотрится в golos.io и в eSteem (там показывается правильная картинка).
@sxiii подтвердил глюк.

**Comment by serejandmyself** [comment]
Актуально? Вносили исправления

**Comment by vadbars** [comment]
Да, актуально по состоянию на 28 апреля 2017.

**Comment by pavelit** [comment]
Похоже что картинка на момент написания поста была именно такая которую положил в кэш наш прокси. Сейчас если перейти по этой ссылке https://imgp.golos.io/0x0/http://distrowatch.com/images/cgfjoewdlbc/rosa.png будет показываться старая картинка (т.е. из кэша). Если в посте немного изменить адрес, добавив например бесполезный параметр в url, то наш прокси пересчитает заново эту картинку и сложит в свой кэш. Вот пример https://imgp.golos.io/0x0/http://distrowatch.com/images/cgfjoewdlbc/rosa.png?0.
