### ISSUE TITLE
Старое лого при регистрации

### ISSUE THREAD

**Issue by sanchomalyutin** [GolosChain/tolstoy#362]
Местами осталось старое лого в процессе регистрации
![Logo](http://i.imgur.com/8QbdePl.png)

**Comment by serejandmyself** [comment]
Кэш / Куки полностью удалены? 90% вероятности что это закэшировано, так как этого лого нет на серверах у нас

**Comment by sanchomalyutin** [comment]
Кеширование исключено, т.к. регистрация выполнялась на стороннем и "чистом" компьютере.

**Comment by serejandmyself** [comment]
Стоп. Речь о процессе регистрации. Моя ошибка. Принял, вполне возможно
