### ISSUE TITLE
Сделать свой нотификатор 

### ISSUE THREAD

**Issue by solodikov** [GolosChain/tolstoy#367]
[По ссылке](https://goloschain.slack.com/archives/C3VA0ER6U/p1493966985553645) в нашем Слеке описывается как именно выявлена некорректность работы счётчика просмотров поста, с подтверждающими скриншотами.

Edit: The final solution is not to debug the current lame side-service, but to embed the notifications into the system itself.

**Comment by serejandmyself** [comment]
Для этого есть свой репозиторий

**Comment by Nemo1369** [comment]
@serejandmyself Initial issue purpose is obviously wrong, but the planned feature needs own issue.

**Comment by jevgenika** [comment]
https://github.com/goloschain/tolstoy/issues/428 дубликат
