### ISSUE TITLE
Закрепленные посты в своем блоге 

### ISSUE THREAD

**Issue by serejandmyself** [GolosChain/tolstoy#371]

**Comment by jevgenika** [comment]
- [ ] переименовать закладку блог в посты
- [ ] в профиле пользователя в закладке блог (посты) отображать мин 3 максимум 5 закрепленных постов этого автора
- [ ] добавить графическое отметки закрепленным постам
- [ ] в настройках поста-дать возможность закрепить пост
- [ ] создать страницу редактирования закрепленных постов
- [ ] в настройках находим и отмечать пост по ссылке
- [ ] в настройках вводим название поста в поле поискам по постам этого автора

**Comment by jevgenika** [comment]
- [ ] пользователь должен иметь в настройках право как открепить так и открепить пост
- [ ] кнопку закрепить пост с иконкой pin -булавкой поставить рядом с кнопкой редактировать пост на странице пост 
![image](https://user-images.githubusercontent.com/30616421/34211931-525cee40-e5a3-11e7-8360-34cdb3b4a3d5.png)
- [ ] внедрить всплывающее окно уточнение-закреплять ли пост
![image](https://user-images.githubusercontent.com/30616421/34212498-1eb87206-e5a5-11e7-90bd-12d7b34f931c.png)
- [ ] откреплять пост там же редактируем пост 
![image](https://user-images.githubusercontent.com/30616421/34212395-dab8cb96-e5a4-11e7-83c9-bad772f639ae.png)
- [ ] экран уточнения при откреплении пост
![image](https://user-images.githubusercontent.com/30616421/34212551-4c9cd3d8-e5a5-11e7-8405-b632c1398a2a.png)

**Comment by sualex** [comment]
Дополнения :

- Закреплять можно до 3-х постов в блоге ЛЮБОГО автора, в том числе и в своем собственном;
- Структура закрепленных постов для каждого блога хранится локально для каждого браузера (как настройки профиля). При очистке LocalStorage все закрепленные посты теряются.

**Comment by jevgenika** [comment]
- [ ] запиненные посты должны быть видны всем пользователям. синхронизировать состояние закладок для всех пользователей.
- [ ] активная кнопка пина, должна заливаться цветом

**Comment by Bacher** [comment]
Вылили текущую версию на sandbox.

Есть один вопрос по тексту когда пользователь пытается закрепить больше чем 5 постов:
![image](https://user-images.githubusercontent.com/2598671/44474493-7752da80-a63b-11e8-9f92-3d27b8e67b7e.png)

**Comment by jevgenika** [comment]
@Bacher текст:
Максимальное количество закрепленных постов в своем блоге -5
Если вы хотите изменить свой список закрепленных постов, открепите один пост, чтобы закрепить другой.

**Comment by Bacher** [comment]
Мне кажется слово "свой", можно убрать, так как эта кнопка активна только в своём блоге.

**Comment by jevgenika** [comment]
@Bacher ок

**Comment by Bacher** [comment]
Текст обновил.

**Comment by daryasattarova** [comment]
Тестирование завершено. Ошибок нет.
