### ISSUE TITLE
Добавить в настройки профиля пол 

### ISSUE THREAD

**Issue by serejandmyself** [GolosChain/tolstoy#372]
При указании пола - выставлять значок рядом с ником?

**Comment by b1acksun** [comment]
В зависимости от выбраного пола добавить склонение в локали ru-Ru, ua

**Comment by NickShtefan** [comment]
#507 Реализовано

**Comment by serejandmyself** [comment]
А какой значок будет?

**Comment by NickShtefan** [comment]
![image](https://user-images.githubusercontent.com/6249597/32345506-77bdaefc-c01b-11e7-93ba-34a8044e80a4.png)

**Comment by serejandmyself** [comment]
Ок
