### ISSUE TITLE
два одинаковых тега в топе

### ISSUE THREAD

**Issue by litrbooh** [GolosChain/tolstoy#375]
![default](https://cloud.githubusercontent.com/assets/22373216/26344847/b260b3f8-3fa9-11e7-9da8-4ad4c1f97cf0.png)

**Comment by litrbooh** [comment]
![default](https://cloud.githubusercontent.com/assets/22373216/26445942/b6d2b3d0-414a-11e7-8f3a-841b11e0bd15.png)

**Comment by Nemo1369** [comment]
@litrbooh Проблема известна. Относится к блокчейну.
