### ISSUE TITLE
Поправить надпись "сохранено в черновик" в мобильной версии сайта

### ISSUE THREAD

**Issue by litrbooh** [GolosChain/tolstoy#380]
Когда пишешь коммент в мобильной версии, клава открыта и нижняя граница экрана попадает в район набора текста,  там постоянно маячит "сохранено в черновик". Периодически не видно, что набираю.

Предлагаю время от последнего нажатия до высветки  "сохранено в черновик" увеличить до 3-5 секунд, сейчас по ощущениям 0,5-1сек.

**Comment by BaroH4er** [comment]
Исправлено. Ошибок нет.
