### ISSUE TITLE
Unexpected error creating new password

### ISSUE THREAD

**Issue by gitbase1** [GolosChain/tolstoy#381]
# Golos.io

Getting an error trying to update my password from a steemit dropshare account.  Since I can't log in with the original password in the UI, I need to update my password.  This error is poping up on the model when confirming. 

<img width="586" alt="screen shot 2017-06-05 at 2 09 52 am" src="https://cloud.githubusercontent.com/assets/25875309/26772551/2cf48812-4994-11e7-9fa6-61b3f3df0b4a.png">

**Comment by pavelit** [comment]
Close #450
