### ISSUE TITLE
Отдельная лента "Поделился"

### ISSUE THREAD

**Issue by vadbars** [GolosChain/tolstoy#382]
Предлагаю вынести все реблоги (репосты) в отдельную ленту. 
Сейчас они зрительно почти не отличаются от авторских постов, что затрудняет чтение блогов. 

Лента "Поделился" - по смыслу практически "закладки" или "избранное", появления которых на Голосе многие ждут.

**Comment by vadbars** [comment]
Либо фильтр "Показывать только посты", как в goldvoice.club

**Comment by vadbars** [comment]
Пост с аналогичными пожеланиями https://golos.io/ru--golos/@aurus/obrashenie-k-komande-golosa

**Comment by t3ran13** [comment]
@vadbars
В голдвойс проблема решена

**Comment by jevgenika** [comment]
- [ ] в профиле выделить закладку -поделился
- [ ] выявить дубликаты репостов
- [ ] отображать дубликат единажды в ленте прописав несколько авторов репоста

**Comment by NickShtefan** [comment]
сделать дропдаун на кнопку лента и там давать выбор из "Только посты", "посты и репосты", "Только репосты"

**Comment by NickShtefan** [comment]
![image](https://user-images.githubusercontent.com/6249597/32451550-215c7f7e-c328-11e7-8c6c-5483bbbc80d9.png)
Например вот так.
