### ISSUE TITLE
Ошибки в отображении истории кураторских наград

### ISSUE THREAD

**Issue by vadbars** [GolosChain/tolstoy#383]
На странице истории кураторских наград иногда происходит смещение списка. Две строки сливаются в одну. Баг?

![kriptoinvestor-pochemu-stoit-stat-uchastnikom-investicionnykh-fondov-takikh-kak-satoshi-pai](https://cloud.githubusercontent.com/assets/115528/26779948/f358ce16-4a00-11e7-9827-cab63bdef666.jpg)
![author-rewards](https://cloud.githubusercontent.com/assets/115528/26786071/bb123772-4a1e-11e7-933c-ef819c14d6e4.jpg)

**Comment by t3ran13** [comment]
тоже самое для авторских
фиксите авторские и кураторские вместе
![2017-10-23_10-36-15](https://user-images.githubusercontent.com/8971041/31877244-69ef7b06-b7de-11e7-8257-188d8936e5b7.png)
