### ISSUE TITLE
Кнопка [Отблагодарить] автора

### ISSUE THREAD

**Issue by gropox** [GolosChain/tolstoy#384]
Просьба аналогично кнопкам [Подписаться] и [Блокировать] добавить кнопку [Отблагодарить]. В профиле пользователя и при просмотре поста, во всплывающем окошке. 

По клику на кнопку должно открыться окно для перевода (transfer).

Поле "к" (to) должно быть заполнено именем пользователя. Причем если кнопка была нажата при просмотре поста, то поле "заметка" (memo) так же должна быть заполнена permlink поста. 

Сейчас если надо перевести монеты определенному автору за работу, или проспонсировать понравившийся текст, приходится либо запоминать ник автора и вводить его вручную, либо копировать имя из ссылки, что не очень удобно.

**Comment by vadbars** [comment]
Поддерживаю. Логичнее даже не добавлять кнопку [Отблагодарить] в выпадающее меню пользователя, а поместить рядом с кнопкой [Продвинуть].
В busy.org это реализовано ссылкой ["Tip the author"](https://busy.org/transfer?to=ontofractal&amount=50.000&currency=STEEM&memo=Thank%20you%20for%20your%20post:%20Poloniex%20Trollbox%20Trending%20News%20and%20Tokens%20Weekend%20Report%20for%20June%203-4)

**Comment by sualex** [comment]
Реализовано полностью. Tag 17.217__SANDBOX.
@vadbars @gropox просьба функционально протестировать и дать фидбек для закрытия issue

**Comment by vadbars** [comment]
В тестнете еще нет, как я понял.

**Comment by jevgenika** [comment]
- [ ] отцентровать текст и расположение кнопок
![image](https://user-images.githubusercontent.com/30616421/34165413-e8b56be8-e4e4-11e7-832e-81a77a365048.png)
- [ ] заменить заглавный текст -"передать пользователю" на "отблагодарить пользователя"
- [ ] -заменить текст "отправить средства на другой аккаунт- "отправить средства на счет другого пользователя"

- [ ] второй экран-заменить текст, перенести запятую
пожалуйста, авторизуйтесь для выполнения операции.
![image](https://user-images.githubusercontent.com/30616421/34165396-db4950be-e4e4-11e7-8e7e-e73fa94fc15c.png)

- [ ] 3 окно, не прошел мастер ключ
- [ ]  убрать слово пароль
![image](https://user-images.githubusercontent.com/30616421/34165682-9e5c99e4-e4e5-11e7-8c46-a9425405ceb7.png)

- [ ] убрать дополнительное поле под окном
![image](https://user-images.githubusercontent.com/30616421/34165971-5b908aca-e4e6-11e7-8137-6cadec49bb78.png)

- [ ] в течении 40 минут трансзакция так и не прошла @NickShtefan надо проверить трансфер
![image](https://user-images.githubusercontent.com/30616421/34166075-a9be8990-e4e6-11e7-81f9-4577bbb30208.png)

- [ ] отцентровать иконку загрузки
- [ ] добавить текст "Операция выполняется. Передача средств может занять некоторое время"

**Comment by b1acksun** [comment]
Данная операция вызывает стандартное окно для передачи средств.

**Comment by jevgenika** [comment]
- [ ] заменить текст "отправить средства на другой аккаунт- "отправить средства на другой счет"

- [ ] на последнем экране добавить текст "Операция выполняется. Передача средств может занять некоторое время"

**Comment by NickShtefan** [comment]
поле мемо по умолчанию надо заменить на
%username% отблагодарил вас за пост %ссылка на пост%

**Comment by jevgenika** [comment]
![image](https://user-images.githubusercontent.com/30616421/34200446-caa6ec4a-e579-11e7-9dfb-a69a4bd43ade.png)
- [ ] поправить нотификацию
 "username" отблагодарил вас за пост (гипперссылка на пост)

**Comment by alex-firsov** [comment]
Лишний пробел, надо поправить.
<img width="356" alt="2017-12-21 12 44 37" src="https://user-images.githubusercontent.com/33282977/34252595-fb756dd2-e64c-11e7-80ee-5e5c98ec168d.png">

**Comment by jevgenika** [comment]
- [ ] Добавить уведомление о статусе трасфера -во все стандарные окна трансфера

На экране перевода с одного счета на другой после загрузки - выводить текст -
- уведомление о позитивном переводе: "Ваша операция успешно выполнена"
- текст при негативном переводе "Произошла ошибка, операция не выполнена. Попробуйте еще раз.

**Comment by jevgenika** [comment]
перенесено в https://github.com/GolosChain/tolstoy/issues/564

**Comment by vadbars** [comment]
Мне кажется, в форме Отблагодарить надо оставить редактируемое поле Заметка (memo). Отправитель сможет тогда указать, за что благодарит Получателя. При желании этим можно будет также пользоваться как аналогом личных сообщений (с переводом минимальной суммы 0,01 токен).

**Comment by jevgenika** [comment]
- [ ] дать возможность редактировать поле мемо  оставив по умолчанию мемо %username% отблагодарил вас за пост %ссылка на пост%

**Comment by sualex** [comment]
Сделано. Тэг 17.247.sandbox

**Comment by jevgenika** [comment]
- [ ] добавить серый текст-подсказку в поле мемо  "Вы можете оставить комментарий к переводу", по умолчанию мемо %username% отблагодарил вас за пост %ссылка на пост%

**Comment by BaroH4er** [comment]
Тест завершен. [Отчет + чек-лист.](https://docs.google.com/spreadsheets/d/1pFRoTBwEf7nT8f1j1aHI68FrAVo0LeJmrcs2HLgjwbQ/edit?usp=sharing) Найденные ошибки локализации не относятся конкретно к этому таску. Баг-репорт по локализации будет опубликован в [Issues-594 ](https://github.com/GolosChain/tolstoy/issues/594) .
