### ISSUE TITLE
QR-коды во вкладке разрешения

### ISSUE THREAD

**Issue by pmartynov** [GolosChain/tolstoy#391]
Недавно на steemit.com добавили полезную фичу - чтение ключа сканированием QR-кода. Хотелось бы видеть тоже самое на golos.io.

Вот как это выглядит:

![](https://imgur.com/JBZuXq2.png)

Вот почему это полезно:

https://steemit.com/steem/@noisy2/what-if-user-would-be-able-to-import-key-from-permission-tab-with-user-friendly-qr-codes

**Comment by b1acksun** [comment]
Implemented in HF

**Comment by pmartynov** [comment]
This is a front-end feature, no need to HF.

**Comment by serejandmyself** [comment]
its already mplememnted.... a long while ago

**Comment by pmartynov** [comment]
Indeed, thanks!
