### ISSUE TITLE
[bug] Не грузятся страницы

### ISSUE THREAD

**Issue by gropox** [GolosChain/tolstoy#392]
В последнее время довольно часто не грузятся страницы со списками. К примеру если кликнуть в меню [Ответы] ([Комментарии] или [Блог], а так же кошелек и тд). Показывается белая страница под заголовком, на ней вращающийся индикатор загрузки. Ничего больше не происходит. Если опять кликнуть по кнопке [Ответы] или F5 для загрузки страницы, то страница мгновенно грузится. Воспроизводится в Chrome и Firefox. Судя по всему я не одинок в этом. В последнее время уж очень часто случается и нервирует. 

![image](https://user-images.githubusercontent.com/26039472/27405577-5c35f11a-56d2-11e7-9bd6-ed05d65feb4a.png)

![image](https://user-images.githubusercontent.com/26039472/27405686-df5e39da-56d2-11e7-931c-d2026d8cd443.png)

**Comment by pavelit** [comment]
Closed: https://github.com/GolosChain/tolstoy/commit/fb9efbf3206b187ad95628ad31450bf8667b5558
