### ISSUE TITLE
Увеличить размер снипета (превью) поста в ленте до 4 - 5 строк

### ISSUE THREAD

**Issue by serejandmyself** [GolosChain/tolstoy#395]

**Comment by NickShtefan** [comment]
Увеличил количество строк в сниппете, вот что получилось.
![image](https://user-images.githubusercontent.com/6249597/32338633-6963b988-c006-11e7-94cd-f012a0e985c1.png)

1) Картинка теперь плохо вписывается, и выглядит отстранено от поста. 
2) Если посмотреть на пост со статистикой (Доброотчет), то видно, что текст едва ли можно назвать осмысленным, поскольку он поясняет картинки, которые не попадают в данное превью.

**Comment by serejandmyself** [comment]
Да, выглядит ужасно )
Давайте сделаем 2 - 3 строки. Картинки можно подогнать

**Comment by NickShtefan** [comment]
![image](https://user-images.githubusercontent.com/6249597/32374928-cab0d766-c0b0-11e7-9df9-2332155ff570.png)

3 строки, без подгона картинок

**Comment by serejandmyself** [comment]
А если подогнать?

**Comment by NickShtefan** [comment]
Если подогнать, то будет так
![image](https://user-images.githubusercontent.com/6249597/32442291-f3d07bd0-c30b-11e7-9935-97f6ab1b528c.png)

**Comment by NickShtefan** [comment]
Вот еще вариант, когда картинки нет, и когда нет текста
![image](https://user-images.githubusercontent.com/6249597/32442468-9a6b5000-c30c-11e7-9f17-ba613bca8ff0.png)

**Comment by serejandmyself** [comment]
Было бы хорошо чтобы откоментили все. Либо увидеть это на песочнице

**Comment by NickShtefan** [comment]
Можно посмотреть в песочнице

**Comment by 21xhipster** [comment]
Раскройте секрет где песочница для отстающих

**Comment by serejandmyself** [comment]
http://sandbox.golos.io/

**Comment by NickShtefan** [comment]
Поскольку за полтора месяца никакого фитбэка не последовало, закрываю таск, изменения отменены. Предлагаю вернуться к нему во время редизайна сайта.
