### ISSUE TITLE
Внедрить новые фильтры под вкладку "фильтр" возле теги и топики

### ISSUE THREAD

**Issue by serejandmyself** [GolosChain/tolstoy#396]
Сделать 3 колонки:
Теги и топики 
Популярные авторы
Лучшее по репутации

Каждую колонку разделить на: "За сутки" "За неделю" "За все время"

**Comment by jevgenika** [comment]
добавить счетчик для авторизированный пользователей
по подсчету добавления постов на избранные теги
![image](https://user-images.githubusercontent.com/30616421/31656373-b37ddfa4-b32b-11e7-8306-8e13b6a4c64b.png)
