### ISSUE TITLE
Внедрить бейджики / значки за достижения 

### ISSUE THREAD

**Issue by serejandmyself** [GolosChain/tolstoy#397]

**Comment by litrbooh** [comment]
А вы будете как-то с голосбордом объединяться, или полностью свой делать?

**Comment by serejandmyself** [comment]
Наверное объединяться

**Comment by jevgenika** [comment]
https://docs.google.com/document/d/1QEwhkpnDrl8PpEgDqRMO-Qf5ETct4hSiKIq7Zz2a7A8/edit#
