### ISSUE TITLE
Ошибки после обновления golos.io

### ISSUE THREAD

**Issue by litrbooh** [GolosChain/tolstoy#398]
1) В своем блоге видно только последние 20 постов
2) При выборе валюты в Настройках не активируется кнопка обновить - в результате не сохраняется.
3) Я не понял как подгружать картинку с устройства
![default](https://user-images.githubusercontent.com/22373216/28116720-0d208198-6713-11e7-9a88-158ec708d849.png)

**Comment by pavelit** [comment]
1. Поправим
2. Нет необходимости обновлять. Переход на другую валюту осуществляется моментально, как и язык интерфейса
3. Необходимо нажать на ссылку "выбрав"
<img width="321" alt="choose" src="https://user-images.githubusercontent.com/25533641/28116945-fa36b650-6713-11e7-9d3b-4fb6769d1dc9.png">

**Comment by litrbooh** [comment]
> Необходимо нажать на ссылку "выбрав"
Не знаю, сначала да - у меня изменилось. Но когда опять зашел через час опять были баксы.

>Необходимо нажать на ссылку "выбрав"
Как такого добиться на десктопе? Не вижу.

**Comment by pavelit** [comment]
> Не знаю, сначала да - у меня изменилось. Но когда опять зашел через час опять были баксы.

Выясним, спасибо!

**Comment by litrbooh** [comment]
> Необходимо отключить wysiwyg редактор.

А можно сделать и в редакторе эту функцию?

**Comment by pavelit** [comment]
> А можно сделать и в редакторе эту функцию?

Конечно!

**Comment by serejandmyself** [comment]
@pavelit возможно стоит добавить кнопку обновить для всех "штук" в настройках. Есть смысл? это тормозит что либо?

**Comment by pavelit** [comment]
> возможно стоит добавить кнопку обновить для всех "штук" в настройках. Есть смысл? это тормозит что либо?

Добавить можно, но не имеет смысла, добавить можно всплывающий нотификатор, мол "успешно сохранено". Черное окошко такое

**Comment by pavelit** [comment]
> А можно сделать и в редакторе эту функцию?

Как я сказал выше, сделать можно, по ресурсам и времени пока сложно оценить насколько это затянется. Насколько это сверх необходимо - тоже для меня пока вопрос.
