### ISSUE TITLE
Как добавить в фильтр мало популярный тэг?

### ISSUE THREAD

**Issue by litrbooh** [GolosChain/tolstoy#399]
Плюсы у тегов в ленте можно поставить, но добавить руками у меня не выходит. Менюшка не разворачивается. Я уже не помню, но вроде бы туда можно было раньше руками вбивать тег.
![default](https://user-images.githubusercontent.com/22373216/28159492-c8e4f9ec-67c5-11e7-96eb-03ce9e8c5162.png)

**Comment by pavelit** [comment]
> Я уже не помню, но вроде бы туда можно было раньше руками вбивать тег.

Ранее такого не было. Но сама идея интересная. Фактически на развороте видим поле для ввода тега, которые можно добавить в свой фильтр. А теперь вопрос, а если тега нет в принципе в цепочке, то что тогда? Очевидно что пустота. Может тогда это не очень актуально. Ведь теги - мы видим при просмотре постов. Значит надо добавить в окне просмотра поста в местах расположения тегов те самы +/- ?

**Comment by serejandmyself** [comment]
Убрал в #330

**Comment by litrbooh** [comment]
> Может тогда это не очень актуально. Ведь теги - мы видим при просмотре постов. Значит надо добавить в окне просмотра поста в местах расположения тегов те самы +/- ?

Не, проще сделать место для ввода тега. Просто если я хочу найти какой-то пост или группу постов по тегу, я хочу в бить тег, а не искать сначала пост на эту тему, а потом тыкать там плюс :)
