### ISSUE TITLE
Огрехи перевода, текст

### ISSUE THREAD

**Issue by gropox** [GolosChain/tolstoy#400]
* Посты с отказом от выплат. Раньше выглядело более явно. Почему суммы выплат не нулевые? Как то запутывает.  Если так и задумано, то пускай. "Payouts declined" не переведено. 

![image](https://user-images.githubusercontent.com/26039472/28251378-067b0f18-6a7c-11e7-94e9-ffd149f32c78.png)

* Между текстом и суммой в истории трансферов отсутствует пробел

![image](https://user-images.githubusercontent.com/26039472/28251390-745e99c8-6a7c-11e7-8391-5909a6347151.png)

![image](https://user-images.githubusercontent.com/26039472/28251393-8ebabcde-6a7c-11e7-9720-e4fe4da49907.png)

* В истории трансферов. Неправильное склонение в тексте перевода. Должно быть "Отправлено" или "Передано" вместо "Передать"

![image](https://user-images.githubusercontent.com/26039472/28251405-cf39967c-6a7c-11e7-82a6-95c8e6bb64a8.png)

**Comment by b1acksun** [comment]
https://github.com/GolosChain/tolstoy/commit/d5e0369de155b90f1f1506b697f3e11e9b4101df
