### ISSUE TITLE
Ошибочный перевод в кошельке - "Эта заметка является приватной"

### ISSUE THREAD

**Issue by vikxx** [GolosChain/tolstoy#401]
Описание дает пользователю ложное представление о приватности memo 
![memo](https://user-images.githubusercontent.com/26347159/28497706-e629d9be-6f95-11e7-8341-606b4177c0e8.png)

**Comment by b1acksun** [comment]
fix in https://github.com/GolosChain/tolstoy/commit/194017425380b124e30ab8a51d459178b828d14d
