### ISSUE TITLE
Улучшить процесс регистрации

### ISSUE THREAD

**Issue by serejandmyself** [GolosChain/tolstoy#402]
1. [x] Добавить подсказки

2. [x] Добавить ответную смс после отправки

3. [x] Проверить на мультиязычность

4. [x] Добавить текст о том "почему смска платная" 

5. [x] Поменять ввод формата номера - пусть человек сам определит страну + проверка на реальность

**Comment by jevgenika** [comment]
- [ ] использовать короткий четырехзначный номер телефона 

- [ ] добавить мультиязычность и определение языка тексту смс подтверждения номера

- [ ] выделить текст-отправить смс

- [ ] перенести текст https://docs.google.com/document/d/1Hzj4dAE0lcs-J95GpK68GQV0VU01NsyHfWQxmk3upDw/edit

- [ ] добавить текст над кнопкой обновить- После получения смс о подтверждения вашего номера обновите страницу регистрации

- [ ] убрать текст про изименеение номера убрать текст

- [ ] Кнопку ”Зачем отправлять смс?“ переименовать в “Подробнее зачем отправлять смс”

- [ ] Поправить раскрывающийся текст -Подробнее зачем отправлять смс https://docs.google.com/document/d/1Hzj4dAE0lcs-J95GpK68GQV0VU01NsyHfWQxmk3upDw/edit

- [ ] определить регион и добавить поиск по региональным мобильным операторам,
показать стоимость исходящего сообщения

- [ ] на этапе регистрации выделить текст и расположить по левому краю

**Comment by serejandmyself** [comment]
[ ] автоматически транслировать имя акаунта на латиницу
[ ] не давать юзеру регистрироваться пока грузится бандл
[ ] авто обновлять страницу

**Comment by jevgenika** [comment]
1. > Использование коротких номеров невозможно до тех пор пока мы не передадим реквизиты юридического лица компании оператору смс и других мобильных услуг.

Ясно

2. >  А если владелец телефона имеет 10 разных операторов по всему миру, то как поступать?

Можем дать ввозможность ввести своего оператора? по поиску определить

3. > Кнопку редактировать и сам текст нельзя убирать

Надо скоректировать текст, сейчас он непонятный.
 
4. > определить регион и добавить поиск по региональным мобильным операторам, показать стоимость исходящего сообщения.
> Это очень непростая задача.

Работа объемная. Но она решает проблему удержания пользователя.
Можно отложить пункты 1,2 ,4.

**Comment by jevgenika** [comment]
внедрить короткий номер на РУ

**Comment by Chiliec** [comment]
Ребят, с двух телефонов пытались зарегистрироваться, не работает :(
<img width="1265" alt="screen shot 2017-09-14 at 15 45 38" src="https://user-images.githubusercontent.com/982358/30425925-2b1634d0-9964-11e7-9bbe-d6f4f58d6a33.png">

**Comment by jevgenika** [comment]
упростить ситему регистрации
1. При нажатии на кнопку "Регистрация", пользователю всплывает окно с просьбой указать его номер моб.телефона. 
2. После указания номера, окно становится белым , текст на экране -Cпасибо. Спасибо в течении нескольки минут на ваш телефон придет смс с кодом. Для регистрации на Golos.io нужно ответить на смс, выслать, присланный вам код в ответ. Внизу по серединке крутится вечное колесо ожидания.  
3. ЮЗЕРУ падает СМС следующего содержания:
 "GOLOS.io, send me back this CODE 4567".  
- [ ] (уточнить  по поводу распоснования страны отправителя-спс отправлять идентифицируя тсранц и подставлять соответсвенный перевод текста смс )
3. Как только пользователь отправил обратное смс и система это увидела. На экране появляется текст -Спасибо за присланное спс. 
4. происходит переход на регистрацию в чейне.

**Comment by jevgenika** [comment]
- [ ] добавить текст объясняющий пользователю как важно сохранение пароля (ваш ключ в мир блокчейна)
- [ ] сделать возможность сохранить ключ-пароль локально в файл ( пример Wallet model в BitShares)
- [ ] дать возможно распечатать ключ-пароль, 
- [ ] дать возможность добавить ключ-пароля в менеджер паролей

**Comment by jevgenika** [comment]
@pav на страницу регистрации надо добавить сообщения: 
- [ ] не пришло сообщение с подтверждением? проверьте правильно ли отправили код.
- [ ] не пришло сообщение? отправить еще раз -кнопка отправить код еще раз 
- [ ] не удалось зарегистрироваться-пишите в тех поддержку support@golos.io

**Comment by jevgenika** [comment]
- [ ] Найти решение ошибоки Conlict или Unexpected token in JSON.

**Comment by jevgenika** [comment]
- [ ] Заменить текст «В ожидании поступления смс с кодом…» Отправьте код ХХХХ на номер ЛЛЛЛЛЛЛЛЛ для подтверждения вашего номера телефона.

**Comment by jevgenika** [comment]
- [ ] Показывать второй блок регистрации после подтверждения смс, до этого текст скрывать.
- [ ] не понятно какой пароль вводить повторно-сгенерированные -тогда надо так и писать
скопируйте и введите повторно сгенерированный пароль
- [ ] Кнопка регистрация -заменить на Создать Аккаунт
- [ ] добавить поле ввода почты

**Comment by jevgenika** [comment]
- [ ] регистрировать пользователя без подтверждения почты
- [ ] поле ввода почты обязательное

**Comment by alex-firsov** [comment]
Поменять текст

«В ожидании поступления СМС сообщения с кодом подтверждения 1056 с указанного Вами номера телефона на наш номер верификации реальных пользователей +46 (769) 43-88-07. Вы можете указать другой номер телефона. Указать другой номер.»

на

«Отправьте код ХХХХ на номер ЛЛЛЛЛЛЛЛЛ для подтверждения вашего номера телефона. Если вы ошиблись во время ввода своего номера телефона, вы можете ввести его заново.»

**Comment by pavelit** [comment]
- [ ] 1. Регистрировать пользователя без подтверждения почты;
- [ ] (отклонено) 2. Поле ввода почты обязательное;
- [ ] (отклонено) 3. Показывать второй блок регистрации после подтверждения смс, до этого текст скрывать;
- [ ] 4. Не понятно какой пароль вводить повторно-сгенерированные -тогда надо так и писать
скопируйте и введите повторно сгенерированный пароль;
- [ ] (отклонено) 5. Кнопка регистрация -заменить на Создать Аккаунт;
- [ ] 6. Добавить поле ввода почты;
- [ ] 7. Заменить текст «В ожидании поступления смс с кодом…» Отправьте код ХХХХ на номер ЛЛЛЛЛЛЛЛЛ для подтверждения вашего номера телефона.;
- [ ] 8. Найти решение ошибок Conlict или Unexpected token in JSON;
- [ ] 9. Добавить текст объясняющий пользователю как важно сохранение пароля (ваш ключ в мир блокчейна);
- [ ] 10. Сделать возможность сохранить ключ-пароль локально в файл (пример Wallet model в BitShares);
- [ ] 11. Дать возможно распечатать ключ-пароль;
- [ ] (отклонено) 12. Дать возможность добавить ключ-пароля в менеджер паролей;
- [ ] 13. Автоматически транслировать имя акаунта на латиницу;
- [ ] 14. Не давать юзеру регистрироваться пока грузится бандл;
- [ ] 15. Авто обновлять страницу.

**Comment by pavelit** [comment]
Перенес в #562

**Comment by pavelit** [comment]
Перенес в #562.
