### ISSUE TITLE
Что делают комментарии к переводам в истории награды за курирование?

### ISSUE THREAD

**Issue by litrbooh** [GolosChain/tolstoy#403]
![default](https://user-images.githubusercontent.com/22373216/28993237-482f8e00-79ba-11e7-9870-71db600f0c7a.png)

**Comment by serejandmyself** [comment]
Косячок... Но скорее это к @vik

**Comment by litrbooh** [comment]
Слушайте, я в гитхабе не силен. Но почему тикет закрыт и куда-то в To do записан? Ничего же не изменилось.
![default](https://user-images.githubusercontent.com/22373216/30799431-7e35b008-a1e5-11e7-81c2-30405775db72.png)

![default](https://user-images.githubusercontent.com/22373216/30799451-8fb46ee6-a1e5-11e7-96c5-d1bbac8c6e97.png)

**Comment by litrbooh** [comment]
Видимо, надо было зачистить браузер. После почистки кэша проблема не появлялась. Извиняюсь за беспокойство.

**Comment by litrbooh** [comment]
Неа. После очистки кеша или ctrl+F5 становится нормально, а потом опять. Браузер Лиса 55.0.3 (32-бит).

**Comment by litrbooh** [comment]
В опере тоже самое, @b1acksun 
![default](https://user-images.githubusercontent.com/22373216/31406571-93a4f742-ae0a-11e7-997e-6cbe5e4cbadb.png)

**Comment by litrbooh** [comment]
@NickShtefan @jevgenika 
бага всё ещё на месте
![default](https://user-images.githubusercontent.com/22373216/39173990-01030c5a-47af-11e8-8650-f9834253d6cb.png)

**Comment by NickShtefan** [comment]
@litrbooh не получается воспроизвести данный баг, необходимо пошаговое описание, как возникает данная ошибка.

**Comment by BaroH4er** [comment]
Невозможно воспроизвести ошибку, протестировано в Chrome 67.0/Opera 53.0/FireFox 60.0/IE 11.48.
Если будут указаны шаги воспроизведения, возможно получится отследить баг.

**Comment by litrbooh** [comment]
Ура! Всего лишь год прошел.
