### ISSUE TITLE
Добавить дудлы (гугл) на основе тегов и лайков юзера 

### ISSUE THREAD

**Issue by serejandmyself** [GolosChain/tolstoy#408]
Дудлы – это необычные творческие версии логотипа главной страницы Google. Они появляются в честь праздников, годовщин великих событий или юбилеев знаменитых художников, первооткрывателей и ученых, изменивших ход истории.

Все дудлы - https://www.google.com/doodles

История дудлов - https://www.google.ru/doodle4google/history.html

Задача - на основе пролайканых юзером тегов, выдавать ему дудлы на фронтенд

**Comment by pavelit** [comment]
> Задача - на основе пролайканых юзером тегов, выдавать ему дудлы на фронтенд

Есть ли более подробное понимание как бы это хотелось видеть на фронте?

**Comment by 21xhipster** [comment]
Ага. Предлагаю попробовать использовать для дудла первую картинку от трендинг поста по хештэгу #гудл (от голосдудл) в том случае если она удовлетворяет нашим требованиям, т.е. она svg
