### ISSUE TITLE
Поддержка html-якорей

### ISSUE THREAD

**Issue by lokkie12** [GolosChain/tolstoy#409]
Внутристраничные якоря вида <a href="#...">не работают. А было бы удобно давать ссылки не на целые простыни текста, - пока получатель найдет, к чему его отсылали, поседеет, - а на конкретный кусок.

**Comment by sualex** [comment]
@lokkie12  - просьба максимально конкретизировать таск. "Внутристраничные якоря вида не работают" не совсем понятно. Распишите плз необходимый функционал подробно для качественной реализации. С уважением.

**Comment by NickShtefan** [comment]
Требуется дополнительное исследование перед реализацией таска.

**Comment by lokkie12** [comment]
Возможность расставлять в тексте самые обычные html-якоря (http://htmlbook.ru/samhtml/yakorya)

На данный момент ссылки вида <a href="#idi-suda-pls"> не работают.

**Comment by BaroH4er** [comment]
Тестирование завершено:
- [x] FireFox
Opera **false**
Chrome **false**

Тест пост: https://sandbox.golos.io/test/@dekol/yakor-test

**Comment by Bacher** [comment]
Не не не, якоря генерируются тегами h1..h6.

Аля https://sandbox.golos.io/test/@destroyer2k/3ishb4-hello#hello_world

**Comment by BaroH4er** [comment]
Функционал генерирования якорей тегами h1...h6 реализован. Однако осталась глобальная проблема перехода по якорям **НЕ** внутри страницы. 

Тестирование завершено:
- [x] FireFox
Opera **false**
Chrome **false**

Тест ссылка: https://sandbox.golos.io/test/@dekol/testt#hello_2

**Comment by BaroH4er** [comment]
Done.
- [x] FireFox
- [x] Opera
- [x] Chrome
