### ISSUE TITLE
Не отображается аватарка в модальном окне 

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/tolstoy#414]
Не отображается аватарка в модальном окне (Профиль - разделы - ссылки)
https://golos.io/ru--obratnaya-svyazx/@shenanigan/ne-otobrazhaetsya-avatarka-v-modalnom-okne-profil-razdely-ssylki

**Comment by BaroH4er** [comment]
### Ошибка **актуальна** для раздела "Ответы": 

**Воспроизведение**: 
1. Открыть главную страницу golos.io
2. Обновить/очистить кэш (ctrl+f5)
3. Открыть ленту актуальное или популярное
4. Открыть страницу профиля через ссылку в блоке ".PostSummary__content" > itemprop="author"
4.1 
![image](https://user-images.githubusercontent.com/21989598/43391894-a0be0050-93fa-11e8-8370-ec7ca77bda84.png)
5. Открыть вкладку "Ответы"
6. Открыть любой ответ через ссылку в заголовке

**Результат**: Не отображается аватарка автора ответа.
**Ожидаемый результат**: Отображается аватарка автора ответа.

**Comment by NickShtefan** [comment]
не актуально, в связи с редизайном
