### ISSUE TITLE
добавить загрузку юзерпика в настройках профиля

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/tolstoy#415]
добавить загрузку юзерпика в настройках профиля

**Comment by b1acksun** [comment]
Кнопка - "Загрузить" после поля "Добавьте URL Вашего изображения"

**Comment by NickShtefan** [comment]
![image](https://user-images.githubusercontent.com/6249597/34118682-99dcc7dc-e430-11e7-8ef7-b626cc1cc789.png)

Добавить кнопку обзор, и загружать изображения на наш хостинг

**Comment by jevgenika** [comment]
![image](https://user-images.githubusercontent.com/30616421/35092164-3422ba76-fc47-11e7-893f-299ed17cb7a0.png)

- [ ] Заменить текст:
- Вместо вставьте урл - "Вставьте ссылку на изображение или загрузите его"
- Вместо "Выбрать" - Кнопка: "Загрузить"
- [ ] Убрать КАПС везде

- [ ] Добавить загрузку обложки по типу загрузки юзерпика
Текст : Вставьте ссылку на обложку или загрузите ее
Кнопка: Загрузить
