### ISSUE TITLE
Не отображаются некоторые картинки на фронте

### ISSUE THREAD

**Issue by litrbooh** [GolosChain/tolstoy#417]
В превью картинка есть:
![default](https://user-images.githubusercontent.com/22373216/29409072-50f91a18-8353-11e7-92e7-8d9ade16c051.png)

А в самом после не отображается:
https://golos.io/ru--golos/@litrbooh/yubileinye-600-podpischikov

![default](https://user-images.githubusercontent.com/22373216/29409088-62932f02-8353-11e7-99ce-520183c69008.png)

При этом в мобильной версии видна...

**Comment by b1acksun** [comment]
Проверьте еще раз, картинка в посте отображается
