### ISSUE TITLE
Почему в кошельке предлагается скомпрометировать приватный ключ?

### ISSUE THREAD

**Issue by vikxx** [GolosChain/tolstoy#432]
![image](https://user-images.githubusercontent.com/26347159/29748328-54f05056-8b1d-11e7-814e-938350a8a8b4.png)

Пусть приватник для memo не используется, так как нет личных сообщений, но зачем просить его опубликовать? Когда появятся GUI для личных сообщений пароли многих уже будут скомпрометированы

**Comment by mrgr88n** [comment]
да и *заметкок* бы переделать

**Comment by b1acksun** [comment]
Это ошибка перевода, пофиксим
