### ISSUE TITLE
Открытые ордера с UIA не отображаются на внутреннем рынке

### ISSUE THREAD

**Issue by gropox** [GolosChain/tolstoy#433]
1. Открытые ордера на продажу и покупку UIA токенов принимаются и записываются в блокчейн, но не отображаются на внутреннем рынке

![image](https://user-images.githubusercontent.com/26039472/29754163-0c522906-8b80-11e7-9af5-664753f8804d.png)

![image](https://user-images.githubusercontent.com/26039472/29754173-4233f98c-8b80-11e7-8a2f-c7dd777cce03.png)

2. В форме размещения ордера возможно перепутаны поля ввода. При вводе вводилась цена "1"

![image](https://user-images.githubusercontent.com/26039472/29754242-8ad75caa-8b81-11e7-9859-6460361ec4ab.png)

А в блокчейне стоит цена 0.1

![image](https://user-images.githubusercontent.com/26039472/29754256-bed2ce72-8b81-11e7-80ae-cba9cd6347d3.png)

3. 
И при попытке покупки выдает непонятное предупреждение хотя цена покупки точно равна цене ордера на продажу. Возможно следствие пункта 2.

![image](https://user-images.githubusercontent.com/26039472/29754187-89422f56-8b80-11e7-8bdd-7357ec62bf41.png)

**Comment by gropox** [comment]
Исходники golos и tolstoy были сегодня склонированы и скомпилированы

**Comment by b1acksun** [comment]
Данная ветка находится еще в разработке

**Comment by gropox** [comment]
> Данная ветка находится еще в разработке

Да, кончно. Нужно для тестов, но к сожалению не работает. Хотелось акцентировать внимание.

**Comment by b1acksun** [comment]
Запушил изменения в ветку, необходимо обновить исходники и заново собрать клиент
