### ISSUE TITLE
Добавить возможность переключения между аккаунтами

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/tolstoy#434]
Добавить возможность переключения между аккаунтами
по примеру google

**Comment by gropox** [comment]
Интересно было бы реализовать модель кошелька, как на rudex.org или bitshares.org. Добавить возможность хранения ключей в кошельке. Мне кажется вероятным будет юзкейс, когда пользователи будут иметь только один какой то ключ от другого аккаунта. К примеру постинг ключ, как вариант делегирования обязанностей. Или активный ключ от мультисиг-аккаунта.
