### ISSUE TITLE
Добавить возможность добавлять мультимедиа контент в постах

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/tolstoy#435]
Добавить возможность добавлять фото\видео\гиф контент в комментариях
сделать мини редактор в комментария -по примеру фб

**Comment by edisorder** [comment]
добавить поддержку embed-кода с youtube/vimeo/soundcloud; т.е. сделать так, чтобы стандартный код вставки, предоставляемый этими сайтами, работал по дефолту, не игнорируя атрибуты width и height, например.

пример с youtube:
`<iframe width="560" height="315" src=" " frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>`

сейчас embed работает криво по двум причинам:
1. если вставлять контент просто ссылкой, то golos.io использует собственный плеер, который растягивается на всю ширину поста, с собственной кнопкой PLAY, едва различимой на фоне превью-картинки;
2. если вставлять контент embed-кодом, предоставляемым сайтом, то он все равно растягивается на ширину поста, но при этом golos.io пытается сохранить пропорции и убивает их окончательно (плывет превью-картинка, заголовки и т.д.);

**Comment by dechadecha** [comment]
Также было бы неплохо добавить, сервисы такие как:

Яндекс.Музыка, Deezer.com, также было бы неплохо если можно было бы встроить кнопки оплаты фиатом, по типу яндекс.денегб робокасса. или им подобных.

**Comment by Bacher** [comment]
Добавил:
- Coub
- Яндекс Карты
- Яндекс Музыка
- Deezer

Поправил превью Youtube, теперь правильная пропорция и красивая красная кнопка!

**Comment by BaroH4er** [comment]
Тестирование завершено. В редакторе функционирует: 

- [x] Coub
- [x] Яндекс Карты
- [x] Яндекс Музыка

Deezer **false**

**Comment by BaroH4er** [comment]
Done
- [x] Deezer

**Comment by NickShtefan** [comment]
- [ ] soundcloud
- [ ] vimeo
