### ISSUE TITLE
вставить активные ссылки в историю кошелька

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/tolstoy#439]
- [x] вставить активные ссылки  в историю кошелька
- [ ] сделать ссылки короткими (пример фб -primus упомянул вас)
<img width="578" alt="11" src="https://user-images.githubusercontent.com/30616421/29812922-945c7530-8ca8-11e7-9635-4da6f2048cb5.png">

**Comment by Chiliec** [comment]
Стоит подумать о запрете индексации страниц `@nickname/transfers`, иначе можно столкнуться с злоупотреблениями SEO-шников :)

https://www.google.ru/search?q=site:golos.io+inurl:/transfers

**Comment by b1acksun** [comment]
Для пункта "сделать ссылки короткими (пример фб -primus упомянул вас)" необходимо использовать сторонний сервис, данные ссылки будут уводить пользователя со страницы на сервис
