### ISSUE TITLE
Глючит редактор при редактировании кода на Python в посте

### ISSUE THREAD

**Issue by pythono-golos** [GolosChain/tolstoy#441]
Пишу в блог на голосе статьи про питон и заметил что после добавления блока с кодом на питоне происходит следующее. Пост добавляется, но если мне нужно его отредактировать то часто(не всегда) часть текста статьи пропадает, и приходится набирать всё заново. Глюк не всегда повторяется, но бывает очень часто на веб-версии сайта. При наборе статей часто переключаю режимы редактора текста, может это как то связано

**Comment by b1acksun** [comment]
В каком режиме (Markdown или HTML) добавялется блок с кодом?

**Comment by pythono-golos** [comment]
Я сперва пишу статью вместе с кодом в обычном Notepad++ потом копирую в Markdown, там в выпадающем списке выбираю Code Block при выделенном коде. Далее переключаю редактор в режим Raw HTML  чтобы вручную добавить еще один &nbsp - так как если этого не сделать то четыре питоньих пробела превращается почему-то в три. 
Ну и потом во время редактирования поста, например когда я перечитал свой пост и решил исправить опечатку, у меня теряется часть текста статьи. Иногда не теряется. Такое происходит не только с питоньим кодом но и с обычным текстом (у меня девушка жаловалась что при редактировании её поста про рецепт облепихового варенья, тоже полтекста удалилось)


>Четверг, 31 августа 2017, 15:21 +06:00 от Igor Tkachenko <notifications@github.com>:
>
>В каком режиме (Markdown или HTML) добавялется блок с кодом?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


С уважением, Иван
wbsr@mail.ru

**Comment by b1acksun** [comment]
Текст набранный в редакторе Markdown не совместим с режимом Raw HTML, при переключении возникают вышеперечисленные "глюки"
