### ISSUE TITLE
пофиксить рендер со стороны сервера

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/tolstoy#442]
криво рендериться и отображается цифра со стороны сервера
нужно пофиксить баннер на главной
<img width="364" alt="17" src="https://user-images.githubusercontent.com/30616421/29916759-118fad04-8e40-11e7-988a-7afbfc9c2fe2.png">
<img width="578" alt="17_1" src="https://user-images.githubusercontent.com/30616421/29916760-11a326cc-8e40-11e7-914f-7aaa82596e0a.png">

**Comment by b1acksun** [comment]
Неправильное отображение связано тем, что сервис query.yahooapis.com, с которого запрашиваются котировки, работает с перебоями

**Comment by Chiliec** [comment]
Может стоит кэшировать ответ?
