### ISSUE TITLE
Реализовать систему приглашений

### ISSUE THREAD

**Issue by chiliec** [GolosChain/tolstoy#443]
Увидел на Голосе предложение сделать простейшую систему приглашений, которая будет подписывать зарегистрированного пользователя на пригласителя. [Подробнее здесь](https://golos.io/ru--golos/@gogirotsky/sistema-priglashenii-na-golos-io-moei-vashei-nashei-mechty-s-blekdzhekom-i-profursetkami#@chiliec/re-gogirotsky-sistema-priglashenii-na-golos-io-moei-vashei-nashei-mechty-s-blekdzhekom-i-profursetkami-20170831t093239805z).

Что думаете?

**Comment by jevgenika** [comment]
- [ ] продумать о создание реферальной системы по предложению @lordarhont
Ссылку регистрации должен генерировать каждый сам ЗА свои голос или гбг, и скажем не более 3 ссылок . Они активны пока кто-то по ней не зарегистрировался. Пригласивший получает скажем 3-5% с каждого поста приглашённого до тех пор пока не откажется от вознаграждения . Приглашённые , тоже получают 3-5% от постов пригласившего, пока от них не откажутся . Чтобы снова сделать рефссылку , нужно отказаться от старой .

- [ ] продумать о создание многоуровневой партнерской программе по предложению @dmitrijv 
1 уровень - 7%
2 уровень - 5%
3 уровень - 3%
Вы размещаете ссылку на регистрацию в программе с вашим партнерским кодом, и получаете 5% от дохода (авторских и кураторских наград, если эти 5% > 0.001 Golos/GBG), людей зарегистрировавшихся по вашей ссылке.
