### ISSUE TITLE
добавить стандартное изображение для отображение постов с тегом NSFW на главной

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/tolstoy#444]
добавить стандартное изображение для отображение постов с тегом NSFW на главной
https://golos.io/ru--obratnaya-svyazx/@dinosaurmike/teg-nsfw-smotrim-na-staruyu-problemu-kak-na-interesnuyu-zadachu

**Comment by b1acksun** [comment]
![image](https://user-images.githubusercontent.com/3322340/30733954-e90e319a-9f81-11e7-909d-3dfe08f7f585.png)

Checkbox для пометки nsfw поста
Убрать в настройках отображения пункт меню "Всегда скрывать"

**Comment by jevgenika** [comment]
заменить стандартное изображение
https://s.yimg.com/uu/api/res/1.2/nylEEM4mv0vU0VmmvM0mFg--~B/aD04MDA7dz0xMTQxO3NtPTE7YXBwaWQ9eXRhY2h5b24-/http://media.zenfs.com/en-US/homerun/hello_giggles_454/fb471d2e1ac48db483de978da866b25c

**Comment by alex-firsov** [comment]
Арты для NSFW постов (обычный/ночной режимы).
![zaglushka_1 2](https://user-images.githubusercontent.com/33282977/34339413-734d3cf4-e97c-11e7-969f-0ccee731b24b.png)
![zaglushka_2](https://user-images.githubusercontent.com/33282977/34339414-7370a932-e97c-11e7-9bb6-5aad61e19d12.png)

**Comment by jevgenika** [comment]
- [ ] Вернуть в настройках отображения пункт меню "Всегда скрывать"

**Comment by sualex** [comment]
Дополнительные изменения :

Отключены ограничения nsfw (Всегда скрывать, Всегда предупреждать) для собственных постов залогиненного пользователя, так как не имеет смысла ограничивать пользователя от его собственного контента. 
То есть, авторизованный пользователь все свои посты в любых категориях видит в режиме nsfw "Отображать всегда".
