### ISSUE TITLE
Проблемы с внутренним рынком. Ветка UIA

### ISSUE THREAD

**Issue by gropox** [GolosChain/tolstoy#446]
Предыдущий баг по теме закрыт, по этому новый баг.

Все еще не работает как надо. Открытые ордера отображаются. Но панели продажи и покупки все еще перепутаны.

![image](https://user-images.githubusercontent.com/26039472/30057036-7e45a7fc-9235-11e7-843a-79b3da5311ab.png)

На скриншоте выше видно, что в панели "купить голос" показывает "доступно 1..... GOLOS", должно быть GBG. Это по линку /market/GBG_GOLOS. 

Если перейти по линку "Внутренний рынок" в боковом меню  /market. То показывает покупку/продажу GBG, а не GOLOS как это сейчас в продакшене. Это будет путать пользователя.

Сейчас в продакшене:
![image](https://user-images.githubusercontent.com/26039472/30057228-375d696e-9236-11e7-99a1-de811896ff55.png)
В ветке UIA:
![image](https://user-images.githubusercontent.com/26039472/30057286-6843e4d6-9236-11e7-9e0d-0acc6d15fba8.png)

Во вторых, ордера на продажу попадают в панель "покупка", что ИМХО не правильно. На скиншоте ниже видно, что я выставлял ордер на продажу 1000 Голосов по цене 0.5. А ордер показывает в панели "ЗАКАЗЫ НА ПОКУПКУ". Причем в секции "ОТКРЫТЫЕ СДЕЛКИ" ордера пользователя не показываются.

![image](https://user-images.githubusercontent.com/26039472/30057078-a86b1ecc-9235-11e7-9015-788e5548c719.png)

**Comment by b1acksun** [comment]
В связи с появлением UIA базовым ассетом стал GOLOS, поэтому внутренний рынок работает с base asset => GOLOS
Панели не перепутаны, баланс отображается на основании base asset, на проде панели "Заказы на покупку/продажу" рпсположенны в том же [порядке](https://github.com/GolosChain/tolstoy/blob/0.1.161221/app/components/pages/Market.jsx#L492), что логично - когда пользователь создает ордер на покупку ему отображаются ордера на продажу и наоборот

**Comment by gropox** [comment]
Но тот же cli_wallet показывает на мой взгляд правильно. С базой GBG ордера расположены в панели "продажа", 
![image](https://user-images.githubusercontent.com/26039472/30058764-a0678c7c-923c-11e7-840b-3ef43f7a540b.png)

**Comment by gropox** [comment]
Но не настаиваю. Возможно я и ошибаюсь. Возможно надо привыкнуть, что все шиворот-на-выворот

**Comment by gropox** [comment]
Не, сравнил с rudex, вот отличии от UIA ветки голоса, там все правильно отображается. Ордера на продажу попадают в панель на продажу

![image](https://user-images.githubusercontent.com/26039472/30059260-a9890b30-923e-11e7-9dbc-2687899b4e54.png)

**Comment by b1acksun** [comment]
https://github.com/GolosChain/tolstoy/issues/514
