### ISSUE TITLE
Реализовать Instant View для Telegram

### ISSUE THREAD

**Issue by chiliec** [GolosChain/tolstoy#447]
Поскольку Телеграм очень популярен среди прогрессивного населения, которое нам и нужно на Голосе, и самые большие сообщества Голоса сформировались именно там, предлагаю попробовать улучшить опыт взаимодействия клиента golos.io и Телеграма реализацией Instant View. Вся необходимая информация здесь: https://instantview.telegram.org/docs

**Comment by Chiliec** [comment]
Не так-то там всё просто, оказывается. Надо добавить домен (добавил), если он пройдет модерацию, то в следующем этапе соревнований можно будет добавить разметку и тогда она будет доступна для всех. А до тех пор надо будет к ссылке добавлять `t.me/iv?url=...&rhash=...`, где `rhash` - хеш шаблона, что не очень-то удобно. Так что ждём и пока откладываем это, наверное.

**Comment by 21xhipster** [comment]
Идея очень сытная :-) Если что я топлю за максимальную интеграцию с телегой

**Comment by vadbars** [comment]
Вик предлагал это: https://golos.io/ru--golos/@vik/shablon-telegram-instantview-dlya-golos-steemit
Есть шаблон разметки.
