### ISSUE TITLE
Убрать активные ссылки на сторонние ресурсы из истории трансферов

### ISSUE THREAD

**Issue by gropox** [GolosChain/tolstoy#448]
В истории трансферов стали подсвечиваться ссылки. По сути это хорошо, пока нет нормального извещения о событиях. Но на мой взгляд перебор показывать ссылки на сторонние ресурсы. Во первых это не работает в текущей реализации как надо - домен заменяется на golos.io, а URI берется из ссылки

![image](https://user-images.githubusercontent.com/26039472/30238912-1d2bfd12-9551-11e7-8631-874302ac3e3e.png)

После клика по ссылке

![image](https://user-images.githubusercontent.com/26039472/30238915-4079121e-9551-11e7-9992-4c8aa2ffe6a6.png)

А во вторых, зачем привлекать на ресурс спамеров? Сейчас ладно, возможно это заставило бы их покупать токены, но с другой стороны, что бы рассылать спам не нужны такие большие суммы, а после ХФ, с приходом UIA вообще рассылку спама можно будет делать бесплатно.

Мое предложение, подсвечивать *только* ссылки на сам golos.io.

**Comment by b1acksun** [comment]
Подсвечиваются только локальные ссылки (ведущие на страницы golos.io)
