### ISSUE TITLE
Невозможно сменить пароль на Golos.io

### ISSUE THREAD

**Issue by pmartynov** [GolosChain/tolstoy#450]
Действия:

1) Открываем меню и выбираем сменить пароль
https://imgur.com/DNnyVNm.png
2) Вводим текущий пароль
3) Нажимаем на кнопку, чтобы сгенерировать пароль
4) Вводим сгенерированный пароль 
5) Ставим две галочки на двух чекбоксах
6) Нажимаем на кнопку "Обновить пароль"
https://imgur.com/KCwMkDh.png

Реальный результат - ошибка:
* https://imgur.com/Bmvr3g9.png

Ожидаемый результат: 
* Пароль сменился

Комментарии:
* Предположительно может быть связано с тем фактом, что аккаунт был создан вместе с первым генезис блоком Голоса.

**Comment by b1acksun** [comment]
https://github.com/GolosChain/tolstoy/issues/293

**Comment by b1acksun** [comment]
https://github.com/GolosChain/tolstoy/issues/381

**Comment by pmartynov** [comment]
Cупер! Ждем деплоя.

**Comment by pavelit** [comment]
> Cупер! Ждем деплоя.

Отпишитесь пжл если проблема осталась. А проблема была в том что в цепочке лежит некорректно записанный json_metadata со значением `created_at: GENESIS`

**Comment by pavelit** [comment]
Деплой прошел, метка [134](https://github.com/GolosChain/tolstoy/tree/17.134)

**Comment by pavelit** [comment]
Деплой прошел, метка [134](https://github.com/GolosChain/tolstoy/tree/17.134)

**Comment by pmartynov** [comment]
Вроде ничего не поменялось. Ctrl+F5 + Disable Cache не помогает.

![error](https://imgur.com/xvJZAPF.png|width=350)

**Comment by pavelit** [comment]
Щя
