### ISSUE TITLE
Ошибка при загрузке большого изображения, перевод, задержка 5 сек

### ISSUE THREAD

**Issue by merrymari** [GolosChain/tolstoy#458]
https://golos.io/ru--obratnayasvyazx/@sterh/zadolbalsya-byl-by-redaktor-v-golose-chuvakom-ya-by-nabil-emu-mordu

**Comment by b1acksun** [comment]
Ошибка при загрузке большого изображения, перевод, задержка 5 сек

**Comment by NickShtefan** [comment]
По поводу времени отображения ошибки напиши мне, когда доберешься до таска.

**Comment by jevgenika** [comment]
@NickShtefan необходимо протестировать
1 раз из 5- сообщение исчезло стремительной, не успела прочитать
![image](https://user-images.githubusercontent.com/30616421/34166716-4dc7e440-e4e8-11e7-8e6f-b3f0a25589ac.png)
- [ ] поправить текст

**Comment by sualex** [comment]
Все ошибки перевел. В указанном выше случае "Ошибка доступа к серверу" скорее всего не означает "Ваше изображение слишком велико", поэтому такой однозначный перевод будет неверным, т.к. код приходит один, а англоязычные сообщения - разные. Нужно повторить ситуацию и увидеть конкретную ошибку в консоли браузера, если текущий перевод не решит вопрос.

**Comment by jevgenika** [comment]
- [ ] заменить текст ссылкой на гитхаб:
"Произошла ошибка. Для решения проблемы укажите больше информации об ошибке тут. "

- [ ]  Создать ишью и собрать логи ошибок из консоли пользователей
" Для решения проблемы с загрузкой  изображения добавьте скриншот информации об ошибке тут. Для этого, пожалуйста, откройте консоль  в вашем браузере, это можно это сделать с помощью комбинации: Ctrl + Shift + J (прописать другие вариации )
скопируйте информацию о вашей ошибке сюда. (приложить картинку для примера)

**Comment by NickShtefan** [comment]
При загрузке изображения больше 2mb возникают следующие ошибки. 
Необходимо обработать такую ошибку и сообщить пользователю, что изображение слишком большое. 
![image](https://user-images.githubusercontent.com/6249597/34771462-b790f702-f615-11e7-9a7c-afec277b3f03.png)
