### ISSUE TITLE
При первом создании статьи было непонятно про markdown

### ISSUE THREAD

**Issue by muhazzz** [GolosChain/tolstoy#464]
При первом написании статьи лично у меня возникло много не очевидных моментов.

Как сейчас: пришлось гуглить про markdown и читать статьи других авторов на эту тему. Иногда забывал как делается то или иное действие (выделить жирным, сделать зачеркивание, ссылка, ссылка на картинку и т.д.) - приходилось лезть, опять же, в стороннюю статью и искать решение там.

Как хотелось бы: кнопки, добавляющие markdown (как в github):
![как в github](https://image.ibb.co/kaZ4pQ/screenshot_9893.jpg)

P.S.: сейчас обратил внимание, что в самом низу экрана редактирования есть ссылка на статью про markdown. Я её, почему-то, в упор не видел и пришлось гуглить. Возможно, есть смысл выбрать для неё более удачное место и/или оформление. Но, конечно же, лучше вообще не заставлять человека читать стороннюю статью, кнопки будут гораздо удобнее.

**Comment by NickShtefan** [comment]
У нового Markdown редактора есть такая панель. 
Так же есть дополнительная кнопка со знаком "?", нажав на которую можно перейти в пост, с описанием работы в markdown

![image](https://user-images.githubusercontent.com/6249597/34222002-12b1673a-e5cb-11e7-9438-3bd0b2658dc6.png)

**Comment by jevgenika** [comment]
- [ ] сделать обводку выбранного редактора с кнопкой выпадающего меню для переключения
![image](https://user-images.githubusercontent.com/30616421/34336938-f8d7b6ce-e963-11e7-8106-abcf00927f34.png)
- [ ] перенести кнопку со знаком вопроса к названию выбранного редактора
![image](https://user-images.githubusercontent.com/30616421/34336957-219e67a6-e964-11e7-8843-c279961d26a4.png)
