### ISSUE TITLE
Добавить функцию смены account_recovery

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/tolstoy#465]
https://golos.io/ru--bezopasnostx/@phenom/instrukciya-o-vosstanovlenii-dostupa-k-akkauntu-i-vybore-doverennogo-lica

**Comment by pavelit** [comment]
Чего сделать-то надо?

**Comment by jevgenika** [comment]
добавить сервис смены account_recovery. Это будет актуально для тех, кто не умеет пользоваться cli_wallet.
