### ISSUE TITLE
изучить и внедрить отображение уникальности контента поста

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/tolstoy#466]
- [ ] изучить плагины и сервисы по проверке уникальности контента
- [ ] внедрить сервис в редактор
- [ ] при запросе пользователя на постинг- автоматически отображать процент уникальности контента.
https://golos.io/ru--golos/@slon21veka/unikalnyi-vash-kontent-ili-ne-unikalnyi

**Comment by litrbooh** [comment]
А просто читаха мало? Зачем делать это централизованно?
