### ISSUE TITLE
создать возможность сохранять посты в избранное

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/tolstoy#467]
- [ ] создать возможность помечать посты 
- [ ] создать возможность сохранять посты в избранное
- [ ] добавить вкладку избранное, отображать закладку избранное в профайле пользователя

**Comment by litrbooh** [comment]
Ура. Ждем! прошу об этом с самого старта

**Comment by jevgenika** [comment]
https://github.com/GolosChain/tolstoy/issues/371

**Comment by jevgenika** [comment]
- в профиле пользователя в закладке блог (посты) отображать мин 1 максимум 3 закрепленных  избранных постов любого автора
- пользователь должен иметь в настройках право как открепить так и открепить пост
- кнопку закрепить пост с иконкой pin -булавкой поставить рядом с кнопкой редактировать пост на странице пост
-  иконка пина меняет вид при различном состоянии закрепленном\открепленном состоянии
-  иконка пина откреплять пост там же редактируем пост
-  при закреплении последующего поста, он идет последним в очереди
[Archive.zip](https://github.com/GolosChain/tolstoy/files/1694929/Archive.zip)

**Comment by BaroH4er** [comment]
### Тестирование завершено. [Отчет + чек-лист](https://docs.google.com/spreadsheets/d/1-zewI8-OpdRjocy_V-PnTaITZ1lOumZ9NEsNwnqfzfw/edit?usp=sharing).

**Ошибка:**
> При наведении указателя мыши на иконку пина всплывает подсказка "vector", а должно - "Закрепить/Открепить пост" в зависимости закреплен он или нет.

**Замечания/Вопросы:**

1. В меню пользователя, ссылка "Блог" переименована в "Посты" - необходимо уточнить, точно ли данное наименование подходит для этого раздела сайта.
2. В данный момент, функционал избранного работает только для постов находящихся в разделе сайта "Блог/Посты", что требует обязательного репоста сторонний статьи к себе в блог, и последующего добавления её в избранное. Правильно ли это?
3. При наведении курсора на span иконку "пина-булавки", возможно стоит менять курсор на "руку", аналогично фокусу на другие иконки (кнопки) .

**Comment by litrbooh** [comment]
@jevgenika, обязательный репост для добавления в избранное, это как-то не правильно.

**Comment by sualex** [comment]
@BaroH4er @litrbooh @jevgenika Не нужно ничего никуда репостить. Нужно открыть посты любого пользователя и там будет доступен пиннинг. Так это работает в текущей версии.

**Comment by BaroH4er** [comment]
Изменено: 
> _2. В данный момент, функционал избранного работает только для постов находящихся в разделе сайта "Блог/Посты", что требует обязательного репоста сторонний статьи к себе в блог, и последующего добавления её в избранное. Правильно ли это?_

2. В данный момент, функционал избранного работает только для постов находящихся в разделе сайта "Блог/Посты" и для потов конкретного пользователя находясь у него на странице. **Предложение**: добавить возможность добавление в избранное постов находящихся во всех лентах.

**Comment by litrbooh** [comment]
@alex-firsov 
Какие планы по внедрению?

**Comment by alex-firsov** [comment]
@litrbooh До конца месяца будет реализовано.
>Какие планы по внедрению?

**Comment by BaroH4er** [comment]
Тестирование завершено. 

- [x] Добавление поста в избранное
- [x] Удаление поста из избранного
- [x] Отображение/подгруздка избранных постов

Работает стабильно. Ошибок нет.
