### ISSUE TITLE
Добавить возможность вызывать окно перевода GBG/Голосов через ссылку с подстановкой параметров перевода

### ISSUE THREAD

**Issue by pokupo** [GolosChain/tolstoy#468]
Для надежной интеграции приема платежей GBG/Голосов в торговые мерчанты (моя команда сейчас занимается этим https://golos.io/golos/@ivelon/razrabotka-modulya-priema-platezhei-golos) необходимо доработать клиент Голоса, чтобы можно было запрашивать платеж по ссылке с параметрами:

1. Тип платежа (GOLOS || GBG)
2. Получатель платежа (ник получателя)
3. Количество (сумма перевода)
4. Примечание (заметка для идентификации платежа)

![](http://joxi.ru/EA4QaewtwGJG4r.png)

Желательно, чтобы ссылка перенаправляла на кошелек пользователя без указания его имени в ней, (сейчас ссылка на кошелек имеет вид https://golos.io/@ivelon/transfers) так как иначе потребуется запрашивать у покупателя его ник, а лишние параметры всегда снижают платежную конверсию при покупке. 

Формат ссылки на усмотрение разработчиков, главное, чтобы была возможность ее генерировать из реквизитов заказа в любом магазине.

**Comment by pokupo** [comment]
Модуль реализован [https://pokupo.ru/payment/8315/payment#//description=%D0%9E%D0%BF%D0%BB%D0%B0%D1%82%D0%B0%20%D0%B7%D0%B0%D0%BA%D0%B0%D0%B7%D0%B0&mailUser=&idMethodPayment=&byGroup=no](url)
Нужна ссылка, иначе руками пользователь будет ошибаться.

**Comment by pokupo** [comment]
Не хочет работать с кодами url

https://golos.io/@ivelon/transfers?to=@ivelon&amount=11.352&token=GBG&memo=Pokupo:%20%D0%9E%D0%BF%D0%BB%D0%B0%D1%82%D0%B0%20%D1%81%D1%87%D0%B5%D1%82%D0%B0%20%E2%84%963629-61d210a19fe5c1c6c1a0

**Comment by sualex** [comment]
`https://sandbox.golos.io/${senderID}/transfers?to=${receiverID}&amount=100&token=GBG&memo=Pokupo:%20%D0%9E%D0%BF%D0%BB%D0%B0%D1%82%D0%B0%20%D1%81%D1%87%D0%B5%D1%82%D0%B0%20%E2%84%963629-61d210a19fe5c1c6c1a0`

где: 

senderID - имя отправителя в блокчейне голос
receiverID - имя получателя в блокчейне голос
amount - сумма
token - правильный идентификатор переводимого ассета
memo - urlencoded string

При несоответствии url вышеуказанным пунктам окно трансфера не вызывается.

**Comment by vadbars** [comment]
Каков правильный формат вызова окна трансфера? Выше @sualex его описывал, но сейчас есть несоответствия: 
- senderID должен быть с @
- memo принимается не urlencoded
 
Поле memo не выводится в форме, что неудобно: надо дать возможность проверить правильность и отредактировать перед отправкой

**Comment by sualex** [comment]
@vadbars в текущей реализации senderID НЕ должен содержать '@' . Memo откроем и разрешим редактировать если нужно. Рабочая ссылка в текущей версии выглядит так <a href="https://golos.io/@sender/transfers?to=receiver&amount=0.001&token=GBG&memo=%D0%B1%D0%BB%D0%B0%D0%B3%D0%BE%D0%B4%D0%B0%D1%80%D1%8E">sandbox</a>

**Comment by vadbars** [comment]
В примере рабочей ссылки senderID содержит @. 
https://golos.io/**@sender**/transfers?to=receiver&amount=0.001&token=GBG&memo=%D0%B1%D0%BB%D0%B0%D0%B3%D0%BE%D0%B4%D0%B0%D1%80%D1%8E

**Comment by sualex** [comment]
@vadbars Так и должно быть. Мое изначальное сообщение содержало ошибку и я его уже поправил
