### ISSUE TITLE
починить отображение грузинской и казахстанской валюты

### ISSUE THREAD

**Issue by Undeadlol1** [GolosChain/tolstoy#47]

**Comment by Undeadlol1** [comment]
₾ - символ грузинской лари
₸ - символ казахстанского тенге
Для выбора символа на данный момент используется модуль [currency-symbol-map](https://github.com/bengourley/currency-symbol-map), в котором данных об этих странах нет. Нужно либо добавлять пулл реквест, либо делать костыль

**Comment by tomarcafe** [comment]
я за пулл

**Comment by Undeadlol1** [comment]
Я сделаю и то и то, потому что пулл реквест неизвестно когда будет одобрен. И будет ли вообще

**Comment by Undeadlol1** [comment]
https://github.com/bengourley/currency-symbol-map/pull/20

**Comment by bestan** [comment]
bengourley/currency-symbol-map#20 merged.  Удачи 😉

**Comment by Undeadlol1** [comment]
@bestan Спасибо огромное!
