### ISSUE TITLE
Добавить функцию удаления/сокрытия постов

### ISSUE THREAD

**Issue by merrymari** [GolosChain/tolstoy#471]
Добавить функцию удаления/сокрытия постов (не показывать их на сайте) 
дать возможность скипать посты в своей ленте, hide от себя
сделать для сайта и приложений

Если есть механизм подмены одного поста другим в режиме редактирования, то почему нельзя сделать простой механизм удаления своих постов – просто не показывать их на сайте. Технически это можно реализовать, например, с помощью специального тега, например, «deleted». Можно даже сделать простановку этого тега с помощью пользовательского интерфейса сайта – автор заходит в редактирование поста и ставит галочку «удалить» или «скрыть» и пост исчезает.

**Comment by pavelit** [comment]
Подробности есть?

**Comment by jevgenika** [comment]
https://github.com/GolosChain/tolstoy/issues/472
