### ISSUE TITLE
исправить баг в отображении постов в тегах, если их больше 5

### ISSUE THREAD

**Issue by merrymari** [GolosChain/tolstoy#473]
- Если тегов больше 5, то в некоторых тегах пост не отображается
- исправить баг в отображении постов в тегах, если их больше 5
https://golos.io/ru--obratnaya-svyazx/@semasping/bag-v-sluchae-esli-tegov-u-posta-bolshe-5

**Comment by BaroH4er** [comment]
Необходимо дополнительное тестирование после релизов команды Core.

**Comment by BaroH4er** [comment]
Тестирование завершено. **Done** - ошибку воспроизвести не удалось, посты отображаются во всех тегах. (sandbox)
