### ISSUE TITLE
исправить ошибку с перекидыванием пользователя на русский языке при обновлении страницы

### ISSUE THREAD

**Issue by merrymari** [GolosChain/tolstoy#474]
https://golos.io/ru--obratnaya-svyazx/@eliel/even-choosing-the-english-language-when-i-update-the-page-back-to-the-russian-language

**Comment by NickShtefan** [comment]
Можно хранить настройки выбранного языка в блокчейне, в таком случае скидываться они не будут

**Comment by BaroH4er** [comment]
### Ошибка актуальна. 

**Проблема**: вне зависимости от указанного ранее языка в настройка профиля, язык интерфейса всегда меняется на русский после чистки кэша (ctrl+f5).

**Воспроизведение**: 
1. Открыть страницу настроек публичного профиля (/@name/settings)
2. Выбрать любой язык в списке "Выберите язык интерфейса" кроме русского.
2.1 Язык изменился
3. Обновить страницу/кэш - ctrl+f5

**Результат**: язык интерфейса изменился на русский.
**Ожидаемый результат**: язык интерфейса соответствует настройкам профиля.
