### ISSUE TITLE
Внедрить встраивание видео с разных видеохостингов

### ISSUE THREAD

**Issue by merrymari** [GolosChain/tolstoy#475]
для плееров RuTube, Вк, Одноклассников и прочих - нужна поддержка Adobe Flash.

Возможно ли на Голосе решить эту проблему с встраиванием видео и ввести поддержку Adobe Flash? Было бы хорошо, если в посты Голоса встраивалось видео с RuTube, Вк, Одноклассников и прочих сайтов.
https://golos.io/ru--obratnaya-svyazx/@aleos/predlagayu-sdelat-na-golose-vstraivanie-video-s-raznykh-videokhostingov

**Comment by Bacher** [comment]
Добавил возможность добавления видео с RuTube, Вк и Одноклассников.

**Comment by BaroH4er** [comment]
Тестирование завершено. 

- [x] ВK
OK **false**
RuTube **false**

**Comment by BaroH4er** [comment]
Done
