### ISSUE TITLE
Предложение по использованию GBG на Голосе

### ISSUE THREAD

**Issue by zhenek73** [GolosChain/tolstoy#477]
Вот какие варианты использования золотых я нашел

 - покупать Промо
 - Выплачивать награду в конкурсах
 - возможно инструмент инвестиций, как и любая другая криптовалюта

Настоящую ценность для меня, как для блогера, представляет только первый пункт. Но я уже ни раз пользовался этим инструментом и могу сказать, что он не работает. По моим ощущениям в раздел Промо не заходит никто (киты и косатки конечно в первую очередь) у всех есть свои ленты, любимые теги... В общем тратить Золото на Промо сейчас не имеет смысла.

А что если исправить эту ситуацию? Сделать так, чтобы посты ПРОМО были бы заметны. Чтобы они включались в ленты насильно, висели баннерами например (без фанатизма конечно). Сделать так, чтобы Промо работало! 

Тогда у GBG появиться реальная ценность на Голосе! Будет мотивация его покупать, копить и вкладывать в свои самые крутые посты.  

И клиентам тогда от этого польза, ведь потраченные на промо ГБГ могут пойти разработчикам клиентов.

**Comment by litrbooh** [comment]
Уже было предложение убрать вкладку ПРОМО как бесполезную (я на стиме ещё год назад предлаал это сделать). И тогда посты с продвижением просто будут в ленте на общих основаниях с учетом продвижения.
