### ISSUE TITLE
Реализовать децентрализованный механизм авторизации сторонних приложений

### ISSUE THREAD

**Issue by pavq** [GolosChain/tolstoy#485]

**Comment by Chiliec** [comment]
Разработчики Multy.io тоже её ждут, как я понял )

**Comment by 21xhipster** [comment]
Ребят, только я не уверен, что правильно делать это прямо через OAuth. Лучший пример того, что нам надо сделать, это Steemconnect 2. Это когда права на конкретное действие дается приложению не потому-что кто-то сохранил приватник у себя на сервере (на такая реализация априори не интересна), а потому-что аккаунт приложения имеет (записанное в блокчейн) authority на то или иное действие

**Comment by serejandmyself** [comment]
Дима, согласен с тобой. Но сейчас стоит выбор между тем чтобы сделать и сказать всем кто хочет пользоваться (те кому это мега срочно и не могут запустится без этого) - что есть вот такая имплементация, с такими то косяками и рисками. И пилить нормальную версию а-ля стим коннект. Либо ждать еще пол года разработки и не дать нескольким проектам (которые знают о рисках и готовы их брать на себя) запустится.

**Comment by 21xhipster** [comment]
Предлагаю ждать еще полгода. Мы не будем брать риски хранения приватных ключей на себя.

**Comment by serejandmyself** [comment]
Нам не нужно брать риски на себя, если о них заявлено в правилах пользования ПО. Никто не предлагает нам хранить эти ключи. 
Кто будет сейчас пояснять инвесторам (готовыми брать эти риски на свой счет) о том что им надо ждать пол года?

**Comment by 21xhipster** [comment]
Ни один приватный ключ (даже постинг) ни при каких обстоятельствах не должен храниться на нашем сервере. Пользовательское соглашение тут не при чем.

**Comment by serejandmyself** [comment]
Причем тут наши сервера? Тот кто это использует, хранит это у себя... Не у нас. Он берет эти риски. Это и есть соглашение пользованием ПО

**Comment by 21xhipster** [comment]
Давай я объясню как работает Auth
[](https://assets.digitalocean.com/articles/oauth/abstract_flow.png)

В нашей схеме Application (client) это преложение golos.io, а Auth server это наш же сервак с SSL сертификатом тоже golos.io

Видишь там четвертый шаг - это предоставление приложению токена доступа? В нашем случае вероятнее всего это приватник хешированный паролем юзера (т.к. без него OAuth сервер не сможет делать запросы в блокчейн без юзера). Следовательно чтобы сервер golos.io мог делать транзакции без участия юзера (а иначе какой смысл в этом Auth) у сервера должен быть приватник этого юзера. 

Может быть ты можешь нарисовать схему в которой нашему серверу не нужно хранить приватник, чтобы делать транзакции от имени юзера?

Или я что-то не так понимаю?

**Comment by serejandmyself** [comment]
Дим, со слов ребят, как раз таки в случае стим коннекта нам придется хранить соли хешей (или ключи в том или ином виде) (точнее инфу для его восстановления). 
В случае с oauth нам не надо нечего хранить. Так как не какого открытого ключа или его солей не хранится на наших серверах. Только на ему доверенных серверах (в этом случае это сервера тех кто использует ПО)

**Comment by 21xhipster** [comment]
Стимконнект != Стимконнект 2. Во второй версии ничего не надо хранть. Там все сделано мудро. 

На самом деле Стимконнект 2 не такая уж и сложная задача. Это просто транзакция добавления еще одного публичного ключа (аккаунта приложения с treshold 1) типа как тут 

<img width="388" alt="screen shot 2017-10-23 at 14 13 59" src="https://user-images.githubusercontent.com/410789/31888493-f3828126-b804-11e7-8d6b-22f0df1ff5f2.png">

У нас в цепоке насколько мне известно есть это функционал и ничего доделывать не надо. Просто нужно сделать в приложении эту фичу и задокументировать для сторонних разработчиков. И вся штука начнет работать без нашег участия.

**Comment by 21xhipster** [comment]
А еще при такой схеме мы создаем реальный спрос на аккаунты со стороны разработчиков приложений

**Comment by serejandmyself** [comment]
@kotbegemot

**Comment by 21xhipster** [comment]
<img src='https://shipusercontent.com/f9d62861cae2c59bdf09be9fa5972d4f/Screen%20Shot%202017-10-23%20at%2014.26.56.png' title='Screen Shot 2017-10-23 at 14.26.56.png' width=388>

Нашел кейс из нашей цепочки :-) Так, что все должно быть действительно тривиально. Просто нужно добавить ux для транзакции и все

**Comment by Chiliec** [comment]
А как так получилось? В нашем ХФ 0.16.0 вроде нету таких операций.

**Comment by Chiliec** [comment]
Дошло! В этом ХФ нету операции делегирования силы, но ещё один ключик прописать можно без проблем)

**Comment by Chiliec** [comment]
Ребят, а может кто-нибудь пояснить, в чём принципиальная разница хранения ключей пользователя от прописывания им нашего ключа?
Насколько я понимаю, при компрометации пользовательских приватных ключей и единого нашего ключа — злоумышленник получает одни и те же возможности. Однако ключ не проходит через каналы передачи информации. 
Получается единственный плюс — защита от MITM-атак?

**Comment by vikxx** [comment]
https://golos.cf/multi/

![image](https://user-images.githubusercontent.com/26347159/32444028-d90dd024-c309-11e7-868c-f03e631aa16e.png)

![image](https://user-images.githubusercontent.com/26347159/32444119-16cd41ce-c30a-11e7-9313-6593bcefe45a.png)


```
<script>
golos.config.set('websocket','wss://api.golos.cf');

steem.config.set('address_prefix','GLS');
steem.config.set('chain_id','782a3039b478c839e4cb0c941ff4eaeb7df40bdd68bd441afd444b9da763de12');

var BUTT = document.querySelector("a.registration");
BUTT.addEventListener("click", function( event ) {
var NAME = document.getElementById("name").value;
var  wif= document.getElementById("wif").value;
var  creator= document.getElementById("creator").value;
golos.api.getAccounts([creator], function(e, data){
     if (e) return console.warn(e)
	 
       var account = data[0];
       var pAuth = account.posting;
	   var memo = account.memo_key;

pAuth.account_auths.push([NAME, pAuth.weight_threshold]);
steem.broadcast.accountUpdate(wif, 
creator, undefined, undefined, 
           pAuth, memo
		   , account.json_metadata, function(err, result) {
         console.log(err,result)
		 if(err){  var jsone = JSON.stringify(err, null, 4);
 return document.getElementById('out').insertAdjacentHTML("afterbegin","<div class='err'><h2>Ошибка!</h2>Подробности ошибки: "+jsone+"</div>")
  }else{
    var json = JSON.stringify(result, null, 4);
  document.getElementById('out').insertAdjacentHTML("afterbegin","<div class='success'><h2>Готово!</h2>Лог транзакции в блокчейн: </br><code>"+json+"</code>")
  }
		 
       });
     
});

})
</script>

```

**Comment by 21xhipster** [comment]
@vikxx Спасибо за доходчивый пример :-)
