### ISSUE TITLE
Исправить информацию на лэндинге

### ISSUE THREAD

**Issue by merrymari** [GolosChain/tolstoy#488]
https://golos.io/ru--obratnaya-svyazx/@allforyou/predlozhenie-obnovlenie-stranicy-dobro-pozhalovat

**Comment by jevgenika** [comment]
@alex-firsov нужно составить текст для правки неактуальной информации для стр welcome

**Comment by jevgenika** [comment]
https://github.com/GolosChain/tolstoy/issues/510 дубликат
