### ISSUE TITLE
Вынести markdown парсер в отдельную js либу

### ISSUE THREAD

**Issue by t3ran13** [GolosChain/tolstoy#491]
Любая новая прилажуха должна писать свой markdown парсер, не дело.
Вынесите парсер в отдельную либу, при этом срочно!

А пока кинте линку где он у нас в репозитории лежит.

**Comment by b1acksun** [comment]
В клиенте используется парсер [remarkable](https://github.com/jonschlinkert/remarkable), который доступен через npm

**Comment by t3ran13** [comment]
@b1acksun спасибо большое!
чет поиск не находит где он подключается??
без плагинов, все дефолтное?

**Comment by b1acksun** [comment]
https://github.com/GolosChain/tolstoy/blob/master/app/components/cards/MarkdownViewer.jsx#L4
Плагины не используются
