### ISSUE TITLE
исправить баг со сбросом настройки валюты при разлогине

### ISSUE THREAD

**Issue by merrymari** [GolosChain/tolstoy#494]
https://golos.io/golosio/@bezborodkin/pozhelaniya-po-interfeisu-golos-io

**Comment by BaroH4er** [comment]
**Протестировано** - воспроизвести ошибку не удалось. В данный момент настройки пользователя сохраняются отдельно для каждого браузера.
- [x] Chrome
- [x] Opera
- [x] FireFox
- [x] IE
