### ISSUE TITLE
The current way of loading a large number of comments freezes the page

### ISSUE THREAD

**Issue by vikxx** [GolosChain/tolstoy#496]
Example with 4000+ comments
https://golos.io/ru--konkurs/@ljpromo/konkurs-na-samogo-aktivnogo-kommentatora-prizovoi-fond-100-golos-50-50

**Comment by Chiliec** [comment]
А разве можно получить пост без комментов или отдельно какую-то их часть?
Мне кажется это вопрос прежде всего к блокчейну https://github.com/GolosChain/golos

**Comment by vikxx** [comment]
Проблема в рекурсии при загрузке
