### ISSUE TITLE
Создать автоматизированную систему жалоб по примеру других соц сетей

### ISSUE THREAD

**Issue by merrymari** [GolosChain/tolstoy#497]
возможно, добавить выбор причины жалобы и т.д.

**Comment by jevgenika** [comment]
создать автоматическую систему жалоб на пост, по примеру других соц сетей 
с возможностью выбора 
- [ ] добавить кнопку -Пожаловаться на публикацию
- [ ] ввести ссылка на форму, с помощью которой можно оставить жалобу
- [ ] в форме 4 позиции и обязательный комментарий пользователя подающего жалобу
- [ ] жалобу может отсавить только зарегистрированный пользователь  -авторизация
жалобы собирают на расмотрение 
- [ ] после набора критического ко-ва (определить) жалоб пост скрывается автоматически

**Comment by Chiliec** [comment]
Только учтите, что эту систему можно будет использовать недоброжелателями с несколькими аккаунтами.

**Comment by NickShtefan** [comment]
## Цели

- Организовать сбор жалоб на посты и комментарии
- Создать интерфейс со статистическими выборками
- Предоставить golos.io данные для фильтрации постов по жалобам

## Детали функционала

- Жалобу может оставить только зарегистрированный пользователь
- После набора критического кол-ва (определить) жалоб пост скрывается автоматически. Таким образом API должно иметь метод для проверки поста, принимающий permlink и author.
- Жалобу можно оставить только с обязательным комментарием
- Жалоба принимается один раз от одного пользователя
- Комментарий обязателен 
- REST API

## Причины жалоб: 
спам 
диффамация
краденный контент
запрещенный контент
персональные данные
обсценная лексика и оскорбления 
порнографический контент

## Технологии
Весь проект предлагается упаковать в один репозиторий. В качестве основных технологий использовать:
Node.Js  + Express
React + WebPack
Tarantool

ТЗ будет обновляться.
