### ISSUE TITLE
Сделать падежи у валюты

### ISSUE THREAD

**Issue by Undeadlol1** [GolosChain/tolstoy#50]

**Comment by 21xhipster** [comment]
Можно апдейт по актуальности? Вроде даже пулл риквест был? Если еще актуально - переоткрой

**Comment by Undeadlol1** [comment]
Нет, не было.
Пока валютой особо не пользуемся, не обмениваемся и не выводим. Поэтому занимался более актуальными делами.

**Comment by serejandmyself** [comment]
Сейчас как некогда актуально

**Comment by serejandmyself** [comment]
Set for sprint №2
