### ISSUE TITLE
В репозитории отсутствует лицензия

### ISSUE THREAD

**Issue by Chiliec** [GolosChain/tolstoy#501]
Почему-то отсутствует. Наверное, должна быть.

**Comment by b1acksun** [comment]
https://github.com/GolosChain/tolstoy/commit/cf6b847aa51a621771b5854e64959f268bef5032

**Comment by b1acksun** [comment]
https://github.com/GolosChain/tolstoy/commit/60bca455feb2d431a0a504e4656983a5553806e3
