### ISSUE TITLE
Исправить отображение мнемоник в теле поста

### ISSUE THREAD

**Issue by b1acksun** [GolosChain/tolstoy#503]
sanitize-html экранирует & в &amp;mdash;

**Comment by b1acksun** [comment]
https://github.com/GolosChain/tolstoy/commit/bb6437026cbb22114ebf5e8de75e5933489a371d

**Comment by html-code** [comment]
А какой вообще смысл экранировать html-entities?

В постах периодически проскакивают `&nbsp;`, `&hellip;` и ещё что-то.
Часто встречающиеся: https://ru.wikipedia.org/wiki/Мнемоники_в_HTML

**Comment by b1acksun** [comment]
Экранирование & происходит в библиотеке [sanitize-html](https://github.com/punkave/sanitize-html/blob/master/index.js#L360) и на выходе получается, что **&mdash;** и другие мнемоники превращаются в **&amp;mdash;**
