### ISSUE TITLE
Предупреждение о точке в конце заголовка

### ISSUE THREAD

**Issue by chiliec** [GolosChain/tolstoy#506]
По правилам русского языка, [в конце заголовка точка не ставится](http://gramota.ru/biblio/magazines/rr/28_563). Однако на Голосе часто можно встретить нарушение этого правила. Предлагаю сделать предупреждение, если в конце заголовка присутствует точка.

**Comment by BaroH4er** [comment]
Тестирование завершено. Done.
![image](https://user-images.githubusercontent.com/21989598/42213070-8049268c-7ec0-11e8-848a-f61cf00b37e5.png)

**Comment by NickShtefan** [comment]
По просьбе пользователей необходимо переделать логику работы 

- [ ] Данное предупреждение является информационным, и не блокирует возможность создания поста.

**Comment by Bacher** [comment]
Текст

> На нашем ресурсе не принято оканчивать заголовок спец символами или точкой

подойдет?

**Comment by BaroH4er** [comment]
Done
