### ISSUE TITLE
Предложение по изменению страницы "Добро пожаловать"

### ISSUE THREAD

**Issue by dankinescop** [GolosChain/tolstoy#510]
https://golos.io/ru--obratnaya-svyazx/@allforyou/predlozhenie-obnovlenie-stranicy-dobro-pozhalovat

**Comment by vadbars** [comment]
Предлагаю сделать ссылку на страницу в wiki Голоса. 
Будет проще обновлять. И пользователей приучать к вики. )

**Comment by bitfag** [comment]
SO SLOW https://golos.io/golosio/@allforyou/208daysofwaiting

**Comment by jevgenika** [comment]
https://github.com/GolosChain/tolstoy/issues/575 дубликат
@alex-firsov нужно составить текст для правки неактуальной информации для стр welcome

**Comment by jevgenika** [comment]
@vadbars Будет проще обновлять информацию, согласна.
Но для входа в Вики есть свои ссылки.  У страницы "Добро Пожаловать" свои цели с нее будем давать переход в Вики.

**Comment by BaroH4er** [comment]
@jevgenika мне бы понять, данный ишью вообще актуален ? Вопрос встал в связи обновлением дизайна страницы и в последствии чего отсутствие данных для изменений.

**Comment by NickShtefan** [comment]
Страница wellcome изменена согласно новому дизайну в issue #655, данная задача не актуальна
