### ISSUE TITLE
Формировать запрос на передачу токенов через URL

### ISSUE THREAD

**Issue by vadbars** [GolosChain/tolstoy#517]
Возможность формировать запрос на передачу токенов через URL страницы трансфера. Что-то вроде https://golos.io/@USER/transfers?to=XXX&amount=XXX&token=GBG&memo=XXXXXXX
По ссылке открывается модальное окно или страница кошелька с заполненными полями.

**Comment by vadbars** [comment]
На рудексе реализовано, если что. https://market.rudex.org/#/transfer?to=vdbrs&amount=1&memo=test&asset=OPEN.BTC

**Comment by b1acksun** [comment]
https://github.com/GolosChain/tolstoy/issues/468

**Comment by pokupo** [comment]
https://golos.io/@anonymous.author/transfers?to=@ivelon&amount=11.352&token=GBG&memo=Pokupo:%20%D0%9E%D0%BF%D0%BB%D0%B0%D1%82%D0%B0%20%D1%81%D1%87%D0%B5%D1%82%D0%B0%20%E2%84%963629-61d210a19fe5c1c6c1a0

В чем тут проблема? Судя по всему не принимает %20 и другие коды урл
