### ISSUE TITLE
Создать движок Голоса-ио для интегрирования на внешние сайты

### ISSUE THREAD

**Issue by alex-firsov** [GolosChain/tolstoy#518]
# Концепция движка

Нужен движок Голоса-ио для интеграции в популярные CMS (вордпрес и пр.). Он должен легко ставиться на любой форум/контент-сайт/стэндэлон блог владельцем домена/хостинга. Соответственно, весь его контент будет писаться в блокчейн Голоса и выводиться у него на домене и на Голосе-ио, комментарии должны работать по тому же принципу, они должны быть сквозными, чтобы их можно было писать/читать с домена автора или Голоса-ио.

## Выгоды и преимущества
Для владельца сайта это дает дополнительную монетизацию контента и аудиторию — автор пишет на своем домене, а получает вознаграждение и комментарии используя всю аудиторию Голос-ио. Для Голос-ио это дает дополнительных авторов, транзации и контент.

**Comment by Chiliec** [comment]
Анатолий уже запилил что-то подобное https://github.com/On1x/HiddenEngine

**Comment by vadbars** [comment]
У Вика есть прототип интеграции Голоса (и Стима) с WP. 
Синхронизация постов в обеих направлениях. Метки, конвертация кириллических тегов, категории, отложенный постинг, короткие ссылки, публикация от разных авторов, выбор ноды и т.п.  
https://golos.io/ru--otkrytyij-kod/@vik/wordpress 
https://github.com/vikxx/wordpress-golos-chain

На Стиме есть несколько реализаций легкого клиента с хостингом на GiitHub, Heroku и т.п. Я делал адаптацию одного из них для Голоса (https://github.com/vadbars/gitblog.github.io).

Нет апвоутов и операций с токенами/ассетами - тут нужен аналог steemconnect или https://steemful.com/ (это сервис от @recrypto на стиме, у него же есть модули для постинга WP->Steem и оплаты на сайте через steem/sbd).
