### ISSUE TITLE
Посты в Testnet.golos.io с первым тегом "test" не отображаются в Новом, Популярном, Актуальном

### ISSUE THREAD

**Issue by allfroyou** [GolosChain/tolstoy#520]
Если создать произвольный пост, но с первым тегом "test", он будет отображаться в профиле, но его не видно во вкладках Новое, Актуальное, Популярное:<hr>
![screenshot_8](https://user-images.githubusercontent.com/17462020/32577720-8c123c8e-c4e3-11e7-8b00-18d5faa32f1e.jpg)<hr>
![screenshot_9](https://user-images.githubusercontent.com/17462020/32577721-8d8a4192-c4e3-11e7-8a93-17ad2fbb0d22.jpg)<hr>
![test](https://user-images.githubusercontent.com/17462020/32577742-9b448bda-c4e3-11e7-9b87-aedd485fb41e.gif)

**Comment by b1acksun** [comment]
Тег test служебный используется для тестирования, поэтому скрывается со всех лент, кроме профиля,
