### ISSUE TITLE
Неопределенная оценочная стоимость нового аккаунта

### ISSUE THREAD

**Issue by vadbars** [GolosChain/tolstoy#521]
[testnet] После регистрации аккаунта не показывается его оценочная стоимость. 
"Оценка стоимости аккаунта - ₽ NaN"

Хотя Сила Голоса считается - 96.065 GOLOS

**Comment by vadbars** [comment]
Может быть это к @Nemo1369

**Comment by Nemo1369** [comment]
@vadbars Kind of a fine situation caused by unpublished feeds. I'm going to make it working just after I'ill finish fixing the platform-dependent synchronisation bug.
