### ISSUE TITLE
Странности с указанием цены в маркете

### ISSUE THREAD

**Issue by vadbars** [GolosChain/tolstoy#523]
[testnet]  Странности с указанием цены и количества ассетов в маркете. Разнится на порядок в нескольких местах.

![golos_testtesttest](https://user-images.githubusercontent.com/115528/32601787-ad48f122-c565-11e7-86cf-b9ef8f8dfb87.jpg)

**Comment by vadbars** [comment]
Может быть это к @Nemo1369

**Comment by Nemo1369** [comment]
Duplicate of https://github.com/GolosChain/golos/issues/230
