### ISSUE TITLE
Стек апвоутов

### ISSUE THREAD

**Issue by vadbars** [GolosChain/tolstoy#525]
Сейчас при попытке апвоута чаще, чем раз в 3 секунды пользователь получает сообщение "вы не можете голосовать чаще..." (не локализованное, кстати). Апвоут не засчитывается. Пользователь должен выждать 3 секунды и повторить действие. Это ломает весь user expiriens.

Почему бы не поставить поспешный апвоут в очередь и выполнить его через эти технологические три секунды, не обращаясь уже к пользователю? (Можно предварительно уведомить его сообщением типа "Будет исполнено через 3 секунды") .

**Comment by jevgenika** [comment]
Issue переносится в Golos Core

**Comment by Chiliec** [comment]
Кажется Стим это делает ещё одним слоем над блокчейном https://github.com/steemit/hivemind
