### ISSUE TITLE
Улучшить SEO настроив канонические URL в связи с появлением зеркала.

### ISSUE THREAD

**Issue by vikxx** [GolosChain/tolstoy#526]
https://golos.io/robots.txt
https://golos.blog/robots.txt

https://support.google.com/webmasters/answer/139066?hl=ru

**Comment by Chiliec** [comment]
Только при чём здесь роботс, это ж в разметке надо делать?

**Comment by vikxx** [comment]
> при чём здесь роботс

- метатег
- sitemap
- robots

Все это должно участвовать

**Comment by b1acksun** [comment]
неактуально
