### ISSUE TITLE
Настроить внутренние ссылки на «зеркалах»

### ISSUE THREAD

**Issue by alex-firsov** [GolosChain/tolstoy#527]
Внутренние ссылки на зеркалах должны вести на страницы на зеркалах, а не на основной сайт. Например, если сейчас люди заходят через golos.blog, нажимают какую-либо ссылку внутри сайта, то их перекидывает на golos.io. Должно перекидывать на эту ссылку на golos.blog.

**Comment by b1acksun** [comment]
неактуально
