### ISSUE TITLE
Сделать страницу с аналитикой

### ISSUE THREAD

**Issue by alex-firsov** [GolosChain/tolstoy#533]
Предлагаю сделать отдельную страницу со следующими данными:
______________________________
- Аккаунтов всего
- Новых аккаунтов за 24 часа / месяц + изменение к предыдущему периоду
- Постов за 24 часа / месяц + изменение к предыдущему периоду
- Авторов за 24 часа / месяц + изменение к предыдущему периоду
- Объем пула наград сейчас
______________________________
- Курс GOLOS к доллару
- Капитализация GOLOS в долларах
______________________________
- Кол-во просмотров страниц за 24 часа / месяц + изменение к предыдущему периоду
- Кол-во уникальных пользователей за 24 часа / месяц + изменение к предыдущему периоду
______________________________
На главную можно вынести:
- постов за 24 часа 
- авторов за 24 часа 
- пул наград 
- курс токена

Перед каждой цифрой иконка (человечек, текст, мешок с деньгами, лого) — этот блок сделать ссылкой на страницу с аналитикой.

**Comment by jevgenika** [comment]
https://github.com/GolosChain/tolstoy/issues/262

**Comment by jevgenika** [comment]
https://github.com/GolosChain/tolstoy/issues/396

**Comment by jevgenika** [comment]
https://github.com/GolosChain/tolstoy/issues/534

**Comment by NickShtefan** [comment]
Требования перенесены в issue #575
