### ISSUE TITLE
Показывать мощность голоса пользователя в профиле

### ISSUE THREAD

**Issue by alex-firsov** [GolosChain/tolstoy#534]
Добавть индикатор мощности голоса в профиль или на каждый экран по сквозному принципу (если пользователь залогинен).

**Comment by NickShtefan** [comment]
поле voting_power

**Comment by NickShtefan** [comment]
как это должно выглядеть?

**Comment by jevgenika** [comment]
@NickShtefan 
По клику на юзерпик пользователя отображается Мощность его Голоса  “Батарейки” в процентах - количество апвоутов (лайков), которые остались для реализации пользователем в течении суток.
Юзерпик высветляется, на его месте видим количество процентов.
Обводка уменьшается по кругу от синего к красному.
![image](https://user-images.githubusercontent.com/30616421/35738588-f3e42e0c-0837-11e8-89d9-04662bcc1f7b.png)

сквозную батарейку показывать в шапке рядом с юзерпиком в рамках редизайна

**Comment by BaroH4er** [comment]
Тестирование завершено. Ошибок нет - функционал кнопки работает исправно. 
Согласованный, новый дизайн отображения батарейки в шапке:
![image](https://user-images.githubusercontent.com/21989598/39924909-52ef0272-5532-11e8-8715-54215b8d1fcd.png)

**Comment by BaroH4er** [comment]
Исправлено.
