### ISSUE TITLE
Регистрация через Civic Secure Identity Ecosystem

### ISSUE THREAD

**Issue by Chiliec** [GolosChain/tolstoy#537]
[Предложил в посте](https://golos.io/golosio/@golosio/na-golos-io-poyavilas-novaya-udobnaya-registraciya#@chiliec/chiliec-re-na-golos-io-poyavilas-novaya-udobnaya-1511429458976), продублирую здесь.

[Civic](https://www.civic.com/app) — блокчейн приложение для авторизации на сайтах. Можно одной этой интеграцией решить сразу несколько задач — и пропиариться внедрением на блокчейн-медиа ресурсах и оказаться среди [крутого списка партнёров](https://www.civic.com/partners), возможно получить от них новую аудиторию, и точно получить удобный и надёжный способ верификации пользователей.

**Comment by pavelit** [comment]
Рано еще для регистрации civic использовать. Регистрация не упрощается никак. Для регистрации надо теперь скачать какой-то civic о котором не все знают и таких будет очень много. Указать там свои перс данные (что тоже покажется сомнительным большинству) и только после этого идти в golos.io на регу. В общем этот вариант через года два может и сгодится.
