### ISSUE TITLE
upvotes не показываются в ленте "Популярное"

### ISSUE THREAD

**Issue by gropox** [GolosChain/tolstoy#540]
Сделанные апвоты не подсвечиваюстя синим в ленте "Популярное" уже два - три дня. Если зайти в пост, и пост снова закрыть то значек апвота обновляется. Тот же эффект на разных компьютерах.

![upvotes gif](https://user-images.githubusercontent.com/26039472/33371346-ae8f491a-d4fa-11e7-9d69-6b460cee573e.gif)

**Comment by b1acksun** [comment]
https://github.com/GolosChain/tolstoy/commit/aab8957492e04c5cb8ff436a6d1fb61eef5c015a
