### ISSUE TITLE
Информация об ошибке появляется на другом слое страницы и ее не видно 

### ISSUE THREAD

**Issue by b1acksun** [GolosChain/tolstoy#541]
https://github.com/GolosChain/golos/issues/311

**Comment by Bacher** [comment]
Issue уже не актуально, сейчас ошибки выглядят вот так:

![screen shot 2018-06-21 at 12 45 20](https://user-images.githubusercontent.com/2598671/41711552-053d788a-7551-11e8-8e3e-3cd82f7c5acf.png)

**Comment by BaroH4er** [comment]
Тестирование завершено.
- [x] FIXED
