### ISSUE TITLE
После закрытия окна выплат, нет возможности посмотреть информацию о выплате

### ISSUE THREAD

**Issue by b1acksun** [GolosChain/tolstoy#542]
https://github.com/GolosChain/golos/issues/310

**Comment by NickShtefan** [comment]
Баг не воспроизводится  
Скриншот поста, ожидающего выплаты
![image](https://user-images.githubusercontent.com/6249597/39713787-b25ddf80-5230-11e8-8027-50f31240f3ec.png)

Скриншот поста, с закрытым окном выплат

![image](https://user-images.githubusercontent.com/6249597/39713827-d5077cbc-5230-11e8-9d77-a5ed3a1bb808.png)
