### ISSUE TITLE
кнопка "ХочуРаботуЗаКрипту"

### ISSUE THREAD

**Issue by lokkie12** [GolosChain/tolstoy#545]
Мне кажется, хорошим вариантом была бы кнопка ХочуРаботуЗаКрипту там, где раньше была яИдуНаГолосФест.

Под кнопкой - ссылка на пост с актуальными вакансиями в команды кор/голосио. Я нашла этот https://golos.io/ru--golos/@golos/nam-nuzhen-ty-vakansii-golosa

**Comment by Chiliec** [comment]
Хорошо работать за крипту, когда она постоянно растёт... Прикольнее будет, когда выплата совпадёт с коррекцией крипторынка 🤓
