### ISSUE TITLE
Добавить пиксели Facebook и ВКонтакте на сайт

### ISSUE THREAD

**Issue by alex-firsov** [GolosChain/tolstoy#546]
# Описание

Добавить на страницы сайта пиксели Facebook и ВКонтакте.

## Пиксели

- [x] Facebook
- [x] ВКонтакте

## Цель

Аналитика, проведение рекламных кампаний

**Comment by b1acksun** [comment]
Кроме sandbox, testnet, development

**Comment by NickShtefan** [comment]
Ожидаем регистрации пикселей
