### ISSUE TITLE
Добавить СТА popup для незарегистрированных пользователей

### ISSUE THREAD

**Issue by alex-firsov** [GolosChain/tolstoy#547]
# Описание

Добавить во все посты пользователей окна с призывом к регистрации на сайте и ссылкой на лендинг и регистрацию для незарегистрированных пользователей.

## Типы окон

- [x] Для топ 20 постов по просмотров
- [x] Для постов, заработавших больше $33
- [x] Для остальных постов

## Цель

Увеличение конверсии в регистрацию, увеличение количества пользователей.

**Comment by jevgenika** [comment]
@NickShtefan 
Для остальных постов важно

**Comment by alex-firsov** [comment]
Надо добавить аватарку Golos.io для третьего вида окон.
