### ISSUE TITLE
Пропуск новых постов

### ISSUE THREAD

**Issue by 21xhipster** [GolosChain/tolstoy#549]
Смотрим в новое на [golos.io](https://golos.io/created/ru--otkrytyij-kod) по определенному тэгу. Заходим к [толику](https://goldvoice.club/tags/ru--otkrytyij-kod/) и видим в 2-3 раза больше постов. Баг уже этот очень давно. Надо фиксить ASAP.

**Comment by b1acksun** [comment]
При вызове `{"id":11,"method":"call","params":[0,"get_discussions_by_created",[{"limit":20,"truncate_body":1024,"select_tags":["ru--otkrytyij-kod"]}]]}` из чейна приходит ответ
![image](https://user-images.githubusercontent.com/3322340/33690740-aed2bf94-daed-11e7-8d40-c028b5eb0056.png)
что соответствует выдаче на странице 
![image](https://user-images.githubusercontent.com/3322340/33690788-e26a4ec6-daed-11e7-9554-1230b5ade36e.png)

Причина пропуска в том, что некоторые посты содержат определенный тег не в первой пятерке тегов
![image](https://user-images.githubusercontent.com/3322340/33690938-7eaa4d7c-daee-11e7-9c74-69ce185f50d4.png)

**Comment by 21xhipster** [comment]
Понял. Может не будем так?

**Comment by b1acksun** [comment]
Не будем так - это о количестве тегов больше 5?

**Comment by 21xhipster** [comment]
Не будем так это о том, чтобы не учитывать тэги, которые после пяти :-)

**Comment by b1acksun** [comment]
Вызов методов `get_discussions_by_*` как раз и не учитывает

**Comment by t3ran13** [comment]
Мне кажется не должно быть разницы сколбко тегов, все должно работать нормалтно, а если количемтво тегов критично - нужно ограничивать количество на уровне блокчейна.

**Comment by NickShtefan** [comment]
#625
