### ISSUE TITLE
Настроить nginx

### ISSUE THREAD

**Issue by tomarcafe** [GolosChain/tolstoy#55]
В текущей конфигурации, при регистрации юзеров вылетает ошибка "могу с одного айпишника регистрировать только раз в 10 минут"

больше всего похоже, что айпи юзера до вебклиента не долетает, а долетает айпи например балансира.

**Comment by Undeadlol1** [comment]
Еще актуально? Или закрываем?

**Comment by tomarcafe** [comment]
пусть будет. еще переоткрывать придется..

**Comment by tomarcafe** [comment]
разве что ты майл закрыть хочешь

**Comment by Undeadlol1** [comment]
Майлстоун закрыть? Да, хочу

**Comment by tomarcafe** [comment]
тога закрываю, бо седня как раз доделов серьезно продвинулся с нгинкосм

**Comment by Undeadlol1** [comment]
Спасибо
