### ISSUE TITLE
HF0.2.0 Неверная ошибка при создании актива с точкой

### ISSUE THREAD

**Issue by gropox** [GolosChain/tolstoy#554]
Тут попытка создать актив с точкой. По идее, должна была быть ошибка о не существующем активе "VOTEFOR". В место этого появляется странное сообщение, как на скриншоте

![image](https://user-images.githubusercontent.com/26039472/33914639-5d53e5d8-df9f-11e7-9b77-bb16dde2b390.png)

Вот такое сообщение выдает cli_wallet при создании токена с таким же именем

![image](https://user-images.githubusercontent.com/26039472/33914749-f1735564-df9f-11e7-8162-4c7d6765df72.png)

**Comment by b1acksun** [comment]
Данная ошибка относится к библиотеке golos-js, [fix](https://github.com/GolosChain/golos-js/blob/master/src/auth/serializer/src/types.js#L46)
