### ISSUE TITLE
отображать тысячные награды после запятой

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/tolstoy#558]
отображать тысячные награды после запятой:
- [ ]  в постах
- [ ]  комментариях
- [ ]  ленте

**Comment by vadbars** [comment]
Думаю, что указание тысячных долей рубля только запутает новичков. К тому же сумма выводится не в общепринятом российском региональном формате 1 000,00 руб. (пробел отделяет тысячи и запятая отделяет доли рубля), а в западном 1,000.00 (запятая и точка).
Хорошо бы привести вывод денежных единиц в соответствие с региональным форматом.

**Comment by jevgenika** [comment]
- [ ] тысячные после запятой привести к региональному формату отображения: российском 1 000,00 руб. (пробел отделяет тысячи и запятая отделяет доли рубля), а в западном 1,000.00 (запятая и точка).
- [ ] тысячные после запятой показываем малькам, 
- [ ] с достаточной(определить ) репутацией можно не отображать тысячные

**Comment by NickShtefan** [comment]
В таком виде будет понятно? 
![image](https://user-images.githubusercontent.com/6249597/36040216-ea3809d4-0dd5-11e8-94e1-a59f9ebf2b3f.png)

Пусть пользователи сами определяют как им будут отображаться награды. 
Но, по умолчанию, пользователя с небольшой силой голоса показываем 3 знака. Вопрос в том, какую силу голоса считать низкой, и после какого значения по умолчанию показывать 2 знака?

**Comment by BaroH4er** [comment]
Тестирование завершено. Ошибок нет. [Отчет + чек-лист](https://docs.google.com/spreadsheets/d/1eRExPPYvQIBr9_NfAUo-CVk92aVlqvUPW94GATH2vkM/edit?usp=sharing).
