### ISSUE TITLE
Открыть зеркало Golos.io в Торе

### ISSUE THREAD

**Issue by alex-firsov** [GolosChain/tolstoy#559]
Открыть в Торе зеркало сайта Golos.io где будут доступны все статьи из блокчейна.

**Comment by NickShtefan** [comment]
зеркало доступно по адресу golos4naqn64true.onion

**Comment by 21xhipster** [comment]
Это восхитительно, парни. @jevgenika @insiderol Нужно это дело попиарить.

**Comment by muhazzz** [comment]
Только обратите внимание, что оно пока в read-only режиме. Можно только читать статьи, комменты и тд. Работу с вебсокетами ещё победить не успел.

**Comment by BaroH4er** [comment]
Время **полной** загрузки страницы от 40 до 180 сек // 0_-

**Comment by NickShtefan** [comment]
Доработать зеркало до полнофункционального приложения. 

- [ ] Возможность ставить лайки/флаги
- [ ] Возможность написать пост/комментарий
- [ ] Возможность совершить транзакцию.
