### ISSUE TITLE
перевести текст -стр не существует

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/tolstoy#565]
![image](https://user-images.githubusercontent.com/30616421/34357130-08ba3e56-ea4d-11e7-80b3-ab681c250404.png)
Перевести 
Текст - Страница, на которую вы попали не существует. Пожалуйста, проверьте правильность написания адреса или вернитесь назад. Также вы всегда можете перейти на Ленту и прочитать свежие посты.
новое\актуальное\ популярное\ промо

**Comment by kuchinskaya** [comment]
https://zpl.io/2yljKl9
https://zpl.io/VQ9A6wn
