### ISSUE TITLE
отображать закрепленные посты пользователя в окне профайла

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/tolstoy#566]
при нажатие на юзернейм пользователя
выводить окно профиля пользователя
- в ленте, 
- стр поста-как автора так и кураторов поста 
![image](https://user-images.githubusercontent.com/30616421/34389794-724fcd52-eb44-11e7-9fa6-48c8af69743f.png)
в окне кроме имени и юзернейма , 
- [x] отображать до 3 строчек описания профайла
- [x] до максимум 3 запинныных постов

![image](https://user-images.githubusercontent.com/30616421/34390149-909b3b28-eb46-11e7-8871-ec27cfd590eb.png)

- [x] кнопки подписаться\отписаться и заблокировать перенести под закрепленными постами, в нижнюю часть поста

**Comment by BaroH4er** [comment]
Done
