### ISSUE TITLE
Ссылку на приложение давать в мобильной версии сайта

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/tolstoy#568]
- В мобильной версии сайта вставить кнопку с ссылкой на приложение. Текст кнопки "Открыть в приложении". Кнопка появляется в нижней части экрана по центру.
- Отображать кнопку в мобильной версии сайта только для андройд устройств, для ios устройств кнопку для ios не отображаем
- В зависимости от устройства подставлять разную ссылку на маркет. Для андройд устройств ссылка https://play.google.com/store/apps/details?id=io.golos.golos
![image](https://user-images.githubusercontent.com/30616421/35577293-d4812678-05e9-11e8-901d-b99332d26db0.png)
- исходники кнопки
width: 190px;
height: 44px;
left: 371px;
top: 352px;
background: #1298FF;
border-radius: 4px

шрифт
font-family: Roboto;
font-style: normal;
font-weight: 500;
line-height: normal;
font-size: 14px

[Archive.zip](https://github.com/GolosChain/tolstoy/files/1696215/Archive.zip)

**Comment by BaroH4er** [comment]
Тестирование завершено. Ошибок нет.

**Comment by BaroH4er** [comment]
В результате заливки в песочницу нового функционала кнопка для Android больше не отображается. Невозможно отследить ошибку ручным тестированием - кнопка не отображается ни при каких условиях.
