### ISSUE TITLE
Добавить кнопку Google Play в верхнее меню

### ISSUE THREAD

**Issue by alex-firsov** [GolosChain/tolstoy#571]
# Задача

Добавить в верхнее меню Golos.io значок «Доступно в Google Play» (https://play.google.com/intl/en_us/badges/) со ссылкой на приложение https://play.google.com/store/apps/details?id=io.golos.golos.

Значок поставить правее логотипа Голос Чата. Дизайн адаптировать под Голос — то есть с инвертированным цветом фона и текста (фон белый, текст черный).

**Comment by NickShtefan** [comment]
![image](https://user-images.githubusercontent.com/6249597/35524656-3c740690-0533-11e8-9d91-355a67b08052.png)

необходимо выбрать где именно будет располагаться баннер. На скриншоте выше представлены три варианта

**Comment by jevgenika** [comment]
@NickShtefan согласован вариант расположения в верхней левой части шапки сайта,
- [ ] Если стоит русский язык стоит, то показываем кнопку по русски.
Если нет, то в любом другом случае - кнопку на английском.

**Comment by BaroH4er** [comment]
Тестирование завершено. Ошибки есть. [Отчет+чек-лист](https://docs.google.com/spreadsheets/d/1pYLo2vuie_Awa0gGfRSEFegbO0D5yAi68oCJLLyg_Jg/edit?usp=sharing).

**Comment by BaroH4er** [comment]
Тест завершен. Ошибок нет. [Отчет + чек-лист](https://docs.google.com/spreadsheets/d/13W4qOC-cCHwVFtn-Jcb5rYeT80kVPRM6VkyZkb_fBrE/edit?usp=sharing).
