### ISSUE TITLE
Разработка системы аналитики

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/tolstoy#575]

**Comment by alex-firsov** [comment]
Методология подсчетов активных пользователей Golos.io помесячно — сколько аккаунтов блокчейна Golos что-либо сделало за месяц (минимум одна транзакция) через Golos.io (а не суммирующим итогом за всю историю на платформе).

**Сделать форму, в которой данные из пункта А можно выводить на любые выбранные промежутки времени** (например, количество активных авторов в день с 10 октября 2017 по 15 января 2018).

**А. Cделать отдельную страницу со следующими данными:**

**Аккаунты**: 1. в golos blockchain, 2. в golos.io 

- Аккаунтов всего
- Новых аккаунтов за 24 часа + изменение к предыдущему периоду (проценты и количество) + график
- Постов за 24 часа + изменение к предыдущему периоду (проценты и количество) + график
- Авторов за 24 часа + изменение к предыдущему периоду (проценты и количество )+ график
- Объем пула наград сейчас (проценты и количество)

**Градации**: 24 часа, 7 дней, Месяц, Год, и сделать возможность выбора промежутка времени (от такой то даты до такой то даты).

- Курс GOLOS к доллару с CoinMarketCap + график
- Капитализация GOLOS в долларах + график

**Градации**: 24 часа, 7 дней, Месяц, Год, и сделать возможность выбора промежутка времени (от такой то даты до такой то даты).

- Кол-во просмотров страниц за 24 часа + изменение к предыдущему периоду (проценты и количество) через API GA + график
- Кол-во уникальных пользователей за 24 часа + изменение к предыдущему периоду (проценты и количество) через API GA + график

**Градации**: 24 часа, 7 дней, Месяц, Год, и сделать возможность выбора промежутка времени (от такой то даты до такой то даты).

**Б. Данные для выноса на главную (будет аккуратно интегрирована в новый дизайн):**

- сколько создано новых постов за 24 часа
- сколько авторов, которые написали хотя бы один пост за 24 часа
- пул наград сейчас
- курс токена golos к доллару сейчас
- 

**Для дизайнера**: 4 иконки и 4 цифры, которые редиректят на страницу аналитики + подсказка при наведении.

**Comment by litrbooh** [comment]
>Методология подсчетов активных пользователей Golos.io помесячно — сколько аккаунтов блокчейна Golos что-либо сделало за месяц (минимум одна транзакция) через Golos.io

Вы хотите посчитать пользователей или активные аккаунты считая тысячи ботов? И что значит транзакции через Golos.io? Вам не интересно сколько всего на голосе пользователей и сколько юзают именно ваше приложение?

**Comment by litrbooh** [comment]
@NickShtefan , уже сделали? где посмотреть?
