### ISSUE TITLE
Ошибки при загрузке изображений (редактор поста, юзерпик профиля)

### ISSUE THREAD

**Issue by sualex** [GolosChain/tolstoy#577]
Для решения проблемы с загрузкой изображения добавьте скриншот информации об ошибке тут. Для этого, пожалуйста, откройте консоль в вашем браузере, это можно это сделать с помощью комбинации Ctrl/Cmd+ Shift + J или из меню Developer tools (Инструменты Разработчика) -> Console (Консоль) скопируйте информацию об ошибке сюда ( не все содержимое консоли, а последнее красное сообщение, где есть путь /images/golos.io ), но лучше сделать скриншот и приложить.
Пример скриншота :
![image.png](https://images.zenhubusercontent.com/5a3000988a75884b908adf0b/da708765-c8fd-4a44-9fdf-25f2e5d3f697)

**Comment by zapominai** [comment]
После вставки и 100% загрузки:
![default](https://user-images.githubusercontent.com/8572404/35203484-fbb11fcc-ff5a-11e7-8c65-1284750728ab.png)
в логах:
![default](https://user-images.githubusercontent.com/8572404/35203519-276cdc96-ff5b-11e7-9465-81dc3e4d4065.png)

**Comment by zapominai** [comment]
Похоже размер большой, картинка меньшего размера вставилась без ошибок.
