### ISSUE TITLE
создать серию подсказок для первого входа новичка

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/tolstoy#579]
- [ ] создать системную серию подсказок, обучающую новичка
 ![image](https://user-images.githubusercontent.com/30616421/35141990-94ea1dcc-fd05-11e7-86cf-65eb3b8bdfde.png)
- [ ] показывать подсказки успешно зарегистрированному , вошедшему первый раз на сайт

**Comment by NickShtefan** [comment]
- [ ] Составить карту подсказок с их очередностью и информацией, содержащейся в самой подсказке
- [ ] Реализовать дизайн
