### ISSUE TITLE
Заголовки на англ яз рисуются шрифтом без засечек

### ISSUE THREAD

**Issue by petermz** [GolosChain/tolstoy#58]
Англ заголовок внизу бросается в глаза:

<img width="965" alt="screen shot 2016-10-18 at 19 35 00" src="https://cloud.githubusercontent.com/assets/16533006/19487254/9ea12224-956a-11e6-984b-833608df5ba5.png">

Если заголовок на двух языках, получается вообще мешанина:
<img width="828" alt="screen shot 2016-10-18 at 19 38 36" src="https://cloud.githubusercontent.com/assets/16533006/19487253/9e9ea5f8-956a-11e6-9608-3ea74a3524be.png">

Мне кстати шрифт без засечек больше нравится, я бы им отрисовывал и заголовок и текст... но по крайней мере стиль должен быть какой-то один

**Comment by petermz** [comment]
Ссылки на посты:
https://golos.io/ru--delegaty/@steve-walschot/delegat-steve-walschot-sozdatel-steempay-teper-na-golose
https://golos.io/golos/@fyrstikken/nichego-sebe-golos-yavlyaetsya-udivitelnym-budushee-pribylo

**Comment by Undeadlol1** [comment]
Похоже это был временный баг. Проверил, уже не актуально.
Если Вы все еще сталкиваетесь с этой проблемой, то, пожалуйста напишите об этом и укажите браузер, которым пользуетесь.

**Comment by petermz** [comment]
Да, сейчас всё хорошо

**Comment by Undeadlol1** [comment]
Спасибо.
