### ISSUE TITLE
Бага на бирже

### ISSUE THREAD

**Issue by litrbooh** [GolosChain/tolstoy#580]
Размещаю заявку на покупку голосов по цене 1.48000 - такая цена стоит в продаже.

А появляются какие-то мутные ставки по цене меньше и ордер на покупку не срабатывает.

![default](https://user-images.githubusercontent.com/22373216/35145964-b053e808-fd1a-11e7-8ef7-0d6a56ad8af3.png)

**Comment by gropox** [comment]
Возможно это из-за ошибко округления. Бывает, что создаешь ордер на продажу, вводишь в форме сумму токенов на продажу, после чего форма автоматом корректирует цену продажи, но из-за округления получается меньше и в итоге ордер попадает в стакан bids и покупки не происходит. Лечится тем, что после ввода суммы токенов, которые хочется продать, надо кликнуть еще раз по желаемой цене в стакане asks, тогда цена в форме ордера обновится из стакана и скорректируется сумма токенов на продажу. В этом случае ордер сразу закрывается.

**Comment by t3ran13** [comment]
да, проблема в округлении. на стиме такая же фигня.
нужно при покупке всегда округлять в большую,  а при продаже в меньшую чем выставил автор) и все будет гуд
