### ISSUE TITLE
Не отображаются апвоуты в треде "Популярное"

### ISSUE THREAD

**Issue by litrbooh** [GolosChain/tolstoy#581]
У меня в "популярном" не отображаются лайки проставленные, вот вам два скрина после заходов в посты лайки есть.
![default](https://user-images.githubusercontent.com/22373216/35146054-efd3c3f4-fd1a-11e7-9886-4112fb6e604c.png)

А после нажатия F5 их уже нету.
![default](https://user-images.githubusercontent.com/22373216/35146068-f85984aa-fd1a-11e7-953d-1217451534eb.png)

**Comment by litrbooh** [comment]
Слушайте, фикс вроде был, приоритет вроде хай. А когда всё это будет на странице?

**Comment by b1acksun** [comment]
Сегодня зарелизили фикс

**Comment by vista7** [comment]
Дамы и господа разрабы, точно такой же баг (как описывает Литрбух) наблюдается у меня и **в обычной ленте новостей (там где подписки пользователя)**. Причём, касается это в основном только свежих постов. Инфа 100%. Началось это не так давно - спустя некоторое время после ХФ 0.17, насколько помню. 
Прошу открыть этот issue и поработать над данным багом, дабы не создавать новый issue.
