### ISSUE TITLE
Добавить возможность добавлять комментарий к репосту

### ISSUE THREAD

**Issue by alex-firsov** [GolosChain/tolstoy#582]
# Задача

Добавить возможность добавлять комментарий к репосту. То есть чтобы при репостинге какого-либо поста в ленте было видно что это репост и комментарий к нему (или его начало, если комментарий длинный).

**Comment by jevgenika** [comment]
зависит от добавления полей в операцию follow plugin https://github.com/GolosChain/golos/issues/758
