### ISSUE TITLE
Добавить в пост счетчик репостов и ссылки на них

### ISSUE THREAD

**Issue by alex-firsov** [GolosChain/tolstoy#586]
- [ ] рядом с иконкой репоста стоит счетчик-к-во репостов
- [ ] если есть 1 и более репостов-при клике на к-ва репостов вызывается доп окно со списком юзеров сделавших репост, указывается их ник, аватар 
- [ ] при нажатии на имя пользователя идет редирект на пост

**Comment by jevgenika** [comment]
связано с задачей https://github.com/GolosChain/tolstoy/issues/767
