### ISSUE TITLE
Поправить отображение всплывающих окон на мобильной версии сайта

### ISSUE THREAD

**Issue by alex-firsov** [GolosChain/tolstoy#587]
Верстка всплывающих окон на мобильной версии сайта разваливается, надо поправить.

![image](https://user-images.githubusercontent.com/30616421/36020641-1107159a-0d8c-11e8-85bc-41b3b7d789d0.png)

**Comment by NickShtefan** [comment]
надо найти все места, где всплывающие окна отображаются неверно, и приложить сюда скриншоты

**Comment by BaroH4er** [comment]
# Galaxy S5 `width == 360` 

![galaxy5-4](https://user-images.githubusercontent.com/21989598/36034781-310a69fc-0dc6-11e8-87d3-32b5defd5153.png)

![galaxy5-5](https://user-images.githubusercontent.com/21989598/36034841-60f2bf52-0dc6-11e8-8a0c-1ecfb44ccb53.png)

![galaxy5-6](https://user-images.githubusercontent.com/21989598/36034842-6111ff48-0dc6-11e8-8a58-98e1c90fa8ae.png)

# Galaxy S5 `width == 640` 
![galaxy5-10](https://user-images.githubusercontent.com/21989598/36034843-612dd39e-0dc6-11e8-8c96-edc45c1d6243.png)

**Comment by BaroH4er** [comment]
# Посты, заработавшие больше $33
## Везде где `width < 770px` // Всплывающие окно отображается некорректно: 

![windowmax770-1](https://user-images.githubusercontent.com/21989598/36068234-798cb470-0ee1-11e8-8a27-a77f65a8c74c.png)
![windowmax770-2](https://user-images.githubusercontent.com/21989598/36068235-79ab540c-0ee1-11e8-8b24-2364493d4070.png)

## `Одна из основных проблем, это реализация <div class="cta-block-text-regular"/>`


## Зы. Радиус у окна стоит  убрать:

![window-3](https://user-images.githubusercontent.com/21989598/36068248-ad9cc48a-0ee1-11e8-8d36-5b84d7087b48.png)

![window-4](https://user-images.githubusercontent.com/21989598/36068281-92f0286a-0ee2-11e8-9916-ecf0c196e638.png)

**Comment by BaroH4er** [comment]
Осталась **проблема**: заработанная сумма вытаскивается в отдельный блок,, который в свою очередь отображается в новой строке.

![image](https://user-images.githubusercontent.com/21989598/40681107-e12b1c30-6390-11e8-8638-39af5e4bf889.png)

**Comment by cudr** [comment]
@BaroH4er, Можно описание того какой именно вид требуется?

**Comment by BaroH4er** [comment]
@cudr выше был предложен вариант:
> запихать весь текст в один единственный `<p class="left cta-block-text-regular"/>`

_включая заработанную сумму_

Но я подозреваю что с этим могут возникнуть трудности. Если да, то данный вопрос стоит поднять в slack канале #mobile_app.

**Comment by jevgenika** [comment]
В  случаи, когда  в моб версии баннер в футоре и кнопка ведущая в андройд приложение накладываются друг на друга,  исключить показ одной из кнопок. 
Показать неавторизованному пользователю только баннер, кнопку приложения показывать только для зарегистрированных пользователей.
![image](https://user-images.githubusercontent.com/30616421/42209334-b3b9a774-7eae-11e8-805d-5a941281ead8.png)

**Comment by Bacher** [comment]
Всё поправил.

**Comment by BaroH4er** [comment]
Done.

![image](https://user-images.githubusercontent.com/21989598/42479597-5620d45a-83e2-11e8-8341-4b56132c9a69.png)
