### ISSUE TITLE
Точки и запятые в числах

### ISSUE THREAD

**Issue by petermz** [GolosChain/tolstoy#59]
Сила голоса 5.000 (точка), оценка стоимости 15,714 (запятая). Сбивает с толку.

<img width="211" alt="screen shot 2016-10-18 at 19 48 22" src="https://cloud.githubusercontent.com/assets/16533006/19487517/e3a929e2-956b-11e6-962c-140b4da1cb59.png">

**Comment by Undeadlol1** [comment]
Спасибо что сообщили.
Если где-то будут еще разногласия, пожалуйста скажите.
