### ISSUE TITLE
Создать онлайн уведомления

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/tolstoy#591]
- [x] 1. **upvote статьи - online уведомление**

У пользователя всплывает окно уведомления с количеством апвоутов за пост, если у статьи появились новые апвоуты за один блок.
Окно содержит в себе ссылку на пост за который пришел апвоут и количество апвоутов.
Окно пропадает в течение 5 секунд, если окно открыто.
При нажатии на окно уведомления происходит переход за пост.
- [x] Окно уведомления вида имеет вид:
Иконка апвоута+текст "За ваш пост (ссылка) проголосовали "73" (счетчик) раза."
- [x] Если апвоут один нотификация имеет вид:
userpic+username поддержал ваш пост (ссылка)
- [x] Если пост получил флаг (downvote) нотификация имеет вид:
Иконка флага+текст “Ваш пост (ссылка) получил 2 (счетчик) флага”
- [x] Если флаг один нотификация имеет вид:
userpic+username поставил флаг вашему пост (ссылка)

- [x] 2. **Трансфер уведомление**

При поступлении новых средств на счет у пользователя всплывает окно уведомления, в котором содержится:
username от кого пришел трансфер + его юзерпик
сумма трансфера
При нажатии на уведомление происходит перенаправление к экрану трансферов.
Окно уведомления вида - Userpic+username-текст -сумма. Пример “Пользователь перевел вам __сумму.”

- [x] 3. **Новый комментарий**

При поступлении нового комментария к посту или комментарию пользователя всплывает окно уведомления. При нажатии на уведомление пользователь переходит на комментарий.
Всплывающие онлайн уведомление содержит:
username+userpic
ответил на ваш пост\ комментарий (ссылка на пост\комментарий)

[Archive.zip](https://github.com/GolosChain/tolstoy/files/1767218/Archive.zip)

**Comment by NickShtefan** [comment]
Информация о поступивших апвотов, формируется один раз в блок, например если в одном блоке пришло 10 апвоутов, то уведомление имеет вид
"за ваш пост проголосовали 10 раз". Если у пользователя несколько постов, то уведомление приходит по каждому посту.
Данное правило действует на все виды онлайн уведомлений. Например если в одном блоке к посту пользователя пришло 10 комментариев, то уведомление будет иметь вид "получено 10 новых комментариев к вашему посту"
Транзакции в сторону пользователя не агрегируются. Т.е. каждая транзакция выводится отдельным уведомлением, даже если в одном блоке было несколько транзакций.

**Comment by BaroH4er** [comment]
## Не соответствует дизайн

**Проблема**: Верстка нотификации не соответствует макету дизайна нотификации. 

**Результат**: 

![image](https://user-images.githubusercontent.com/21989598/38530039-028501f8-3c71-11e8-934a-d1026d128c5d.png)
![image](https://user-images.githubusercontent.com/21989598/38530094-4c123886-3c71-11e8-8270-b636dc8ce6f3.png)

**Ожидаемый результат**: 

![image](https://user-images.githubusercontent.com/21989598/38530082-414ae9ca-3c71-11e8-8d43-db0ad77f0209.png)

<hr/>

- [ ] Верстка согласно макету
- [ ] Убрать отображение наименований(содержания) поста/комментария/блога 

<hr/>

## Уведомление о снятии голоса 

**Проблема**: При снятии голосов с поста или комментария, нотификация сообщает автору об обратном: "имя поддержал ваш пост" и "имя поддержал ваш комментарий".

**Воспроизведение**:

1. Проголосовать за пост
└ Автору пришло уведомлении "имя поддержал ваш пост"
2. Снять голос с поста


**Результат**: Автору пришло уведомлении "имя поддержал ваш пост".
**Ожидаемый результат**: Автору не пришло никакого уведомления.

<hr/>

- [ ] Убрать нотификацию при снятии голоса с поста/комментария 

<hr/>

**Comment by sualex** [comment]
В случае отсутствия аватара у пользователя ставим плейсхолдер в виде силуэта 
![image](https://user-images.githubusercontent.com/19490632/38546339-0ea2c83c-3cb5-11e8-8cab-faa058e4c050.png) или вообще не рендерим никакое изображение, а только текст
![image](https://user-images.githubusercontent.com/19490632/38546404-3b51de04-3cb5-11e8-8b61-6432769101f6.png)
?

**Comment by BaroH4er** [comment]
## Даш под всей надписью в уведомлении перевода средств

**Проблема**: При каждом уведомлении о трансфере, вылазит голубой даш под всем текстом. 

**Воспроизведение**:

1. Открыть кошелек авторизованного пользователя
2. Открыть выпадающее меню цифровых токенов ГОЛОС или Золотой
![image](https://user-images.githubusercontent.com/21989598/38822892-7cf2b570-41ad-11e8-9792-4354312d249a.png)
3. Выбрать пункт "Передать".
4. Совершить минимальный трансфер средств на тестовый аккаунт(аккаунт к которому есть доступ, авторизован в момент воспроизведения).
5. Проверить уведомление на тестовом аккаунте. 


**Результат**: Даш под всей надписью в уведомлении перевода средств.
![image](https://user-images.githubusercontent.com/21989598/38821952-b426848e-41aa-11e8-9e54-fef5d1d32c7e.png)
**Ожидаемый результат**: Прерывистое подчеркивание отсутствует. 
![image](https://user-images.githubusercontent.com/21989598/38822018-e675abe0-41aa-11e8-80b9-b3bf024f9e02.png)

<hr/>

- [ ] Прерывистое подчеркивание отсутствует.  

<hr/>

**Comment by BaroH4er** [comment]
Тестирование завершено. Ошибок не обнаружено.
