### ISSUE TITLE
Обновить информацию на стр golos.io/about

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/tolstoy#597]
Добавить и обновить информацию  на стр https://golos.io/about

- [x] 1. - Убрать логотип esteem, Вставить иконку приложения Golos.io
- Убрать ссылку esteem, заменить на https://play.google.com/store/apps/details?id=io.golos.golos 
- [x] Заголовок поправить на "Приложение Golos.io для Android"
- [x]  описание поправить на " Мобильное приложение для Андройд для чтения, публикации, голосований, коментирования.

- [x] Заменить лого доски почета
![golosboard-logo](https://user-images.githubusercontent.com/30616421/35798535-c20dad1e-0a6b-11e8-8f88-c1a38a8e765f.png)

- [x]  убрать GolosD

- [x] добавить Golos Explorer
ссылка https://explorer.golos.io/
описание  - Сервис для просмотра транзакций в блокчейне Голос в реальном времени и поиска информации по ним

- [ ]1.1 Добавить прилижения
- [x] Мобильная платформа SteepShot
Социальная платформа, вознаграждающая пользователей за публикации фотографий о своей жизни и окружающем мире.
Вставить ссылку https://steepshot.io/
логотип ![image](https://user-images.githubusercontent.com/30616421/38127367-2a8e88aa-33f6-11e8-8031-a3b3c95266b0.png)

- [ ] GoldVoice.club - социальная сеть 
Вставить ссылку https://goldvoice.club/

- [x] MapalaNet — сообщество самостоятельных путешественников.
Вставить ссылку http://mapala.net

- [x] Сайт OnePlace
Веб-клиент для блокчейнов Golos и Steem.
ссылка https://oneplace.media/g

- [x]  CPEDA.SPACE
социальная сеть на блокчейне Голос
https://cpeda.space/socnet/

- [x] База знаний Golos Wiki
Вики является результатом коллективного труда. Каждый может поучаствовать в ее развитии.
https://wiki.golos.io/

- [x] Фотопремия Golos Photography Awards Первая криптовалютная награда в области фотографии, созданная на базе медиа-блокчейна «Голос»
http://golosphoto.ru/

- [x] Pokupo - Платформа для создания интерент магазина за 10 минут и 0 рублей без абонентской платы. 
Вставить ссылку https://pokupo.ru
Вставить логотип 
![logo200](https://user-images.githubusercontent.com/30616421/36085928-f0e7575a-0fd1-11e8-925f-7cb52271638d.png)

- [x] Добавить прилижение
заголовок "Статистика аккаунта"
Описание Сервис для просмотра статистики аккаунта http://golos.accusta.tk
вставить ссылку http://golos.accusta.tk/
![accusta_logo](https://user-images.githubusercontent.com/30616421/36090617-b960dcbc-0fe9-11e8-87e0-3b6a5cce4b77.png)

- [x] В конца блока с приложениями по центру добавить тест "Больше приложений для блокчейна Голос". Вставить ссылку в текст  http://chainstore.io,

- [x] 2. Заменить Машу Листван, на Юлия Родникова
https://golos.io/golosio/@yulia.rodnikova
почта community@golos.io

- [x] 3. Добавить фото и ссылки на гитхаб и аккаунт на голосе
Николай Штефан, Team Lead, Scrum Master
https://golos.io/@nickshtefan/
https://github.com/NickShtefan

- Сергей Монастырский, iOs dev
https://golos.io/@msm72/
https://github.com/Monserg

- Алеся Николаенкова, Support manager
https://golos.io/@chinpu

Алексей Гутник  Web dev 
https://golos.io/@sualex
https://github.com/sualex
 
Евгений Паршин  QA Tester
https://golos.io/@dekol 
https://github.com/BaroH4er

- [x] 4. Поменять очередность юзерпиков Golos.io
Георгий, Евгения, Николай, Игорь
Денис, Павел, Юрий, Сергей
Александр Фирсов, Юлия Родникова, Денис Белых, Алеся
Алексей, Евгений Паршин

- [ ] 5. Заменить статусы
Игорь\ JS Ninja
Павел\ Web dev
Мария Дьячук  Community Manager
Евгения Харченко CMO, Product Owner

- [x] 6. добавить ссылку на фб и иконку фб
Александр Фирсов
https://www.facebook.com/alex.v.firsov

Jevgenika  ссылку на фб и иконку фб и linkedin
https://www.facebook.com/jevgenija.kharchenko
https://www.linkedin.com/in/jevgenija-kharchenko-1a816b10/

- [x] 7. добавить ссылку на аккаунт golosio рядом с Golos.io https://golos.io/@golosio и ссылку на чат с иконкой телеграмма https://t.me/golos_support

добавить ссылку на goloscore соответсвенно https://golos.io/@goloscore и ссылку на чат ссылку на чат с иконкой телеграмма https://t.me/goloscoretech

- [x] 8. Добавить новых людей в панель Golos Core
- [x] 8.1 Убрать Михаил Комаров 
- [x] 8.2. добавить 
Андрей Фалалеев
https://github.com/afalaleev
https://golos.io/@andreypf
Team Lead, Блокчейн разработка

Владимир Павлив
Блокчейн разработка 
https://golos.io/@abgvedr  
https://github.com/vpavliv 

Константинов Константин 
блокчейн разработка 
https://github.com/zxcat 
https://golos.io/@zxcat

Тимур Купаев
Data scientist
https://github.com/timurkupaev
https://golos.io/@timurku/

Ерлан Шиндаулетов
https://github.com/epexa
https://golos.io/@epexa
Инженер-программист

заменить фото Антону Корпусенко

- [x] 8.3 Поменять очередность юзерпиков Golos Core 
Андрей Фалалеев, Александр Б, Тимур Купаев, Мария Д, 
Антон Корпусенко, Константинов Константин, Владимир Павлив, Ерлан Шиндаулетов

- [x] 9. поменять поля местами.
- поле Команда (Вся команда, основатели и посты) поставить сразу поле поле Видео.
- после поля Команда - вставить поле Инструменты Голоса, 
- Вопросы и ответы вставить после инструментов голоса.  На текст "вопросы-ответы"вставить ссылку на вики https://wiki.golos.io/

- [x] 10. В поле видео после вставленного видео вставить  заменить текст и кнопку
текст: "Golos.io — блог-платформа следующего поколения. Зарегистрируйтесь, чтобы публиковать свои истории и комментарии и получать за это вознаграждения!"
Кнопка "Создать аккаунт" ссылка на регистрацию https://golos.io/create_account
Кнопка "Узнать больше" ссылка https://golos.io/start

- [ ] 11. Поправить, зафиксировать текст Golos в локализированной версии сайта. Голос, при смене языка интерфейса, должен переводится как Golos
![image](https://user-images.githubusercontent.com/30616421/35979118-284e47ba-0cf0-11e8-90b8-adee08073176.png)

- [ ] поправить перевод -вместо Voice media player - Golos blockchain.

- [x] 12. Поправить год с 2017 на 2018 в футере

- [x] 13. Отцентровать название команд в моб версии сайта

- [x] 14. убрать блок с послами Голоса

- [ ] 15. убрать логотип и ссылку мапалы и футера

**Comment by BaroH4er** [comment]
Тестирование завершено. Найдены ошибки:

- [ ]  1. В разделе инструменты, не хватает продукта **GoldVoice.club** - социальная сеть. Вставить ссылку https://goldvoice.club/

- [ ] 2. В разделе команды Golos.io, у Евгении Харченко не хватает **CMO**, помимо Product Owner.

- [ ] 3. Невозможно затестировать из-за отсутствия переключения локализации:
> Поправить, зафиксировать текст Golos в локализированной версии сайта. Голос, при смене языка интерфейса, должен переводится как Golos

- [ ] 4. Невозможно затестировать из-за отсутствия переключения локализации:
> поправить перевод -вместо Voice media player - Golos blockchain.

- [ ] 5. Непонятно что имелось ввиду под футером, но так-как в разделе партнеры был удален только mapala , футер явно до сих пор там) 
> убрать логотип и ссылку мапалы и футера

- [ ] 6. Не отображается логотип:
![image](https://user-images.githubusercontent.com/21989598/39939826-2951bf3a-5560-11e8-9b21-0fe919b097e6.png)

- [ ] 7. Не отображается логотип:
![image](https://user-images.githubusercontent.com/21989598/39939843-3237a628-5560-11e8-91d4-af06e31ebade.png)

- [ ] 8. Не отображается логотип:
![image](https://user-images.githubusercontent.com/21989598/39939858-3dc87008-5560-11e8-9a72-7ffc098f20e5.png)

- [ ] 9. Не отображается логотип:
![image](https://user-images.githubusercontent.com/21989598/39939872-4bbc00bc-5560-11e8-8ff8-1891fd3429ac.png)

- [ ] 10. Не отображается картинка:
![image](https://user-images.githubusercontent.com/21989598/39939947-5f9f9508-5560-11e8-8705-e2a4f1e05f95.png)

**Comment by jevgenika** [comment]
Поправить и обновить информацию на стр

- 1. [ ] оставить шапку сайта, но убрать ленты 
- 2. [ ] убрать раздел Golos Fund и Основатели
- 3. [ ] убрать раздел инструменты 

- 4. [ ] поправить раздел Партнеры
- [ ]  убрать всех кроме Куны, Форклога
- [ ]   добавить альтернативных клиентов Голоса в раздел партнеры соглано предоставленому списку

- 5. [ ] поправить информацию в разделе Команда соглано предоставленой инфнормации
- 6. [ ] поправить предыдущие комментарии от @BaroH4er

**Comment by marijadia** [comment]
Добавить:
Анна Чемерицкая - Community manager -  https://golos.io/@annaeq https://github.com/annaeq
Вадим Кайнаров - С++ dev - https://github.com/kaynarov, https://golos.io/@kaynarov
Юлия Журавлева - C++ dev - https://github.com/maslenitsa93 https://golos.blog/@maslenitsa
Александр Назаров - Технический писатель -  https://github.com/anazarov79
Убрать: 
Александр Боргардт
Владимир Павлин
Изменить:
Мария Дьячук - Project manager - https://golos.io/@mariadia https://github.com/marijadia
Тимур Купаев - Блокчейн аналитик - https://golos.io/@timurku https://github.com/timurkupaev

**Comment by jevgenika** [comment]
- [ ] добавить галерею  скринов  с возможностью пролистывания их каруселью
- [ ] разные для русск и англ стр

**Comment by BaroH4er** [comment]
Fixed.

**Comment by BaroH4er** [comment]
## Команды - добавить отступы 

**Проблема:** для блоков с текстами
>Разработка, поддержка и развитие клиента Golos.io - Новости проекта

и

>Разработка, поддержка и развитие блокчейна Golos - Новости проекта

 - [ ] Добавить отступы с права и слева `>=5px`.
 
![image](https://user-images.githubusercontent.com/21989598/41653505-f68c2c04-748e-11e8-9cb1-615f3b4a2148.png)![image](https://user-images.githubusercontent.com/21989598/41653492-ed97d1d4-748e-11e8-8f94-b0df67ad1b04.png)

**Comment by BaroH4er** [comment]
@jevgenika для добавления галереи потребуется отдельное ишью.

**Comment by alex-firsov** [comment]
По странице /about на песочнице:

1. Поменять текст «Golos.io - это блог-платформа, построенная на децентрализованной системе блокчейн.» на текст «Golos.io — это блог-платформа, построенная на медиаблокчейне Голос.»
и сделать его заголовком.

2. Поставить на место слетевшие заголовки рубрик Голосио и Голоскор

3. Заменить «Новости проекта» на «Читать блог Golos.io — @golosio.»
и «Читать блог Golos Core — @goloscore.» и вынести в отдельную строку.

**Comment by BaroH4er** [comment]
Done

**Comment by marijadia** [comment]
Убрать со страницы Команды из Golos Core:
Ростислав Величко
Тимур Купаев
Ерлан Шиндаулетов

**Comment by BaroH4er** [comment]
Done
