### ISSUE TITLE
SF 0.16.5. Remove get state api call

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/tolstoy#601]
- [x]  Написать Unit тесты
- [x] Обновление кода вызовов api

**Comment by b1acksun** [comment]
https://github.com/GolosChain/tolstoy/commit/261824a9d829fcc493161b832337d5478c0eb6e0
https://github.com/GolosChain/tolstoy/commit/ed0e145c4de9a569b280757db130b0c27b7206ed
https://github.com/GolosChain/tolstoy/commit/9ed988ca1f72595522af74c7d3201b1bc67f887b
https://github.com/GolosChain/tolstoy/commit/ca52b40b2bbab33514bfe323b1297db590c44559
https://github.com/GolosChain/tolstoy/commit/d438667c7b98de7122bcced1a29e092a210514b1
