### ISSUE TITLE
Unit тестирование редактора постов и комментариев 

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/tolstoy#602]
- [ ] определить список тестов

**Comment by BaroH4er** [comment]
## 1. Пустая публикация - проверка на попытку публикации без заполнения минимально обязательных полей

## 2. Публикация без голосования:
**Заголовок** - проверка максимального количества символов
**Toolbar**:
1. Heading
2. Bold
3. Italic
4. Bold+Italic
5. Heading+Italic
6. Code
7. Quote
8. Code+Italic
9. Quote+Code+Italic
10. Generic List
11. Numbered List
12. Generic List + Numbered List 
13. Numbered List + Generic List
14. Generic List + Bold + Italic + Code
15. Numbered List + Bold + Italic + Code
16. Generic List + Numbered List + Bold + Italic + Code
17. Numbered List + Generic List + Bold + Italic + Code
18. ink 
19. Image
20. Video
20.1) YouTube
20.2) ...

**Drag and drop**:
- jpeg
- png
- ...

**Tags**: 
- Количество
- Длина

## 3. Публикация с голосованием:
**Заголовок** - проверка максимального количества символов
**Toolbar**:

1. Heading х6
2. Bold
3. Italic
4. Bold+Italic
5. Heading+Italic
6. Code
7. Quote
8. Code+Italic
9. Quote+Code+Italic
10. Generic List
11. Numbered List
12. Generic List + Numbered List 
13. Numbered List + Generic List
14. Generic List + Bold + Italic + Code
15. Numbered List + Bold + Italic + Code
16. Generic List + Numbered List + Bold + Italic + Code
17. Numbered List + Generic List + Bold + Italic + Code
18. Link 
19. Image
20. Video
20.1) YouTube
20.2) ...

**Drag and drop**:
- jpeg
- png
- ...

**Tags**: 
- Количество
- Длина

Чек бокс проголосовать 

## 4. Публикация с наградой - силой голоса 100%
**Заголовок** - проверка максимального количества символов
**Toolbar**:

1. Heading х6
2. Bold
3. Italic
4. Bold+Italic
5. Heading+Italic
6. Code
7. Quote
8. Code+Italic
9. Quote+Code+Italic
10. Generic List
11. Numbered List
12. Generic List + Numbered List 
13. Numbered List + Generic List
14. Generic List + Bold + Italic + Code
15. Numbered List + Bold + Italic + Code
16. Generic List + Numbered List + Bold + Italic + Code
17. Numbered List + Generic List + Bold + Italic + Code
18. Link 
19. Image
20. Video
20.1) YouTube
20.2) ...

**Drag and drop**:
- jpeg
- png
- ...

**Tags**: 
- Количество
- Длина

**Награда** - 100%


## 5. Публикация с наградой - силой голоса 50% / 50%
**Заголовок** - проверка максимального количества символов
**Toolbar**:
1. Heading х6
2. Bold
3. Italic
4. Bold+Italic
5. Heading+Italic
6. Code
7. Quote
8. Code+Italic
9. Quote+Code+Italic
10. Generic List
11. Numbered List
12. Generic List + Numbered List 
13. Numbered List + Generic List
14. Generic List + Bold + Italic + Code
15. Numbered List + Bold + Italic + Code
16. Generic List + Numbered List + Bold + Italic + Code
17. Numbered List + Generic List + Bold + Italic + Code
18. Link 
19. Image
20. Video
20.1) YouTube
20.2) ...

**Drag and drop**:
- jpeg
- png
- ...

**Tags**: 
- Количество
- Длина

**Награда** - 50% / 50%

## 6. Публикация с наградой - Отказаться от выплаты
**Заголовок** - проверка максимального количества символов
**Toolbar**:
1. Heading х6
2. Bold
3. Italic
4. Bold+Italic
5. Heading+Italic
6. Code
7. Quote
8. Code+Italic
9. Quote+Code+Italic
10. Generic List
11. Numbered List
12. Generic List + Numbered List 
13. Numbered List + Generic List
14. Generic List + Bold + Italic + Code
15. Numbered List + Bold + Italic + Code
16. Generic List + Numbered List + Bold + Italic + Code
17. Numbered List + Generic List + Bold + Italic + Code
18. Link 
19. Image
20. Video
20.1) YouTube
20.2) ...

**Drag and drop**:
- jpeg
- png
- ...

**Tags**: 
- Количество
- Длина

**Награда** - Отказаться от выплаты

## 7. Заполнение и проверка функционала кнопки "Очистить"
