### ISSUE TITLE
Заверстать прототип редактора

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/tolstoy#609]
Заверстать прототип редактора согласно дизайн документу. 

- [x] Футтер
- [x] Тело редактора
- [x] Всплывающая панель редактирования текста
- [x] Всплывающие кнопки для добавления контента
- [x] Всплывающие окна
- [x] кнопка 18+

**Comment by BaroH4er** [comment]
# Найдены следующие проблемы:

## Body is empty

**Проблема:** Не переведен текст в сплывающем окне при попытке публикации поста с пустым body формы.

**Воспроизведение:**

1) Заполнить заголовок формы
2) Добавить минимум 1 тег в форму
3) Попытаться опубликовать пост с помощью кнопки "Пост"

**Результат:** всплывающие окно выводит текст "Body is empty"
**Ожидаемый результат:** всплывающие окно выводит текст: "Заполните содержимое поста" / "Добавьте информацию в форму" / Свой вариант


## Скролл из-за всплывающего окна

**Проблема:** Всплывающие окно у кнопки "Пост" добавляет скролл по горизонтали у страницы редактора.

**Воспроизведение:** _подходит воспроизведение из Body is empty_

1) Оставить форму пустой
2) Попытаться опубликовать пост с помощью кнопки "Пост"

**Результат:** Всплывающие окно отображается непосредственно над кнопкой "Пост" - тем самым уезжает и добавляет скролл по горизонтали.
**Ожидаемый результат:** Всплывающие окно отображается немного левее от кнопки "Пост".

## Нотификация за футером

**Проблема:** Окно нотификации находится ниже уровнем чем футер редактора.

**Воспроизведение:** 
1) Создать(заполнить форму) и опубликовать пост
2) Создать новый пост (заполнить форму) и попытаться опубликовать пост меньше чем через 5 минут после создания первого (1пункт)

**Результат:** Нотификация с информацией о невозможности публикации меньше чем через 5 минут находится ниже уровнем чем футер редактора.
**Ожидаемый результат:** Нотификация с информацией о невозможности публикации меньше чем через 5 минут находится выше уровнем чем футер редактора.

**Comment by BaroH4er** [comment]
## Нотификация о слишком большом размере картинки
- [ ]  FIXED

**Проблема:** при попытке добавить изображение через тулбар(или иным способом) размером более чем 2мб, редактор ни как не реагирует.

**Решение:** добавить уведомление что "изображение слишком большое".

**Comment by BaroH4er** [comment]
# Изменения
### Добавления картинки с двумя опциями.
>Добавление картинки в обоих тулбарах должно работать идентично - Пользователь нажимает на пункт добавления картинки в обоих тулбарах, показываем окно с 2 опциями- загрузить с компа или указать ссылку.
- [x] ADD
<hr/>

### Количество редакторов и названия
>переименовать "Новый редактор" и "HTML редактор"
- [x] ADD
</hr>

# Речек проблем
### Body is empty => переведен как "Что-то пошло не так"
- [ ] FIXED

**Ожидаемый результат:** всплывающие окно выводит текст: "Заполните содержимое поста" / "Добавьте информацию в форму"
<hr/> 

### .maximum_block_size => всплывает нотификация с немпереведенным текстом.
- [ ] FIXED

**Ожидаемый результат:** 
1) В всплывающей нотификацией отображается текст - "Пост слишком большой".
2) Убрать нотификацию > оставить только всплывающие окно у кнопки "Пост"

**Comment by BaroH4er** [comment]
Тестирование завершено. Done.
