### ISSUE TITLE
починить "reblog" функционал

### ISSUE THREAD

**Issue by Undeadlol1** [GolosChain/tolstoy#61]

**Comment by Undeadlol1** [comment]
<img width="380" alt="screen shot 2016-10-29 at 13 57 03" src="https://cloud.githubusercontent.com/assets/4124323/19828497/55633bf0-9de0-11e6-99df-1dbfb45fa0cd.png">
<img width="596" alt="screen shot 2016-10-29 at 13 56 53" src="https://cloud.githubusercontent.com/assets/4124323/19828496/55631e04-9de0-11e6-94ab-15f196d89a41.png">

Текст ошибки:
`
"3030008 tx_missing_posting_auth: missing required posting authority
Missing Posting Authority misha
    {"id":"misha","posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS5PTR2iGv2TnuPB1tfqCYextkoba2XkJ6QhY7KgFPojEBh2j2Ew",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS665qjwdv7EGyYafpknj9p12edDceSHRZmgoVGpwYyzVEryNm2R",1]]},"owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["GLS7oy7TrtHcnwjYwXQ5359WnvQDtvi9iLH755fKRKjSZ43d6MQkq",1]]}}
    th_a  transaction.cpp:132 verify_authority

    {"ops":[["custom_json",{"required_auths":[],"required_posting_auths":["misha"],"id":"follow","json":"[\"reblog\",{\"account\":\"misha\",\"author\":\"tort\",\"permlink\":\"tt\"}]"}]],"sigs":["GLS8mYZ7kfErLUH3BgLMnNhmszrCfmdkLYHzbZPFvwWv1qehyo5Sq"]}
    th_a  transaction.cpp:174 verify_authority

    {"*this":{"ref_block_num":55857,"ref_block_prefix":3126123985,"expiration":"2016-10-29T08:57:15","operations":[["custom_json",{"required_auths":[],"required_posting_auths":["misha"],"id":"follow","json":"[\"reblog\",{\"account\":\"misha\",\"author\":\"tort\",\"permlink\":\"tt\"}]"}]],"extensions":[],"signatures":["201a799efd0dbaa2c9890e768556c93457deef3449a157c8bd9469a145d0f719f3690e2d89a3fd54b75d4a22fcd77edddb9477340a8035c07db953049c179f5ce8"]}}
    th_a  transaction.cpp:287 verify_authority

    {"trx":{"ref_block_num":55857,"ref_block_prefix":3126123985,"expiration":"2016-10-29T08:57:15","operations":[["custom_json",{"required_auths":[],"required_posting_auths":["misha"],"id":"follow","json":"[\"reblog\",{\"account\":\"misha\",\"author\":\"tort\",\"permlink\":\"tt\"}]"}]],"extensions":[],"signatures":["201a799efd0dbaa2c9890e768556c93457deef3449a157c8bd9469a145d0f719f3690e2d89a3fd54b75d4a22fcd77edddb9477340a8035c07db953049c179f5ce8"]}}
    th_a  database.cpp:3079 _apply_transaction

    {"trx":{"ref_block_num":55857,"ref_block_prefix":3126123985,"expiration":"2016-10-29T08:57:15","operations":[["custom_json",{"required_auths":[],"required_posting_auths":["misha"],"id":"follow","json":"[\"reblog\",{\"account\":\"misha\",\"author\":\"tort\",\"permlink\":\"tt\"}]"}]],"extensions":[],"signatures":["201a799efd0dbaa2c9890e768556c93457deef3449a157c8bd9469a145d0f719f3690e2d89a3fd54b75d4a22fcd77edddb9477340a8035c07db953049c179f5ce8"]}}
    th_a  database.cpp:700 push_transaction"
`

**Comment by Undeadlol1** [comment]
В клиенте я порылся и ошибок не нашел. Может дело в чем-то еще?
@21xhipster 
@vitalylvov 
@tomarcafe 
Поделитесь информацией, пожалуйста.

**Comment by Undeadlol1** [comment]
@ValeryLitvin в клиенте проблема или в блокчейне?

**Comment by Undeadlol1** [comment]
@vitalylvov сказал можно закрывать.

**Comment by ValeryLitvin** [comment]
@Undeadlol1 в дополнительном апи на стороне блокчейна. Скажу когда оно будет и когда можно будет на клиенте подключать
