### ISSUE TITLE
Разработать поиск пользователей блокчейна

### ISSUE THREAD

**Issue by rodnikova** [GolosChain/tolstoy#614]
Разработать  отдельный сервис поиска по юзернеймам пользователяй по базе  блокчейна. 
- [ ] при вводе имени пользователя в комментариях
- [ ] использовать функционал  при вводе юзернейма в окне транзакций
![default](https://user-images.githubusercontent.com/36824904/37919692-518a5d06-312d-11e8-981d-9350e673b3ba.jpg)

**Comment by vista7** [comment]
Да, вот эта штука полезная) На стиме такое есть - когда делаешь перевод, то можно выбрать из нескольких последних получателей, удобно. Может просто "свистнуть" со стима эту фишку?  Давайте попросим Гороха, он уже имеет такой опыт - вытаскивать со стима разные штуки :)

**Comment by jevgenika** [comment]
дубликат https://github.com/GolosChain/tolstoy/issues/618

**Comment by daryasattarova** [comment]
отсутствует фича: 
![image](https://user-images.githubusercontent.com/42342756/47289533-f052bc00-d603-11e8-8b8b-1906b4b35dc0.png)

**Comment by daryasattarova** [comment]
обрезается список
![image](https://user-images.githubusercontent.com/42342756/47482304-d81ab100-d83e-11e8-891d-83b53a93e4ea.png)

**Comment by Bacher** [comment]
Поправлено уже в #1125
