### ISSUE TITLE
Пересмотреть логику наличия и работы лент

### ISSUE THREAD

**Issue by alex-firsov** [GolosChain/tolstoy#617]
Пересмотреть на Golos.io логику наличия и работы лент:

Лента — остается в неизменном виде (вывод постов в хронологическом порядке);
Новое — заменить на алгоритмическую ленту (вывод постов в зависимости от интересов пользователя по рекомендательному алгоритму);
Актуальное — заменить на ленту «Видео»;
Популярное — заменить на ленту «Фото»;
Промо — удалить ленту, добавив на Golos.io механизм вывода любого своего поста в промо-раздел (верхний пост выбранной ленты).

**Comment by litrbooh** [comment]
@alex-firsov
А где я буду смотреть ВСЕ новые посты? А где я буду смотреть ТОП? От этих вкладок нельзя отказываться.

**Comment by alex-firsov** [comment]
Вопрос дискуссионный, поэтому и ярлык у него "proposal".

На мой личный взгляд функция просмотра всех новых постов абсолютна бессмысленна. Особенно с увеличением количества пользователей. Вам нужна была бы лента со всеми новыми постами всех пользователей Фэйсбука, например? Не думаю, что так.

**Comment by litrbooh** [comment]
@alex-firsov 
Хорошо, я уточню вопрос. Допустим мне нужны новые посты по интересующему меня тегу. Или ТОП посты по интересующему меня тегу. Как  я их должен найти без вкладок Новое и популярное?

Сейчас это просто делается, я тыкаю в тег и потом в Новое или поппулярное. А если вы всё это уберете, то как мне это всё найти?

**Comment by litrbooh** [comment]
Кстати, я не против введения дополнительных лент Фото и Видео. Надо ещё понять механизм из наполнения.

**Comment by vikxx** [comment]
> Актуальное — заменить на ленту «Видео»;

Без встроенного аплодера, ipfs и т.п. - это будет минус. Вкладка видео есть - возможности загружать видео нет. 

> Популярное — заменить на ленту «Фото»;

А как же делать презентацию возможности платформы? Вкладка популярное хороший мотиватор.
Разумеется с недельным окном выплат - ранжирование в ней должно быть пересмотрено.

**Comment by litrbooh** [comment]
@vikxx 
Да, возможно стоит подумать над вкладками ТОП за сутки и ТОП за неделю, ведь не все могут заходить на голос каждый день.

**Comment by dechadecha** [comment]
КМК, должна быть общая лента как она есть сейчас с возможностью тегов и прочего, лента топ, и лента в которой просто можно переключать подкатегории: фото, видео, музыка. Хотя смысл сомнительный учитывая наличие тегов.

**Comment by alex-firsov** [comment]
>Без встроенного аплодера, ipfs и т.п. - это будет минус. Вкладка видео есть - возможности загружать видео нет.
@vikxx Согласен, однозначно, я здесь не прописал, но это в логике поднятия клиента тип dtube как части golos.io.

**Comment by alex-firsov** [comment]
@litrbooh Хорошая идея, я бы еще добавил фичу вывода топа за произвольный день/неделю/месяц или другой промежуток времени.
>Да, возможно стоит подумать над вкладками ТОП за сутки и ТОП за неделю, ведь не все могут заходить на голос каждый день.

**Comment by alex-firsov** [comment]
@vikxx Логично, для незарегистрированных пользователей можно место алгоритмической ленты показывать топ по выплатам за неделю.
>А как же делать презентацию экономических возможностей платформы? Вкладка популярное хороший мотиватор.
