### ISSUE TITLE
Переформировать на Golos.io механизм продвижения постов

### ISSUE THREAD

**Issue by alex-firsov** [GolosChain/tolstoy#618]
Убрать на Golos.io ленту «Промо» и добавить возможность вешать пост верхним постом в любую выбранную ленту. Пост должен иметь пометку «Промо». Выбор поста должен осуществляться аукционом с окном показа поста в один час. Внедрить механизм участия в аукционе из любого поста на Golos.io.

**Comment by litrbooh** [comment]
@alex-firsov 
А почему выбран такой мудреный механизм? Я бы предложил показывать пост как обычно, только к стоимости его оценки добавлять количество "запромированно".

Например, пост набрал апвоутов на 100р + задонатил в нуль голосов на 2000р. Значит, оценка поста 2100р. Вот он с такой оценкой пусть в топе и висит.

Это просто, понятно и особо делать не нужно, и мутки с аукционами не нужны.

**Comment by alex-firsov** [comment]
Что значит «показывать пост как обычно» в разрезе механизма продвижения постов? Не могли бы вы более подробно расписать предлагаемый вами механизм.

**Comment by litrbooh** [comment]
@alex-firsov 
Просто показывайте в Популярном (и остальных разделах) суммарную оценку стоимости поста с учетом продвижения. 

Кстати, продвижение будет оплачиваться в пользу блокчейна или в пользу голос.ио?

**Comment by jevgenika** [comment]
https://github.com/GolosChain/tolstoy/issues/726
