### ISSUE TITLE
Добавить экран перехода на внешний ресурс

### ISSUE THREAD

**Issue by alex-firsov** [GolosChain/tolstoy#619]
Добавить на Golos.io возможность включать функцию отображения экрана предупреждения о переходе по ссылкам с сайта на внешние ресурсы.

Экран предупреждения должен содержать:

— Заголовок о переходе на внешний ресурс;
— Информацию о покидании сайта Golos.io;
— Домен внешнего ресурса;
— Предупреждение о потенциальных угрозах;
— Рекомендации по безопасности;
— Кнопку отмены перехода.

**Comment by alex-firsov** [comment]
**Текст для страницы:**

Вы покидаете Golos.io

Вы кликнули на ссылку, ведущую на внешний ресурс, и покидаете блог-платформу Golos.io.

Ссылка, на которую вы кликнули, переведет вас по адресу: %адрес ссылки%. [неактивная ссылка, просто текст]

Golos.io не имеет никакого отношения к сайту, расположенному по ссылке выше, и не может гарантировать вам безопасность его использования. Сайты с закрытым исходным кодом могут содержать вредоносные скрипты и использовать мошеннические схемы.

Рекомендуем вам не переходить по ссылке, если у вас нет серьезных оснований доверять внешнему ресурсу. Помните, что активный ключ вашего аккаунта на Golos.io не может быть восстановелн, а доступ к нему позволит мошенникам завладеть всеми вашими средствами.

[Кнопки:]
Вернуться на Golos.io [синий фон]
Перейти по ссылке [серый фон]

**Comment by alex-firsov** [comment]
На время, когда экран перехода на внешний ресурс не будет включен, предлагаю перед всеми внешними ссылками на сайте ставить иконку перехода на внешний ресурс.

Пример:
<img width="132" alt="2018-04-06 15 52 53" src="https://user-images.githubusercontent.com/33282977/38424867-ae11608c-39b2-11e8-888f-6d87c532ccb4.png">

**Comment by BaroH4er** [comment]
В посте, ссылки "ответить" и "редактировать" ведут на /leave_page? (переход как по внешней ссылке)

**Comment by BaroH4er** [comment]
Тестирование завершено. Исправлено - ошибок нет.
