### ISSUE TITLE
[Report 03.04.2018] Golos.blog && Golos.io - Неизвестный пользователь 

### ISSUE THREAD

**Issue by BaroH4er** [GolosChain/tolstoy#622]
## "Неизвестный пользователь" вместо "колеса загрузки"

**Проблема**: При открытии страницы автора, страница загрузки данных выдает некорректный текст пользователю. 

**Воспроизведение**:
1. Открыть любой пост
2. Перейти в блог автора, информации о котором ещё нет в кэше

**Результат**:  1-2 сек. пользователь находится на странице с текстом "Неизвестный пользователь", пока идет загрузка информации об авторе.

**Ожидаемый результат**: 1-2 сек. пользователь находится на странице с "колесом загрузки", пока идет загрузка информации об авторе.

**Comment by jevgenika** [comment]
https://github.com/GolosChain/tolstoy/issues/490 дубликат

**Comment by BaroH4er** [comment]
Проблема актуальна.

**Comment by BaroH4er** [comment]
Исправлено.
