### ISSUE TITLE
Поменять отображение выплат в постах/комментах с GBG на Голос в связи с остановкой печати GBG

### ISSUE THREAD

**Issue by vista7** [GolosChain/tolstoy#623]
Здравствуйте дамы и господа разрабы, команда Голоса. 
Как вы знаете, печать GBG-токенов недавно была прекращена. Теперь награды за посты/комменты и за кураторство выдаётся в Голос-токенах. Но на сайте golos.io до сих пор отображается, что выплата производится в GBG. Скриншот ниже:
![-](https://user-images.githubusercontent.com/33452731/38378119-11b7c2e8-3940-11e8-9126-7a54da1d5503.png)

Подробнее написал об этом в посте: https://golos.io/goldvoice/@aleos/novaya-yekonomika-na-golose-kak-teperx-ustroeny-vyplaty-za-postykommenty 

В общем, надо бы поменять на сайте отображение выплат с ГБГ на Голос. А ещё лучше, чтобы ориентировочно указывалось сразу, сколько зачислится в Голос-токены и сколько в СГ, как это реализовано на стиме.

**Comment by bitfag** [comment]
Предлагаю сделать отображение как сейчас на стиме, т.е. прогнозировать в чём будет выплата и показывать соответственно, например: `X GBG, Y GOLOS, Z Golos Power`.

**Comment by litrbooh** [comment]
поддерживаю предыдущего оратора, на стимит удобно сделано

**Comment by litrbooh** [comment]
@vista7 
лучше включить сразу все параметры

**Comment by vista7** [comment]
@litrbooh не будем спорить) Возможно, вы и битфраг правы и лучше отображать сразу все параметры, а то вдруг gbg-шки снова начнут печататься.
