### ISSUE TITLE
Увеличьте в посте число тегов до 10-ти хотя бы...

### ISSUE THREAD

**Issue by litrbooh** [GolosChain/tolstoy#625]
Более число тегов нужно, для лучше каталогизации контента. Например, если у вас сообщество ВП, вы первый тег отдаете в категорию или app, потом если есть тег сообщества и остается только три тега...

**Comment by t3ran13** [comment]
5 тегов в учетов что часто 1 уходит под апп, маловато) я бы хотел не меньше 7и, но лучше больше)

**Comment by baybak** [comment]
поддержу

**Comment by abduramanoff** [comment]
Я за. Поддерживаю.

**Comment by erikkartmen** [comment]
5 тегов - это кастыль прошлого! В goldvoice их больше и всё нормально работает, даже, как сказано уже выше - позволит лучше каталогизировать контент! 
Если и требуется какое-либо ограничение, то пускай >10

**Comment by alex-firsov** [comment]
@litrbooh Сейчас каталогизация без исправления логики работы API работает только по пяти первым тегам, увеличение количества тегов не даст никакого преимущества для каталогизации.

**Comment by litrbooh** [comment]
@alex-firsov , плохо, надо открыть ещё одно ищью :)

**Comment by NickShtefan** [comment]
есть API блокчейна, при помощи него мы работаем с данными, получаем их, строим выборки, и в текущий момент времени в после может быть указано больше пяти тегов, однако выборки по тегу, чей порядковый номер больше 5, работать не будут

Для того чтобы корректно строить выдачи, при этом использовать больше 5 тегов, надо обкладывать клиент базами данных и достаточно значительно менять архитектуру приложения. 
В ближайшее время мы это делать не планируем. 

P.S. [Тут можно часть дискуссии по тегам. ](https://github.com/GolosChain/tolstoy/issues/549#issuecomment-349810579)
