### ISSUE TITLE
выбор превью изображения из нескольких изображений поста

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/tolstoy#626]
Дать возможность пользователю выбора: какое из нескольких изображений в посте отображать как превью поста.
- [ ] В редакторе определять все изображения поста
- [ ] пользователь чек боксом-выделением отображает заглавное -превью изображение
![image](https://user-images.githubusercontent.com/30616421/47870865-3c2b0f80-de13-11e8-9768-1b9184ae34f6.png)

**Comment by erikkartmen** [comment]
Почему бы не реализовать возмоожность создавать для превью совершенно отдельнцю картинку/фото, то есть которой нет в самом посте!

**Comment by jevgenika** [comment]
@erikkartmen для реализации такой возможности, в любом случаи, нужно разработать отдельный редактор - админку и возможность хранить эти данные.

**Comment by rodnikova** [comment]
- [ ] сделать возможным выбор миниатюры для превью поста
