### ISSUE TITLE
Не работает ссылка для совершения прямого перевода. 

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/tolstoy#628]
Пример 
https://golos.io/@denis-skripnik/transfers?to=receiver&amount=0.001&token=gbg&memo=%D0%B1%D0%BB%D0%B0%D0%B3%D0%BE%D0%B4%D0%B0%D1%80%D1%8E

**Comment by BaroH4er** [comment]
Тестирование завершено. Ошибок нет. Работает в Chrome/FireFox/Opera/IE
