### ISSUE TITLE
Первый тег при вторичном редактировании невозможно удалить

### ISSUE THREAD

**Issue by mguryeva** [GolosChain/tolstoy#63]
При вторичном редактировании система не дает удалить первый тег и соответственно перенести пост в другую группу постов

**Comment by Undeadlol1** [comment]
Первый тэг нельзя менять. Изменение первого тэга просто создает новый в списке тэгов.
Первый тэг - это категория поста, эти данные сохраняются навсегда и менять их нельзя.

**Comment by Undeadlol1** [comment]
В steemit.com логика такая же.
