### ISSUE TITLE
Отображение уведомлений.

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/tolstoy#631]
- [x] Создать вкладку “Уведомления” в профайле пользователя.

- _содержимое вкладки отображается только для пользователя, который авторизован в текущий момент (нет возможности увидеть чужую историю)_  (@sualex)

- [x] Отображать счетчик уведомлений на аватарке пользователя
- [x] Во вкладке "Уведомления" отображать все уведомления пользователя, полученный от системы нотификаций

- [ ] 1. Счетчик уведомлений. 
На иконке нотификаций  отображается количество произошедших событий, при нажатии на нее, счетчик обнуляется, а пользователь видит список, состоящий из 5 последних пунктов, в конце есть кнопка “показать все“. При нажатии на “показать все“, открывается страница уведомлений
- [ ] 2. Страница уведомлений
Показывает последние 30 событий, в конце этого списка есть кнопка “показать еще“, при нажатии на которую загружаются еще 30 событий.

https://app.zeplin.io/project/5aa27bf6d6ee04d0124acc41/screen/5ac190f34ac0ecde47700787

Внешний вид компонента.

**Comment by litrbooh** [comment]
Я думал уже всё готово и после ХФ заработает, а это всё только создавать надо?

**Comment by NickShtefan** [comment]
Как связана система нотификаций с хардфорком? 

[Здесь мы писали](http://localhost:8080/golosio/@golosio/golos-io-otchet-za-fevral) о том, что унаследованная система нотификаций от стимита нам не подходит и мы решили сделать свою.

**Comment by BaroH4er** [comment]
Done
