### ISSUE TITLE
Сделать форматирование поля ввода номера телефона при регистрации

### ISSUE THREAD

**Issue by dankinescop** [GolosChain/tolstoy#639]
Исключить возможность ввода номера телефона с 0 в качестве первой цифры на русской и английской версиях. При условии "первая цифра 0" выдавать сообщение. Варианты сообщений:

Неверный формат/Wrong format
Номер не может начинаться с 0/The phone number can't start with zero
Пожалуйста, укажите номер телефона без 0 в качестве первой цифры, так как международный код подставляется автоматически/Please specify your phone number without zero as the first digit due to automated addition of the international code

**Comment by BaroH4er** [comment]
- [x] Ru - Тестирование завершено. Ошибок нет.
- [ ] En - "_Ошибка локализаций_ #652 "

**Comment by Bacher** [comment]
Поправим в новой версии регистрации.
