### ISSUE TITLE
Язык интерфейса в зависимости от определение языка браузера или языка интерфейса пользовтаеля

### ISSUE THREAD

**Issue by chugoi911** [GolosChain/tolstoy#640]
Иностранные пользователи по умолчанию видят русский интерфейс. Так как переключение языка явно не выделено и подписано РУС(как вариант изменить на RU), то у некоторых возникают проблемы.   

https://golos.io/golosio/@golosio/golos-io-zhizn-posle-khardforka#@chugoi/re-golosio-golos-io-zhizn-posle-khardforka-20180413t200609887z

**Comment by rodnikova** [comment]
Лучше реализовать данный функционал через определение языка браузера или языка интерфейса. Так как многие пользуются сейчас различными vpn-сервисами, реализация через ip нецелесообразна.

**Comment by b1acksun** [comment]
https://github.com/GolosChain/tolstoy/issues/1251
