### ISSUE TITLE
Реализовать запрет публикаций тега stihi-io

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/tolstoy#641]
Необходимо реализовать запрет публикаций статей с тегом stihi-io на сайте golos.io и golos.blog.
Если пользователь пытается опубликовать пост, содержащий тег stihi-io необходимо выводить предупреждение о том, что создание постов с этим тегом невозможно

**Comment by litrbooh** [comment]
@NickShtefan 
Объясните пожалуйста, как так получается. Я видел, что ранее несколько человек обращались с вопросом, чтобы для их фронта сделали специальный тег, чтобы не отображать их посты на голос.ио. Но тогда был не аргументированный отказ.

Какая теперь политика партии, каждый создающий свой фронт может попросить выделить ему тег, по которому посты не будут отображаться на голос.ио?

**Comment by litrbooh** [comment]
@jevgenika 
Можете ответить на вопрос выше?

**Comment by jevgenika** [comment]
@litrbooh  вы путаете понятия, конкретно в данном таске стоит задача исключить возможность публикации тега через толстого, а не сокрытие постов

**Comment by litrbooh** [comment]
@jevgenika 
а в чем смысл запрета публиковать такой тег? этоже можно легко обойти, скорее нужно было запретить не тег, а категорию или как stihi-io будут фильтровать контент на свой фронт?
