### ISSUE TITLE
Заверстать header и footer согласно новому дизайну 

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/tolstoy#654]
Новый дизайн [можно найти здесь ](https://app.zeplin.io/project/5aa27bf6d6ee04d0124acc41/screen/5adf840e86f0b950b9586843)

**Comment by alex-firsov** [comment]
Надо добавить возможность открывать боковое меню не будучи залогиненным.

**Comment by BaroH4er** [comment]
### Шапка: верстка по ширине
**Проблема**: если ширина разрешения экрана от 640px до 880px, верстка едет:
![image](https://user-images.githubusercontent.com/21989598/39896268-2322f80e-54b6-11e8-9643-99c943cf15de.png)

<hr/>

### Подвал: ссылка на сумму выплаты
**Проблема**: в подвале, указанная цифра суммы выплат является ссылкой, которая ведет на страницу перехода на внешний ресурс (/leave_page?), откуда в свою очередь мы никуда попасть не можем. 
![image](https://user-images.githubusercontent.com/21989598/39896774-2f04a440-54b8-11e8-85aa-ad69d38375bc.png)
**Решение**: убрать ссылку с цифры суммы выплат.

<hr/>

### Подвал: ссылки в меню
**Проблема**: в меню футера есть прямые ссылки(golos.io/../../), что в данный момент вызывает страницу перехода на внешний ресурс (/leave_page?):

**Решение**:
- Политика Конфиденциальности - поменять на `/ru--konfidenczialxnostx/@golos/politika-konfidencialnosti`

- Условия пользования - поменять на` /legal/terms_of_service.pdf`

<hr/>

- [ ] Шапка: верстка по ширине
- [ ] Подвал: ссылка на сумму выплаты
- [ ] Подвал: ссылки в меню

<hr/>

### Дополнительно

**Comment by kuchinskaya** [comment]
Общие рекомендации:
https://prnt.sc/jk81lh

Шапка 640:
https://projects.invisionapp.com/d/main#/console/13480730/298191299/preview

Обновленная шапка:
https://projects.invisionapp.com/d/main#/console/13480730/293342894/preview

**Comment by BaroH4er** [comment]
Исправлено. Соответствует рекомендациям.

**Comment by vista7** [comment]
Ребят, предлагаю **убрать вообще** из футера сумму выплат. Нафига она там? Ради понтов что ли?) Во первых - она постоянно мозолит глаза (всплывает на полэкрана) когда переключаешься по разным разделам и страничкам сайта golos.io , во вторых - это может привлечь внимание каких-нибудь регуляторов/законодателей, которые мечтают обложить налогами крипту, обменники и т.д.
