### ISSUE TITLE
Заверстать стр welcome согласно новому дизайну

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/tolstoy#655]
Заверстать https://golos.io/welcome согласно новому [дизайну ](https://app.zeplin.io/project/5aa27bf6d6ee04d0124acc41/screen/5aee3ae7df662f9157165c54)

**Comment by kuchinskaya** [comment]
1) Если строка не влазит, то лучше перенести "а не модерируется" сразу после запятой https://prnt.sc/jqa9t0
2) Поднять посты выше https://prnt.sc/jqabk8 как тут https://prnt.sc/jqab0c
3) Расстояние между "в прошлом" и "месяце" сделать чуть меньше, так будет понятнее что это дно предложение http://prntscr.com/jqaegv
4) $ переносить нельзя, лучше сделать строку длиннее http://prntscr.com/jqaepy
5) Если просто фотография, разбеленный градиент делать не надо http://prntscr.com/jqafr6
6) Уголки батарейки должны быть закругленными http://prntscr.com/jqaph5
7) Кнопки должны анимироваться вот так: https://material-components.github.io/material-components-web-catalog/#/component/button
8) Лайк при наведении должен поменять цвет http://prntscr.com/jqam4a
9) У карточек при наведении тень должна стать выше и плотнее, как уже сделано у кнопок с лево http://prntscr.com/jqavav (только тень пусть будет еще выше на 2 px) http://prntscr.com/jqb2af
10) Должно быть визуальное деление блоков, один блок пусть будет белый, а второй серый.
11) Кнопка должна быть длиннее так как у слова 'Подробнее" межбуквенное расстояние 3. Должно быть так: http://prntscr.com/jqaylr А получилось так: http://prntscr.com/jqay7y

**Comment by BaroH4er** [comment]
Тестирование завершено. Обнаружены следующие ошибки: 

## 1. Ссылка у кнопки перехода на Android приложение.

**Проблема:** на кнопке Google play стоит ссылка не из белого списка: https://play.google.com/store/apps/details?id=io.golos.golos&utm_source=&utm_campaign=&pcampaignid=MKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1

**Решение:** необходимо заменить на https://play.google.com/store/apps/details?id=io.golos.golos 

- [ ] Заменить ссылку на андройд приложение 

<hr/>

## 2. Иконки валют

**Проблема:** при смене валюты в настройках, на странице /welcome, в блоке поста валюта конвертируется но остается иконка $.

![image](https://user-images.githubusercontent.com/21989598/41051689-7b7f842c-69bf-11e8-93f5-7edf79b9ab1b.png) ![image](https://user-images.githubusercontent.com/21989598/41051756-a8352b34-69bf-11e8-98e6-69f81e2a4789.png)

**Проблема актуальна для всех валют.** 

**Решение:** При смене валюты добавить смену иконки на соответствующую.

- [ ] Добавить иконки валют.

<hr/>

## 3. Кнопка "подробнее" у блока "Посты не удаляются".

**Проблема:** у блока "Посты не удаляются" не хватает кнопки "подробнее".
![image](https://user-images.githubusercontent.com/21989598/41052115-9deb8bb8-69c0-11e8-9b56-6f56fef6e528.png)

**В случае если нет соответствующего поста, отметить как выполнено.**

- [ ] Добавить кнопку "подробнее" в блок "Посты не удаляются".

**Comment by rodnikova** [comment]
Нужно переименовать: 
раздел “с чего начать и о чем писать?” в “что почитать?“; 
раздел “маленькие отличия” в “наши отличия“.

**Comment by rodnikova** [comment]
- [ ] «Голоса сообщества» сделать дольше задержку на текстах, не хватает времени на чтение.

- [ ] «Голоса сообщества» сделать возможность менять тексты нажатием на аватар.

- [ ] Опечатки

Поздравляем с регистрацией заменить точку на восклицательный знак.
По идее, эту фразу можно и совсем убрать, т.к. на страницу велком могут зайти и не зарегистрированные пользователи и те, кто стопицот лет уже на голосе.

«Наши отличия»
Ключи
Виртуальный паспорт в мире блокчейна. Ключи подтверждают, что ваш аккаунт и токены принадлеж**А**т только вам.

Голосование
Каждый день у вас есть 40 голосов, чтобы оценить чужие посты. Не упустите их. Когда вы нажимаете кнопку «Вверх» **ПОД** постом — топ Golos.io становится интереснее, а вы получ**АЕТЕ** награду за курирование.

Кнопку «Вверх» лучше заменить на «Голосовать за». 

Поста
Исправить на Пост**Ы**

«Голоса сообщества»
Ольга, художник
Добавить запятую: Это хороший проект, и я в него верю.

«Остались вопросы»
Или через сайт заменить на - уточните через сайт

© 2018 Golos.io - социальная платформа, сообщество блогеров, медиасеть, разработанная на Медиаблокчейне ГОЛОС

**Comment by BaroH4er** [comment]
## Блок: Голоса сообщества. 360х640
**Проблемы:** 
- [ ]  **Перенос запятой в заголовке.** Запятая переносится стабильно во всех заголовках(div=name) блока "Голоса сообщества". 
- [ ]  **Ширина блока с текстом.** Увеличить ширину блока с текстом(div=description) на сколько это возможно.

![image](https://user-images.githubusercontent.com/21989598/41463216-55fa418e-709e-11e8-959f-de578a03f7d0.png)

## Блок: Приложение для Android. 360х640

**Проблемы:**

- [ ] **Перенос текста.** Для текста "*Мы уже работаем над приложением для IPhone, оно будет готово летом.*" убрать перенос после слова "*для*".
- [ ] **Кнопка Google play.** Отцентрировать кнопку и добавить отступ снизу.

![image](https://user-images.githubusercontent.com/21989598/41464057-7cb647ac-70a1-11e8-97ac-33f3f03a2bc6.png)

**Comment by BaroH4er** [comment]
Есть проблема с "**Блок: Голоса сообщества. 360х640**"
>Ширина блока с текстом. Увеличить ширину блока с текстом(div=description) на сколько это возможно.

Конечно имелось ввиду на сколько это возможно в рамках ширины экрана при 360px). В данный момент у блока с классом .slick-list и у его внутренних divов не хватает width. Необходимо привести к виду согласно дизайну.

![image](https://user-images.githubusercontent.com/21989598/42698576-fbe759cc-86c6-11e8-8a60-1055b3fc320e.png)

**Comment by Bacher** [comment]
Починил.
