### ISSUE TITLE
Актуализировать информацию о количестве токенов при регистрации

### ISSUE THREAD

**Issue by alex-firsov** [GolosChain/tolstoy#658]
- [x] Убрать строку «Получи 5 ГОЛОСОВ бесплатно» на странице https://golos.io/about

- [x] Убрать строку «После регистрации на ваш аккаунт будут начислены пять токенов Golos.» на странице https://golos.io/create_account#

- [x] Убрать строку «Зарегистрируйся — получи 5 голосов!» на странице https://vk.com/goloschain?w=wall-50005253_4028

**Comment by jevgenika** [comment]
Done
