### ISSUE TITLE
Реализовать делегирование СГ на уровне клиента

### ISSUE THREAD

**Issue by denis-skripnik** [GolosChain/tolstoy#659]
Здравствуйте. Начну с делегирования. Не знаю, почему его нет в Steemit: хотелось бы, чтоб после ХФ 18 данная функция была внедрена. Например, выбираешь в кошельке свою СГ, появляется меню, где есть "Вывести СГ" и т. п. Предлагаю добавить ещё одну ссылку: "Делегировать", по клику на которую появляется форма на подобии формы перевода:
- От кого;
- кому
- Сколько;
- Время делегирования (В том числе и неограниченно).

После делегирования появляется пункт, позволяющий отменить его.

По поводу ползунка.
Пользователям, кажется, от 300 силы Голоса доступна возможность выбора процента апвота.
Но проблема в том, что существующий ползунок, позаимствованный у Steemit, не доступен незрячим. я не могу им с клавиатуры управлять. Буду очень благодарен, если измените его на другой или добавите две кнопки: + и -, которые бы перемещали ползунок на 5 единиц. Благодарю.

**Comment by t3ran13** [comment]
не виду проблем отображать делегирование в кошельке, так что +1

**Comment by NickShtefan** [comment]
@denis-skripnik Спасибо за предложение, мы возьмем за основу твое описание и немного откорректируем его, в соответсвии с функционалом, поддерживаемым блокчейном

**Comment by denis-skripnik** [comment]
@NickShtefancommented, интересно, в чём заключаться будут корректировки?

**Comment by NickShtefan** [comment]
Делегирование Силы Голоса(далее СГ) должно быть доступно во вкладке кошелек. 

При нажатии на СГ у пользователя появляется возможность делегировать свою СГ, данное диалоговое окно можно сделать аналогичным окну перевода средств. 
В данном окне должны присутствовать следующие пункты: 

От Кого: Имя пользователя, который делегирует СГ - нередактируемое поле. 
Кому: Имя пользователя, кому будет делегирована СГ, редактируемое поле. 
Сумма, которую пользователь хочет делегировать: Редактируемое поле. В данном поле существуют ограничения: Есть минимальная сумма, которую можно делегировать. Сумма делегированной СГ не может превышать баланс СГ пользователя. 
Кнопка “Делегировать”. При нажатии на нее, происходит следующее:  Пользователь, которому делегирована СГ добавляется в список пользователей, которому с текущего аккаунта была делегирована СГ. 

В разделе «Балансы» кошелька под оценочной стоимостью акаунта при делегировании СГ хотя бы одному пользователю появляется список.

Название списка: «Делегированная Сила Голоса»
Подпись: «Часть своей Силы Голоса вы решили делегировать другим пользователям. В любой момент вы можете изменить размер делегированной Силы Голоса или отменить делегирование.»
Список состоит из: Имя пользователя, которому была делегирована СГ, Сумма делегированной СГ. 
Из данного списка можно производить следующие действия. 
Отменить делегирование СГ
Изменить сумму делегированной СГ, на данное поле работают те же правила, что и на поле “сумма”, а именно существует минимальное значение делегированной СГ, ниже которого опуститься невозможно. Так же существует порог изменения СГ, т.е. увеличить или уменьшить можно только на n пунктов.

**Comment by denis-skripnik** [comment]
@NickShtefan, супер! Благодарю, и очень жду реализации функционала.
P. S. Вот и ещё одна уникальность будет по сравнению со Steemit.

**Comment by denis-skripnik** [comment]
Здравствуйте. Появилась идея, касающаяся делегирования СГ.

Мне известно, что можно будет получить список тех, кто делегировал СГ текущему аккаунту. Предлагаю выводить об этом уведомление в кошельке, как это делается на Steemit с наградами.
Было бы удобно очень многим, как считаю.

Причём это можно делать как через историю транзакций, так и через специальный метод (Не помню сейчас, как он называется: он записан).

И ещё. Не знаю, возможно ли это: было бы замечательно, если бы при делегировании СГ можно было указать причину. Это отличный способ сообщить пользователям, за что они получили силу Голоса.
Если же такого нет на уровне блокчейна, возможно есть смысл добавить в ХФ, если это возможно на текущем этапе?

Благодарю.

**Comment by b1acksun** [comment]
https://github.com/GolosChain/tolstoy/commit/bc80aa8e47ed6a7ebcabaef3092db79e3d07b7a6

**Comment by BaroH4er** [comment]
Не реализован функционал изменения суммы делегирования СГ: 
>Изменить сумму делегированной СГ, на данное поле работают те же правила, что и на поле “сумма”, а именно существует минимальное значение делегированной СГ, ниже которого опуститься невозможно. Так же существует порог изменения СГ, т.е. увеличить или уменьшить можно только на n пунктов.

- [ ] ADD
