### ISSUE TITLE
Не работает функция голосования с десктопа 

### ISSUE THREAD

**Issue by mguryeva** [GolosChain/tolstoy#66]
Нажимаю кнопку проговосовать, реакции никакой, при этом сила голоса регулируется... Хром.

**Comment by 21xhipster** [comment]
<img width="653" alt="screen shot 2016-10-20 at 6 08 57 pm" src="https://cloud.githubusercontent.com/assets/410789/19568059/5868dde2-96f0-11e6-85ab-d9f597285e8d.png">

**Comment by 21xhipster** [comment]
@tomarcafe Есть версия, что эта хрень из-за ngnix. Что скажешь?

**Comment by tomarcafe** [comment]
ща буду смотреть, немного отстал от вас )
да, просьба - при фикировании бага по возможности писать коммитхэш (зелененькие буквы внизу слева)

**Comment by Undeadlol1** [comment]
Я так понимаю, что это уже не актуально. Закрываю.
