### ISSUE TITLE
Создать белый лист внешних ссылок 

### ISSUE THREAD

**Issue by alex-firsov** [GolosChain/tolstoy#662]
Создать лист внешних ссылок, для которых не будет возникать страница «Вы покидаете Golos.io».

Добавить в лист ссылки:
- [x] https://play.google.com/store/apps/details?id=io.golos.golos
- [x] https://golos.blog/
- [x] https://sandbox.golos.io/
- [x] https://explorer.golos.io/
- [x] https://github.com/
- [x] https://wiki.golos.io/

**Comment by vista7** [comment]
Маловато ссылок в белом листе, мне кажется) Почему бы не внести ещё https://github.com (тут вирусы навряд ли появятся) и прочие ресурсы типа фэйсбука, хабрахабр и т.п. Можно ещё и новостные сайты добавить в белый лист: 
https://www.novayagazeta.ru 
https://newtimes.ru 
и некоторые другие, проверенные ресурсы.

**Comment by NickShtefan** [comment]
Предлагаю зафиксировать список ресурсов, переход на которые будет возможен без открытия предупреждения о переходе на внешний ресурс

**Comment by vista7** [comment]
@alex-firsov добавьте в белый список https://github.com ещё, ибо часто в постах голос.ио и голос.кор встречаются ссылки на гитхаб.

**Comment by vista7** [comment]
Или хотя бы такую ссылку в белый список - https://github.com/GolosChain , это ведь репозитории Голоса.

**Comment by NickShtefan** [comment]
я за то, чтобы добавить весь github в исключения, а не только наш репозиторий

**Comment by BaroH4er** [comment]
Тестирование завершено: 
- [https://github.com/](https://github.com/) - не попал в белый список.
- [https://wiki.golos.io/](https://wiki.golos.io/) - находится в белом списке, хотя его нет в задаче.
<hr/>
@alex-firsov Будет ли дополняться список?

**Comment by vista7** [comment]
@BaroH4er , когда я писал свой коммент предыдущий, Вики не было вообще в списке и при переходе на Вики вылазил экран с предупреждением. А Гитхаб хоть и был в списке и галочка стояла уже - по факту экран тоже вылазил)

**Comment by beautyfree** [comment]
@vista7 @BaroH4er в продакшен не ушло еще, поэтому и вылезает.
все поддомены golos.io находятся в белом списке, что логично

**Comment by vista7** [comment]
@beautyfree . просто там в чекбоксе галочки стоят, как будто задача уже выполнена) на самом деле - нет, получается. Зачем галочки ставят, не очень понятно. Скриншот:
![default](https://user-images.githubusercontent.com/33452731/41038360-35e47e1c-69d9-11e8-8f62-218f758c619a.png)

**Comment by BaroH4er** [comment]
Тестирование завершено. Белый список реализован на песочнице. 

>  https://play.google.com/store/apps/details?id=io.golos.golos
  https://golos.blog/
  https://sandbox.golos.io/
  https://explorer.golos.io/
  https://github.com/
  https://wiki.golos.io/

**Comment by beautyfree** [comment]
Добавлен play.google.com в исключения, чтобы покрыть ссылки с utm метками

**Comment by vista7** [comment]
@beautyfree в гугл-плее иногда распространяются вирусные приложения. Не опасно весь сайт play.google.com в исключения добавлять?
