### ISSUE TITLE
Добавить в настройках возможность отключения предупреждений о переходе по внешним ссылкам

### ISSUE THREAD

**Issue by vista7** [GolosChain/tolstoy#664]
Дамы и господа из golos.io, предлагаю сделать **возможность отключить полностью в настройках экран с предупреждением о переходе по ссылкам**. Не все же нубы на Голосе, многие в кибер-безопасности разбираются хорошо и знают сами по каким ссылкам можно заходить, а куда не стоит. 
Проще говоря - далеко не всем нужен этот экран с предупреждениями, и многие его с радостью отключили бы вообще. Но по умолчанию - пусть будет включен в настройках.

**Comment by mad-max-traveller** [comment]
К тому же необходимо изменить модель поведения этого предупреждения. 
Не знаю, кому пришла в голову идея, перехватывать клики на ссылки, в постах,  выдавать страницу с вопросом: Вы покидаете Golos.io? И потом открывать линк, по которому переходишь, в этой же вкладке. В браузере настроено конкретное поведение, открывать ссылки в новой вкладке, а текущая реализация меняет это поведение на своё. Это не допустимо.

**Comment by vista7** [comment]
@mad-max-traveller согласен с вами на все 100. @jevgenika обратите внимание, пожалуйста.
