### ISSUE TITLE
Создать возможность автоматизировнанной рассылки

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/tolstoy#666]
1. Цель: Создать автоматизированную рассылку для новичков: Приветственное письмо при регистрации со ссылками на полезные материалы и инструкциями как начать писать на Голос. 
Задача отправлять письмо зарегистрированному пользователю на почту после успешного завершения регистрации

Приветственное шаблонное письмо 
- Сразу после успешной регистрации пользователю на электронную почту от noreply от имени Golos.io отправляется шаблонное письмо со ссылками на полезные материалы и инструкциями как начать писать на Голос.
- Письмо шаблонное, одинаковое для всех зарегистрированных
- содержит заголовок
- сверстанный макет письма письма, возможность перейти на сверстанную стр письма
- возможность отписаться от рассылки
- без возможности ответить на письмо

2. Цель: смотивировать пользователей
Задача: встроить проверку, если в течении  неделя от регистрации не была сделана публикация — отправлять мотивирующее письмо.

Мотивирующие шаблонное письмо
- Если в течении недели от успешной регистрации не был сделан первый пост - пользователю на электронную почту от noreply от имени Golos.io отправляется шаблонное письмо со ссылками на полезные материалы и инструкциями как начать писать на Голос.
- Письмо шаблонное, одинаковое для всех
- содержит заголовок
- сверстанный макет письма письма, возможность перейти на сверстанную стр письма
- возможность отписаться от рассылки

3. Цель: вернуть пользователей
Встроить проверку, если в течении  2 недель от регистрации не было сделана ни одно из действий (пост, лайк, дизлайк, коммент, трансфер) отправлять мотивирующее письмо 

Мотивирующие нешаблонное письмо
- Если в течении 2 недель от регистрации не было сделано ни одно из действий (пост, лайк, дизлайк, коммент, трансфер) пользователю на электронную почту от noreply от имени Golos.io отправляется письмо 
- содержит заголовок
- сверстанный макет письма письма, возможность перейти на сверстанную стр письма
- содержимое письма частично может изменяться - каждые 2 недели (зависит от обновлений в спринте) в ручную меняется текст новости в шаблоне письма
- возможность отписаться от рассылки

**Comment by Bacher** [comment]
Задача зверя
