### ISSUE TITLE
Обновить зависимости клиента

### ISSUE THREAD

**Issue by beautyfree** [GolosChain/tolstoy#671]
Rewrited webpack configs to es5
Updated webpack to 4
React 16
Upgraded redux-saga and code 
Plugin for start server
Updated packages
Deleted stats generation
Refactored use of webpack isotools config
mini-css-extract-plugin
Hot reload
Source map
Refactored universal render
Cleaned Main.js
Progress bar while compiling
webpack-serve and etc
renderToNodeStream
styled-components
Node 8.11.3
redux 4
storybook 4 alpha for webpack 4
fixed some legacy react methods
webpack improvements
fixed bugs on welcome page
fixed leave page logic
fixed reducer for new redux
hide subMenu on welcome and pages with param in ResolveRoute

[Branch with commits](https://github.com/GolosChain/tolstoy/tree/671_webpack-react-upgrades)

**Comment by BaroH4er** [comment]
@beautyfree в sandbox найдены следующие проблемы:


1. Header > menu UL > aria-haspopup (информационное меню) > Вики - не открывает
2. Header > menu UL > aria-haspopup (информационное меню) > Центр приложений - не открывает
3. Footer > Условия пользования > 502 ошибка
4. Стр. /welcome - 500 ошибка

**Comment by BaroH4er** [comment]
Fixed. На данный момент никаких ошибок не обнаружено - основной функционал работает исправно, все стабильно отображается и открывается.
