### ISSUE TITLE
Баг с отображением коммента

### ISSUE THREAD

**Issue by litrbooh** [GolosChain/tolstoy#674]
У меня в этом посте: https://golos.io/goldvoice/@litrbooh/novyie-golosuemye-parametry-ot-goloscore-vyzyvayut-nedoumenie

Не отображается этот коммент:
https://golos.io/goldvoice/@zxcat/re-zxcat-re-litrbooh-novyie-golosuemye-parametry-ot-goloscore-vyzyvayut-nedoumenie-20180609t081010843z

![default](https://user-images.githubusercontent.com/22373216/41192133-3dab22b0-6c02-11e8-9f09-1ee460f3128d.png)

Поддержка почему-то не реагирует на обращение в чат.

**Comment by BaroH4er** [comment]
Fixed > [golos#733](https://github.com/GolosChain/golos/issues/733)
