### ISSUE TITLE
Вызвать окно перевода средств по URL-у, с возможностью задания суммы перевода пользователем

### ISSUE THREAD

**Issue by gropox** [GolosChain/tolstoy#676]
Существующее решение с вызовом окна переводов по ссылке не позволяет оставить открытой сумму перевода и создать ссылку не привязанной к отправителю. Надо в ссылке указать обязательно отправителя и сумму к переводу.

Хотелось бы создать ссылку с открытой суммой перевода и не привязанной к отправителю. К примеру для сбора донатов. 

```<a href="https://golos.io/transfer?to=eparshin&token=gbg&memo=На пиво">Донат на развитие</a>```

По клику должен открыться диалог перевода, с редактируемым полем ввода суммы перевода и в качестве отправителя должен быть подставлен залогиненный пользователь.

**Comment by BaroH4er** [comment]
@gropox возможность есть:
https://golos.io/@dekol/transfers?to=eparshin&amount=0.001&token=gbg&memo=%D0%9D%D0%B0%20%D0%BF%D0%B8%D0%B2%D0%BA%D0%BE

**Comment by gropox** [comment]
Отлично! Единственное, что тогда хотелось бы - открытая сумма к переводу. Сейчас если не передать параметр "amount", окно вообще не появляется. Хотелось бы, что бы пользователь мог сам ввести сумму к переводу, если amount не задан.  Поле amount к сожалению не редактируемое.

**Comment by gropox** [comment]
И непонятно, зачем указывать, от кого перевод. Нельзя к примеру сделать ссылку "Пожертвуйте на пропитание". Вернее я догадываюсь, что бы использовать существующую форму перевода. Но это получается сделали как проще, а не как удобнее

**Comment by jevgenika** [comment]
@gropox ваше ишью о том, чтобы сделать поле amount редактируем, так? Чтобы  окно транзакции открывалось с возможностью указать сумму (отредактировать) Тогда следует переименовтаь задачу.
Или нужна ссылка с незаполненным окном транзакции? Неясна проблема и задача, которую вы хотите решить этим таском. Можете расписать подробнее, пожалуйста, чтобы мы понимали приоритет.

**Comment by jevgenika** [comment]
@gropox если идет трансфер со смыслом"Пожертвуйте на пропитание" все равно должен быть адресат и отправитель средств.
Опишите проблему и задачу точнее, пожалуйста

**Comment by gropox** [comment]
Адресат в любом случае, но отправитель должен быть подставлен автоматически, пользователь, который открыл ссылку в golos.io и залогинен. 

С решением сейчас, я не могу создать такую ссылку. Попробуйте кликнуть по ссылке во втором комментарии и перевести монеты. В окне будет поставлен ropox в качестве отправителя, но не jevgenika! И у меня нету возможности изменить отправителя. 

Взять те же донаты, я не могу знать, кто кликнет по ссылке и какую сумму захочет пожертвовать. Мне нужно указать только получателя. Меценату нужен только адрес, куда перевести, что бы он не копировал его из текста.

Второй кейс. У меня есть бот. У бота можно купить премиум вариант за 50 GOLOS-ов.  Сейчас пользователь копирует memo генерируемое ботом и переводит 50 голосов аккаунту бота. Было бы проще, если бы пользователь получил ссылку, кликнув по которой открылось бы окно перевов, в котором мемо, сумма и получатель были бы уже подставлены, а в качестве отправителя выступал бы залогиненный пользователь.

Если я опущу один из параметров в URL, желательно, что бы это поле в форме перевода было редактируемым и пустым.

**Comment by jevgenika** [comment]
Итак, судя по вышесказанному вы просите:
первый вариант
- сделать поле amount редактируем, пустым
- при использовании ссылки указывать  залогиненного пользователя, который открыл ссылку трансфера
- при использовании оставить в ссылке только имя отправителя

второй вариант
- создать ссылку -в которой выставляется отправитель и сумма,
- при использовании ссылки указывать  залогиненного пользователя, который открыл ссылку трансфера

**Comment by gropox** [comment]
Ни первый ни второй вариант. Я не хочу указывать отправителя. Совсем.  

- Отправитель должен быть пользователь открывший ссылку
- Остальные поля должны быть заполнены из опциональных параметров. Если указал в ссылке amount - сумма будет подставлена, не указал, поле остается свободным.

Классическая html форма

**Comment by b1acksun** [comment]
https://github.com/GolosChain/tolstoy/issues/1377
