### ISSUE TITLE
Неправильное отображение делегированной СГ

### ISSUE THREAD

**Issue by Tristamoff** [GolosChain/tolstoy#679]
Аккаунт **А** делегировал аккаунту **В 1 СГ**.
После этого в кошельке **А** напротив СГ написано, что делегировано **-1 СГ**, а у **В +1 СГ**.
Затем **А** делегировал аккаунту **В 0 СГ**.
После этого в кошельке **А** напротив СГ написано, что делегировано **-1 СГ**, а у **В** нет делегированной СГ.
Затем **А** делегировал аккаунту **В 2 СГ**.
После этого в кошельке **А** напротив СГ написано, что делегировано **-3 СГ**, а у **В +2 СГ**.

## Фактический результат:
У того, кто делегировал отображается **-3 СГ**, а у того, кому делегировали - отображается **+2 СГ.**

## Ожидаемый результат:
У того, кто делегировал отображается **-2 СГ**, а у того, кому делегировали - отображается **+2 СГ**.

**Comment by b1acksun** [comment]
> После этого в кошельке А напротив СГ написано, что делегировано -1 СГ, а у В нет делегированной СГ.

Возврат делегированной силы происходит через неделю, соответственно и пропадет надпись
