### ISSUE TITLE
Русские тэги не отображаются как ссылка

### ISSUE THREAD

**Issue by gamerate** [GolosChain/tolstoy#68]
Английские успешно превращаются в ссылку, но русские остаются просто текстом на который нельзя нажать.
[Вот например пост в котором это видно](https://golos.io/ru--golos/@dr2073/bag-s-russkimi-tegami)

**Comment by 0n0t0le** [comment]
есть такая фигня, еще с тестнета

**Comment by Undeadlol1** [comment]
Не занимаюсь этим вопросом, потому что ждем нового редактора текста от команды steemit.

**Comment by tomarcafe** [comment]
не воспроизводится, закрываю
