### ISSUE TITLE
Срок жизни кэша

### ISSUE THREAD

**Issue by gropox** [GolosChain/tolstoy#681]
В последнее время стало особенно неудобно работать с голосом. При открытии страницы golos.io показываются данные со времени последнего посещения страницы. Лента, Блог, Кошелек. 

После открытия страницы в браузере приходится нажимать F5, что бы golos.io перечитал данные из блокчейна.

После перевода средств тоже теперь стало необходимым нажимать F5, что бы golos.io перечитал балансы и показал новые данные.

Может как то уменьшить время жизни данных в кэше до минут?

**Comment by litrbooh** [comment]
Да, меня это тоже порядком умотало, писал несколько раз в чат поддержки - ноль реакции.

**Comment by t3ran13** [comment]
Согласен, тоже достало. Особенно нелогично кешировать так жестоко ленту

**Comment by litrbooh** [comment]
@jevgenika 
Есть планы наладить работу golos.io? Все жалуются, что без Ф5 на сайт хоть не заходи, вы этого не замечаете?

**Comment by jevgenika** [comment]
@litrbooh проблему видим, ищем причину почему так происходит

**Comment by BaroH4er** [comment]
@gropox @litrbooh @t3ran13 
Приветствую! Хочу уточнить, актуальна ли ещё эта проблема?
