### ISSUE TITLE
Реализовать мультиаккаунтинг

### ISSUE THREAD

**Issue by litrbooh** [GolosChain/tolstoy#683]
Очень неудобно пользоваться голос.io, если тебе надо использовать несколько аккаунтов. Как ГВ вырубился, я уже замотался держать 3 браузера с открытыми там golos.io и golos.blog под разные аккаунты.

Чего проще сделать переключение межу аккаунтами?

**Comment by jevgenika** [comment]
@litrbooh вы правы, это важная задача 
будем реализовывать в рамках issue https://github.com/GolosChain/tolstoy/issues/434
