### ISSUE TITLE
Вывод из сейфа ломает кошелек

### ISSUE THREAD

**Issue by vikxx** [GolosChain/tolstoy#684]
Если поставить средства на вывод из сейфа - вкладка  /transfers ломается 
(воспроизводится с залогиненым пользователем)
![1](https://user-images.githubusercontent.com/26347159/41870145-e1ec295a-78c3-11e8-8725-8da61f6791a9.png)

**Comment by BaroH4er** [comment]
Тестирование завершено. 
- [x] FIXED
Изменения залиты в прод., в данный момент на песочнице ошибка воспроизводится.
