### ISSUE TITLE
Посты старше 7 дней не репостятся

### ISSUE THREAD

**Issue by litrbooh** [GolosChain/tolstoy#686]
Снимите ограничение на репост постов старше 7ми дней в нем нет смысла.

![default](https://user-images.githubusercontent.com/22373216/41920268-0958d6a0-7969-11e8-9248-2dd66b93dd31.png)

**Comment by b1acksun** [comment]
https://github.com/GolosChain/tolstoy/commit/b69fd07f37e90afe44b9be2266d4ee8421f22a01

**Comment by b1acksun** [comment]
https://github.com/GolosChain/tolstoy/commit/a3ec826abb435567acdc27db76e14e4283882df9
