### ISSUE TITLE
Добавить в список валют Golos и GBG

### ISSUE THREAD

**Issue by rodnikova** [GolosChain/tolstoy#687]
Нужно добавить в список валют, которые можно выбрать в настройках профиля, Golos и GBG.
Чтобы была возможность видеть награду под постом не только в фиатной валюте, но и в токенах Golos.

**Comment by BaroH4er** [comment]
Done.

![image](https://user-images.githubusercontent.com/21989598/42461459-31a4002c-83a9-11e8-8dc1-4657e55ebf4b.png)

- [x] GBG
- [x] GOLOS

Смена валют функционирует.
