### ISSUE TITLE
Внешние ссылки и окно предупреждения перехода

### ISSUE THREAD

**Issue by BaroH4er** [GolosChain/tolstoy#690]
## FireFox - правая кнопка мыши
**Проблема:** кликая правой кнопкой мыши по ссылке, вместо открытия контекстного меню открывается новая вкладка.

**Браузер:** FireFox

## Новая реализация работы окна предупреждения перехода
**Новая реализация окна предупреждения**:

1. Клик по ссылке
2. Открытие в новой вкладке:
- **a**) если ссылка в белом списке - открывается страница ссылки.
- **b**) если ссылка **НЕ** в белом списке - открывает страницу предупреждения.

Функционал не должн распространятся на ссылки в меню футера сайта и меню профиля (внутренние ссылки сайта).

**Comment by litrbooh** [comment]
да, это реально бесит

**Comment by litrbooh** [comment]
В мобильной версии вообще нет кнопки перейти по ссылке 
![0310ec49-c558-43e6-9f86-7a0f1fbc544c](https://user-images.githubusercontent.com/22373216/43775326-f68b47a8-9a54-11e8-963c-b5026f5b8501.jpg)

**Comment by BaroH4er** [comment]
## Fixes
- [x] FireFox - правая кнопка мыши
- [x] Новая реализация работы окна предупреждения перехода
- [x] кнопка перехода добавлена

## Новые исправления


### Кнопка "ВЕРНУТЬСЯ НА GOLOS.IO"
**Проблема:** на странице предупреждения о переходе на сторонний сайт, открытый в новой вкладке, кнопка "ВЕРНУТЬСЯ НА GOLOS.IO" не работает.

- [x] FIXED

**Воспроизведение:** 
1. Открыть https://sandbox.golos.io/ и авторизоваться.
2. Создать и опубликовать новый пост с ссылкой на сторонний ресурс которого нет в белом списке 
 (ya.ru)
3. Открыть страницу опубликованного поста
4. Кликнуть на ссылку правой кнопкой мыши > открыть в новой вкладке, или mouse3 по ссылке
5. Перейти в открывшеюся вкладку и кликнуть на кнопку "ВЕРНУТЬСЯ НА GOLOS.IO"

**Результат:** нечего не происходит > кнопка не активна

**Ожидаемый результат:** 
**Варианты**
- Вкладка закрывается
- Пользователя возвращает на страницу откуда была открыта страница предупреждения
- Пользователя возвращает на главную golos.io

_Возвращать на страницу откуда была открыта страница предупреждения не вижу смысла, т.к. получается дубль вкладок, на главную тоже достаточно сомнительно, думаю самый оптимальный вариант закрывать вкладку_ @jevgenika @NickShtefan 

<hr/>

### Моб. версия 

**Проблема:** в мобильной версии сайта, страница предупреждения открывается в виде фиксированного окна - на страницу подгружается и шапка и футер, и при скролле они отображаются. 

- [x] FIXED

![image](https://user-images.githubusercontent.com/21989598/46147179-6b2af000-c26d-11e8-82e6-dbd198789c79.png)

**Решение:** отключить шапку и футер сайта в мобильной версии / убрать фиксацию окна предупреждения.

<hr/>

**Проблема:** кнопка "перейти по ссылке" уезжает за пределы экрана.

- [x] FIXED

![image](https://user-images.githubusercontent.com/21989598/46147489-47b47500-c26e-11e8-8849-4f3a7ea4ec30.png)

**Решение:** добавить отступ bottom у кнопки / убрать фиксацию окна

**Comment by AlexRekish** [comment]
было исправлено в #1875
