### ISSUE TITLE
Реализовать возможность копировать картинки в редактор через буфер обмена

### ISSUE THREAD

**Issue by alex-firsov** [GolosChain/tolstoy#691]
Реализовать возможность загружать картинки в редактор постов путем копирования через буфер обмена. Use case: Я копирую текст и картинки из Google документа (Ctrl+A, Ctrl+C) и вставляю (Ctrl+V) в редактор Golos.io, они корректно загружаются и отображаются.

**Comment by Bacher** [comment]
Сделал Ctrl+V для отдельных картинок.
Копи паст из гугл документов пока слишком сложно реализовать.

**Comment by Bacher** [comment]
Сделал Ctrl+V для отдельных картинок.
Копи паст из гугл документов пока слишком сложно реализовать.

**Comment by BaroH4er** [comment]
Тестирование завершено, найдены проблемы:

**Comment by Bacher** [comment]
- [x] Fixed
Убрал HTML

**Comment by BaroH4er** [comment]
Done
