### ISSUE TITLE
Частично закрыть контент на страницах постов

### ISSUE THREAD

**Issue by alex-firsov** [GolosChain/tolstoy#692]
Закрыть на 2/3 (видно только первую 1/3 объема текста) все страницы постов на Golos.io для незарегистрированных пользователей. Для того, чтобы прочитать недостающую часть, необходимо будет зарегестрироваться (по аналогии с pay wall в медиа).

Цель: увеличение конверсии в регистрацию, увеличение количества пользователей на платформе.

**Comment by jevgenika** [comment]
@alex-firsov можно протестировать на 100 стр самых популярных статей

**Comment by litrbooh** [comment]
Учитывая сложности с регистрацией это бредовая идея
