### ISSUE TITLE
Добавить асинхронную загрузку компонентов

### ISSUE THREAD

**Issue by Bacher** [GolosChain/tolstoy#693]
Некоторые компоненты приложения редко и не всеми пользователями используются, но загружаются всегда при загрузке страницы.

Цель: вынести такие компоненты и загружать по требованию.
Предварительный список:
- [x] Редактор постов
![screen shot 2018-07-04 at 13 43 20](https://user-images.githubusercontent.com/2598671/42272911-3f655598-7f90-11e8-8b08-4c85e04ffa2b.png)
- [x] Редактор комментариев
- [x] Биржа
![screen shot 2018-07-04 at 13 41 22](https://user-images.githubusercontent.com/2598671/42272876-258a9156-7f90-11e8-922f-f55a0cad1a97.png)
- [x] Welcome
- [x] Голосовать за делегатов

Возможно по ходу работы вынести и какие-то другие.

**Comment by BaroH4er** [comment]
Done.
