### ISSUE TITLE
"Показать больше топиков" не отображает информацию о тегах

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/tolstoy#694]

**Comment by b1acksun** [comment]
https://github.com/GolosChain/tolstoy/commit/2f6b2445c266fb7c3e2b4f40300d9ea1174a7352

**Comment by BaroH4er** [comment]
Done. 

![image](https://user-images.githubusercontent.com/21989598/42327722-182d1d04-8075-11e8-9e98-5075f9c6dd29.png)
