### ISSUE TITLE
Сделать в новом редакторе добавление тегов пробелом

### ISSUE THREAD

**Issue by litrbooh** [GolosChain/tolstoy#697]
добавлять теги через + неудобно

**Comment by t3ran13** [comment]
Можно и плюс и пробел и еще спецсимвол какойто. Не вижу проблем

**Comment by jevgenika** [comment]
сейчас теги добавляются через enter
@litrbooh @t3ran13 спасибо за ваше предложение с пробелом

**Comment by BaroH4er** [comment]
Done
