### ISSUE TITLE
Указав тег на кириллице, генерируется 2 тега

### ISSUE THREAD

**Issue by BaroH4er** [GolosChain/tolstoy#698]
**Проблема:** При публикации поста с тегом на кириллице, он дублируется на транслите. 

1. Создать и опубликовать пост с тегом "тест" через форму на странице /submit
2. Вернуться в свой блог и зайти на страницу нового поста
2.1 Тег "тест" отображается на кириллице.
3. Зайти в редактировать через кнопку "редактировать"

**Результат:** В поле с тегами появляется два тега в таком порядке - "ru--test" "тест".
**Ожидаемый результат:**  кириллические теги не переводятся в транслит, сохраняются в исходном виде и не дублируются.

**Comment by Bacher** [comment]
[x] Fixed

**Comment by BaroH4er** [comment]
Done
