### ISSUE TITLE
Правки в новый редактор

### ISSUE THREAD

**Issue by rodnikova** [GolosChain/tolstoy#700]
Кнопка предпросмотра

- [x] сделать так, чтобы она сильно отличалась в режиме предпросмотра и режиме редактирования, например, с помощью заливки.

- [x] закрепить кнопку предпросмотра, чтобы и в режиме редактирования и в режиме предпросмотра при прокрутке текста, она всегда была на виду.

Кнопка пост

- [x] в случае, если пользователь не заполнил какое-то из полей в процессе публикации поста, при наведении на кнопку «пост» выдавать подсказку:
- если это заголовок - нужно добавить заголовок или добавьте заголовок;
- если это тело поста - нужно добавить пост или напишите пост;
- если это теги - нужно добавить теги или добавьте теги.

**Comment by allfory0u** [comment]
Можно пожалуйста еще закрепить панель инструментов сверху, чтобы при прокрутке набранного текста она не исчезала? 
![default](http://g.recordit.co/3uyhm2jlle.gif)

**Comment by Bacher** [comment]
@allfory0u HTML редактор править сейчас нет возможности. Он идет одним внешним компонентом и его мы не трогали.

Правки можно вносить только в новый редактор.

**Comment by jevgenika** [comment]
- [ ] поправить текст в подсказках при выборе типа награды за пост @alex-firsov

**Comment by Bacher** [comment]
Готово. Финальные тексты:

> "payout_option_100": "Сила голоса 100%",
> "payout_option_100_hint": "Получить всю награду в Силе Голоса",
> "payout_option_50": "50%/50%",
> "payout_option_50_hint": "Получить награду Силой Голоса и Золотыми",
> "payout_option_0": "Отказ от выплат",
> "payout_option_0_hint": "Опубликовать пост без получения награды",

---

> "payout_option_100": "Power of voice 100%",
> "payout_option_100_hint": "Receive all payout in Golos tokens",
> "payout_option_50": "50%/50%",
> "payout_option_50_hint": "Receive payout in Golos and GBG",
> "payout_option_0": "Refuse payout",
> "payout_option_0_hint": "Publish post without payout",

**Comment by BaroH4er** [comment]
Done
