### ISSUE TITLE
Поправить новый редактор комментариев

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/tolstoy#701]
- [x] внедрить предпросмотр комментария
- [x] добавить рамки границам редактора комментария
- [x] убрать кнопку в тулбаре -руководство по маркдаун
- [x] поправить текст в форме подтверждения очистки формы, уменьшить шрифт в окне потверждения
> Менять размер шрифтов в диалоге нельзя просто так, все диалоги унифицированы, либо везде либо нигде. В дизайне размер такой.

- [x] Заменить кнопку "Пост" на "Ответить", и кнопку "обновить" при редактирования поста
- [x] Добавить редактирование комментариев

---

- [ ] убрать сохранение не опубликовано комментария
> Этот пункт я пофиксил, там была бага. Теперь этот фунционал работает правильно. Совсем отключать сохранение черновика не стал, с фиксом всё работает прозрачно.

- [ ] добавить к кнопку предпросмотра
> Сейчас сделал что предпросмотр всегда отображается (как в старой версии комментариев)

- [ ] заверстать редактор комментариев согласно дизайн документу.
> Не совсем понятно имеет ли смысл верстать комментарии без переделки остальной верстки поста.

**Comment by Bacher** [comment]
![screen shot 2018-07-10 at 19 44 38](https://user-images.githubusercontent.com/2598671/42524606-b71d1236-8479-11e8-8636-9c6f6d2c41ae.png)

**Comment by Bacher** [comment]
Если делать по новому дизайну, нужно весь блок комментариев переделывать сейчас.

**Comment by Bacher** [comment]
Предлагаю вот так:
![screen shot 2018-07-10 at 19 57 11](https://user-images.githubusercontent.com/2598671/42525304-7d4966b6-847b-11e8-909c-f12c5fe38f35.png)

**Comment by BaroH4er** [comment]
Done.
