### ISSUE TITLE
Отмена делегирование и уменьшение СГ

### ISSUE THREAD

**Issue by denis-skripnik** [GolosChain/tolstoy#704]
Здравствуйте.
1. Не удаётся отменить делегирование СГ через golos.io путём ввода числа "0": добавьте функционал отмены по клику на ссылку возле "Делегировать", если делегированная СГ другим аккаунтам есть, либо пусть можно будет отменить делегирование путём ввода "0" (без кавычек) по ссылке "Делегировать";
2. На аккаунте https://golos.io/@prazdnik еесть делегированная другим аккаунтам СГ, а также полученная. При попытке вывода Силы Голоса появляется ошибка "Transaction broadcast error."
Сделайте пожалуйста или ошибку более подробной/понятной, или возможность вывода той СГ, которая не делегирована другим аккаунтам (если проблема в этом) или пусть в случае запуска вывода делегирование отменяется автоматически.

Благодарю.

**Comment by b1acksun** [comment]
2. https://github.com/GolosChain/tolstoy/commit/f1effca53e26a50e4e1245d61b0e0e0a3d985ac2

**Comment by litrbooh** [comment]
@denis-skripnik  @b1acksun 
Не нужно отменять делегирование автоматически, в этом нет смысла. Делегирование возвращается неделю, а понижать я хочу уже сейчас. Нужно, просто сделать как на стимит. 
https://github.com/GolosChain/tolstoy/issues/706

**Comment by b1acksun** [comment]
1. https://github.com/GolosChain/tolstoy/commit/bc80aa8e47ed6a7ebcabaef3092db79e3d07b7a6

**Comment by BaroH4er** [comment]
Необходимо дополнить информацию в окне отмены делегирования СГ.

**Воспр.**:
1. Открыть страницу профиля авторизированного пользователя
2. Открыть вкладку "Кошелек"
3. Открыть выпадающий список Силы голоса и делегировать СГ _пользователю_
![image](https://user-images.githubusercontent.com/21989598/43410049-47df4050-942e-11e8-868d-df572f309947.png)
4. Открыть окно отмены делегирования Силы Голоса с помощью ссылки под суммой СГ, и кнопки "Отмена" в таблице делегирования.
![image](https://user-images.githubusercontent.com/21989598/43410226-e798b6ee-942e-11e8-83a9-c84d16371b92.png)

**Результат:**
>Вы действительно хотите отозвать делегированную Силу Голоса у пользователя %name%

**Ожидаемый результат:**
Возврат Силы Голоса займет **7 дней**. Вы действительно хотите отозвать делегированную Силу Голоса у пользователя %name% ?

**Comment by BaroH4er** [comment]
Актуально:
- [ ] Необходимо дополнить информацию в окне отмены делегирования СГ.
https://github.com/GolosChain/tolstoy/issues/704#issuecomment-408926488

**Comment by NickShtefan** [comment]
Надо провести тестирование в новом дизайне

**Comment by BaroH4er** [comment]
Done
