### ISSUE TITLE
изменить текст в смс при подтверждении номера

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/tolstoy#705]
В процессе регистрации изменить текст в смс рассылке 

при подтверждении номера.
Рус: Спасибо, ваш номер подтвержден. Продолжите регистрацию.
Анг: Thank you, your number is successfully confirmed. Please, continue the registration.

Текст при отправки пользователю код подтверждения:
Рус: Ваш код подтверждения Golos.io XXXX
Анг: Your Golos.io verification code is XXXX

**Comment by BaroH4er** [comment]
**Проблема:** Текст в смс рассылке при подтверждении номера не соответствует: 

![img_7789](https://user-images.githubusercontent.com/21989598/45753156-8e77ee80-bc20-11e8-93be-65a7d9c3a825.jpg)

**Решение:** 
Рус: Спасибо, ваш номер подтвержден. Продолжите регистрацию.
Анг: Thank you, your number is successfully confirmed. Please, continue the registration.

**Comment by BaroH4er** [comment]
Исправлено.
