### ISSUE TITLE
Баг редактора (комментариев) в мобильных браузерах

### ISSUE THREAD

**Issue by vikxx** [GolosChain/tolstoy#709]
Ошибку воспроизвели пользователи (3) в safari и яндекс браузерах на IOS.
После инициализации поля ввода для комментария при вводе символа редактор закрывается и перенаправляет на главную.

> Хочу писать коммент, жму "Ответить", получаю форму для ввода коммента

> Ставлю курсор в поле ввода нажимаю букву  и выкидывает в ленту

> У меня такая же проблема, комментировать с айпада получается только методом копирования из блокнота и вставки готового текста в новый редактор комментариев.

`iOS 11.4.11`

**Comment by Bacher** [comment]
Пофикшено! Ждем выливки.
