### ISSUE TITLE
Заверстать стр FAQ

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/tolstoy#712]
- [ ] создать и заверстать стр FAQ https://golos.io/faq согласно разработанному [дизайну](https://projects.invisionapp.com/share/P7MYKBXUE94/#/screens/296817972/comments/97844271)

**Comment by BaroH4er** [comment]
### Раскрывающаяся панель ответа на вопрос

**Проблема:** для открытия ответа на вопрос, используется **небольшая** иконка справа от вопроса, что ухудшает "юзабельность".  

- [ ] FIXED

**Решение:** раскрывающаяся панель функционирует при клике по титлу вопроса, а не только по иконке раскрытия. 

![image](https://user-images.githubusercontent.com/21989598/44788443-bdabba80-aba2-11e8-9d3b-0baa73f496b4.png)

<hr/>

**Вопрос:**

>*вставить ссылку на FAQ в футер, меню, стр добро пожаловать*

Это должно быть выполнено в рамках этого ишью? или при редактировании футера сайта? Я правильно понимаю что имеется ввиду футер сайта, а не футер страницы "Добро пожаловать" ?

- [ ] Решен

**Comment by NickShtefan** [comment]
обновления тут https://preview.golos.io/faq

**Comment by BaroH4er** [comment]
Тестирование завершено. Ошибок нет.
