### ISSUE TITLE
расчет мощности голоса

### ISSUE THREAD

**Issue by epexa** [GolosChain/tolstoy#713]
с эксплорером возникает недоразумение из-за:
1. почему называется Golos Power, если это Voting Power?
2. нужно округлять до 100%, потомучто странно что макс. значение это 99.5%.
3. этот показатель не считается в реал. тайме, когда в реале к примеру значение уже 93.08%, то в блоге показывается 97.41%.

в блоге:
![erlan kotov epexa golos io](https://user-images.githubusercontent.com/2198826/42746734-fcb2b12c-88e1-11e8-881f-c2ec6804852a.png)

в эксплорере:
![golosexplorer 1](https://user-images.githubusercontent.com/2198826/42746737-fe5182e2-88e1-11e8-988c-e15a1ec236d5.png)

1. это Voting Power, так как это берётся из метода get_accounts, элемент voting_power:
```js
golos.api.getAccounts(['epexa'], console.log);
=> voting_power: 9950
```
а Golos Power выстчитается так:
```js
Golos Power = golos.formatter.vestToGolos(account.vesting_shares, getDynamicGlobalProperties.total_vesting_shares, getDynamicGlobalProperties.total_vesting_fund_steem);
```
[описание из документации](https://github.com/GolosChain/golos-js/tree/master/doc#vest-to-golos)

2. чтобы округлять до 100.0% нужно делать:
```js
Math.min(currentVotingPower / 100, 100).toFixed(2)
```

3. по всей видимости значение берётся из кэша.

**Comment by t3ran13** [comment]
совсем в ио все зеленые(((
