### ISSUE TITLE
Баг с отображением оценки постов в GOLOS

### ISSUE THREAD

**Issue by litrbooh** [GolosChain/tolstoy#716]
вот оценка поста
![default](https://user-images.githubusercontent.com/22373216/42805973-ec53a0d2-89b5-11e8-94cf-4f4b3557c9c8.PNG)

Написано, что я как автор получил 447 GOLOS

А вот выплата: 
![default](https://user-images.githubusercontent.com/22373216/42806010-0066c694-89b6-11e8-9d45-8330acf05223.PNG)

Всего 326 GOLOS. Где ещё мои 121 голосов? 

Ну и размер кураторских в 116 голосов тоже полный бред, и в абсолютных и в относительных цифрах.

**Comment by daryasattarova** [comment]
связанные задачи #1057

**Comment by litrbooh** [comment]
да ладно...
