### ISSUE TITLE
некорректный счетчик голосов в разных разделах

### ISSUE THREAD

**Issue by 0n0t0le** [GolosChain/tolstoy#72]
Отображается разное количество голосов при просмотре непосредственно под самим постом и при просмотре того же поста, из других разделов (например популярное, блог, и.т.д )

![](https://s14.postimg.org/5w8cyxp01/000.png)

Подробности тут:
https://golos.io/ru--golos/@on0tole/veb-klient-golosa-bagreport-1

**Comment by Undeadlol1** [comment]
Судя по комментарию под постом, это не баг. Правильно?
Актуально? Закрываю?
