### ISSUE TITLE
Локализация настроек публичного профиля

### ISSUE THREAD

**Issue by BaroH4er** [GolosChain/tolstoy#721]
- [ ] убрать локализацию для Украинского, Сербского, Румынского языков

- [ ] добавить перевод настроек для англ языка

**Требуется перевод текста:**

- Отображение наград
  - Округлять до целого числа
  - Один знак после запятой
  - Два знака после запятой
  - Три знака после запятой
- Вставьте ссылку на изображение или загрузите его
  - Загрузить
- Вставьте ссылку на обложку или загрузите ее
  - Загрузить

![image.png](https://images.zenhubusercontent.com/5a6f31974b5806bc2bc4b26e/034ca430-4aa7-45a2-a14e-8f088aef0828)

**Comment by NickShtefan** [comment]
украинский предлагаю оставить

**Comment by BaroH4er** [comment]
@jevgenika не хватает перевода на украинский язык, этот ишью предлагаю закрыть, т.к. поставленная задача не актуалена для нового профиля. @beautyfree есть ли список необходимый для перевода?
