### ISSUE TITLE
Добавить в редактор кнопки для выравнивания текста

### ISSUE THREAD

**Issue by litrbooh** [GolosChain/tolstoy#722]
Ни в мардауне, ни в хтмл редакторе нету, это недобно
![default](https://user-images.githubusercontent.com/22373216/43280489-b116c4ca-9119-11e8-9537-4f5e9a829584.png)

**Comment by gropox** [comment]
Я заворачиваю в 

```
<div class="text-justify">
Текст
</div>
```
Если это о том

**Comment by litrbooh** [comment]
@gropox 

> Я заворачиваю в

если бы я знал во что ты заворачиваешь ) 
я больше про <center>фото</center>

**Comment by gropox** [comment]
А, я понял ты про выравнивание текста, что бы от края до края, а ты про центрирование. Так бы и писал

**Comment by litrbooh** [comment]
@gropox 
Не, я про все выравнивания и по центру и от края до края, я только не понимаю как вообще код впихнуть в редактор, поэтому ещё одно ищью завел: 
https://github.com/GolosChain/tolstoy/issues/723

**Comment by jevgenika** [comment]
@litrbooh центрирования не было в тулбаре MD и Html редактора. Вернуть не можем) 
Добавить да!)

**Comment by litrbooh** [comment]
@jevgenika 
Раньше можно было код вставить руками и редактор это сжирал, а сейчас - нет.

**Comment by litrbooh** [comment]
@NickShtefan пишет, что редактор понимает HTML
