### ISSUE TITLE
Добавить в HTML редактор кнопку для просмотра хтмл кода

### ISSUE THREAD

**Issue by litrbooh** [GolosChain/tolstoy#723]
Че-то я все глаза просмотрел, а где кнопка, чтобы посмотреть и вставить код в хтмл редакторе?
![default](https://user-images.githubusercontent.com/22373216/43280811-9c374362-911a-11e8-807d-e98049d53076.png)

Может я тупой, но как?
![default](https://user-images.githubusercontent.com/22373216/43280868-bb117e10-911a-11e8-99fa-8a7326ccdd74.png)

![default](https://user-images.githubusercontent.com/22373216/43280883-c7b1488a-911a-11e8-9c8e-4a72ad6f3576.png)

**Comment by NickShtefan** [comment]
@litrbooh просто воспользуйся новым редактором, вставь свой html код туда

**Comment by litrbooh** [comment]
@NickShtefan 
Ну, ставил я код, допустим он был где-то кривой, как мне вернуться  в редактирование кода?

**Comment by NickShtefan** [comment]
@litrbooh не могу понять о чем именно идет речь, попробуй переформулировать свои мысли. 

Насчет работы HTML редактора. Этот тот же самый редактор, который всегда присутствовал на сайте, и мы его сохранили, чтобы не травмировать привыкших к нему пользователей, в том числе по этой же причине у него осталось старое название. В данный момент мы не занимаемся доработками старого редактора, однако при необходимости можем добавлять функциональность к новому. Пожелания принимаются в комментариях под постами golosio и в виде сформулированного issue на github


Далее будет пошаговая инструкция, как  работать с HTML тегами в новом редакторе

1. Нажать кнопку "Добавить пост" в шапке сайта. (подчеркнуто зеленым)

![image](https://user-images.githubusercontent.com/6249597/43410935-46adb9b6-9431-11e8-8d1d-25d8538b400a.png)

2. Перед тобой появится экран создания поста, тут надо выбрать "Новый редактор" (для простоты понимания выделено зеленым квадратом)
![image](https://user-images.githubusercontent.com/6249597/43411031-a4cf2e12-9431-11e8-82fc-e0b18e9991e4.png)

3. Надо нажать левой кнопкой мыши по полю, в котором написано "Расскажите свою историю". 

![image](https://user-images.githubusercontent.com/6249597/43411270-585f9408-9432-11e8-8ba3-7466fdab9817.png)

4. Теперь можно начинать вводить текст, используя HTML теги, либо markdown

![image](https://user-images.githubusercontent.com/6249597/43411531-0f5bdc5c-9433-11e8-9811-a80f958ee2a2.png)

Обращу внимание, что не все введенные теги будут отображаться на сайте golos.io

5. Для того, чтобы перейти в режим предпросмотра необходимо нажать на "глаз" в правом верхнем углу

![image](https://user-images.githubusercontent.com/6249597/43411590-4176f500-9433-11e8-9794-7db372d7ea40.png)

6. Режим предпросмотра отображает текст так, как он будет отображаться на сайте
Для того, чтобы выйти из режима предпросмотра надо еще раз нажать на "глаз" в правом верхнем углу

![image](https://user-images.githubusercontent.com/6249597/43411858-20bb8992-9434-11e8-9ce3-03b2f0305b38.png)

Экспериментируй, если возникнут сложности, со мной можно связаться [напрямую здесь](https://t.me/golos_developers)

**Comment by gropox** [comment]
Вы переименуйте HTML редактор в "Визуальный редактор", а то путает. Я думал, что это как раз редактор, что бы писать html код. А получается html код надо писать в "Новом редакторе", а HTML Редакторе его не напишешь

**Comment by litrbooh** [comment]
@NickShtefan, @gropox правильно пишет, что у вас HTML редактором называется то, что им не является. Вообще, связка графический редактор + HTML был бы удобным. 

У вас же получается невозможно что-то визуально поправить, а что-то в коде, как бы в старом редаторе и как есть в ГВ и и форме вика. Получается, что я либо чисто код правлю и всё время жмакаю кнокпу просмотра, или чисто графически. А раньше, я могл вереключаться с визуальный редактор обратно в редактор с кодом.

Вообще, раньше сразу был препросмотр и это было в разы удобнее. А теперь щелкать всё время надо
