### ISSUE TITLE
В редакторе не работает спеллчек

### ISSUE THREAD

**Issue by gropox** [GolosChain/tolstoy#724]
Без проверки орфографии никуда, особенно таким троечникам как я ))
Раньше работало, а сейчас встроенный spellcheck в хроме, фаерфокс не работает больше.

**Comment by Bacher** [comment]
В результате исследования вопроса стало понятно, что в текущем редакторе не получается нормальными способами включить проверку орфографии. Задача откладывается.

**Comment by Bacher** [comment]
Так, вроде как получилось добавить браузерный spellcheck.
Сменил рендер движек.
Для тестирования: надо проверить, что редактор ведет себя как ожидается и нет серьезных различий до и после (кроме проверки орфографии).

**Comment by Bacher** [comment]
Правка была сделана на основе треда https://discuss.codemirror.net/t/inputstyle-contenteditable-we-may-hope-for-browser-spell-checking/608/4

**Comment by BaroH4er** [comment]
Работает. Могут возникать ошибки из-за редактирования текста, но они допустимы. Done.
