### ISSUE TITLE
Закрыть дыры в безопасности аккаунтов

### ISSUE THREAD

**Issue by litrbooh** [GolosChain/tolstoy#725]
Наверно, все в курсе проблемы: https://golos.io/thallid/@ksantoprotein/ksantoprotein-1532534789

Сегодня ещё одна жертва: https://golos.io/@ms-boss/transfers

![default](https://user-images.githubusercontent.com/22373216/43322875-a69af198-91b8-11e8-9d65-181f1b80d991.png)

Нужно сделать две вещи:
1) Запретить в мемо засовывать приватный ключ
2) Нужно, сделать чтобы при смене ключей через пароль была возможность сбросить все настройки по мульсигам, иначе пользователь не сможет выбраться из случая описанного в посте.

**Comment by Bacher** [comment]
Пока что реализована только первая часть задачи.
> Запретить в мемо засовывать приватный ключ

**Comment by Bacher** [comment]
Вторую часть задачи вынес в отдельную задачу https://github.com/GolosChain/tolstoy/issues/1814
