### ISSUE TITLE
Покупка внимания

### ISSUE THREAD

**Issue by gropox** [GolosChain/tolstoy#726]
Не знаю почему, но до сих пор кроме "продвижения поста" на golos.io нету другой возможности продвинуть пост. 

Раз уж golos.io старается стать самоокупаемым проектом, то почему бы не добавить возможность купить внимание к посту. 

- Купить допустим подсветку поста в ленте
- Позицию поста в ленте, возможно алгоритмическую, такую же как сейчас при продвижении поста.  Чем выше доля уплаченной суммы за пост от суммы всех оплаченных постов, тем выше место в ленте. Ну и плюс зависимость от времени.

Сейчас уже авторы отдают бустерам большие деньги с минимальной выгодой, что бы побыть немного в топе, возможно это составит конкуренцию бустерам, если стоимость покупки внимания будет доступной/конкурентноспособной.

**Comment by t3ran13** [comment]
а еще лучше продвинутые посты начать отображать в ленте у всех)

**Comment by t3ran13** [comment]
Можно без исключений.
При грамотной реализации, например аукцион по времени отображения на первой позиции при прогрузке ленты

Минимум дискомфорта от 1 поста, максимум профита)
