### ISSUE TITLE
Выбор фида в мобильной версии

### ISSUE THREAD

**Issue by gropox** [GolosChain/tolstoy#727]
Выпадающий список с лентами слишком мелкий в мобильной версии. Трудно попасть. 

![image](https://user-images.githubusercontent.com/26039472/43707795-24fc4c1e-9969-11e8-9271-467d599d33a6.png)

**Comment by kuchinskaya** [comment]
Нужно сделать отступ от краев по 20px http://prntscr.com/kf9v88  И между словами отступ на высоту слова (примерно 16 px)
