### ISSUE TITLE
Не работает кнопка поделиться статьей на фэйсбук

### ISSUE THREAD

**Issue by 0n0t0le** [GolosChain/tolstoy#73]
Из названия в принципе все понятно, баг проявляется во всех браузерах.

![](https://s11.postimg.org/b8dedvso3/image.png)

**Comment by Undeadlol1** [comment]
Я еще код не читал и в проблеме не разбирался, но @tomarcafe подписываю тебя, возможно ты знаешь в чем проблема. Вроде ты занимался этим вопросом в прошлом.
Если проблема не в фейсбуке, а клиенте, то перебрасывай на меня.
