### ISSUE TITLE
обновить интерфейс регистрации

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/tolstoy#730]
- [x] обновить интерфейс регистрации относительного готового интерфейса стр
- [x] разбить регистрацию на шаги

**Comment by BaroH4er** [comment]
- [ ] https://github.com/GolosChain/registration-frontend/issues/1
- [ ] https://github.com/GolosChain/registration-frontend/issues/3
- [ ] https://github.com/GolosChain/registration-frontend/issues/4

**Comment by Bacher** [comment]
Всё готово, кроме GolosChain/registration-frontend#3
Эта задача блокируется до того момента когда у нас будет реализованна страница авторизации на golos.io.

**Comment by Bacher** [comment]
Вообще это задачу нужно закрыть полностью. Проверку вести только в репозитории registration-frontend. А то сломанный телефон получается.

**Comment by BaroH4er** [comment]
Актуально:
- [ ] GolosChain/registration-frontend#1

**Comment by Bacher** [comment]
GolosChain/registration-frontend#1 поправил, но в целом эту задачу стоит я думаю закрыть, так как все фиксы находится в репозитории registration-frontend. В репозиторий tolstoy не должно ничего сыпаться с регистрации.

**Comment by BaroH4er** [comment]
Done
