### ISSUE TITLE
Неправильное отображение некоторых символов в постах Golos.io при публикации через сторонние клиенты

### ISSUE THREAD

**Issue by vista7** [GolosChain/tolstoy#731]
Иногда бывает такой баг в постах Golos.io: некоторые символы, **опубликованные через сторонние клиенты** неправильно отображаются на Golos.io, показываются в html-коде. Например, знак троеточия (...) показывается вот так, в html-коде:

![default](https://user-images.githubusercontent.com/33452731/43733198-3a636af4-99f7-11e8-8755-56ca0fd2f815.png)

В данном случае, на скрине пример поста, сделанного в stihi.io, как он отображается в golos.io.
Иногда ещё знак кавычек (вот таких - " ") не правильно отображается, тоже в html-коде показывается, и прочие подобные символы. 
Этот баг уже давно существует, не первый месяц.

**Comment by vista7** [comment]
Также, если в постах опубликованных через stihi.io написать какой-то коммент в golos.io, то частенько бывает баг с отображением этих комментов на stihi.io - они показываются кракозябрами. 
Возможно это баг именно клиента stihi.io, но тем не менее. 

А тот баг, что описан в самом ишью - это баг именно golos.io, как мне кажется.

**Comment by yurgent71** [comment]
В свое время разработчики сделали поддержку спецсимволов &laquo; и &raquo; (левая и правая двойные кавычки). За это спасибо большое. Но до остальных символов так и не добрались. Предлагаю хотя бы несколько самых популярных еще добавить: &mdash; &ndash; &copy; &hellip; &lt; &gt; &quot; &prime; &shy;

**Comment by dechadecha** [comment]
Также нет возможность добавить в заголовок символы которые могут быть использованы в маркдаун, например многоточие в заголовке или пару звездочек для цензурировании
