### ISSUE TITLE
убрать юзернейм пользователя в ответах к посту

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/tolstoy#732]
- убрать вывод имени пользователя в ответах к посту,
- оставить вывод имени пользователя в комментариях

**Comment by litrbooh** [comment]
а в чем разница?

**Comment by t3ran13** [comment]
Это нужно вынести в настройки пользователя

**Comment by vista7** [comment]
@litrbooh , Евгения наверное имела ввиду "убрать юзернейм пользователя в ответах к СОБСТВЕННОМУ посту", да, @jevgenika ? ;) 
Я об этом баге сообщал недавно, действительно - в ответах к своему посту не нужен ник, а он сейчас подставляется автоматом.
