### ISSUE TITLE
Странное поведение редактора.

### ISSUE THREAD

**Issue by gropox** [GolosChain/tolstoy#733]
1. Не работает встроенная в браузер проверка орфографии. Особенно важно таким троечникам как я.
2. Во вторых кнопка Home закидывает в начало Предложения, а не строки. Хотя в других редакторах это именно переход в начало текущей строки.  Очень путает.

Вот так вот выглядит на голосе
![goloseditor gif](https://user-images.githubusercontent.com/26039472/43778775-d618c30e-9a56-11e8-8313-0c868c9c4528.gif)

А так на github к примеру, ну и видно, что на гитхабе ошибки подчеркнуты, а на голосе нет

![githubeditor gif](https://user-images.githubusercontent.com/26039472/43778797-e0d4d486-9a56-11e8-895e-9699443e6889.gif)

**Comment by t3ran13** [comment]
Незнаю пофиксили или нет, еще редактирование сообщений глючило по полной

А с телефона перенос каретки это вообще издевательство, неправильно скачет. Плпробуйте в редакторе с телефона выделить текст и скопировать, тот еще квест

**Comment by vista7** [comment]
Подтверждаю! Попробовал сейчас в самой свежей версии Фаерфокс-браузера (десктоп) - не подсвечиваются ошибки в орфографии в редакторе Голос.ио, хотя - должны. Раньше не обращал внимание на это.

**Comment by MachtFrei** [comment]
spellcheck заработал, второй пункт нет

> Во вторых кнопка Home закидывает в начало Предложения, а не строки. Хотя в других редакторах это именно переход в начало текущей строки. Очень путает.

**Comment by Bacher** [comment]
> Во вторых кнопка Home закидывает в начало Предложения, а не строки. Хотя в других редакторах это именно переход в начало текущей строки. Очень путает.

Это мы поправить не сможем.

Можно закрывать.
