### ISSUE TITLE
Картинка содержащая в url пробелы не показывается в ленте

### ISSUE THREAD

**Issue by gamerate** [GolosChain/tolstoy#74]
Если url картинки содержит пробелы, то в ленте она показывается серым квадратом (первый скриншот верхний пост), если перезалить картинку без пробелов - все отображается ок  (второй скриншот).
Не критично, но все же баг.
![screenshot from 2016-10-21 02-52-44](https://cloud.githubusercontent.com/assets/954529/19582000/e9930d26-9739-11e6-8b79-d3e8beb57863.png)
![screenshot from 2016-10-21 02-53-30](https://cloud.githubusercontent.com/assets/954529/19581999/e992f868-9739-11e6-9376-2fc621732aff.png)

**Comment by 0n0t0le** [comment]
Можешь привести примеры обоих ссылок на img
Пытаюсь понять почему куча фотохостингов работающих на стиме не работает тут

**Comment by gamerate** [comment]
Аналогичная вот такой не сработала:
https://httpsimage.com/img/Screenshot from 2016-10-21 02-52-44.png
После того как убрал пробелы из нее - и перезалил туда же - заработала

**Comment by Undeadlol1** [comment]
Юрл не должен содержать пробелов.
Извините что сразу не закрыл ишью. Думал написать функцию, которая будет убирать пробелы, но в предверии нового редактора текста все откладывал.
Закрываю потому что неизвестно когда будет добавлен новый редактор, и какая логика добавления изображений будет там. Возможно в будущем это ишью снова будет актуально.
Не отказано, но отложено на неопределнный срок.
