### ISSUE TITLE
Интеграция tolstoy и rates-service

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/tolstoy#743]

**Comment by BaroH4er** [comment]
# Не совпадают ценники golos.io - sandbox  

- **Стоимость поста**
- **Стоимость аккаунта**

<hr/>

## golos.io

![image](https://user-images.githubusercontent.com/21989598/45432012-739dfb00-b6b1-11e8-91b4-6a5b216c1983.png)
![image](https://user-images.githubusercontent.com/21989598/45433432-cfb64e80-b6b4-11e8-976f-6b1949f63619.png)



## sandbox.golos.io

![image](https://user-images.githubusercontent.com/21989598/45431891-3afe2180-b6b1-11e8-9d66-b1e2cc90be68.png)
![image](https://user-images.githubusercontent.com/21989598/45433416-c88f4080-b6b4-11e8-95dd-2ae6298aa848.png)

<hr/>

**Предположение:** 
1) делегированное СГ плюсует в стоимость поста, а не в оценку стоимости аккаунта. 
2) в оценки стоимости аккаунта, не хватает кроме СГ ещё чего-то...

**Comment by Bacher** [comment]
Они и не должны совпадать, у нас теперь более точная версия.

**Comment by Bacher** [comment]
Проверить можно так, поставить отображение валюты в GBG, посмотреть значение в GBG и умножить на курс обмена с GBG => валюту на https://coinmarketcap.com/currencies/golos-gold/ и посмотреть, что получается таже цена, что и предлагает новая версия на сандбоксе.
