### ISSUE TITLE
Голосовалки и опросники на голосе

### ISSUE THREAD

**Issue by yurgent71** [GolosChain/tolstoy#754]
Предлагаю встроить систему создания голосований или опросов на клиенте golos.io

Голосование в опросе - это же тот же комментарий. 
Теперь как сделать - автор создает внутри поста опрос - при этом система генерит уникальный идентификатор (guid) опроса и guid'ы для вариантов ответов. 
Когда же кто-то голосует, то он оставляет комментарий содержащий два guid'а (опроса и варианта ответа). 
Стандартное голосование должно начинаться с каких-то спецсимволов, чтобы его не отображать в комментариях (на golos.io) - в других же клиентах (которые не знают об этом) будет выглядеть как комментарий вида "##{C290A815-BAAA-4455-82EA-F18F5D0CEF2E} {52335ABA-2D8B-4892-A8B7-86B817AAC607}" где ## - выбранный спецтег для опроса, первый гуид - это ид-опроса, а второй ид ответа.

**Comment by gropox** [comment]
В принципе рабочая система, можно было бы попробовать. Но мне кажется подвержена манипуляциям. Не средствами голоса такое делать. Могут просто заспамить.

Вместо GUID наверное проще создавать коментарии с permlink осбого вида. Вроде "choice-variant-1-20180606T121212Z" а в теле комментария писать вариант ответа, как заданно в опроснике.

Тогда в других клиентах будет виден нормальный ответ к посту с вариантом ответа, а в клиенте golos можно будет консолидировать такие ответы в виде графика.

**Comment by yurgent71** [comment]
Согласен. И, кстати, нужен какой-то сгенеренный идентификатор  завязанный  в том числе на времени, чтобы избежать вариантов, когда автор взял и исправил свой опрос, перевернув варианты с ног на голову. Тогда при любом редактировании опроса через интерфейс golo.io будет заново сгенерен этот id. Соответсвено, ранее сделанные ответы "протухают" при редактировании основного поста. Даже если же какой-то "хакер" поменяет сырцы опроса из другого клиента (напр. goldvoice), то произойдет расхождение той части идентификатора, которая содержит datetime с полем, содержащим дату и время изменения поста и, таким образом, ранее сделанные ответы не будут относиться и отражаться в графике на golos.io) - они так и останутся привязанными к первоначальному опросу.
