### ISSUE TITLE
Реализация вкладки "ключи" в обновленном профиле

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/tolstoy#756]

**Comment by BaroH4er** [comment]
## Страница настроек > Вкладка "Ключи" > Блок: Активный ключ > кнопка «Авторизуйтесь для этой транзакции»

**Проблема:** При открытии окна авторизации для получения приватного активного ключа сохраняется текстовка с предыдущей попытки авторизации.

- [ ] FIXED

**Воспроизведение:**
1. открыть https://sandbox.golos.io/
2. авторизироваться
3. зайти на Настройки -> Ключи -> Ключи
4. нажать на кнопку ""Авторизируйтесь для этой транзакции""
5. ввести неверный ключ -> нажать кнопку ""Войти"" (появится текстовка под полем ввода с указанием, что ключ неверный)
6. закрыть окно и открыть заново

**Результат:** при повторном открытии окна текстовка о неверном ключе сохраняется"
**Ожидаемый результат:** должно открыться окно входа (без текстовок)

<hr/>

## Страница настроек > Вкладка «Новый ключ» > Кнопка «Обновить» 

**Проблема:** Блокируются поля ввода после неудачного обновления ключа.

- [ ] FIXED

**Воспроизведение:**
1. открыть https://sandbox.golos.io/
2. авторизироваться
3. зайти на Настройки -> Ключи -> Новый ключ
4. ввести в поле ""Текущий пароль"" неверный пароль
5. заполнить остальные поля верно
6. нажать кнопку ""Обновить""

**Результат:** поля ввода недоступны для редактирования
**Ожидаемый результат:** должен появиться пуш с текстом причины, почему ключ не обновлен. Поля ввода должны быть активны для дальнейшей их корректировки
<hr/>

## Страница настроек > Вкладка «Новый ключ» > Поле "Сгенерированный пароль" 

**Проблема:** Поле "Сгенерированный пароль" редактируется.
	
- [ ] FIXED

**Воспроизведение:**
1. открыть https://sandbox.golos.io/
2. авторизироваться
3. зайти на Настройки -> Ключи -> Новый ключ

**Результат:** поле редактируется"
**Ожидаемый результат:** поле ""Сгенерированный пароль"" не должно редактироваться

<hr/>

## Страница настроек > Вкладка «Новый ключ» > Кнопка «Обновить» 

**Проблема:** Неверная текстовка в пуше при попытке обновления ключа	

- [ ] FIXED

**Воспроизведение:**
1. открыть https://sandbox.golos.io/
2. авторизироваться
3. зайти на Настройки -> Ключи -> Новый ключ
4. ввести в поле ""Текущий пароль"" неверный пароль
5. заполнить остальные поля верно
6. нажать кнопку ""Обновить""

**Результат:**  появляется пуш с текстом ""Missing Owner Authority [ник юзера]"""
**Ожидаемый результат:**  должен появиться пуш, который говорит причину, почему ключ не обновился

<hr>

### Репорт составлен на основе чек-листа:
https://docs.google.com/spreadsheets/d/1RHpkhk23s6z9Spdkv3KbGz2LL5IY6souOXQaM1Tukw0/edit#gid=232561360 строки 248 - 262

**Comment by BaroH4er** [comment]
Исправлено. Done.
