### ISSUE TITLE
Изменить алгоритм выдачи "Популярное" до первых выплат

### ISSUE THREAD

**Issue by lehard** [GolosChain/tolstoy#76]
Возможно ли поменять временно алгоритм выдачи на странице популярное? Что бы появилась ротация статей, иначе до первых выплат я так понимаю будем видеть одни и те же статьи в топе и те, которые будут к ним добавляться по ходу дела.

**Comment by lehard** [comment]
Сейчас одни делегатские посты))) Думаю это будет вызывать недовольство уже в ближайшие дни.
![image](https://cloud.githubusercontent.com/assets/22220976/19603732/995606b4-97cb-11e6-9471-10f42b09be5d.png)

**Comment by Undeadlol1** [comment]
Это все еще актуально?
По моим наблюдениям популярное работает именно так как и должно. Пару дней висят особо популярные посты, затем они сменяются потихоньку другими.
Для новых и набирающих популярность постов есть соответствующие вкладки.

**Comment by lehard** [comment]
Актуально. В Стиме это работает так, что посты уходят из Популярного после первой выплаты. У нас выплат нет, поэтому посты копятся за все время. И так будет продолжатся до первых выплат. Еще 2,5 месяца этот раздел будет с минимальной ротацией постов.

**Comment by Undeadlol1** [comment]
Посоветовался с @valzav, и выяснилось что повлиять на эту выдачу нельзя.
В качестве альтернативы убрал селекторы "24 часа" и "30 дней".
Придется терпеть два с половиной месяца :(
