### ISSUE TITLE
Реализация компонента popover "Информация о пользователе"

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/tolstoy#763]
Создать компонент, согласно разработанному дизайну
Компонент имеет следующее наполнение:

- [ ] Username
- [ ] Имя пользователя
- [ ] Аватарка пользователя
- [ ] Информация из раздела "О себе"
- [ ] Количество подписчиков
- [ ] Первые 3 закрепленных поста (название и ссылка)
- [ ] Кнопки "Подписаться" и "Заблокировать"

![image](https://user-images.githubusercontent.com/6249597/44665233-10a83500-aa1e-11e8-90c4-ecfb54187e79.png)

**Comment by NickShtefan** [comment]
#783 Необходимо учитывать при разработке

**Comment by BaroH4er** [comment]
Done
