### ISSUE TITLE
Реализация компонента "Боковая панель поста"

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/tolstoy#765]
Реализовать компонент, согласно разработанному дизайну
Содержание компонента

- [x] Кнопка "Лайк" + количество лайков
- [x] Кнопка "Дизлайк" + количество дизлайков
- [x] Кнопка "Репост" + количество репостов
- [x] Кнопка "Поделиться в соц. сетях"
- [x] Кнопка "Добавить в Избранное"

В том случае, если пользователь, просматривающий пост поставил посту лайк, дизлайк репост и т.д. или, необходимо подсвечивать соответствующую кнопку

Панель должна всегда отображаться сбоку от поста, вне зависимости от скрола

![image](https://user-images.githubusercontent.com/6249597/44665140-de96d300-aa1d-11e8-9790-1c90c4913952.png)

**Comment by BaroH4er** [comment]
В ишью не описан реализованный механизм при просмотре постов авторизованного пользователя (созданные посты и репосты), при просмотре которых, вместо Кнопки "Добавить в Избранное" отображается кнопка "Закрепить пост". При этом, кнопка "Закрепить пост" дублируется в меню настроек поста:
![image](https://user-images.githubusercontent.com/21989598/46718220-3ce8df80-cc73-11e8-9599-2452f0ba8484.png)

**Проблема:** авторизованный пользователь не может добавить свой, или репостный пост в избранное через страницу поста. Вместо кнопки "Добавить в избранное", отображается кнопка "Закрепить пост".

- [ ] FIXED

**Решение:**  при просмотре постов авторизованного пользователя (созданные посты и репосты), в "Боковой панели поста" отображается кнопка "Добавить в избранное"

**Comment by daryasattarova** [comment]
панель не отображается

**Comment by dmitryorelopt** [comment]
исправлена смена "закрепить пост" и "в избранное"
