### ISSUE TITLE
Реализация компонента "Об авторе" 

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/tolstoy#766]
Реализовать карточку "об авторе" 

Содержание карточки

- [ ] Аватар пользователя (автора поста)
- [ ] Имя пользователя
- [ ] Username пользователя
- [ ] Информация из раздела "о себе"
- [ ] Кнопки "подписаться" и "отблагодарить"

![image](https://user-images.githubusercontent.com/6249597/44665100-c6bf4f00-aa1d-11e8-82c0-f7b77e4d9d41.png)

**Comment by BaroH4er** [comment]
Done
