### ISSUE TITLE
Переработка страницы поста

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/tolstoy#767]
Переработать страницу поста, согласно разработанному дизайну. 

Верхняя часть должна содержать 

- [x] Аватар автора поста, при нажатии [должен открываться popover](https://github.com/GolosChain/tolstoy/issues/763)
- [x] Кнопка "подписаться", в случае если читатель подписан на автора, кнопка превращается в галочку
- [x] Кнопка "Добавить в избранное"

![image](https://user-images.githubusercontent.com/6249597/44666502-3aaf2680-aa21-11e8-8d03-f769595c0ec3.png)

- [x] Первый Тег 
- [x] Заголовок
- [x] Тело поста
- [x] Список тегов

![image](https://user-images.githubusercontent.com/6249597/44666594-67fbd480-aa21-11e8-88c9-cc61a1212ce9.png)

Список действий над постом

- [x] кнопка лайк ( + количество лайков)
- [x] выплаты за пост 
- [x] кнопка Дизлайк ( + количество дизлайков)
- [ ] кнопка Репост ( + количество репостов)
- [x] кнопка Поделиться в соц. сетях
- [x] Количество Комментариев
- [x] кнопка Ответить

![image](https://user-images.githubusercontent.com/6249597/44666755-bf9a4000-aa21-11e8-9a5f-6812f0fd993b.png)

**Comment by BaroH4er** [comment]
Найден баг, ишью #1000

**Comment by NickShtefan** [comment]
к сожалению, в текущий момент блокчейн не отдает количество репостов для поста. 
в связи с чем реализация данного функционала откладывается либо до того момента, когда это будет сделать в БЧ, либо до реализации кеширующих сервисов. 
так или иначе в ближайшее время решить данный вопрос не получится.
