### ISSUE TITLE
Почему-то не голосуется

### ISSUE THREAD

**Issue by mguryeva** [GolosChain/tolstoy#77]
При голосовании появляется надпись (нижний левый угол) - can't increase reward of post within the last minute... И не голосуется

![image](https://cloud.githubusercontent.com/assets/7629337/19607454/a865b30a-97d2-11e6-80a7-83632f67a1df.png)

**Comment by gamerate** [comment]
Сообщение появляется если посту более 24 часов, те второй 30 дневный период голосования фактически неактивен.

**Comment by Undeadlol1** [comment]
Это не баг, а фича. До первых выплат за старый контент голосовать нельзя.
