### ISSUE TITLE
Баг-репорт new Profile Page [24.08.2018]

### ISSUE THREAD

**Issue by BaroH4er** [GolosChain/tolstoy#772]
## Пункт меню «Посты»

**Проблема:** название вкладки не соответствует требуемому названию.
- [x] FIXED

**Воспроизведение:**

1. открыть https://sandbox.golos.io/
2. авторизоваться
3. открыть свой профиль

**Результат:** вкладка называется "Блог"
**Ожидаемый результат:** вкладка с постами должна называться "Посты"
<hr/>

**Проблема:** под постом/комментарием отсутствует кнопка перехода к комментариям.
- [x] FIXED

**Воспроизведение:**

1. открыть https://sandbox.golos.io/
2. авторизоваться
3. открыть чей-либо профиль
4. открыть вкладку ""Посты""/""Комментарии"

**Результат:** кнопка отсутствует
**Ожидаемый результат:** на любом посте/комментарии должна быть иконка комментария, по нажатию на которую осуществляется переход к комментариям под этим постом/комментарием
<hr/>

**Проблема:** После вторичной попытки удаления голоса не появляется окно подтверждения удаления голоса.
- [x] FIXED

**Воспроизведение:**

1. Открыть https://sandbox.golos.io/
2. авторизоваться
3. открыть любой профиль
4. Проголосовать за пост -> убрать голос (в первый раз окно подтверждения удаления голоса появляется) 
5. Поставить голос снова и снова его убрать на том же посте

**Результат:** окно не появляется. голос просто убирается
**Ожидаемый результат:** снова должно появиться окно подтверждения удаления голоса 
<hr/>

**Проблема:** Отображение фотографии на превью поста не соответствует дизайну.	
- [x] FIXED

**Воспроизведение:**

1. открыть https://sandbox.golos.io/
2. авторизоваться
3. открыть любой профиль
4. найти пост с фотографией

**Результат:** отображение фото на превью не соответствует дизайну (углы слева вверху и внизу закруглены)
**Ожидаемый результат:** фото на превью должно соответствовать дизайну
<hr/>

## Левый блок : подписки и подписчики
 
**Проблема:** нет ссылки на открытия окна/списка с кол-вом подписчиков/подписок - в дизайне присутствует иконка открытия:
![screenshot_1](https://user-images.githubusercontent.com/21989598/44720100-558ba480-aace-11e8-9494-2c0a0d96afe8.png)
- [x] FIXED

**Воспроизведение:**
1. Открыть страницу любого профиля sandbox.golos.io/@%username%

**Результат:** в левом блоке, у счетчика подписчиков и подписок отсутствует иконка раскрытие списка/окна.
**Ожидаемый результат:** в левом блоке, у счетчика подписчиков и подписок отображается и функционирует иконка раскрытия.

**Решение:** можно сделать в виде открытия модального окна с табличкой.
<hr/>

## Левый блок : Рейтинг/Статус пользователя

**Проблема:**  у рейтига пользователя отсутствует иконка, наименование не совпадает с дизайном: рейтинг - статус.
![screenshot_2](https://user-images.githubusercontent.com/21989598/44720294-0134f480-aacf-11e8-8fa3-eb418b4c0999.png)

- [ ] FIXED

**Воспроизведение:**
1. Открыть страницу любого профиля /@%username%

**Результат:** в левом блоке: 
1) У рейтинга пользователя отсутствует иконка
2) Нименование функционала не совпадает с дизайном
**Ожидаемый результат:** в левом блоке:
1) У рейтинга пользователя присутствует иконка согласно дизайну
2) Наименование функционала согласно дизайну
</hr>

## Левый блок : Пол пользователя

**Проблема:** У пола пользователя отсутствует иконка:
![screenshot_3](https://user-images.githubusercontent.com/21989598/44720299-07c36c00-aacf-11e8-9b20-4a25210c7515.png)

- [ ] FIXED

**Воспроизведение:**

1. Открыть страницу любого профиля sandbox.golos.io/@%username%

**Результат:** в левом блоке, у пола пользователя отсутствует иконка.
**Ожидаемый результат:** в левом блоке, у пола пользователя присутствует иконка согласно дизайну.
<hr/>

## Левый блок : Дата регистрации пользователя

**Проблема:** Отображение даты регистрации не соответствует дизайну: 
![screenshot_4](https://user-images.githubusercontent.com/21989598/44720403-64268b80-aacf-11e8-8677-cbc2a13eefb0.png)

- [ ] FIXED

**Воспроизведение:**

1. Открыть страницу любого профиля sandbox.golos.io/@%username%

**Результат:** в левом блоке, отображение даты регистрации не соответствует дизайну
**Ожидаемый результат:** в левом блоке, отображение даты регистрации соответствует дизайну
<hr/>

## Левый блок : Социальные сети

**Проблема:** ссылки работают не правильно: `https://sandbox.golos.io/https://www.facebook.com/`
 
- [x] FIXED

**Воспроизведение:**
1. Открыть страницу настроек авторизованного пользователя sandbox.golos.io/@%username%/settings
2. Открыть вкладку ""Учетная запись""
3. Добавить ссылку в любое поле из блока ""Социальные сети"" и обновить настройки
4. Открыть страницу авторизованного пользователя /@%username%
4.1. Отображается иконка социальной сети в чьё поле была вписана ссылка
5. Кликнуть по иконке социальной сети

**Результат:** ссылка ведет на: https://sandbox.golos.io/https://www.facebook.com/
**Ожидаемый результат:** ссылка ведет на: https://www.facebook.com/
<hr/>

## Правый блок: Отображение и функционирование стоимости аккаунта

1) Сумма не совпадает с golos.io
2) Отображение валюты не реагирует на настройки ""Выберите валюту""
3) Знаки после запятой не реагирует на настройки ""Отображение наград""

**Проблема:** сумма не совпадает с golos.io

- [ ] FIXED

**Воспроизведение:**

1. Открыть страницу любого профиля sandbox.golos.io/@%username%
2. Открыть эту же страницу на проде: golos.io/@%username% для сравнения.

**Результат:** Сумма стоимости аккаунта отличается.
**Ожидаемый результат:** Сумма стоимости аккаунта совпадает.

**Проблема:**  Валюта и отображение наград не реагируют на настройки.

- [ ] FIXED

**Воспроизведение:**

1. Открыть страницу настроек авторизованного пользователя sandbox.golos.io/@%username%/settings
2. Открыть вкладку ""Общие"" и внести изменения в блоки  ""Выберите валюту"" и  ""Отображение наград"".
3. Обновить настройки и вернутся на страницу авторизированного пользователя sandbox.golos.io/@%username%
4. Обратить внимание на правый блок.

**Результат:** изменение в настройках не отображаются.
**Ожидаемый результат:** изменения в настройках отображаются
<hr/>

## Правый блок: меню кошелька

**Проблема:**  Модальные окна имеют возможность скролла страницы.

- [x] FIXED

**Воспроизведение:**

1. Открыть страницу авторизованного пользователя sandbox.golos.io/@%username%
2. В правом блоке страницы кликнуть по кнопке ""Передать""
3. В открывшимся модальном окне, проскроллить страницу колесиком мышки.

**Результат:** страница скроллится
**Ожидаемый результат**: в открытом модальном окне, скролл страницы невозможен

**Прим.:** актуально для всех модальных окон страницы профиля.
<hr/>

## Правый блок - меню кошелька - кнопка: Делегировать/Уменьшить СГ

**Проблема:**  Во вкладке «Отправленные», в столбце «Действия» - кнопка «Изменить» открывает скролл для изменения делегированной СГ, но изменить делегированную СГ невозможно, нет кнопки для сохранения или отмены изменений.

- [x] FIXED

**Воспроизведение:**

1. Открыть страницу авторизованного пользователя sandbox.golos.io/@%username%
2. В правом блоке страницы кликнуть по кнопке ""Делегировать силу голоса""
3. Предварительно делегировав СГ любому пользователю, в открытом модальном окне перейти во вкладку «Отправленные»
4. Нажать на кнопку ""Изменить"" в столбце ""Действия""

**Результат:** Нет кнопок ""Сохранить"" и ""Отменить"" изменения.
**Ожидаемый результат:** кнопки ""Сохранить"" и ""Отменить"" отображаются и функционируют должным образом.

**Решение:** 
1. Добавить кнопки ""Сохранить"" и ""Отменить"" изменения.
2. При сохранении изменений добавить окно подтверждения действия с паролем пользователя.
<hr/>

## Горизонтальное меню - настройка ""Список"" и ""Сетка"" 

**Проблема:** не соответствует отображение настроек ""Список"" и ""Сетка"" согласно дизайну:
![image](https://user-images.githubusercontent.com/2598671/44783038-c6e05b80-ab91-11e8-9570-888e870dcdf0.png)

- [x] FIXED

**Воспроизведение:**

1. Открыть страницу авторизованного пользователя sandbox.golos.io/@%username%
2. Обратить внимание на правую часть горизонтального меню страницы пользователя

**Результат:** иконки переключеня ""Список"" и ""Сетка"" отображаются одновременно, стоят последовательно(в ряд). 
**Ожидаемый результат:** отображается только иконка неактивного состояния."	

**Решение:**

1. Отображается только иконка неактивного состояния.
2. При клике на иконку неактивного состояния(например ""Сетка"") > она меняется на иконку ""Список"" - что будет являтся неактивны состоянием. Т.е.
По умолчанию пользователю отображаются блоки постов в виде ""Списка"" в этот момент в горизонтальном меню отображается иконка ""Сетки"".
3. Настройки меняются согласно вышеперечисленным действиям.
<hr/>

## Пункт меню «Кошелек» - вкладка «Сила голоса»/«Делегирование»

**Проблема:** Цвет иконок ее соответствует дизайну:
![screenshot_8](https://user-images.githubusercontent.com/21989598/44721934-1f512380-aad4-11e8-957c-55554b44c75a.png)

- [x] FIXED

**Воспроизведение:**

1. Открыть страницу кошелька авторизованного пользователя  sandbox.golos.io/@%username%/transfers 
2. Открыть вкладку «Сила голоса»/«Делегирование» предварительно делегировав СГ и получив делегирование от другого пользователя

**Результат:** цвет иконок не совпадает с дизайном
** Ожидаемый результат:** цвет иконок соответствует дизайну
<hr/>

## Пункт меню «Кошелек» - вкладка «Сила голоса»/«Делегирование»

**Проблема:** Невозможно отменить делегирование - страница /transfers выдает 500 ошибку"	

- [x] FIXED

**Воспроизведение:**

1. Открыть страницу кошелька авторизованного пользователя  sandbox.golos.io/@%username%/transfers 
2. Открыть вкладку «Сила голоса»/«Делегирование» предварительно делегировав СГ
3. Попытаться отменить делегирование с помощью кнопки ""Отменить""

**Результат:** кнопка ""Отменить"" кидает на страницу /transfers с 500 ошибкой.
**Ожидаемый результат:** кнопка ""Отменить"" открывает модальное окно с подтверждением отмены делегирования.
<hr/>

## Пункт меню «Настройки» - Вкладка «Общие»

**Проблема:** Изменения настроек в вкладке ""Общее"" не применяются на сайте"	

- [ ] FIXED

**Воспроизведение:**

1. Открыть страницу настроек авторизированного пользователя sandbox.golos.io/@%username%/settings
2. Открыть вкладку ""Общие""
3. Внести любые изменения в настройках и обновить.

**Результат:** внесенные изменения в настройках не отображаются на сайте.
**Ожидаемый результат:** внесенные изменения в настройках отображаются на сайте. 
<hr/>

## Открытие настроек профилей авторизованным и неавторизованным пользователем

1) Пользователь разлогинен /@username/settings - пытается открыться страницу
2) Пользователь залогинен /@username/settings открывает и отображает настройки вкладки ""учетная запись"""	

**Проблема:** пользователь разлогинен и пытается открыться страницу  /@username/settings - открывает

- [x] FIXED

**Воспроизведение:**

1. Зайти на сайт sandbox.golos.io неавторизированным.
2. Перейти на страницу настроек любого пользователя  /@username/settings 

**Результат:** страница настроек в постоянной загрузке
**Ожидаемый результат:** страница настроек пользователя(п.2) не открывается

**Проблема:** пользователь залогинен и пытается открыть страницу  /@username/settings - открывает и отображает настройки вкладки ""учетная запись""

- [x] FIXED

**Воспроизведение:**

1. Зайти на сайт sandbox.golos.io авторизированным.
2. Перейти на страницу настроек любого пользователя  /@username/settings 

**Результат:** вкладка Общие и Уведомления отображают настройки авторизированного пользователя, а вкладка ""Учетная запись"" отображает настройки пользователя чья ссылка открыта в п.2 (/@username/settings).
**Ожидаемый результат:** страница настроек пользователя(п.2) не открывается

**Comment by BaroH4er** [comment]
## Функционал "Отблагодарить" пост, выводит некорректную форму.

**Проблема:** использование кнопки "Отблагодарить" пост, добавляет в историю транзакций некорректное сообщение: 
![image](https://user-images.githubusercontent.com/21989598/44722700-8a9bf500-aad6-11e8-89cf-134c6a903fe9.png)
- [ ] FIXED

**Воспроизведение:**
1. Зайти на сайт sandbox.golos.io
2. Авторизоваться и открыть любую ленту постов
3. Выбрать пост и нажать кнопку "отблагодарить"
4. Провести транзакцию, оставив поле "заметка" пустой

**Результат:** в истории транзакций авторизованного пользователя некорректное сообщение.
**Ожидаемый результат:**  в истории транзакций авторизованного пользователя выводится сообщение согласно дизайну/текстовке.

**Comment by BaroH4er** [comment]
Репорт составлен на основе документа: https://docs.google.com/spreadsheets/d/1MBuDxBO4Lns9Uj3_MNy6qXagRZ1RjKn_Y8jlnFrUFzo/edit

**Comment by BaroH4er** [comment]
## Левый блок: о себе
- [ ] FIXED

**Проблема:** Согласно изменениям в дизайне, надпись "О себе" заменяется ссылкой на сайт профиля.

![image](https://user-images.githubusercontent.com/21989598/44783597-88e43700-ab93-11e8-8326-28b5ceb95d9d.png)


**Решение:**

![image](https://user-images.githubusercontent.com/21989598/44783620-97cae980-ab93-11e8-860c-d651e830343e.png)

<hr/>

## Блок поста: фокус на дату

**Проблема:** при наведении курсора мыши на давность публикации поста(focus > PostCard__PostDate), не отображается тултип с точной датой и временем публикации. 

**Воспроизведение:** 

1. Открыть страницу любого профиля /@%username%
2. Навести курсор мыши на дату давности поста.

**Результат:** подсказка по умолчанию:

![image](https://user-images.githubusercontent.com/21989598/44784250-a914f580-ab95-11e8-91e7-998c65163b79.png)

**Ожидаемый результат:** тултип согласно дизайну:

![image](https://user-images.githubusercontent.com/21989598/44784263-b4682100-ab95-11e8-909f-b5518db32344.png)

**Comment by BaroH4er** [comment]
## Вкладка комментарии - блок комментария
**Проблема:** не соответствует дизайну кнопки "количества комментариев" и "Ответить":

- [ ] FIXED

### **Сейчас**

![image](https://user-images.githubusercontent.com/21989598/44985402-ebb94200-af88-11e8-8b9c-81814eb54e63.png)

### **В дизайне**

![image](https://user-images.githubusercontent.com/21989598/44985409-f378e680-af88-11e8-9617-779eaa387cb8.png)

**Решение:** привести к виду согласно дизайну.


<hr/>

## Некорректное отображение картинки поста во вкладке "Посты"

**Проблема:** при отображении постов "Сеткой", картинка поста отображается некорректно.

**Воспроизведение:** 
1. Открыть страницу любого пользователя sandbox.golos.io/@%username%
2. Переключить отображение постов "Сеткой"
![image](https://user-images.githubusercontent.com/21989598/44985580-7bf78700-af89-11e8-9bb6-f4affdad0855.png)

**Результат:** картинка поста отображается некорректно.

![image](https://user-images.githubusercontent.com/21989598/44985725-02ac6400-af8a-11e8-8198-1a7aa8301272.png)


**Ожидаемый результат:** в состоянии отображения постов "Сеткой" нижние углы картинки должны быть закруглены, а верхние - прямые.

**Comment by jevgenika** [comment]
дубликаты https://github.com/GolosChain/tolstoy/issues/970
https://github.com/GolosChain/tolstoy/issues/969
https://github.com/GolosChain/tolstoy/issues/968
https://github.com/GolosChain/tolstoy/issues/967
https://github.com/GolosChain/tolstoy/issues/965
https://github.com/GolosChain/tolstoy/issues/964
https://github.com/GolosChain/tolstoy/issues/959
