### ISSUE TITLE
вставить ссылку на стр FAQ

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/tolstoy#776]
- [ ] вставить ссылку на стр FAQ в футер, меню, стр добро пожаловать, текст для ссылки "Частые вопросы и ответы"
- на стр https://golos.io/welcome cсылку вставляем в блоке -Остались вопросы? первым
- убираем блок и ссылку на ""уточните через сайт, убираем ссылку https://golos.io/submit?type=submit_feedback
![image](https://user-images.githubusercontent.com/30616421/44792939-58a59400-aba5-11e8-97e6-ed277da0a5d1.png)

**Comment by NickShtefan** [comment]
на превью
