### ISSUE TITLE
Введение закладки "посмотреть позже, и функции поиска по хештегам.

### ISSUE THREAD

**Issue by imag1ne666** [GolosChain/tolstoy#79]
1. Когда в ленте новостей нажимаешь на никнэйм автора, появляется на мой взгляд не нужное меню, в котором можно выбрать только один вариант это [Профиль].

Предлагаю:

a) Автоматически после клика по никнейму пользователя перенаправлять на профиль аккаунта. Делать это если мы листаем свою новостную ленту, от людей на которых мы уже подписаны.

б) В других разделах помимо [Профиля] добавить ещё возможность [Подписаться] или [Отписаться] одним кликом, если речь идёт о разделах новое/актуальное/популярное/продвигаемое/обсуждаемое.

в) [Важно] Также можно было бы добавить около поста, какую нибудь незаметную кнопку(что-то типа репоста), при использовании которой можно было бы отложить пост в отдельную категорию, допустим под названием [Посмотреть позже], как на YouTube и видимую только тебе. Постов интересных много, но времени для просмотра не всегда есть на данный момент, и также не хочется отдельно держать кучу открытых вкладок, это очень неудобно и думаю всем это знакомо. Потом по мере просмотра поста, скрывать его из данной категории, либо убирать при нажатии определенной кнопки. Мне кажется этой категории не хватает как Голосу, так и Стимиту.
![default](https://cloud.githubusercontent.com/assets/23002212/19621342/79677acc-9898-11e6-9f8b-a995e4d06c94.jpg)
![3](https://cloud.githubusercontent.com/assets/23002212/19621344/7976b1ae-9898-11e6-86c3-2fed5deac7d3.jpg)
1. Не хватает функции поиска по хештегам через ввод данных, как это реализовано на Стимите.
   ![2](https://cloud.githubusercontent.com/assets/23002212/19621347/9b3d81f0-9898-11e6-871b-5ecba32c431b.jpg)
   ![4](https://cloud.githubusercontent.com/assets/23002212/19621348/9b3f2938-9898-11e6-93a4-db3d20ad129e.jpg)

**Comment by 21xhipster** [comment]
Исправлено давно
