### ISSUE TITLE
Адаптировать диалоги для мобильных устройств

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/tolstoy#796]
Заверстать диалоги для мобильных устройств согласно разработанному дизайну

**Comment by BaroH4er** [comment]
## Не отображается PostCard__VotePanel у потов с картинками.

**Проблема:** У постов в ленте, не отображается блок PostCard__VotePanel если пост содержит картинку.

- [ ] FIXED

**Воспроизведение:**

1. Открыть https://sandbox.golos.io
2. Авторизоваться
3. Создать и опубликовать 2 поста
  3.1 Первый пост: картинка + текст
  3.2 Второй пост: текст
4. Открыть страницу авторизованного пользователя https://sandbox.golos.io/@%username%

**Результат:** 

<hr/>

### Пост с картинкой не отображает PostCard__VotePanel

<hr/>

![image](https://user-images.githubusercontent.com/21989598/45619458-00fe9800-ba82-11e8-84f3-237637190583.png)

<hr/>

### Пост без картинки отображает PostCard__VotePanel

<hr/>

![image](https://user-images.githubusercontent.com/21989598/45619673-cfd29780-ba82-11e8-8825-41903f350bf0.png)

**Ожидаемый результат:** 


- Пост с картинкой отображает PostCard__VotePanel
- Пост без картинки отображает PostCard__VotePanel

**Comment by BaroH4er** [comment]
## На размере экрана **360х640** не видно всех символов ключа, и кнопки.

**Проблема:** В настройках ключей пользователя, за экран уезжает часть символов ключа. А также, кнопка "Авторизуйтесь для этой транзакции".

- [ ] FIXED

**Воспроизведение:**

1. Открыть https://sandbox.golos.io/ и авторизоваться.
2. Перейти на страницу авторизованного профиля https://sandbox.golos.io/@%username%
3. Открыть вкладку "настройки > ключи > ключи"

**Результат:** 

![image](https://user-images.githubusercontent.com/21989598/45689427-a1c18600-bb5c-11e8-9ca7-222ec4044fdc.png)

**Ожидаемый результат:** Все символы ключей и кнопки видны пользователю.

Ключи:
- Постиг ключ
- Активный ключ
- Ключ владельца
- Ключ заметок

Кнопка:
- Кнопка "Авторизуйтесь для этой транзакции"

**Comment by Bacher** [comment]
Оба комментария от @BaroH4er не относятся к данному ишью.
Ишью правит верстку диалогов перевода денег, сейфа, конвертации и тд (действия из панели).

**Comment by Bacher** [comment]
![image](https://user-images.githubusercontent.com/2598671/45745131-c6733780-bc08-11e8-9c2f-04e53d0338cb.png)
