### ISSUE TITLE
Сделать чтобы меню скроллилось свайпом (на телефоне)

### ISSUE THREAD

**Issue by Bacher** [GolosChain/tolstoy#797]
![image.png](https://images.zenhubusercontent.com/5b0ff4b64b5806bc2bd5811e/6b59ac37-92fd-4141-85e5-69269d72ff54)

Добавить свайп.

**Comment by Bacher** [comment]
Теперь свайпается. Ветка `797_mobile-profile-navigation` .

**Comment by BaroH4er** [comment]
Done.
