### ISSUE TITLE
Некоторые баги с апвойтом комментариев.

### ISSUE THREAD

**Issue by imag1ne666** [GolosChain/tolstoy#80]
1. По непонятной причине не могу опубликовать пост, выдает следующую ошибку. Может кто знает в чём проблема?
   ![3](https://cloud.githubusercontent.com/assets/23002212/19621384/52bd56fc-9899-11e6-811d-1c6c3bc6f2d0.jpg)
2. Нельзя проголосовать за старые комментарии. Или это пока так и задумано?
   ![1](https://cloud.githubusercontent.com/assets/23002212/19621387/5d8ae608-9899-11e6-9d2c-b82ea48eba10.jpg)
3. Также нельзя голосовать за новые комментарии, которые находятся в ветке Автора комментария, у которого прошло больше суток.
   ![2](https://cloud.githubusercontent.com/assets/23002212/19621390/68b7e008-9899-11e6-9ae6-6fb7b4e42d76.jpg)

**Comment by Undeadlol1** [comment]
Первое еще актуально?
Остальное не баг, а фича :-) До первых выплат нельзя апвойтить контент, который старше суток.

**Comment by Undeadlol1** [comment]
Скорее всего неактуально, закрываю.
