### ISSUE TITLE
Исправления локализации

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/tolstoy#805]
Необходимо использовать counterpart для корректной работы локализации
- [x] src/app/helpers/currency.js
- [x] src/app/containers/userProfile/blog/BlogContent.jsx
- [x] src/app/containers/userProfile/comments/CommentsContent.jsx
- [x] src/app/containers/userProfile/favorites/FavoritesContent.jsx
- [x] src/app/containers/userProfile/replies/RepliesContent.jsx
- [x] src/app/containers/userProfile/wallet/WalletContent.jsx
- [x] src/app/components/common/CommentCard/CommentCard.jsx
- [x]  src/app/components/common/ReplyBlock/ReplyBlock.jsx

**Comment by b1acksun** [comment]
https://github.com/GolosChain/tolstoy/issues/1089
https://github.com/GolosChain/tolstoy/issues/1090
