### ISSUE TITLE
Резолвинг картинок из Instagram

### ISSUE THREAD

**Issue by vitalylvov** [GolosChain/tolstoy#82]

**Comment by vitalylvov** [comment]
@tomarcafe Вот пример https://golos.io/ru--test/@vitaly-lvov/test-insty

**Comment by Undeadlol1** [comment]
Зря вы этим занимаетесь.
Во-первых, скоро новый редактор парни из стимита сделают и сейчас заниматься старым бессмысленно.
Во-вторых, что если человек не хочет вставлять картинку, а просто хочет добавить ссылку на свой пост в инстаграмме? Тогда все время будет резолвится картинка и ему придется прибегать к костылика по типу: instagram . com/image123

**Comment by 21xhipster** [comment]
Закрыл в обмена на #310
