### ISSUE TITLE
Реализовать модальное окно для "Подписок" и "Подписчиков" 

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/tolstoy#829]
При нажатии на пункты "Подписки" и "Подписчики"  необходимо реализовать модальное окно, в котором будет отображаться список подписок или подписчиков соответственно.

В случае, когда пользователь просматривает список "Подписчики", 

- [x] если пользователь не подписан на своего подписчика надо отобразить кнопку "Подписаться" 
- [x] если пользователь подписан на своего подписчика, отображаем "Отписаться", при нажатии на которую происходит отписка (необходимо получить подтверждение от пользователя)

**Comment by BaroH4er** [comment]
Done
