### ISSUE TITLE
Неверный тип ключа при голосовании за делегата

### ISSUE THREAD

**Issue by petermz** [GolosChain/tolstoy#83]
<img width="803" alt="screen shot 2016-10-23 at 23 46 06" src="https://cloud.githubusercontent.com/assets/16533006/19629321/fed2f21c-997a-11e6-814a-f7048d9a8a13.png">

"Эта операция требует вашего Постинг ключа" -- на самом деле требуется Активный ключ или ключ владельца

**Comment by petermz** [comment]
PR: https://github.com/GolosChain/tolstoy/pull/84

**Comment by Undeadlol1** [comment]
Еще раз спасибо!
Твой ник peterz в Голосе? Сделаю mention на твою страницу в когда буду делать обзор изменений.

**Comment by petermz** [comment]
да! =)
