### ISSUE TITLE
Рефакторинг "шапки" сайта

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/tolstoy#832]
- [x] Перевести шапку сайта на использование styled-components
- [x] Перенести шапку в новую структуру проекта
- [x] Обновить отображение, согласно дизайну

**Comment by NickShtefan** [comment]
- [ ] Добавить в меню пункт FAQ, сразу после "Добро пожаловать"

![image](https://user-images.githubusercontent.com/6249597/45880730-9dda7180-bdb1-11e8-8b24-d3fc4d12e299.png)

- [ ] Скрывать выпадающее меню, при переходе на его разделы

![image](https://user-images.githubusercontent.com/6249597/45880768-b8144f80-bdb1-11e8-8bd1-cac50cef75e1.png)

**Comment by Bacher** [comment]
> Исправить переход на "Сообщения"
Как воспроизвести проблему?

**Comment by Bacher** [comment]
PR: https://github.com/GolosChain/tolstoy/pull/872

**Comment by BaroH4er** [comment]
Done
