### ISSUE TITLE
Реализовать компонент "информация о выплатах"

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/tolstoy#849]
В зависимости от того, произошла ли выплата или нет, необходимо отображать корректный заголовок.

pending_author_payout_gests_value: ‘314407.604115 GESTS’,
pending_author_payout_golos_value: ‘88.439 GOLOS’,
- выплаты за пост автору 

pending_benefactor_payout_gests_value: ‘0.000000 GESTS’, - выплаты бенефициару
pending_curator_payout_gests_value: ‘4326.530763 GESTS’, - выплаты кураторам

![image.png](https://images.zenhubusercontent.com/5a27458f8a75884b908a072e/19e182dc-a774-4372-b041-c4bd34d83bb0)

**Comment by NickShtefan** [comment]
имеется баг #914

**Comment by BaroH4er** [comment]
Валюта в "Информации о выплатах" разве не должна соответствовать настройкам пользователя? Или всё отображается в "GOLOS" ? 

![image](https://user-images.githubusercontent.com/21989598/46720109-3dd04000-cc78-11e8-881d-cdba96c3746f.png)

**Comment by Bacher** [comment]
Я тоже уточнял, выплаты должны отображаться в валю в которой были выплачены. Перевод в валюту только вверху.
