### ISSUE TITLE
Поле ввода для комментариев слишком узкое

### ISSUE THREAD

**Issue by petermz** [GolosChain/tolstoy#85]
Когда пишешь комментарий к посту, "Предварительный просмотр" и "Поддерживается стилизация с Markdown" сливаются в одну строчку:

<img width="903" alt="screen shot 2016-10-25 at 16 06 34" src="https://cloud.githubusercontent.com/assets/16533006/19687164/145a45ba-9acd-11e6-9368-28da85b13a37.png">

Когда отвечаешь на комментарий, такого нет, потому что поле ввода шире. Можно увеличить ширину поля для комментариев верхнего уровня, или сократить вторую строчку: "Поддерживается Markdown", или уменьшить шрифт. Или всё вместе =)

**Comment by Undeadlol1** [comment]
Парни из стимита удалили эту надпись. Мне кажется это разумным, потому выпилино и у нас.
Спасибо что сообщили.

**Comment by petermz** [comment]
Ну не знаю, спорно. Откуда люди теперь узнают про маркдаун?
Уже начались вопросы: https://golos.io/ru--katalog/@catalog/pervyi-post-i-startovyi-vypusk-kataloga-vypusk-0

**Comment by Undeadlol1** [comment]
Открою пока ишью, чтобы не забыть обмозговать этот вопрос.

**Comment by petermz** [comment]
Даже тем, кто про Маркдаун знает, полезно иметь подсказку под рукой. Вот я всех деталей наизусть не помню
