### ISSUE TITLE
Реализовать компонент написания комментария

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/tolstoy#855]
Инпут для ввода текста. 
![image.png](https://images.zenhubusercontent.com/5a27458f8a75884b908a072e/0701fc29-5397-47c8-a5d9-a32b660c7c57)

После того, как пользователь начинает вводить текст в инпут, сразу под ним (по аналогии с текущим продом) появляется компонент отображения комментария, в котором отображается превью введенного текста.

**Comment by BaroH4er** [comment]
**Проблема:** вместо компонента отображения комментария, в котором отображается превью введенного текста, добавлен функционал кнопки превью, как при создании поста. 


![image](https://user-images.githubusercontent.com/21989598/46525696-fec77680-c894-11e8-96b5-35610ea62687.png)

**Решение:** реализовать функционал аналогичный проду:

![image](https://user-images.githubusercontent.com/21989598/46525364-0a666d80-c894-11e8-8b8f-22c1db96033a.png)

- [ ] FIXED
