### ISSUE TITLE
Реализовать компонент отображения комментария

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/tolstoy#856]
![image.png](https://images.zenhubusercontent.com/5a27458f8a75884b908a072e/1444083e-ed9b-4fbd-83bf-7bf88c48b3fd)

Компонент содержит в себе 
- [x] Аватар пользователя
- [x] Дату написания комментария
- [x] Тело комментария
- [x] Кнопку "редактировать"
- [x] Кнопку "лайк" и счетчик выставленных лайков. Если пользователь поставил лайк, то кнопка должна отображаться другим цветом
- [x] Оценочную выплату (по нажатию должен открываться поповер)
- [ ] Кнопку "дизлайк" и счетчик выставленных дизлайков. Если пользователь поставил дизлайк, то кнопка должна отображаться другим цветом
- [x] Иконка "ответов" и счетчик ответов на комментарий
- [ ] Кнопка "ответить"

**Comment by BaroH4er** [comment]
**Проблема:** компонент отображения комментария, который находится на странице поста, не должен содержать заголовок поста.

![image](https://user-images.githubusercontent.com/21989598/46526368-b90bad80-c896-11e8-955f-51df64c1442d.png)

- [ ] FIXED

**Comment by daryasattarova** [comment]
при попытке поставить лайк/дизлайк или изменить свое решение (т.е. убрать лайк/дизлайк)
![inkedimage 2 _li](https://user-images.githubusercontent.com/42342756/46949180-36020880-d089-11e8-869d-8339bb2f55d1.jpg)

**Comment by daryasattarova** [comment]
ответы к некоторым комментариям не отображаются 
![image](https://user-images.githubusercontent.com/42342756/46949298-95f8af00-d089-11e8-83bf-edd2e1a9b2f5.png)

**Comment by daryasattarova** [comment]
не отображается фото в комментарии
![image](https://user-images.githubusercontent.com/42342756/47000945-1541bd80-d132-11e8-8535-1d514eb55e92.png)

**Comment by daryasattarova** [comment]
видео отображается некорректно 
![image](https://user-images.githubusercontent.com/42342756/47292012-6cea9800-d60e-11e8-96ee-7593346c76fd.png)
