### ISSUE TITLE
Не отображается сколько получего голов при понижении СГ

### ISSUE THREAD

**Issue by litrbooh** [GolosChain/tolstoy#874]
Перестало отображаться сколько Голосов получено в результате понижения

![default](https://user-images.githubusercontent.com/22373216/45964088-77c10580-c02d-11e8-9b14-3f955f5ef34c.png)

Кстати, где в новом интерфейсе кнопка понижения и информация о понижении?

![default](https://user-images.githubusercontent.com/22373216/45964114-8f988980-c02d-11e8-972d-922714278a71.png)

**Comment by jevgenika** [comment]
Добавить в Кошельке рядом с кнопкой делегировать сг кнопку -Уменьшить силу голоса,
добавить окно с инфнормацией -Следующие понижение Силы Голоса возможно через 7 дней.

это предупреждение отображать и в кошельке
![image](https://user-images.githubusercontent.com/30616421/47906058-1ba19a80-de91-11e8-939d-d827a78b4fe6.png)
[Дизайн](https://projects.invisionapp.com/d/main#/console/13480730/320003084/preview)

[Дизайн страниц](https://projects.invisionapp.com/d/main#/console/13480730/320003089/preview)

[Дизайн моб версии](https://projects.invisionapp.com/d/main#/console/13480730/320003073/preview)

**Comment by jevgenika** [comment]
Дубль https://github.com/GolosChain/tolstoy/issues/1474
Задача готова на песочнице
