### ISSUE TITLE
Хочу видеть все свой комментарии для поиска нужных статей

### ISSUE THREAD

**Issue by mguryeva** [GolosChain/tolstoy#89]
Почему не все сделанные мною комментарии отображаются в моем профиле? 
Самых ранние (часть вчерашних и позавчерашних ) отсутствуют...

![image](https://cloud.githubusercontent.com/assets/7629337/19706784/7e6ee2fe-9b1c-11e6-865d-7f341db788da.png)

**Comment by Undeadlol1** [comment]
У меня все отображается нормально.
Эта проблема еще актуальна?
