### ISSUE TITLE
Комментарии: Обрезается кнопка на новой строке

### ISSUE THREAD

**Issue by Bacher** [GolosChain/tolstoy#900]
![image.png](https://images.zenhubusercontent.com/5b0ff4b64b5806bc2bd5811e/b16c6b94-7480-499d-8349-96c34eed3890)

Дизайн: https://app.zeplin.io/project/5ba9f49fb422725fe0f07dbf/screen/5ba9f67cb285705d9c55dcd4

**Comment by BaroH4er** [comment]
Done
