### ISSUE TITLE
Привести расчеты выплат по постам к единому виду

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/tolstoy#914]
Расчеты выплат во всплывающем диалоге отличаются от выплат отображаемых под постом

**Comment by Bacher** [comment]
![image](https://user-images.githubusercontent.com/2598671/46664772-9ea13f00-cbca-11e8-95a4-555e2bd814a4.png)

**Comment by Bacher** [comment]
Так, нужно решить что и как мы должны показывать основываясь на данных приходящих из блокчейна.
Вот поля этого поста:
```
author_gbg_payout_value 0.000 GBG
author_gests_payout_value 123690.332098 GESTS
author_golos_payout_value 34.871 GOLOS
beneficiary_gests_payout_value 27486.346345 GESTS
beneficiary_payout_value 8.660 GBG
curator_gests_payout_value 38017.635832 GESTS
curator_payout_value 11.979 GBG
last_payout 2018-10-01T12:55:57
max_accepted_payout 1000000.000 GBG
pending_author_payout_gbg_value 0.000 GBG
pending_author_payout_gests_value 0.000000 GESTS
pending_author_payout_golos_value 0.000 GOLOS
pending_author_payout_value 0.000 GBG
pending_benefactor_payout_gests_value 0.000000 GESTS
pending_benefactor_payout_value 0.000 GBG
pending_curator_payout_gests_value 0.000000 GESTS
pending_curator_payout_value 0.000 GBG
pending_payout_value 0.000 GBG
total_payout_value 77.954 GBG
total_pending_payout_value 0.000 GBG
```

**Comment by Bacher** [comment]
Первое отображаемое число считается по формуле (взято из текущего golos.io):
```
total_payout_value + curator_payout_value = 89.933 GBG (~100.162 GOLOS конвертация) 
```
Вопрос первый, судя из формулы, в `total_payout_value` не входят выплаты кураторам. Так ли это?

Еще, входят ли бенефициарские выплаты (`beneficiary_payout_value`) в `total_payout_value`?

Теперь как считать детализацию этого числа.
Если взять поля из блокчейна:
```
author_golos_payout_value + beneficiary_payout_value = 34.871 GOLOS + 8.660 GBG ~= 39.97 GBG
```
Теперь если из total_payout_value (77.954 GBG) вычесть эти 39.97 GBG, то получится 37.984 GBG, чья это награда?

**Comment by afalaleev** [comment]
Первое с чем стоит определится, так это с тем, что курс золотого - этого динамическая величина, а не фиксированная во времени, поэтому неправильно пытаться сконвертировать произведенные выплаты в GBG в Golos по текущему курсу.
То что выдает БЧ, это в тех курсах, что были на момент выплаты.
Поэтому  `author_golos_payout_value (GOLOS!!!!) + beneficiary_payout_value` дает другое значение, чем ожидается.

**Comment by afalaleev** [comment]
Второе, GESTS тоже величина динамическая, она меняется на каждом блоке.
И БЧ выдает информацию по тому курсу, по которому была произведена выплата.

Это кстати удобный момент, можно посмотреть какой курс GBG <-> GOLOS <-> GESTS был на момент выплаты.

**Comment by afalaleev** [comment]
`total_payout_value` - содержит авторские + бенефициарские, сконвертированные в GBG по курсам на момент выплат.
`curator_payout_value` содержит кураторские, сконвертированные в GBG по курсу на момент выплат.
`beneficiary_payout_value` - содержит бенефициарские (они уже есть в total_payout_value), сконвертированные в GBG по курсу на момент выплат.

**Comment by afalaleev** [comment]
Чисто авторские награды, которые ему прямо в таком виде и были начислены:
author_gbg_payout_value 0.000 GBG
author_gests_payout_value 123690.332098 GESTS
author_golos_payout_value 34.871 GOLOS

**Comment by afalaleev** [comment]
Бенефициары получают чисто в СГ:
beneficiary_gests_payout_value 27486.346345 GESTS

При этом для удобства учета, есть это значение в GBG (опять же по курсам на момент выплат).
beneficiary_payout_value 8.660 GBG

**Comment by afalaleev** [comment]
Кураторы получают только в СГ:
curator_gests_payout_value 38017.635832 GESTS

При этом для удобства учета, есть это значение в GBG (опять же по курсам на момент выплат).
curator_payout_value 11.979 GBG

**Comment by afalaleev** [comment]
Чтобы узнать чисто авторскую награду в сконвертированную в GBG (опять же по курсам на момент выплат):
`total_payout_value - beneficiary_payout_value`

**Comment by afalaleev** [comment]
Поля `pending_*` заполняются для постов, для которых выплата еще не произошла, если выплаты уже произведены, там будут 0.

**Comment by Bacher** [comment]
Одно уточнение, можете пояснить
```
author_gbg_payout_value 0.000 GBG
author_gests_payout_value 123690.332098 GESTS
author_golos_payout_value 34.871 GOLOS
```
`author_gests_payout_value` и `author_golos_payout_value` это два разных значения которые реально получил автор просто в разных валютах или это конвертация одного значения в другое для удобства?

**Comment by zxcat** [comment]
два разных

**Comment by Bacher** [comment]
Столкнулся с проблемой в расчетах.
Исследую старый пост Николая https://golos.io/ru--idunavzlyot/@nickshtefan/brosayu-vyzov-idu-na-vzlyot-shtefan-in-da-golos (тут авторская выплата происходит в GOLOS и в GBG и в GESTS одновременно).
Вот поля:
```
author_gbg_payout_value: "263.052 GBG"
author_gests_payout_value: "352622.930638 GESTS"
author_golos_payout_value: "0.431 GOLOS"
beneficiary_gests_payout_value: "0.000000 GESTS"
beneficiary_payout_value: "0.000 GBG"
curator_gests_payout_value: "223268.979043 GESTS"
curator_payout_value: "168.643 GBG"
total_payout_value: "528.116 GBG"
```
Первое: ищу отношение GBG <=> GESTS. Беру для этого кураторские выплаты и делю:
```curator_gests_payout_value / curator_payout_value = 1323.9148914748907```

Второе: раскручиваю формулу:
```
total_payout_value = author_gbg_payout_value + author_golos_payout_value + author_gests_payout_value + beneficiary_gests_payout_value
```
Получается:
```
528.116 GBG = 263.052 GBG + 0.431 GOLOS + 352622.930638 GESTS + 0
```
Переношу, вычитаю, получается:
```
265.064 GBG - 352622.930638 GESTS =  0.431 GOLOS
```
Заменяем GBG => GESTS с коэффициентом из пункта 1:
```
(265.064 GBG * 1323.9148914748907) - 352622.930638 GESTS =  0.431 GOLOS
```
Далее
```
350922.1767939005 GESTS - 352622.930638 GESTS =  0.431 GOLOS
```
Далее
```
-1700.7538440995268 GESTS = 0.431 GOLOS
```

Получилось отрицательное число, я так понимаю это произошло из-за округлений чисел при первичном сохранении значений. Хотя немного странно, ведь 3 знака после запятой довольно точные значения должны давать. Я пока что в тупике. Расчет произвел 3 раза, один раз кодом, второй раз руками, третий раз когда писал этот коммент.

Правильно я понял формулы для расчета?

**Comment by afalaleev** [comment]
Это произошло из за того, что после каждого начисления вестинга кому либо, курс вестинга меняется. После выплаты вестинга кураторам, курс вестинга поменялся, и автору он начислялся уже по другому курсу.

**Comment by afalaleev** [comment]
Выплаты автору делаются по соотношению `percent_steem_dollars / 2 ` - это сколько процентов будет выплачено в vesting, а сколько в gbg+golos.

Чаще всего там 100%.

Отсюда в vesting выплачено в 50%, остальное в gbg и в golos.
528.116 GBG = 263.052 GBG + 0.431 GOLOS + 352622.930638 GESTS

Поскольку распределение по 50%:
263.052 GBG + 0.431 GOLOS = 352622.930638 GESTS

Посчитаем сколько стоил 1 GBG в GESTS в момент выплаты автору:
528.116 GBG / 2 = 352622.930638 GESTS
264.068 = 352622.930638 GESTS
1 GBG = 1335,399535852 GESTS

Посчитаем сколько стоил 1 GOLOS в GBG в момент выплаты автору:
263.052 GBG + 0.431 GOLOS = 264.068 GBG
0.431 GOLOS = 264.068 GBG - 263.052 GBG
0.431 GOLOS = 1.016 GBG

**Comment by Bacher** [comment]
Спасибо большое!

**Comment by Bacher** [comment]
50% СГ будет только в том случае если тут выбрано (50%/50%) при создании поста?
Я должен учитывать эту настройку? И если да, то где я могу его подсмотреть?
![image](https://user-images.githubusercontent.com/2598671/46722984-7889a680-cc7f-11e8-97b5-5b631c155bb7.png)

**Comment by Bacher** [comment]
А, это как раз на значение `percent_steem_dollars` и влияет?
Получается если `percent_steem_dollars` будет 0, то выплаты автору в `GOLOS` не будет, и мы не сможем посчитать соотношение `GOLOS` <=> `GESTS`? Они нужны чтобы правильно кураторские и бенефициарские отобразить.

**Comment by afalaleev** [comment]
Хуже того, там есть посты за которые есть GBG + GESTS, и снова нету GOLOS.

Я вот не доконца понимаю тягу отобразить все в одном активе.
Это динамические величины, они в каждый момент времени меняются.
При попытке это сконвертировать в один актив - становится непонятно по какому курсу идет отображение: по курсу на момент выплат? Так на следующий же день те активы, которые получил автор имеют совсем другое выражение в смежных активах. 
Именно поэтому в стиме и сделали аккумулирующие поля в GBG на момент выплаты, чтобы была хоть какая нибудь привязка хоть к какому нибудь активу.

**Comment by Bacher** [comment]
Я так понимаю Николай хочет в GOLOS отображать выплаты которые были выданы в Силе Голоса, потому что у пользователей есть представление что GOLOS и Сила Голоса это одна единица, просто в разных состояниях. Там же конвертация 1 к 1 всегда если я правильно понимаю, то есть и то и то для пользователя это GOLOS.
Когда мы GBG добавляем, то получается мы конвертируем в эквивалент. Человек по факту получил например 10 Силы Голоса, а мы ему отображаем что он получил 8 GBG. Это немного путает мне кажется.

**Comment by Bacher** [comment]
@afalaleev Но, если у нас сейчас по факту недостаточно информации чтобы точно отображаться цифры, придется как-то подстраиваться коненчо.

**Comment by afalaleev** [comment]
Курс GOLOS <-> GESTS плавающий, он никогда 1 к 1 не идет.

**Comment by afalaleev** [comment]
Скорее путает то, что авторы получат в разных активах, а отображается в одном.

**Comment by Bacher** [comment]
`GOLOS <-> GESTS `плавающий это да, но мы вместо `GESTS` всегда конвертируем в `Силу Голоса`. Значение Силы Голоса может меняться со временем?

**Comment by Bacher** [comment]
![image](https://user-images.githubusercontent.com/2598671/46728363-55fd8a80-cc8b-11e8-9e45-2a451d71b1a1.png)

Эти цифры вроде не меняются со временем, могу ошибаться.

**Comment by Bacher** [comment]
Получается промежуточный итог вроде такой, что если у поста не было выплаты в GOLOS, то мы не можем отобразить выплату и детализацию выплаты в GOLOS. Только в GBG.

Во всех остальных случаях вроде получается в GOLOS перевести.

**Comment by Bacher** [comment]
Кстати есть одно решение, если мы добавим в наш сервис который сохраняет исторические курсы валют еще и то отношение `GOLOS <-> GBG` которое было в день выплаты, то сможем его универсально применять. Но это надо прям пилить-пилить будет на беке.

**Comment by afalaleev** [comment]
GESTS которые на счету не меняются, это актив который автор/куратор/бенефициар/... получил.
А вот с курсом происходит постоянные перетрубации.

Я бы предложил сделать следующее:
- отображать в тех активах, что было/будет получено
- конвертацию в другие активы(GOLOS в том числе)/фиат осуществлять из GBG (в котором оно было зафиксировано в момент выплаты) по текущему курсу.

Потому что все остальные варианты конвертации вызывают массу вопросов, так как соотношения валют меняются по несколько раз за один блок.

**Comment by Bacher** [comment]
Там получится что по постам по которым выплаты уже прошли, ото дня к дню будут меняться значения выплаты, либо мы должны уточнять что это именно конвертированная ценность, а не оригинальная.

**Comment by Bacher** [comment]
> отображать в тех активах, что было/будет получено
Со всеми активами кроме GESTS это можно сделать. Получается мы вынуждены отображать GESTS как GBG, а это не та валюта которая была получена.

**Comment by afalaleev** [comment]
Так в этом и суть, что в системе нет одного актива - каждый актив работает по своим правилам и есть точки соприкосновения между этими активами.

Пользователь не получал всю выплату в GOLOS, или всю выплату в GESTS, или в GBG, а уж тем более в фиате.
Он ее получал в разных пропорциях в разных активах.
Сильнее всего к внешнему рынку на тот момент был GBG, потому что делегаты выполняя роль оракулов в системе публикуют прайс фиды.

Это будет обманом показывать пользователям, что авторы получили выплату чисто в GOLOS или GESTS, потому что когда автор получает этот актив в распоряжение - чтобы его сконвертировать у него есть ряд опций:
- Начать вывод GESTS в GOLOS - а это 13 недель и 13 раз он будет получать долю но новому курсу и сколько он получит в итоге - очень сложно предсказать.
- Сконвертировать GBG в GOLOS - а это 3.5 дня и price_feed может поменятся.
- Продать GBG за GOLOS на внутренней бирже и снова неизвестно сколько он получит
- Продать GBG за фиат на внешней бирже
- Продать GOLOS за фиат или BTC на внешней бирже.

Это как раз обман пользователей - попытка сконвертировать выплату в один актив.

**Comment by Bacher** [comment]
Была идея показывать в 2 активах.
```10.5 GOLOS + 8.3 GBG```
При этом `10.5 GOLOS` это сумма реальной выплаты в `GOLOS` + `GESTS` сконвертированные в `GOLOS` по той же формуле по которой мы конвертируем `GESTS` в `GOLOS` при отображении.

![image](https://user-images.githubusercontent.com/2598671/46731748-3028b380-cc94-11e8-9057-f3b28d8f4a5c.png)

**Comment by afalaleev** [comment]
Я выскажу свое IMHO.

Надо вперую очередь пользователю говорить о том, какими полезными свойствами обладает тот или иной актив, а уже потом про вторичные.
Полезное свойство в данном случае - это возможность голосовать и продвигать посты, а не зарабатывать в долгосроке на хранении. 
При том что с последним пунктом как раз определенный обман (IMHO) - оказывается чтобы получить эту выгоду в долгосроке - ее еще и выводить 13 недель.

GESTS обладает ключевыми свойствами на платформе - не нужно их прятать за другим активом, тем более тем, который просто так не получишь. Наоборот нужно как можно больше светить GESTS.

**Comment by Bacher** [comment]
Идея интересная. Если идти на это, нужно будет просветительскую работу с народом проводить.
