### ISSUE TITLE
Кошелек: подставлять имя получателя из страницы текущего профиля

### ISSUE THREAD

**Issue by Bacher** [GolosChain/tolstoy#933]
![image.png](https://images.zenhubusercontent.com/5b0ff4b64b5806bc2bd5811e/54d3b516-6bd4-4b12-be73-85dbea348c22)

**Comment by daryasattarova** [comment]
![image](https://user-images.githubusercontent.com/42342756/46615028-f33bb000-cb1f-11e8-8cf0-707a63e7cf44.png)
