### ISSUE TITLE
fix isomorphic tools error

### ISSUE THREAD

**Issue by Undeadlol1** [GolosChain/tolstoy#94]
By @tomarcafe

> Я обновил с репозитория, соотв переустановил модули в вебклиенте - 
> `> [webpack-isomorphic-tools] [error] .development() method is now deprecated (for server-side instance only, not for webpack plugin instance) and has no effect. Set up a proper process.env.NODE_ENV variable instead.`
> нода 6.5.0 19:46
>  идёт как ворнинг

**Comment by 21xhipster** [comment]
@Undeadlol1 Если еще актуально - переоткрой
