### ISSUE TITLE
Скрывать кнопки "Подписаться" "Заблокировать" при просмотре своего аккаунта

### ISSUE THREAD

**Issue by Bacher** [GolosChain/tolstoy#950]
Скрывать кнопки "Подписаться" "Заблокировать" при просмотре своего аккаунта.

![image.png](https://images.zenhubusercontent.com/5b0ff4b64b5806bc2bd5811e/c1d20e5e-f98b-477b-b8cf-6f5d80003fa5)

**Comment by BaroH4er** [comment]
Актуально
![image](https://user-images.githubusercontent.com/21989598/46668647-b92ce580-cbd5-11e8-915d-801c67002b56.png)

**Comment by daryasattarova** [comment]
не реализовано
