### ISSUE TITLE
Добавить автокомплит имен аккаунтов в диалогах кошелька

### ISSUE THREAD

**Issue by Bacher** [GolosChain/tolstoy#953]
Добавить автокомплит имен аккаунтов в диалогах кошелька

**Comment by Bacher** [comment]
Баг:
![image](https://user-images.githubusercontent.com/2598671/46656450-bf5f9980-cbb6-11e8-978e-b9d288b29f2a.png)

**Comment by Bacher** [comment]
Связанные баги:
#977

**Comment by BaroH4er** [comment]
Добавлен баг
#998
