### ISSUE TITLE
Отображение картинок с хостингов

### ISSUE THREAD

**Issue by ValeryLitvin** [GolosChain/tolstoy#96]
[С рокетчата] 
Коллеги разработчики, прошу вас обратить внимание, что картинки со многих хостингов не подгрузаются в посты на golos.io
Дело тут именно в golos, так как на steem проблем нет. Наверно, это не критично для тех кто пости 1-2 картинку, но для фотографов это очень неудобно. Так как фотки уже залиты на фотинги, и перезаливать всё - это большой гимор. И с проблемой загрузки картинок сталкиваются многие пользователи, в том числе и новые. Посылать их на избранные фото-хостинги это не камильфо.

@tomarcafe думаю, проблема в инфре

**Comment by Undeadlol1** [comment]
Цитата от @valzav 
>  у вас картинки показываются без прокси как у нас, поэтому процент битых гораздо выше, я спрошу у roadscape про исходники этого прокси

**Comment by Undeadlol1** [comment]
Насколько я понял, это сейчас не актуально.
Леша сделал прокси, все, вроде, нормально.
