### ISSUE TITLE
Профиль: краткая информация о пользовтеле отсутсвует локализация на анг

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/tolstoy#967]
Проблема: краткая информация о пользовтаеле отсутсвует локализация
![image](https://user-images.githubusercontent.com/30616421/46609401-0b9fd080-cb08-11e8-96e8-0343232db999.png)

- [ ]   FIXED

Воспроизведение:

Открыть страницу настроек авторизированного пользователя sandbox.golos.io/@%username%/settings
Открыть вкладку ""Общие""
Внести любые изменения в настройках языка интерефейса и обновить.
Результат: внесенные изменения в настройках не отображаются в блоке краткая информация, баланс, кнопки действий..
Ожидаемый результат: внесенные изменения в настройках отображаются на сайте.

**Comment by daryasattarova** [comment]
не исправлено
![image](https://user-images.githubusercontent.com/42342756/47291159-4d05a500-d60b-11e8-924a-eac7e407f090.png)
