### ISSUE TITLE
Блок поста: фокус на дату

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/tolstoy#969]
Проблема: при наведении курсора мыши на давность публикации поста(focus > PostCard__PostDate), не отображается тултип с точной датой и временем публикации.

- [x] Fixed

Воспроизведение:

Открыть страницу любого профиля /@%username%
Навести курсор мыши на дату давности поста.
Результат: подсказка по умолчанию:
![image](https://user-images.githubusercontent.com/30616421/46610165-368b2400-cb0a-11e8-86f0-184ebf19e3b5.png)

Ожидаемый результат: тултип согласно дизайну:
![image](https://user-images.githubusercontent.com/30616421/46610169-3ab74180-cb0a-11e8-80d9-8505ac81dc3e.png)

**Comment by Bacher** [comment]
Есть функционал тултипов если выставить аттрибут
`data-tooltip="<span>19.06.2018 <span style="color: #999">19:10</span>"`
и указать флаг
`data-tooltip-html`
то будет такой tooltip.

**Comment by Bacher** [comment]
![image](https://user-images.githubusercontent.com/2598671/47215827-76c09100-d3ab-11e8-9edb-132a727be9b5.png)
