### ISSUE TITLE
Вкладка комментарии - блок комментария не соответствует дизайну

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/tolstoy#970]
Вкладка комментарии - блок комментария
Проблема: не соответствует дизайну кнопки "количества комментариев" и "Ответить":
Решение: привести к виду согласно дизайну.

- [ ] Fixed

Текущее состояние 
![image](https://user-images.githubusercontent.com/30616421/46610284-97b2f780-cb0a-11e8-94d1-9bba2d58d5d6.png)
Ожидаемое
![image](https://user-images.githubusercontent.com/30616421/46610292-9eda0580-cb0a-11e8-86ff-a086731d4a98.png)

**Comment by NickShtefan** [comment]
На данном экране речь идет о комментариях пользователя, который сам же их и написал. 
Кнопка "Ответить" в данном случае не нужна.
