### ISSUE TITLE
Профиль пользователя: вкладка кошелек\ награды не соответсвует дизайну

### ISSUE THREAD

**Issue by jevgenika** [GolosChain/tolstoy#974]
Профиль пользователя: вкладка кошелек\ награды не соответсвует дизайну

- [x]  Fixed

Воспроизведение:

- открыть https://sandbox.golos.io/
- авторизоваться
- открыть свой профиль
- перейти в кошелек, вкладка награды

Результат: вид отображения наград не соответвует дизайну.
Ожидаемый результат: вид отображения наград не соответвует дизайну. Отображается заголовок поста, не его сокращенная ссылка.

Текущее состояние:
![image](https://user-images.githubusercontent.com/30616421/46611467-355bf600-cb0e-11e8-960c-382aacb95fba.png)

В дизайне:
![image](https://user-images.githubusercontent.com/30616421/46611512-51f82e00-cb0e-11e8-9ff7-884214329886.png)

**Comment by daryasattarova** [comment]
проблема с именами:
открыть кураторские, перейти на авторские, и снова перейти на кураторские
Реальный результат: названия постов из вкладки авторских дублируются во вкладке кураторских
