### ISSUE TITLE
Белый экран вместо поста

### ISSUE THREAD

**Issue by BaroH4er** [GolosChain/tolstoy#976]
**Проблема:** вместо поста пользователя, отображается белый экран.

- [x] FIXED

**Воспроизведение:**
1. Открыть страницу любого пользователя https://sandbox.golos.io/@%username%
2. Открыть любой пост пользователя

**Результат:**

![image](https://user-images.githubusercontent.com/21989598/46662028-06538c00-cbc3-11e8-8c9f-5280ea243bf7.png)

**Ожидаемый результат:** отображается пост пользователя

**Reproduced: 3/5**

**Comment by NickShtefan** [comment]
![image](https://user-images.githubusercontent.com/6249597/46726334-c8b83700-cc86-11e8-90b8-7a17ce29b0e2.png)
