### ISSUE TITLE
Реализовать возможность перейти в режим редактирования поста из ленты профиля

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/tolstoy#981]
![image.png](https://images.zenhubusercontent.com/5a27458f8a75884b908a072e/f8818693-e3a1-4450-9e39-6ccd9fe833cd)

**Comment by Bacher** [comment]
Начало в ветке `981_edit-post-button`

**Comment by Bacher** [comment]
Реализовано в #1028
