### ISSUE TITLE
Реализовать карточку поста для главной страницы

### ISSUE THREAD

**Issue by NickShtefan** [GolosChain/tolstoy#985]
[пример](https://app.zeplin.io/project/5ba9f49fb422725fe0f07dbf/screen/5bb1f0f0d8f1991eabd935de)

Карточка может быть двух видов: 

- С картинкой, в случае, если пользователь добавил изображение в пост, если изображений больше одного, отображаем первую (в перспективе пользователь сможет указать какое изображение должно быть использовано в качестве превью). 300 символов
- Без картинки - отображаем больше текста. 600 символов

**Comment by Bacher** [comment]
Карточка пока что заменилась только в профиле. В ленте появится он скоро, с соседней задачей, которую Алексей сейчас делает.

**Comment by daryasattarova** [comment]
1. создала пост без фото с кол-вом символов 1000+
2. перешла в "новое"

результат: карточки растянулись
![image](https://user-images.githubusercontent.com/42342756/47554952-5183d380-d913-11e8-83ad-c34292d1af51.png)
